# TROP on the example dataset

This notebook shows how to run the TROP estimator from the packaged implementation on the Penn dataset.

It covers:

- How to load and shape the Penn panel into `(N, T)` form.
- How to construct a simple treatment indicator matrix `W` consistent with the replication scripts.
- A quick overview of the TROP objective and its tuning parameters:  
  `lambda_unit`, `lambda_time`, `lambda_nn`.
- How to tune these parameters using placebo cross-validation on the control-only subpanel.

## 1. Setup

### Install 

If you are running this from a clean environment, install the package and its dependencies:

```bash
pip install trop
```

### Import

In [1]:
from __future__ import annotations

import sys
import os
from pathlib import Path

# Add the local src directory to sys.path to import from local source
# In Jupyter notebooks, __file__ is not defined, so we use the current working directory
notebook_dir = Path(os.getcwd()).parent if "notebooks" in os.getcwd() else Path(os.getcwd())
src_path = notebook_dir / "src"
if str(src_path) not in sys.path:
    sys.path.insert(0, str(src_path))

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.ticker import ScalarFormatter

np.random.seed(0)

# Import the TROP package from local src
from trop import TROP_TWFE_average, TROP_cv_single, TROP_cv_cycle, TROP_cv_joint, adaptive_TROP_cv

## 2. Load the Penn panel and build `(N, T)` arrays

The replication scripts treat `PENN.csv` as a balanced panel with:

- `T = 48` years (1960–2007)
- `N = 111` countries

The file is arranged year-major: all countries for a given year, then the next year, etc.

The helper below replicates the transformation used in the provided scripts:
- reshape to `(T, N)` then transpose to `(N, T)`.
- standardize the outcome: divide by its overall standard deviation, then de-mean.

In [2]:
DATA_PATH = Path("data/PENN.csv")

def load_penn_panel(
    outcome: str = "log_gdp",
    treatment: str = "dem",
    data_path: Path = DATA_PATH,
) -> dict:
    '''
    Load PENN.csv and return a dict with:
      - Y: (N, T) outcome matrix
      - D: (N, T) boolean treatment matrix from the raw column (e.g., 'dem')
      - assignment_vector: (N,) indicator of whether a unit is ever-treated in D
      - countries: list[str] length N (row labels)
      - years: list[int] length T (column labels)
    '''
    if not data_path.exists():
        raise FileNotFoundError(
            f"Could not find {data_path.resolve()}. "
            "Put PENN.csv next to the notebook or update DATA_PATH."
        )

    df = pd.read_csv(data_path, sep=";")

    years = sorted(df["year"].unique().tolist())
    T = len(years)

    # country ordering
    countries = df.loc[df["year"] == years[0], "country"].tolist()
    N = len(countries)

    # Replication reshape
    Y = np.reshape(df[outcome].values, (T, -1)).T.astype(float)
    D = np.reshape(df[treatment].values, (T, -1)).T.astype(bool)

    # Standardize outcome
    Y = Y / np.std(Y)
    Y = Y - np.mean(Y)

    # Ever-treated indicator
    Ds = np.argwhere(D == True)[:, 0]
    assignment_vector = np.zeros((N,), dtype=int)
    assignment_vector[Ds] = 1

    return {
        "Y": Y,
        "D": D,
        "assignment_vector": assignment_vector,
        "countries": countries,
        "years": years,
    }

penn = load_penn_panel(outcome="log_gdp", treatment="dem")
Y = penn["Y"]
D_raw = penn["D"]
assignment = penn["assignment_vector"]
countries = np.array(penn["countries"])
years = np.array(penn["years"])

N, T = Y.shape
n_treated_units = int(assignment.sum())
n_controls = int((assignment == 0).sum())

print(f"Y shape: {Y.shape} (N units x T periods)")
print(f"Treated units (ever-treated in raw D): {n_treated_units}")
print(f"Control units (never-treated in raw D): {n_controls}")
print(f"Years: {years.min()}–{years.max()} (T={T})")

Y shape: (111, 48) (N units x T periods)
Treated units (ever-treated in raw D): 29
Control units (never-treated in raw D): 82
Years: 1960–2007 (T=48)

### Wrap `Y` in a labeled DataFrame

This can make it easier to sanity-check the data.

In [3]:
Y_df = pd.DataFrame(Y, index=countries, columns=years)
D_df = pd.DataFrame(D_raw.astype(int), index=countries, columns=years)

display(Y_df.head())
display(D_df.head())

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007
Argentina,0.459565,0.472985,0.465061,0.420462,0.470667,0.532111,0.521764,0.532993,0.563534,0.625232,...,0.793367,0.754941,0.738903,0.691537,0.584976,0.647053,0.710737,0.773197,0.829573,0.893544
Australia,0.945638,0.937950,0.973811,1.012899,1.048132,1.050276,1.085085,1.111744,1.153944,1.194163,...,1.637364,1.661018,1.668190,1.692356,1.708161,1.731681,1.747457,1.758828,1.776253,1.791384
Austria,0.637185,0.675559,0.687001,0.717799,0.761884,0.778395,0.818241,0.838914,0.870268,0.919760,...,1.563039,1.591436,1.617518,1.625162,1.635160,1.638775,1.657305,1.672238,1.697689,1.725785
Burundi,-1.749135,-1.902008,-1.853043,-1.817452,-1.786339,-1.768153,-1.756531,-1.664568,-1.684714,-1.714763,...,-1.600755,-1.621742,-1.645554,-1.648216,-1.634669,-1.670885,-1.663649,-1.683810,-1.667511,-1.667726
Belgium,0.627998,0.665283,0.703995,0.733969,0.783546,0.805141,0.824501,0.852002,0.887212,0.935857,...,1.510903,1.538943,1.566818,1.570604,1.581740,1.583850,1.609014,1.621129,1.636202,1.658591

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007
Argentina,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Australia,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
Austria,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
Burundi,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Belgium,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

## 3. Construct the treatment indicator `W

Thee treatment is implemented as:

- pick a set of treated units `treated_units`
- set `W[treated_units, -treated_periods:] = 1`

The treatment is a tail block affecting the last `treated_periods` years, for those selected units.

Below is the file convention:
- treated units = countries that are ever-treated in the raw `dem` indicator
- post-treatment block = last `treated_periods` years

In [4]:
treated_periods = 10

treated_units = np.where(assignment == 1)[0]
control_units = np.where(assignment == 0)[0]

W = np.zeros((N, T), dtype=float)
W[treated_units, -treated_periods:] = 1.0

post_years = years[-treated_periods:]
print("Post-treatment years:", post_years.tolist())
print("Number treated units:", treated_units.size)

print("Fraction treated cells in W:", W.mean())

Post-treatment years: [1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007]
Number treated units: 29
Fraction treated cells in W: 0.05442942942942943

## 4. Overview of the TROP estimator

TROP estimates an average treatment effect parameter `τ` from a weighted two-way fixed effects objective, with an optional low-rank adjustment.

### Objective

Let:
- `Y` be the outcome matrix `(N × T)`
- `W` be the treatment indicator matrix `(N × T)`
- `α_i` unit fixed effects, `γ_t` time fixed effects, `μ` intercept
- `L` an optional low-rank component (matrix) with nuclear-norm regularization

TROP solves (schematically):

$$
\min_{\mu,\alpha,\gamma,\tau, L}
\;
\sum_{i,t} \delta_{it}
\Big( Y_{it} - \mu - \alpha_i - \gamma_t - \tau W_{it} - L_{it} \Big)^2
\;+
\;
\lambda_{nn}\,\lVert L \rVert_*
$$

where the weights factorize into:

$$
\delta_{it}
=
\exp\!\big(-\lambda_{unit}\,\text{dist\_unit}(i)\big)
\cdot
\exp\!\big(-\lambda_{time}\,\text{dist\_time}(t)\big)
$$

- `dist_unit(i)` measures how dissimilar unit *i* is from the average treated pre-treatment trajectory.
- `dist_time(t)` measures how far time *t* is from the center of the treated tail block.

The reported estimate is the optimized value of `τ`.

### What the tuning parameters do

- **`lambda_unit` (≥ 0):** controls how aggressively you downweight “dissimilar” control units.  
  - `0` → uniform unit weighting.  
  - larger → concentrate weight on nearest neighbors to the treated trajectory (in pre-periods).

- **`lambda_time` (≥ 0):** controls how aggressively you downweight time periods far from the treated block.  
  - `0` → uniform over time.  
  - larger → concentrate weight around the treated/post block.

- **`lambda_nn` (≥ 0 or `np.inf`):** nuclear norm penalty on the low-rank component `L`.  
  - `np.inf` → **disable** the low-rank adjustment (pure weighted TWFE).  
  - finite positive values → allow a low-rank `L` to soak up latent factor structure.  
  - very large values → push `L → 0` (back toward weighted TWFE).

Because `lambda_unit` uses distances computed from `Y`, the scale of `Y` matters. Standardizing `Y` (as above) makes `lambda_unit` values more comparable across outcomes.

In [5]:
# Example 1: weighted TWFE only
tau_wtwfe = TROP_TWFE_average(
    Y=Y,
    W=W,
    treated_units=treated_units,
    lambda_unit=0.0,
    lambda_time=0.0,
    lambda_nn=np.inf,
    treated_periods=treated_periods,
    solver="OSQP",
    verbose=False,
)

# Example 2: weights + low-rank adjustment
tau_trop = TROP_TWFE_average(
    Y=Y,
    W=W,
    treated_units=treated_units,
    lambda_unit=0.3,
    lambda_time=0.325,
    lambda_nn=0.016,
    treated_periods=treated_periods,
    solver="SCS",
    verbose=False,
)

# Example 3: No distance weights, but with low-rank adjustment
tau_mc = TROP_TWFE_average(
    Y=Y,
    W=W,
    treated_units=treated_units,
    lambda_unit=0.0,
    lambda_time=0.0,
    lambda_nn=0.6,
    treated_periods=treated_periods,
    solver="SCS",
    verbose=False,
)

print("Estimated tau (weighted TWFE only):", tau_wtwfe)
print("Estimated tau (TROP: weights + low-rank):", tau_trop)
print("Estimated tau (MC-style: no weights, low-rank):", tau_mc)

Estimated tau (weighted TWFE only): 0.2217182353059236
Estimated tau (TROP: weights + low-rank): 0.04543782572780066
Estimated tau (MC-style: no weights, low-rank): 0.06632514895547821

## 6. Tuning the parameters via placebo cross-validation

The functions `TROP_cv_single`, `TROP_cv_cycle`, and `TROP_cv_joint` implement a placebo CV idea:

- Use a control-only panel `Y_control`.
- For each candidate tuning parameter value:
  - repeatedly assign a placebo treatment to random units for the last `treated_periods` columns
  - compute the placebo TROP estimate `\hat\tau`
- Since the placebo treatment has true effect 0, a good tuning parameter should make the placebo estimates small on average.

The CV score is the RMSE of placebo estimates:

$$
\text{score}(\lambda)
=
\sqrt{\mathbb{E}\!\left[\hat{\tau}(\lambda)^2\right]}
$$

### Practical guidance

- Start with small grids and small `n_trials` to validate the pipeline.
- Increase `n_trials` and refine grids once everything runs.
- For speed, use `n_jobs=-1` to parallelize placebo trials.

In [6]:
Y_control = Y[control_units, :]

n_placebo_treated = min(len(treated_units), Y_control.shape[0] - 1)
print("Placebo treated units per trial:", n_placebo_treated)

# Candidate grids
unit_grid = np.linspace(0.0, 1.5, 7)                        # lambda_unit
time_grid = np.linspace(0.0, 1.0, 6)                        # lambda_time
nn_grid = np.array([0.001, 0.005, 0.01, 0.02, 0.05, 0.1])   # lambda_nn

Placebo treated units per trial: 29

In [ ]:
# Adaptive joint placebo CV for the control-only panel
best_unit, best_time, best_nn = adaptive_TROP_cv(
    Y_control,
    treated_periods=treated_periods,
    init_ranges=((0.0, 1.0), (0.0, 1.0), (0.0, 1.0)),
    n_points=5,
    n_trials=20,
    n_jobs=1,
    prefer="threads",
    expand_factor=1.0,
    max_expansions=2,
    zoom=True,
    zoom_factor=4.0,
    zoom_n_points=5,
    cv_sampling_method="resample",
    n_treated_units=n_placebo_treated,
    random_seed=0,
    solver="SCS",
    verbose=True,
)

print("Adaptive CV selected lambdas:", (best_unit, best_time, best_nn))

(CVXPY) Jul 07 11:38:56 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:38:56 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:38:56 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:38:56 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:38:56 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:38:56 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:38:56 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:38:56 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:38:56 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:38:56 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:38:56 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:38:56 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:38:56 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:38:56 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:38:56 AM: Applying reduction SCS
(CVXPY) Jul 07 11:38:56 AM: Finished problem compilation (took 6.196e-02 seconds).
(CVXPY) Jul 07 11:38:56 AM: Invoking solver SCS  to obtain a solution.

===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  1.74e-01  4.38e+01  2.52e+01  1.00e-01  5.66e-02

(CVXPY) Jul 07 11:38:56 AM: Problem status: optimal
(CVXPY) Jul 07 11:38:56 AM: Optimal value: 1.506e-11
(CVXPY) Jul 07 11:38:56 AM: Compilation took 6.196e-02 seconds
(CVXPY) Jul 07 11:38:56 AM: Solver (including time spent in interface) took 2.819e-01 seconds
(CVXPY) Jul 07 11:38:56 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:38:56 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:38:56 AM: DCP verification time: 0.0003 seconds.
(CVXPY) Jul 07 11:38:56 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:38:56 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:38:56 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:38:56 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:38:56 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:38:56 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:38:56 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:38:56 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:38:56 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:38:56 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:38:56 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:38:56 AM: Applying reduction SCS
(CVXPY) Jul 07 11:38:56 AM: Finished problem compilation (took 5.292e-02 seconds).
(CVXPY) Jul 07 11:38:56 AM: Invoking solver SCS  to obtain a solution.

    25| 2.80e-07  3.34e-08  6.79e-06  3.39e-06  1.00e-01  2.75e-01
------------------------------------------------------------------
status:  solved
timings: total: 2.75e-01s = setup: 2.57e-02s + solve: 2.49e-01s
	 lin-sys: 1.60e-02s, cones: 2.24e-01s, accel: 8.70e-04s
------------------------------------------------------------------
objective = 0.000003
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.62e+00  2.02e-01  4.53e+01  2.61e+01  1.00e-01  3.31e-02

(CVXPY) Jul 07 11:38:57 AM: Problem status: optimal
(CVXPY) Jul 07 11:38:57 AM: Optimal value: 1.555e-11
(CVXPY) Jul 07 11:38:57 AM: Compilation took 5.292e-02 seconds
(CVXPY) Jul 07 11:38:57 AM: Solver (including time spent in interface) took 2.436e-01 seconds
(CVXPY) Jul 07 11:38:57 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:38:57 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:38:57 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:38:57 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:38:57 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:38:57 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:38:57 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:38:57 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:38:57 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:38:57 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:38:57 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:38:57 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:38:57 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:38:57 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:38:57 AM: Applying reduction SCS
(CVXPY) Jul 07 11:38:57 AM: Finished problem compilation (took 5.452e-02 seconds).
(CVXPY) Jul 07 11:38:57 AM: Invoking solver SCS  to obtain a solution.

    25| 4.29e-07  5.25e-08  7.34e-06  3.67e-06  1.00e-01  2.37e-01
------------------------------------------------------------------
status:  solved
timings: total: 2.38e-01s = setup: 2.47e-02s + solve: 2.13e-01s
	 lin-sys: 1.41e-02s, cones: 1.91e-01s, accel: 7.75e-04s
------------------------------------------------------------------
objective = 0.000004
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.55e+00  1.80e-01  4.61e+01  2.66e+01  1.00e-01  3.48e-02

(CVXPY) Jul 07 11:38:57 AM: Problem status: optimal
(CVXPY) Jul 07 11:38:57 AM: Optimal value: 1.592e-11
(CVXPY) Jul 07 11:38:57 AM: Compilation took 5.452e-02 seconds
(CVXPY) Jul 07 11:38:57 AM: Solver (including time spent in interface) took 2.359e-01 seconds
(CVXPY) Jul 07 11:38:57 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:38:57 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:38:57 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:38:57 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:38:57 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:38:57 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:38:57 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:38:57 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:38:57 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:38:57 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:38:57 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:38:57 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:38:57 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:38:57 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:38:57 AM: Applying reduction SCS
(CVXPY) Jul 07 11:38:57 AM: Finished problem compilation (took 5.606e-02 seconds).
(CVXPY) Jul 07 11:38:57 AM: Invoking solver SCS  to obtain a solution.

    25| 4.22e-07  5.22e-08  7.69e-06  3.84e-06  1.00e-01  2.31e-01
------------------------------------------------------------------
status:  solved
timings: total: 2.32e-01s = setup: 2.43e-02s + solve: 2.07e-01s
	 lin-sys: 1.50e-02s, cones: 1.84e-01s, accel: 7.04e-04s
------------------------------------------------------------------
objective = 0.000004
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.60e+00  1.95e-01  4.57e+01  2.63e+01  1.00e-01  4.68e-02

(CVXPY) Jul 07 11:38:57 AM: Problem status: optimal
(CVXPY) Jul 07 11:38:57 AM: Optimal value: 1.585e-11
(CVXPY) Jul 07 11:38:57 AM: Compilation took 5.606e-02 seconds
(CVXPY) Jul 07 11:38:57 AM: Solver (including time spent in interface) took 2.290e-01 seconds
(CVXPY) Jul 07 11:38:57 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:38:57 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:38:57 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:38:57 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:38:57 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:38:57 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:38:57 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:38:57 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:38:57 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:38:57 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:38:57 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:38:57 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:38:57 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:38:57 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:38:57 AM: Applying reduction SCS
(CVXPY) Jul 07 11:38:57 AM: Finished problem compilation (took 5.442e-02 seconds).
(CVXPY) Jul 07 11:38:57 AM: Invoking solver SCS  to obtain a solution.

    25| 4.27e-07  5.39e-08  7.52e-06  3.76e-06  1.00e-01  2.24e-01
------------------------------------------------------------------
status:  solved
timings: total: 2.24e-01s = setup: 2.59e-02s + solve: 1.99e-01s
	 lin-sys: 1.39e-02s, cones: 1.77e-01s, accel: 8.21e-04s
------------------------------------------------------------------
objective = 0.000004
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  1.81e-01  4.30e+01  2.47e+01  1.00e-01  7.58e-02

(CVXPY) Jul 07 11:38:58 AM: Problem status: optimal
(CVXPY) Jul 07 11:38:58 AM: Optimal value: 1.459e-11
(CVXPY) Jul 07 11:38:58 AM: Compilation took 5.442e-02 seconds
(CVXPY) Jul 07 11:38:58 AM: Solver (including time spent in interface) took 2.628e-01 seconds
(CVXPY) Jul 07 11:38:58 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:38:58 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:38:58 AM: DCP verification time: 0.0010 seconds.
(CVXPY) Jul 07 11:38:58 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:38:58 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:38:58 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:38:58 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:38:58 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:38:58 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:38:58 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:38:58 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:38:58 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:38:58 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:38:58 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:38:58 AM: Applying reduction SCS
(CVXPY) Jul 07 11:38:58 AM: Finished problem compilation (took 4.940e-02 seconds).
(CVXPY) Jul 07 11:38:58 AM: Invoking solver SCS  to obtain a solution.

    25| 2.90e-07  3.23e-08  6.47e-06  3.24e-06  1.00e-01  2.57e-01
------------------------------------------------------------------
status:  solved
timings: total: 2.57e-01s = setup: 6.66e-02s + solve: 1.91e-01s
	 lin-sys: 1.29e-02s, cones: 1.69e-01s, accel: 7.78e-04s
------------------------------------------------------------------
objective = 0.000003
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.51e+00  1.87e-01  4.97e+01  2.86e+01  1.00e-01  4.82e-02

(CVXPY) Jul 07 11:38:58 AM: Problem status: optimal
(CVXPY) Jul 07 11:38:58 AM: Optimal value: 1.799e-11
(CVXPY) Jul 07 11:38:58 AM: Compilation took 4.940e-02 seconds
(CVXPY) Jul 07 11:38:58 AM: Solver (including time spent in interface) took 2.820e-01 seconds
(CVXPY) Jul 07 11:38:58 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:38:58 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:38:58 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:38:58 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:38:58 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:38:58 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:38:58 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:38:58 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:38:58 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:38:58 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:38:58 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:38:58 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:38:58 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:38:58 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:38:58 AM: Applying reduction SCS
(CVXPY) Jul 07 11:38:58 AM: Finished problem compilation (took 5.009e-02 seconds).
(CVXPY) Jul 07 11:38:58 AM: Invoking solver SCS  to obtain a solution.

    25| 4.29e-07  6.00e-08  9.19e-06  4.60e-06  1.00e-01  2.77e-01
------------------------------------------------------------------
status:  solved
timings: total: 2.77e-01s = setup: 2.46e-02s + solve: 2.52e-01s
	 lin-sys: 1.54e-02s, cones: 2.29e-01s, accel: 1.02e-03s
------------------------------------------------------------------
objective = 0.000005
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.72e+00  1.98e-01  4.53e+01  2.61e+01  1.00e-01  4.72e-02

(CVXPY) Jul 07 11:38:58 AM: Problem status: optimal
(CVXPY) Jul 07 11:38:58 AM: Optimal value: 1.558e-11
(CVXPY) Jul 07 11:38:58 AM: Compilation took 5.009e-02 seconds
(CVXPY) Jul 07 11:38:58 AM: Solver (including time spent in interface) took 2.677e-01 seconds
(CVXPY) Jul 07 11:38:58 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:38:58 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:38:58 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:38:58 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:38:58 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:38:58 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:38:58 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:38:58 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:38:58 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:38:58 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:38:58 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:38:58 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:38:58 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:38:58 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:38:58 AM: Applying reduction SCS
(CVXPY) Jul 07 11:38:58 AM: Finished problem compilation (took 5.113e-02 seconds).
(CVXPY) Jul 07 11:38:58 AM: Invoking solver SCS  to obtain a solution.

    25| 4.45e-07  5.39e-08  7.34e-06  3.67e-06  1.00e-01  2.64e-01
------------------------------------------------------------------
status:  solved
timings: total: 2.64e-01s = setup: 2.41e-02s + solve: 2.40e-01s
	 lin-sys: 1.56e-02s, cones: 2.17e-01s, accel: 1.13e-03s
------------------------------------------------------------------
objective = 0.000004
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  1.36e-01  3.96e+01  2.28e+01  1.00e-01  3.56e-02

(CVXPY) Jul 07 11:38:59 AM: Problem status: optimal
(CVXPY) Jul 07 11:38:59 AM: Optimal value: 1.313e-11
(CVXPY) Jul 07 11:38:59 AM: Compilation took 5.113e-02 seconds
(CVXPY) Jul 07 11:38:59 AM: Solver (including time spent in interface) took 2.434e-01 seconds
(CVXPY) Jul 07 11:38:59 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:38:59 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:38:59 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:38:59 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:38:59 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:38:59 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:38:59 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:38:59 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:38:59 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:38:59 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:38:59 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:38:59 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:38:59 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:38:59 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:38:59 AM: Applying reduction SCS
(CVXPY) Jul 07 11:38:59 AM: Finished problem compilation (took 5.405e-02 seconds).
(CVXPY) Jul 07 11:38:59 AM: Invoking solver SCS  to obtain a solution.

    25| 2.33e-07  2.82e-08  5.30e-06  2.65e-06  1.00e-01  2.37e-01
------------------------------------------------------------------
status:  solved
timings: total: 2.37e-01s = setup: 2.47e-02s + solve: 2.13e-01s
	 lin-sys: 1.48e-02s, cones: 1.90e-01s, accel: 8.25e-04s
------------------------------------------------------------------
objective = 0.000003
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.72e+00  1.94e-01  4.64e+01  2.67e+01  1.00e-01  4.32e-02

(CVXPY) Jul 07 11:38:59 AM: Problem status: optimal
(CVXPY) Jul 07 11:38:59 AM: Optimal value: 1.612e-11
(CVXPY) Jul 07 11:38:59 AM: Compilation took 5.405e-02 seconds
(CVXPY) Jul 07 11:38:59 AM: Solver (including time spent in interface) took 2.578e-01 seconds
(CVXPY) Jul 07 11:38:59 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:38:59 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:38:59 AM: DCP verification time: 0.0003 seconds.
(CVXPY) Jul 07 11:38:59 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:38:59 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:38:59 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:38:59 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:38:59 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:38:59 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:38:59 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:38:59 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:38:59 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:38:59 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:38:59 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:38:59 AM: Applying reduction SCS
(CVXPY) Jul 07 11:38:59 AM: Finished problem compilation (took 5.564e-02 seconds).
(CVXPY) Jul 07 11:38:59 AM: Invoking solver SCS  to obtain a solution.

    25| 4.51e-07  5.66e-08  7.79e-06  3.90e-06  1.00e-01  2.54e-01
------------------------------------------------------------------
status:  solved
timings: total: 2.54e-01s = setup: 2.32e-02s + solve: 2.31e-01s
	 lin-sys: 1.47e-02s, cones: 2.09e-01s, accel: 8.30e-04s
------------------------------------------------------------------
objective = 0.000004
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  1.64e-01  4.09e+01  2.35e+01  1.00e-01  4.59e-02

(CVXPY) Jul 07 11:38:59 AM: Problem status: optimal
(CVXPY) Jul 07 11:38:59 AM: Optimal value: 1.364e-11
(CVXPY) Jul 07 11:38:59 AM: Compilation took 5.564e-02 seconds
(CVXPY) Jul 07 11:38:59 AM: Solver (including time spent in interface) took 2.587e-01 seconds
(CVXPY) Jul 07 11:38:59 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:38:59 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:38:59 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:38:59 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:38:59 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:38:59 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:38:59 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:38:59 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:38:59 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:38:59 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:38:59 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:38:59 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:38:59 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:38:59 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:38:59 AM: Applying reduction SCS
(CVXPY) Jul 07 11:38:59 AM: Finished problem compilation (took 5.374e-02 seconds).
(CVXPY) Jul 07 11:38:59 AM: Invoking solver SCS  to obtain a solution.

    25| 2.57e-07  2.96e-08  5.73e-06  2.86e-06  1.00e-01  2.54e-01
------------------------------------------------------------------
status:  solved
timings: total: 2.54e-01s = setup: 2.37e-02s + solve: 2.31e-01s
	 lin-sys: 1.35e-02s, cones: 2.10e-01s, accel: 1.04e-03s
------------------------------------------------------------------
objective = 0.000003
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  2.02e-01  4.43e+01  2.55e+01  1.00e-01  4.24e-02

(CVXPY) Jul 07 11:39:00 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:00 AM: Optimal value: 1.516e-11
(CVXPY) Jul 07 11:39:00 AM: Compilation took 5.374e-02 seconds
(CVXPY) Jul 07 11:39:00 AM: Solver (including time spent in interface) took 2.488e-01 seconds
(CVXPY) Jul 07 11:39:00 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:00 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:00 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:39:00 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:00 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:00 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:00 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:00 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:00 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:00 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:00 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:00 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:00 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:00 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:00 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:00 AM: Finished problem compilation (took 5.053e-02 seconds).
(CVXPY) Jul 07 11:39:00 AM: Invoking solver SCS  to obtain a solution.

    25| 3.28e-07  3.37e-08  6.98e-06  3.49e-06  1.00e-01  2.43e-01
------------------------------------------------------------------
status:  solved
timings: total: 2.44e-01s = setup: 3.17e-02s + solve: 2.12e-01s
	 lin-sys: 1.29e-02s, cones: 1.91e-01s, accel: 8.43e-04s
------------------------------------------------------------------
objective = 0.000003
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.60e+00  1.88e-01  4.63e+01  2.67e+01  1.00e-01  3.30e-02

(CVXPY) Jul 07 11:39:00 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:00 AM: Optimal value: 1.606e-11
(CVXPY) Jul 07 11:39:00 AM: Compilation took 5.053e-02 seconds
(CVXPY) Jul 07 11:39:00 AM: Solver (including time spent in interface) took 2.489e-01 seconds
(CVXPY) Jul 07 11:39:00 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:00 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:00 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:39:00 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:00 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:00 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:00 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:00 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:00 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:00 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:00 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:00 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:00 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:00 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:00 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:00 AM: Finished problem compilation (took 5.477e-02 seconds).
(CVXPY) Jul 07 11:39:00 AM: Invoking solver SCS  to obtain a solution.

    25| 4.31e-07  5.35e-08  7.76e-06  3.88e-06  1.00e-01  2.43e-01
------------------------------------------------------------------
status:  solved
timings: total: 2.43e-01s = setup: 2.42e-02s + solve: 2.19e-01s
	 lin-sys: 1.72e-02s, cones: 1.94e-01s, accel: 7.63e-04s
------------------------------------------------------------------
objective = 0.000004
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.63e+00  1.86e-01  4.40e+01  2.53e+01  1.00e-01  3.46e-02

(CVXPY) Jul 07 11:39:00 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:00 AM: Optimal value: 1.501e-11
(CVXPY) Jul 07 11:39:00 AM: Compilation took 5.477e-02 seconds
(CVXPY) Jul 07 11:39:00 AM: Solver (including time spent in interface) took 3.500e-01 seconds
(CVXPY) Jul 07 11:39:00 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:00 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:00 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:39:00 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:00 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:00 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:00 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:00 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:00 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:00 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:00 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:00 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:00 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:00 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:00 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:00 AM: Finished problem compilation (took 7.637e-02 seconds).
(CVXPY) Jul 07 11:39:00 AM: Invoking solver SCS  to obtain a solution.

    25| 4.25e-07  5.01e-08  6.87e-06  3.43e-06  1.00e-01  3.46e-01
------------------------------------------------------------------
status:  solved
timings: total: 3.46e-01s = setup: 2.36e-02s + solve: 3.22e-01s
	 lin-sys: 1.59e-02s, cones: 2.98e-01s, accel: 2.57e-03s
------------------------------------------------------------------
objective = 0.000003
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  1.97e-01  4.29e+01  2.47e+01  1.00e-01  4.20e-02

(CVXPY) Jul 07 11:39:01 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:01 AM: Optimal value: 1.457e-11
(CVXPY) Jul 07 11:39:01 AM: Compilation took 7.637e-02 seconds
(CVXPY) Jul 07 11:39:01 AM: Solver (including time spent in interface) took 3.570e-01 seconds
(CVXPY) Jul 07 11:39:01 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:01 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:01 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:39:01 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:01 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:01 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:01 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:01 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:01 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:01 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:01 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:01 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:01 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:01 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:01 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:01 AM: Finished problem compilation (took 5.430e-02 seconds).
(CVXPY) Jul 07 11:39:01 AM: Invoking solver SCS  to obtain a solution.

    25| 3.15e-07  3.15e-08  6.44e-06  3.22e-06  1.00e-01  3.51e-01
------------------------------------------------------------------
status:  solved
timings: total: 3.51e-01s = setup: 3.23e-02s + solve: 3.19e-01s
	 lin-sys: 1.49e-02s, cones: 2.96e-01s, accel: 8.99e-04s
------------------------------------------------------------------
objective = 0.000003
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.48e+00  1.85e-01  5.00e+01  2.88e+01  1.00e-01  4.62e-02

(CVXPY) Jul 07 11:39:01 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:01 AM: Optimal value: 1.800e-11
(CVXPY) Jul 07 11:39:01 AM: Compilation took 5.430e-02 seconds
(CVXPY) Jul 07 11:39:01 AM: Solver (including time spent in interface) took 2.475e-01 seconds
(CVXPY) Jul 07 11:39:01 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:01 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:01 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:39:01 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:01 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:01 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:01 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:01 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:01 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:01 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:01 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:01 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:01 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:01 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:01 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:01 AM: Finished problem compilation (took 5.057e-02 seconds).
(CVXPY) Jul 07 11:39:01 AM: Invoking solver SCS  to obtain a solution.

    25| 4.25e-07  6.02e-08  9.35e-06  4.68e-06  1.00e-01  2.42e-01
------------------------------------------------------------------
status:  solved
timings: total: 2.42e-01s = setup: 2.38e-02s + solve: 2.18e-01s
	 lin-sys: 1.41e-02s, cones: 1.97e-01s, accel: 8.02e-04s
------------------------------------------------------------------
objective = 0.000005
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.83e+00  2.11e-01  4.32e+01  2.49e+01  1.00e-01  4.59e-02

(CVXPY) Jul 07 11:39:01 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:01 AM: Optimal value: 1.478e-11
(CVXPY) Jul 07 11:39:01 AM: Compilation took 5.057e-02 seconds
(CVXPY) Jul 07 11:39:01 AM: Solver (including time spent in interface) took 2.619e-01 seconds
(CVXPY) Jul 07 11:39:01 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:01 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:01 AM: DCP verification time: 0.0009 seconds.
(CVXPY) Jul 07 11:39:01 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:01 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:01 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:01 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:01 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:01 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:01 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:01 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:01 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:01 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:01 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:02 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:02 AM: Finished problem compilation (took 5.158e-02 seconds).
(CVXPY) Jul 07 11:39:02 AM: Invoking solver SCS  to obtain a solution.

    25| 4.54e-07  5.09e-08  6.55e-06  3.27e-06  1.00e-01  2.56e-01
------------------------------------------------------------------
status:  solved
timings: total: 2.56e-01s = setup: 2.59e-02s + solve: 2.30e-01s
	 lin-sys: 1.58e-02s, cones: 2.07e-01s, accel: 7.57e-04s
------------------------------------------------------------------
objective = 0.000003
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  1.68e-01  4.19e+01  2.41e+01  1.00e-01  3.21e-02

(CVXPY) Jul 07 11:39:02 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:02 AM: Optimal value: 1.391e-11
(CVXPY) Jul 07 11:39:02 AM: Compilation took 5.158e-02 seconds
(CVXPY) Jul 07 11:39:02 AM: Solver (including time spent in interface) took 2.426e-01 seconds
(CVXPY) Jul 07 11:39:02 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:02 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:02 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:39:02 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:02 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:02 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:02 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:02 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:02 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:02 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:02 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:02 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:02 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:02 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:02 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:02 AM: Finished problem compilation (took 5.631e-02 seconds).
(CVXPY) Jul 07 11:39:02 AM: Invoking solver SCS  to obtain a solution.

    25| 2.66e-07  3.04e-08  6.10e-06  3.05e-06  1.00e-01  2.37e-01
------------------------------------------------------------------
status:  solved
timings: total: 2.37e-01s = setup: 2.38e-02s + solve: 2.13e-01s
	 lin-sys: 1.63e-02s, cones: 1.89e-01s, accel: 1.06e-03s
------------------------------------------------------------------
objective = 0.000003
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.51e+00  1.87e-01  4.88e+01  2.81e+01  1.00e-01  4.54e-02

(CVXPY) Jul 07 11:39:02 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:02 AM: Optimal value: 1.725e-11
(CVXPY) Jul 07 11:39:02 AM: Compilation took 5.631e-02 seconds
(CVXPY) Jul 07 11:39:02 AM: Solver (including time spent in interface) took 2.454e-01 seconds
(CVXPY) Jul 07 11:39:02 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:02 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:02 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:39:02 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:02 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:02 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:02 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:02 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:02 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:02 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:02 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:02 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:02 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:02 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:02 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:02 AM: Finished problem compilation (took 4.907e-02 seconds).
(CVXPY) Jul 07 11:39:02 AM: Invoking solver SCS  to obtain a solution.

    25| 4.26e-07  5.85e-08  8.79e-06  4.40e-06  1.00e-01  2.41e-01
------------------------------------------------------------------
status:  solved
timings: total: 2.42e-01s = setup: 2.36e-02s + solve: 2.18e-01s
	 lin-sys: 1.49e-02s, cones: 1.96e-01s, accel: 7.19e-04s
------------------------------------------------------------------
objective = 0.000004
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.58e+00  1.89e-01  4.73e+01  2.73e+01  1.00e-01  3.30e-02

(CVXPY) Jul 07 11:39:02 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:02 AM: Optimal value: 1.666e-11
(CVXPY) Jul 07 11:39:02 AM: Compilation took 4.907e-02 seconds
(CVXPY) Jul 07 11:39:02 AM: Solver (including time spent in interface) took 2.454e-01 seconds
(CVXPY) Jul 07 11:39:02 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:02 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:02 AM: DCP verification time: 0.0011 seconds.
(CVXPY) Jul 07 11:39:02 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:02 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:02 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:02 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:02 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:02 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:02 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:02 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:02 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:02 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:02 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:02 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:03 AM: Finished problem compilation (took 5.479e-02 seconds).
(CVXPY) Jul 07 11:39:03 AM: Invoking solver SCS  to obtain a solution.

    25| 4.31e-07  5.64e-08  8.19e-06  4.09e-06  1.00e-01  2.41e-01
------------------------------------------------------------------
status:  solved
timings: total: 2.42e-01s = setup: 2.47e-02s + solve: 2.17e-01s
	 lin-sys: 1.47e-02s, cones: 1.95e-01s, accel: 8.17e-04s
------------------------------------------------------------------
objective = 0.000004
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  1.89e-01  4.42e+01  2.55e+01  1.00e-01  3.94e-02

(CVXPY) Jul 07 11:39:03 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:03 AM: Optimal value: 1.512e-11
(CVXPY) Jul 07 11:39:03 AM: Compilation took 5.479e-02 seconds
(CVXPY) Jul 07 11:39:03 AM: Solver (including time spent in interface) took 2.408e-01 seconds
(CVXPY) Jul 07 11:39:03 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:03 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:03 AM: DCP verification time: 0.0003 seconds.
(CVXPY) Jul 07 11:39:03 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:03 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:03 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:03 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:03 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:03 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:03 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:03 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:03 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:03 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:03 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:03 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:03 AM: Finished problem compilation (took 5.440e-02 seconds).
(CVXPY) Jul 07 11:39:03 AM: Invoking solver SCS  to obtain a solution.

    25| 3.06e-07  3.29e-08  6.95e-06  3.48e-06  1.00e-01  2.34e-01
------------------------------------------------------------------
status:  solved
timings: total: 2.34e-01s = setup: 2.76e-02s + solve: 2.07e-01s
	 lin-sys: 1.47e-02s, cones: 1.83e-01s, accel: 8.12e-04s
------------------------------------------------------------------
objective = 0.000003
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 4.65e+00  2.04e-01  1.01e+02 -3.50e+00  1.00e-01  5.52e-02

(CVXPY) Jul 07 11:39:04 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:04 AM: Optimal value: 8.017e+00
(CVXPY) Jul 07 11:39:04 AM: Compilation took 5.440e-02 seconds
(CVXPY) Jul 07 11:39:04 AM: Solver (including time spent in interface) took 1.096e+00 seconds
(CVXPY) Jul 07 11:39:04 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:04 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:04 AM: DCP verification time: 0.0003 seconds.
(CVXPY) Jul 07 11:39:04 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:04 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:04 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:04 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:04 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:04 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:04 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:04 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:04 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:04 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:04 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:04 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:04 AM: Finished problem compilation (took 5.079e-02 seconds).
(CVXPY) Jul 07 11:39:04 AM: Invoking solver SCS  to obtain a solution.

    75| 9.63e-06  7.32e-08  1.08e-05  8.02e+00  1.00e-01  1.09e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.09e+00s = setup: 2.70e-02s + solve: 1.06e+00s
	 lin-sys: 5.02e-02s, cones: 9.90e-01s, accel: 5.11e-03s
------------------------------------------------------------------
objective = 8.017251
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 5.11e+00  2.36e-01  1.03e+02 -2.67e+00  1.00e-01  4.81e-02

(CVXPY) Jul 07 11:39:05 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:05 AM: Optimal value: 8.285e+00
(CVXPY) Jul 07 11:39:05 AM: Compilation took 5.079e-02 seconds
(CVXPY) Jul 07 11:39:05 AM: Solver (including time spent in interface) took 1.012e+00 seconds
(CVXPY) Jul 07 11:39:05 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:05 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:05 AM: DCP verification time: 0.0003 seconds.
(CVXPY) Jul 07 11:39:05 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:05 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:05 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:05 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:05 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:05 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:05 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:05 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:05 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:05 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:05 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:05 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:05 AM: Finished problem compilation (took 5.619e-02 seconds).
(CVXPY) Jul 07 11:39:05 AM: Invoking solver SCS  to obtain a solution.

    75| 9.98e-06  1.20e-07  8.99e-06  8.29e+00  1.00e-01  1.01e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.01e+00s = setup: 2.62e-02s + solve: 9.82e-01s
	 lin-sys: 5.45e-02s, cones: 9.09e-01s, accel: 5.83e-03s
------------------------------------------------------------------
objective = 8.285309
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 5.02e+00  2.30e-01  1.04e+02 -2.17e+00  1.00e-01  3.71e-02

(CVXPY) Jul 07 11:39:06 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:06 AM: Optimal value: 8.325e+00
(CVXPY) Jul 07 11:39:06 AM: Compilation took 5.619e-02 seconds
(CVXPY) Jul 07 11:39:06 AM: Solver (including time spent in interface) took 1.104e+00 seconds
(CVXPY) Jul 07 11:39:06 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:06 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:06 AM: DCP verification time: 0.0003 seconds.
(CVXPY) Jul 07 11:39:06 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:06 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:06 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:06 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:06 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:06 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:06 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:06 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:06 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:06 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:06 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:06 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:06 AM: Finished problem compilation (took 8.623e-02 seconds).
(CVXPY) Jul 07 11:39:06 AM: Invoking solver SCS  to obtain a solution.

    75| 9.72e-06  8.58e-08  1.02e-05  8.33e+00  1.00e-01  1.10e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.10e+00s = setup: 2.62e-02s + solve: 1.07e+00s
	 lin-sys: 7.23e-02s, cones: 9.82e-01s, accel: 5.07e-03s
------------------------------------------------------------------
objective = 8.325257
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 5.14e+00  2.38e-01  1.03e+02 -2.40e+00  1.00e-01  6.02e-02

(CVXPY) Jul 07 11:39:08 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:08 AM: Optimal value: 8.306e+00
(CVXPY) Jul 07 11:39:08 AM: Compilation took 8.623e-02 seconds
(CVXPY) Jul 07 11:39:08 AM: Solver (including time spent in interface) took 1.337e+00 seconds
(CVXPY) Jul 07 11:39:08 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:08 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:08 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:39:08 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:08 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:08 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:08 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:08 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:08 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:08 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:08 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:08 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:08 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:08 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:08 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:08 AM: Finished problem compilation (took 5.835e-02 seconds).
(CVXPY) Jul 07 11:39:08 AM: Invoking solver SCS  to obtain a solution.

    75| 7.82e-06  1.06e-07  8.49e-06  8.31e+00  1.00e-01  1.33e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.33e+00s = setup: 3.34e-02s + solve: 1.30e+00s
	 lin-sys: 6.90e-02s, cones: 1.21e+00s, accel: 5.18e-03s
------------------------------------------------------------------
objective = 8.305905
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 4.68e+00  2.06e-01  1.00e+02 -3.99e+00  1.00e-01  4.49e-02

(CVXPY) Jul 07 11:39:09 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:09 AM: Optimal value: 7.998e+00
(CVXPY) Jul 07 11:39:09 AM: Compilation took 5.835e-02 seconds
(CVXPY) Jul 07 11:39:09 AM: Solver (including time spent in interface) took 1.144e+00 seconds
(CVXPY) Jul 07 11:39:09 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:09 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:09 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:39:09 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:09 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:09 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:09 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:09 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:09 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:09 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:09 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:09 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:09 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:09 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:09 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:09 AM: Finished problem compilation (took 6.471e-02 seconds).
(CVXPY) Jul 07 11:39:09 AM: Invoking solver SCS  to obtain a solution.

    75| 1.02e-05  7.24e-08  9.02e-06  8.00e+00  1.00e-01  1.14e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.14e+00s = setup: 2.98e-02s + solve: 1.11e+00s
	 lin-sys: 7.25e-02s, cones: 1.01e+00s, accel: 7.52e-03s
------------------------------------------------------------------
objective = 7.997631
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 5.04e+00  2.31e-01  1.07e+02 -1.24e-01  1.00e-01  6.62e-02

(CVXPY) Jul 07 11:39:10 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:10 AM: Optimal value: 8.417e+00
(CVXPY) Jul 07 11:39:10 AM: Compilation took 6.471e-02 seconds
(CVXPY) Jul 07 11:39:10 AM: Solver (including time spent in interface) took 1.063e+00 seconds
(CVXPY) Jul 07 11:39:10 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:10 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:10 AM: DCP verification time: 0.0003 seconds.
(CVXPY) Jul 07 11:39:10 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:10 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:10 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:10 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:10 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:10 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:10 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:10 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:10 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:10 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:10 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:10 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:10 AM: Finished problem compilation (took 5.650e-02 seconds).
(CVXPY) Jul 07 11:39:10 AM: Invoking solver SCS  to obtain a solution.

    75| 1.15e-05  8.43e-08  1.05e-05  8.42e+00  1.00e-01  1.06e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.06e+00s = setup: 3.77e-02s + solve: 1.02e+00s
	 lin-sys: 5.58e-02s, cones: 9.37e-01s, accel: 7.22e-03s
------------------------------------------------------------------
objective = 8.417383
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 5.19e+00  2.42e-01  1.03e+02 -2.67e+00  1.00e-01  4.97e-02

(CVXPY) Jul 07 11:39:11 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:11 AM: Optimal value: 8.277e+00
(CVXPY) Jul 07 11:39:11 AM: Compilation took 5.650e-02 seconds
(CVXPY) Jul 07 11:39:11 AM: Solver (including time spent in interface) took 9.186e-01 seconds
(CVXPY) Jul 07 11:39:11 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:11 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:11 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:39:11 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:11 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:11 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:11 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:11 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:11 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:11 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:11 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:11 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:11 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:11 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:11 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:11 AM: Finished problem compilation (took 6.148e-02 seconds).
(CVXPY) Jul 07 11:39:11 AM: Invoking solver SCS  to obtain a solution.

    75| 8.83e-06  8.74e-08  1.03e-05  8.28e+00  1.00e-01  9.11e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.12e-01s = setup: 2.95e-02s + solve: 8.82e-01s
	 lin-sys: 5.08e-02s, cones: 8.10e-01s, accel: 5.98e-03s
------------------------------------------------------------------
objective = 8.277185
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 4.67e+00  2.05e-01  9.70e+01 -5.94e+00  1.00e-01  3.36e-02

(CVXPY) Jul 07 11:39:12 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:12 AM: Optimal value: 7.905e+00
(CVXPY) Jul 07 11:39:12 AM: Compilation took 6.148e-02 seconds
(CVXPY) Jul 07 11:39:12 AM: Solver (including time spent in interface) took 8.752e-01 seconds
(CVXPY) Jul 07 11:39:12 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:12 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:12 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:39:12 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:12 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:12 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:12 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:12 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:12 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:12 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:12 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:12 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:12 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:12 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:12 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:12 AM: Finished problem compilation (took 5.475e-02 seconds).
(CVXPY) Jul 07 11:39:12 AM: Invoking solver SCS  to obtain a solution.

    75| 9.13e-06  8.38e-08  9.70e-06  7.90e+00  1.00e-01  8.70e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.70e-01s = setup: 2.36e-02s + solve: 8.47e-01s
	 lin-sys: 4.80e-02s, cones: 7.81e-01s, accel: 4.38e-03s
------------------------------------------------------------------
objective = 7.904979
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 5.21e+00  2.44e-01  1.04e+02 -2.02e+00  1.00e-01  4.71e-02

(CVXPY) Jul 07 11:39:13 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:13 AM: Optimal value: 8.383e+00
(CVXPY) Jul 07 11:39:13 AM: Compilation took 5.475e-02 seconds
(CVXPY) Jul 07 11:39:13 AM: Solver (including time spent in interface) took 9.290e-01 seconds
(CVXPY) Jul 07 11:39:13 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:13 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:13 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:39:13 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:13 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:13 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:13 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:13 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:13 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:13 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:13 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:13 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:13 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:13 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:13 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:13 AM: Finished problem compilation (took 5.654e-02 seconds).
(CVXPY) Jul 07 11:39:13 AM: Invoking solver SCS  to obtain a solution.

    75| 1.10e-05  1.20e-07  9.72e-06  8.38e+00  1.00e-01  9.23e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.24e-01s = setup: 2.37e-02s + solve: 9.00e-01s
	 lin-sys: 4.45e-02s, cones: 8.36e-01s, accel: 4.67e-03s
------------------------------------------------------------------
objective = 8.382588
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 4.63e+00  2.02e-01  9.83e+01 -5.20e+00  1.00e-01  4.83e-02

(CVXPY) Jul 07 11:39:14 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:14 AM: Optimal value: 7.893e+00
(CVXPY) Jul 07 11:39:14 AM: Compilation took 5.654e-02 seconds
(CVXPY) Jul 07 11:39:14 AM: Solver (including time spent in interface) took 9.998e-01 seconds
(CVXPY) Jul 07 11:39:14 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:14 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:14 AM: DCP verification time: 0.0010 seconds.
(CVXPY) Jul 07 11:39:14 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:14 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:14 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:14 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:14 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:14 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:14 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:14 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:14 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:14 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:14 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:14 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:14 AM: Finished problem compilation (took 5.350e-02 seconds).
(CVXPY) Jul 07 11:39:14 AM: Invoking solver SCS  to obtain a solution.

    75| 1.09e-05  9.70e-08  1.34e-05  7.89e+00  1.00e-01  9.93e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.94e-01s = setup: 2.46e-02s + solve: 9.69e-01s
	 lin-sys: 4.72e-02s, cones: 9.03e-01s, accel: 4.65e-03s
------------------------------------------------------------------
objective = 7.893247
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 4.84e+00  2.17e-01  1.02e+02 -3.21e+00  1.00e-01  6.17e-02

(CVXPY) Jul 07 11:39:15 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:15 AM: Optimal value: 7.996e+00
(CVXPY) Jul 07 11:39:15 AM: Compilation took 5.350e-02 seconds
(CVXPY) Jul 07 11:39:15 AM: Solver (including time spent in interface) took 9.846e-01 seconds
(CVXPY) Jul 07 11:39:15 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:15 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:15 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:39:15 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:15 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:15 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:15 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:15 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:15 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:15 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:15 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:15 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:15 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:15 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:15 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:15 AM: Finished problem compilation (took 5.638e-02 seconds).
(CVXPY) Jul 07 11:39:15 AM: Invoking solver SCS  to obtain a solution.

    75| 9.28e-06  6.55e-08  1.09e-05  8.00e+00  1.00e-01  9.78e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.78e-01s = setup: 2.66e-02s + solve: 9.52e-01s
	 lin-sys: 5.52e-02s, cones: 8.73e-01s, accel: 5.49e-03s
------------------------------------------------------------------
objective = 7.996007
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 5.09e+00  2.35e-01  1.04e+02 -2.07e+00  1.00e-01  3.82e-02

(CVXPY) Jul 07 11:39:16 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:16 AM: Optimal value: 8.314e+00
(CVXPY) Jul 07 11:39:16 AM: Compilation took 5.638e-02 seconds
(CVXPY) Jul 07 11:39:16 AM: Solver (including time spent in interface) took 9.277e-01 seconds
(CVXPY) Jul 07 11:39:16 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:16 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:16 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:39:16 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:16 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:16 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:16 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:16 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:16 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:16 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:16 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:16 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:16 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:16 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:16 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:16 AM: Finished problem compilation (took 5.937e-02 seconds).
(CVXPY) Jul 07 11:39:16 AM: Invoking solver SCS  to obtain a solution.

    75| 9.93e-06  8.47e-08  1.11e-05  8.31e+00  1.00e-01  9.22e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.23e-01s = setup: 2.79e-02s + solve: 8.95e-01s
	 lin-sys: 5.16e-02s, cones: 8.20e-01s, accel: 5.32e-03s
------------------------------------------------------------------
objective = 8.313644
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 5.12e+00  2.37e-01  1.01e+02 -3.38e+00  1.00e-01  3.90e-02

(CVXPY) Jul 07 11:39:17 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:17 AM: Optimal value: 8.245e+00
(CVXPY) Jul 07 11:39:17 AM: Compilation took 5.937e-02 seconds
(CVXPY) Jul 07 11:39:17 AM: Solver (including time spent in interface) took 9.301e-01 seconds
(CVXPY) Jul 07 11:39:17 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:17 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:17 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:39:17 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:17 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:17 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:17 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:17 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:17 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:17 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:17 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:17 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:17 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:17 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:17 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:17 AM: Finished problem compilation (took 5.629e-02 seconds).
(CVXPY) Jul 07 11:39:17 AM: Invoking solver SCS  to obtain a solution.

    75| 9.79e-06  9.86e-08  1.01e-05  8.25e+00  1.00e-01  9.23e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.25e-01s = setup: 2.65e-02s + solve: 8.99e-01s
	 lin-sys: 4.66e-02s, cones: 8.29e-01s, accel: 4.97e-03s
------------------------------------------------------------------
objective = 8.245380
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 4.81e+00  2.15e-01  1.00e+02 -4.04e+00  1.00e-01  4.93e-02

(CVXPY) Jul 07 11:39:18 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:18 AM: Optimal value: 7.835e+00
(CVXPY) Jul 07 11:39:18 AM: Compilation took 5.629e-02 seconds
(CVXPY) Jul 07 11:39:18 AM: Solver (including time spent in interface) took 9.264e-01 seconds
(CVXPY) Jul 07 11:39:18 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:18 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:18 AM: DCP verification time: 0.0009 seconds.
(CVXPY) Jul 07 11:39:18 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:18 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:18 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:18 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:18 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:18 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:18 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:18 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:18 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:18 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:18 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:18 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:18 AM: Finished problem compilation (took 6.063e-02 seconds).
(CVXPY) Jul 07 11:39:18 AM: Invoking solver SCS  to obtain a solution.

    75| 1.11e-05  8.32e-08  1.27e-05  7.83e+00  1.00e-01  9.19e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.20e-01s = setup: 2.58e-02s + solve: 8.94e-01s
	 lin-sys: 4.80e-02s, cones: 8.27e-01s, accel: 5.03e-03s
------------------------------------------------------------------
objective = 7.834655
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 5.01e+00  2.30e-01  1.07e+02  8.42e-02  1.00e-01  4.75e-02

(CVXPY) Jul 07 11:39:19 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:19 AM: Optimal value: 8.398e+00
(CVXPY) Jul 07 11:39:19 AM: Compilation took 6.063e-02 seconds
(CVXPY) Jul 07 11:39:19 AM: Solver (including time spent in interface) took 9.306e-01 seconds
(CVXPY) Jul 07 11:39:19 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:19 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:19 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:39:19 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:19 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:19 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:19 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:19 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:19 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:19 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:19 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:19 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:19 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:19 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:19 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:19 AM: Finished problem compilation (took 6.094e-02 seconds).
(CVXPY) Jul 07 11:39:19 AM: Invoking solver SCS  to obtain a solution.

    75| 1.09e-05  7.60e-08  1.07e-05  8.40e+00  1.00e-01  9.25e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.25e-01s = setup: 2.57e-02s + solve: 9.00e-01s
	 lin-sys: 5.22e-02s, cones: 8.29e-01s, accel: 4.71e-03s
------------------------------------------------------------------
objective = 8.398381
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 5.30e+00  2.49e-01  1.01e+02 -3.87e+00  1.00e-01  4.64e-02

(CVXPY) Jul 07 11:39:20 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:20 AM: Optimal value: 8.226e+00
(CVXPY) Jul 07 11:39:20 AM: Compilation took 6.094e-02 seconds
(CVXPY) Jul 07 11:39:20 AM: Solver (including time spent in interface) took 9.350e-01 seconds
(CVXPY) Jul 07 11:39:20 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:20 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:20 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:39:20 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:20 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:20 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:20 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:20 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:20 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:20 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:20 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:20 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:20 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:20 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:20 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:20 AM: Finished problem compilation (took 6.018e-02 seconds).
(CVXPY) Jul 07 11:39:20 AM: Invoking solver SCS  to obtain a solution.

    75| 1.05e-05  1.11e-07  9.32e-06  8.23e+00  1.00e-01  9.29e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.29e-01s = setup: 2.46e-02s + solve: 9.05e-01s
	 lin-sys: 4.70e-02s, cones: 8.39e-01s, accel: 4.74e-03s
------------------------------------------------------------------
objective = 8.225623
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 4.83e+00  2.16e-01  9.94e+01 -4.59e+00  1.00e-01  6.73e-02

(CVXPY) Jul 07 11:39:21 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:21 AM: Optimal value: 7.954e+00
(CVXPY) Jul 07 11:39:21 AM: Compilation took 6.018e-02 seconds
(CVXPY) Jul 07 11:39:21 AM: Solver (including time spent in interface) took 9.739e-01 seconds
(CVXPY) Jul 07 11:39:21 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:21 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:21 AM: DCP verification time: 0.0020 seconds.
(CVXPY) Jul 07 11:39:21 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:21 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:21 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:21 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:21 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:21 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:21 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:21 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:21 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:21 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:21 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:21 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:21 AM: Finished problem compilation (took 5.829e-02 seconds).
(CVXPY) Jul 07 11:39:21 AM: Invoking solver SCS  to obtain a solution.

    75| 9.06e-06  8.87e-08  1.14e-05  7.95e+00  1.00e-01  9.67e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.67e-01s = setup: 4.13e-02s + solve: 9.26e-01s
	 lin-sys: 5.13e-02s, cones: 8.54e-01s, accel: 4.51e-03s
------------------------------------------------------------------
objective = 7.954303
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 5.02e+00  2.30e-01  1.06e+02 -6.43e-01  1.00e-01  4.98e-02

(CVXPY) Jul 07 11:39:22 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:22 AM: Optimal value: 8.385e+00
(CVXPY) Jul 07 11:39:22 AM: Compilation took 5.829e-02 seconds
(CVXPY) Jul 07 11:39:22 AM: Solver (including time spent in interface) took 1.067e+00 seconds
(CVXPY) Jul 07 11:39:22 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:22 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:22 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:39:22 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:22 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:22 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:22 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:22 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:22 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:22 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:22 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:22 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:22 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:22 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:22 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:22 AM: Finished problem compilation (took 6.040e-02 seconds).
(CVXPY) Jul 07 11:39:22 AM: Invoking solver SCS  to obtain a solution.

    75| 1.05e-05  7.89e-08  9.85e-06  8.38e+00  1.00e-01  1.06e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.06e+00s = setup: 2.78e-02s + solve: 1.03e+00s
	 lin-sys: 8.39e-02s, cones: 9.32e-01s, accel: 4.70e-03s
------------------------------------------------------------------
objective = 8.384889
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 5.10e+00  2.36e-01  1.05e+02 -1.46e+00  1.00e-01  4.26e-02

(CVXPY) Jul 07 11:39:23 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:23 AM: Optimal value: 8.356e+00
(CVXPY) Jul 07 11:39:23 AM: Compilation took 6.040e-02 seconds
(CVXPY) Jul 07 11:39:23 AM: Solver (including time spent in interface) took 9.188e-01 seconds
(CVXPY) Jul 07 11:39:23 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:23 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:23 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:39:23 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:23 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:23 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:23 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:23 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:23 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:23 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:23 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:23 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:23 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:23 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:23 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:23 AM: Finished problem compilation (took 6.582e-02 seconds).
(CVXPY) Jul 07 11:39:24 AM: Invoking solver SCS  to obtain a solution.

    75| 1.03e-05  9.28e-08  1.11e-05  8.36e+00  1.00e-01  9.14e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.14e-01s = setup: 2.26e-02s + solve: 8.92e-01s
	 lin-sys: 4.72e-02s, cones: 8.27e-01s, accel: 4.58e-03s
------------------------------------------------------------------
objective = 8.355744
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 4.77e+00  2.12e-01  1.02e+02 -3.25e+00  1.00e-01  4.74e-02

(CVXPY) Jul 07 11:39:24 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:24 AM: Optimal value: 8.057e+00
(CVXPY) Jul 07 11:39:24 AM: Compilation took 6.582e-02 seconds
(CVXPY) Jul 07 11:39:24 AM: Solver (including time spent in interface) took 9.642e-01 seconds
(CVXPY) Jul 07 11:39:24 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:24 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:24 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:39:24 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:24 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:24 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:24 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:24 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:24 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:24 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:25 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:25 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:25 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:25 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:25 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:25 AM: Finished problem compilation (took 5.351e-02 seconds).
(CVXPY) Jul 07 11:39:25 AM: Invoking solver SCS  to obtain a solution.

    75| 1.13e-05  7.35e-08  1.22e-05  8.06e+00  1.00e-01  9.59e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.60e-01s = setup: 2.41e-02s + solve: 9.36e-01s
	 lin-sys: 4.68e-02s, cones: 8.70e-01s, accel: 5.02e-03s
------------------------------------------------------------------
objective = 8.056572
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.90e+00  3.09e-01  2.74e+02 -8.97e+01  1.00e-01  4.97e-02

(CVXPY) Jul 07 11:39:26 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:26 AM: Optimal value: 1.499e+01
(CVXPY) Jul 07 11:39:26 AM: Compilation took 5.351e-02 seconds
(CVXPY) Jul 07 11:39:26 AM: Solver (including time spent in interface) took 9.547e-01 seconds
(CVXPY) Jul 07 11:39:26 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:26 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:26 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:39:26 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:26 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:26 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:26 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:26 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:26 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:26 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:26 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:26 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:26 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:26 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:26 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:26 AM: Finished problem compilation (took 6.034e-02 seconds).
(CVXPY) Jul 07 11:39:26 AM: Invoking solver SCS  to obtain a solution.

    75| 1.72e-05  1.62e-07  2.69e-05  1.50e+01  1.00e-01  9.47e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.48e-01s = setup: 2.67e-02s + solve: 9.21e-01s
	 lin-sys: 5.22e-02s, cones: 8.47e-01s, accel: 5.89e-03s
------------------------------------------------------------------
objective = 14.986233
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.98e+00  3.14e-01  2.75e+02 -8.88e+01  1.00e-01  4.78e-02

(CVXPY) Jul 07 11:39:27 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:27 AM: Optimal value: 1.553e+01
(CVXPY) Jul 07 11:39:27 AM: Compilation took 6.034e-02 seconds
(CVXPY) Jul 07 11:39:27 AM: Solver (including time spent in interface) took 9.762e-01 seconds
(CVXPY) Jul 07 11:39:27 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:27 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:27 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:39:27 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:27 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:27 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:27 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:27 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:27 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:27 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:27 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:27 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:27 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:27 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:27 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:27 AM: Finished problem compilation (took 5.649e-02 seconds).
(CVXPY) Jul 07 11:39:27 AM: Invoking solver SCS  to obtain a solution.

    75| 1.70e-05  1.83e-07  2.51e-05  1.55e+01  1.00e-01  9.70e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.71e-01s = setup: 2.52e-02s + solve: 9.45e-01s
	 lin-sys: 4.45e-02s, cones: 8.82e-01s, accel: 5.43e-03s
------------------------------------------------------------------
objective = 15.532861
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.88e+00  3.07e-01  2.76e+02 -8.83e+01  1.00e-01  4.46e-02

(CVXPY) Jul 07 11:39:28 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:28 AM: Optimal value: 1.560e+01
(CVXPY) Jul 07 11:39:28 AM: Compilation took 5.649e-02 seconds
(CVXPY) Jul 07 11:39:28 AM: Solver (including time spent in interface) took 1.054e+00 seconds
(CVXPY) Jul 07 11:39:28 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:28 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:28 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:39:28 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:28 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:28 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:28 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:28 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:28 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:28 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:28 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:28 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:28 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:28 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:28 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:28 AM: Finished problem compilation (took 6.206e-02 seconds).
(CVXPY) Jul 07 11:39:28 AM: Invoking solver SCS  to obtain a solution.

    75| 1.85e-05  1.86e-07  2.62e-05  1.56e+01  1.00e-01  1.05e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.05e+00s = setup: 2.29e-02s + solve: 1.02e+00s
	 lin-sys: 4.91e-02s, cones: 9.55e-01s, accel: 5.46e-03s
------------------------------------------------------------------
objective = 15.599687
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 8.03e+00  3.17e-01  2.76e+02 -8.86e+01  1.00e-01  4.90e-02

(CVXPY) Jul 07 11:39:29 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:29 AM: Optimal value: 1.556e+01
(CVXPY) Jul 07 11:39:29 AM: Compilation took 6.206e-02 seconds
(CVXPY) Jul 07 11:39:29 AM: Solver (including time spent in interface) took 8.434e-01 seconds
(CVXPY) Jul 07 11:39:29 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:29 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:29 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:39:29 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:29 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:29 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:29 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:29 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:29 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:29 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:29 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:29 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:29 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:29 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:29 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:29 AM: Finished problem compilation (took 6.240e-02 seconds).
(CVXPY) Jul 07 11:39:29 AM: Invoking solver SCS  to obtain a solution.

    75| 1.71e-05  1.88e-07  2.61e-05  1.56e+01  1.00e-01  8.38e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.38e-01s = setup: 2.47e-02s + solve: 8.13e-01s
	 lin-sys: 4.62e-02s, cones: 7.51e-01s, accel: 4.13e-03s
------------------------------------------------------------------
objective = 15.559408
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.91e+00  3.09e-01  2.73e+02 -9.02e+01  1.00e-01  3.40e-02

(CVXPY) Jul 07 11:39:30 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:30 AM: Optimal value: 1.495e+01
(CVXPY) Jul 07 11:39:30 AM: Compilation took 6.240e-02 seconds
(CVXPY) Jul 07 11:39:30 AM: Solver (including time spent in interface) took 8.673e-01 seconds
(CVXPY) Jul 07 11:39:30 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:30 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:30 AM: DCP verification time: 0.0010 seconds.
(CVXPY) Jul 07 11:39:30 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:30 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:30 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:30 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:30 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:30 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:30 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:30 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:30 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:30 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:30 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:30 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:30 AM: Finished problem compilation (took 5.428e-02 seconds).
(CVXPY) Jul 07 11:39:30 AM: Invoking solver SCS  to obtain a solution.

    75| 1.66e-05  1.65e-07  2.66e-05  1.49e+01  1.00e-01  8.60e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.60e-01s = setup: 2.41e-02s + solve: 8.36e-01s
	 lin-sys: 4.89e-02s, cones: 7.68e-01s, accel: 4.78e-03s
------------------------------------------------------------------
objective = 14.946365
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 8.05e+00  3.19e-01  2.79e+02 -8.63e+01  1.00e-01  4.52e-02

(CVXPY) Jul 07 11:39:31 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:31 AM: Optimal value: 1.579e+01
(CVXPY) Jul 07 11:39:31 AM: Compilation took 5.428e-02 seconds
(CVXPY) Jul 07 11:39:31 AM: Solver (including time spent in interface) took 8.644e-01 seconds
(CVXPY) Jul 07 11:39:31 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:31 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:31 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:39:31 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:31 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:31 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:31 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:31 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:31 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:31 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:31 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:31 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:31 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:31 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:31 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:31 AM: Finished problem compilation (took 5.392e-02 seconds).
(CVXPY) Jul 07 11:39:31 AM: Invoking solver SCS  to obtain a solution.

    75| 1.83e-05  1.76e-07  2.59e-05  1.58e+01  1.00e-01  8.58e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.59e-01s = setup: 2.47e-02s + solve: 8.34e-01s
	 lin-sys: 4.70e-02s, cones: 7.67e-01s, accel: 4.65e-03s
------------------------------------------------------------------
objective = 15.787216
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 8.04e+00  3.19e-01  2.75e+02 -8.88e+01  1.00e-01  4.47e-02

(CVXPY) Jul 07 11:39:32 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:32 AM: Optimal value: 1.551e+01
(CVXPY) Jul 07 11:39:32 AM: Compilation took 5.392e-02 seconds
(CVXPY) Jul 07 11:39:32 AM: Solver (including time spent in interface) took 8.907e-01 seconds
(CVXPY) Jul 07 11:39:32 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:32 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:32 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:39:32 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:32 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:32 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:32 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:32 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:32 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:32 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:32 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:32 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:32 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:32 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:32 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:32 AM: Finished problem compilation (took 5.962e-02 seconds).
(CVXPY) Jul 07 11:39:32 AM: Invoking solver SCS  to obtain a solution.

    75| 1.77e-05  1.86e-07  2.53e-05  1.55e+01  1.00e-01  8.85e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.85e-01s = setup: 2.37e-02s + solve: 8.61e-01s
	 lin-sys: 4.27e-02s, cones: 7.99e-01s, accel: 5.22e-03s
------------------------------------------------------------------
objective = 15.509199
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.91e+00  3.09e-01  2.69e+02 -9.21e+01  1.00e-01  3.42e-02

(CVXPY) Jul 07 11:39:32 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:32 AM: Optimal value: 1.475e+01
(CVXPY) Jul 07 11:39:32 AM: Compilation took 5.962e-02 seconds
(CVXPY) Jul 07 11:39:32 AM: Solver (including time spent in interface) took 8.208e-01 seconds
(CVXPY) Jul 07 11:39:32 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:32 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:32 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:39:32 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:32 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:32 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:32 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:32 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:32 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:32 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:32 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:32 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:32 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:32 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:32 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:32 AM: Finished problem compilation (took 5.152e-02 seconds).
(CVXPY) Jul 07 11:39:32 AM: Invoking solver SCS  to obtain a solution.

    75| 1.77e-05  1.63e-07  2.71e-05  1.48e+01  1.00e-01  8.15e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.16e-01s = setup: 2.47e-02s + solve: 7.91e-01s
	 lin-sys: 4.70e-02s, cones: 7.24e-01s, accel: 6.84e-03s
------------------------------------------------------------------
objective = 14.752117
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 8.06e+00  3.20e-01  2.76e+02 -8.82e+01  1.00e-01  4.19e-02

(CVXPY) Jul 07 11:39:33 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:33 AM: Optimal value: 1.571e+01
(CVXPY) Jul 07 11:39:33 AM: Compilation took 5.152e-02 seconds
(CVXPY) Jul 07 11:39:33 AM: Solver (including time spent in interface) took 8.641e-01 seconds
(CVXPY) Jul 07 11:39:33 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:33 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:33 AM: DCP verification time: 0.0009 seconds.
(CVXPY) Jul 07 11:39:33 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:33 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:33 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:33 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:33 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:33 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:33 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:33 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:33 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:33 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:33 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:33 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:33 AM: Finished problem compilation (took 5.760e-02 seconds).
(CVXPY) Jul 07 11:39:33 AM: Invoking solver SCS  to obtain a solution.

    75| 1.72e-05  1.87e-07  2.58e-05  1.57e+01  1.00e-01  8.60e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.60e-01s = setup: 2.27e-02s + solve: 8.37e-01s
	 lin-sys: 5.03e-02s, cones: 7.65e-01s, accel: 6.25e-03s
------------------------------------------------------------------
objective = 15.714669
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.90e+00  3.09e-01  2.71e+02 -9.14e+01  1.00e-01  4.48e-02

(CVXPY) Jul 07 11:39:34 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:34 AM: Optimal value: 1.473e+01
(CVXPY) Jul 07 11:39:34 AM: Compilation took 5.760e-02 seconds
(CVXPY) Jul 07 11:39:34 AM: Solver (including time spent in interface) took 9.028e-01 seconds
(CVXPY) Jul 07 11:39:34 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:34 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:34 AM: DCP verification time: 0.0017 seconds.
(CVXPY) Jul 07 11:39:34 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:34 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:34 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:34 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:34 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:34 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:34 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:34 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:34 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:34 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:34 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:34 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:34 AM: Finished problem compilation (took 8.509e-02 seconds).
(CVXPY) Jul 07 11:39:34 AM: Invoking solver SCS  to obtain a solution.

    75| 1.66e-05  1.59e-07  2.70e-05  1.47e+01  1.00e-01  8.96e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.96e-01s = setup: 2.44e-02s + solve: 8.72e-01s
	 lin-sys: 5.54e-02s, cones: 7.97e-01s, accel: 5.44e-03s
------------------------------------------------------------------
objective = 14.732109
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 8.11e+00  3.24e-01  2.74e+02 -8.94e+01  1.00e-01  4.48e-02

(CVXPY) Jul 07 11:39:35 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:35 AM: Optimal value: 1.494e+01
(CVXPY) Jul 07 11:39:35 AM: Compilation took 8.509e-02 seconds
(CVXPY) Jul 07 11:39:35 AM: Solver (including time spent in interface) took 8.807e-01 seconds
(CVXPY) Jul 07 11:39:35 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:35 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:35 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:39:35 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:35 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:35 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:35 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:35 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:35 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:35 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:35 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:35 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:35 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:35 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:35 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:35 AM: Finished problem compilation (took 5.303e-02 seconds).
(CVXPY) Jul 07 11:39:35 AM: Invoking solver SCS  to obtain a solution.

    75| 1.62e-05  1.67e-07  2.66e-05  1.49e+01  1.00e-01  8.75e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.75e-01s = setup: 2.40e-02s + solve: 8.51e-01s
	 lin-sys: 4.71e-02s, cones: 7.84e-01s, accel: 4.79e-03s
------------------------------------------------------------------
objective = 14.936587
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 8.05e+00  3.19e-01  2.76e+02 -8.82e+01  1.00e-01  4.77e-02

(CVXPY) Jul 07 11:39:36 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:36 AM: Optimal value: 1.557e+01
(CVXPY) Jul 07 11:39:36 AM: Compilation took 5.303e-02 seconds
(CVXPY) Jul 07 11:39:36 AM: Solver (including time spent in interface) took 1.051e+00 seconds
(CVXPY) Jul 07 11:39:36 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:36 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:36 AM: DCP verification time: 0.0003 seconds.
(CVXPY) Jul 07 11:39:36 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:36 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:36 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:36 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:36 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:36 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:36 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:36 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:36 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:36 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:36 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:36 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:37 AM: Finished problem compilation (took 5.449e-02 seconds).
(CVXPY) Jul 07 11:39:37 AM: Invoking solver SCS  to obtain a solution.

    75| 1.75e-05  1.91e-07  2.66e-05  1.56e+01  1.00e-01  1.04e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.04e+00s = setup: 2.63e-02s + solve: 1.02e+00s
	 lin-sys: 4.55e-02s, cones: 9.54e-01s, accel: 4.97e-03s
------------------------------------------------------------------
objective = 15.567077
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 8.09e+00  3.22e-01  2.74e+02 -8.96e+01  1.00e-01  4.54e-02

(CVXPY) Jul 07 11:39:37 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:37 AM: Optimal value: 1.544e+01
(CVXPY) Jul 07 11:39:37 AM: Compilation took 5.449e-02 seconds
(CVXPY) Jul 07 11:39:37 AM: Solver (including time spent in interface) took 9.436e-01 seconds
(CVXPY) Jul 07 11:39:37 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:37 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:37 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:39:37 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:37 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:37 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:37 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:37 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:37 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:37 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:37 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:37 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:38 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:38 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:38 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:38 AM: Finished problem compilation (took 5.536e-02 seconds).
(CVXPY) Jul 07 11:39:38 AM: Invoking solver SCS  to obtain a solution.

    75| 1.77e-05  1.92e-07  2.60e-05  1.54e+01  1.00e-01  9.38e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.39e-01s = setup: 2.40e-02s + solve: 9.15e-01s
	 lin-sys: 5.04e-02s, cones: 8.42e-01s, accel: 6.00e-03s
------------------------------------------------------------------
objective = 15.438346
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 8.07e+00  3.21e-01  2.73e+02 -9.02e+01  1.00e-01  4.30e-02

(CVXPY) Jul 07 11:39:38 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:38 AM: Optimal value: 1.463e+01
(CVXPY) Jul 07 11:39:38 AM: Compilation took 5.536e-02 seconds
(CVXPY) Jul 07 11:39:38 AM: Solver (including time spent in interface) took 9.473e-01 seconds
(CVXPY) Jul 07 11:39:39 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:39 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:39 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:39:39 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:39 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:39 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:39 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:39 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:39 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:39 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:39 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:39 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:39 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:39 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:39 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:39 AM: Finished problem compilation (took 6.207e-02 seconds).
(CVXPY) Jul 07 11:39:39 AM: Invoking solver SCS  to obtain a solution.

    75| 1.69e-05  1.77e-07  2.64e-05  1.46e+01  1.00e-01  9.42e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.42e-01s = setup: 2.34e-02s + solve: 9.18e-01s
	 lin-sys: 5.48e-02s, cones: 8.40e-01s, accel: 5.47e-03s
------------------------------------------------------------------
objective = 14.624903
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 8.03e+00  3.18e-01  2.80e+02 -8.61e+01  1.00e-01  5.06e-02

(CVXPY) Jul 07 11:39:39 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:40 AM: Optimal value: 1.575e+01
(CVXPY) Jul 07 11:39:40 AM: Compilation took 6.207e-02 seconds
(CVXPY) Jul 07 11:39:40 AM: Solver (including time spent in interface) took 9.202e-01 seconds
(CVXPY) Jul 07 11:39:40 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:40 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:40 AM: DCP verification time: 0.0003 seconds.
(CVXPY) Jul 07 11:39:40 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:40 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:40 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:40 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:40 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:40 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:40 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:40 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:40 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:40 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:40 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:40 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:40 AM: Finished problem compilation (took 4.706e-02 seconds).
(CVXPY) Jul 07 11:39:40 AM: Invoking solver SCS  to obtain a solution.

    75| 1.80e-05  1.77e-07  2.57e-05  1.57e+01  1.00e-01  9.16e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.17e-01s = setup: 2.62e-02s + solve: 8.90e-01s
	 lin-sys: 5.66e-02s, cones: 8.14e-01s, accel: 5.80e-03s
------------------------------------------------------------------
objective = 15.746873
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 8.10e+00  3.23e-01  2.73e+02 -9.00e+01  1.00e-01  4.74e-02

(CVXPY) Jul 07 11:39:41 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:41 AM: Optimal value: 1.541e+01
(CVXPY) Jul 07 11:39:41 AM: Compilation took 4.706e-02 seconds
(CVXPY) Jul 07 11:39:41 AM: Solver (including time spent in interface) took 9.483e-01 seconds
(CVXPY) Jul 07 11:39:41 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:41 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:41 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:39:41 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:41 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:41 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:41 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:41 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:41 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:41 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:41 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:41 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:41 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:41 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:41 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:41 AM: Finished problem compilation (took 4.701e-02 seconds).
(CVXPY) Jul 07 11:39:41 AM: Invoking solver SCS  to obtain a solution.

    75| 1.68e-05  1.90e-07  2.52e-05  1.54e+01  1.00e-01  9.44e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.44e-01s = setup: 2.46e-02s + solve: 9.20e-01s
	 lin-sys: 5.30e-02s, cones: 8.46e-01s, accel: 4.66e-03s
------------------------------------------------------------------
objective = 15.411570
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 8.08e+00  3.21e-01  2.72e+02 -9.08e+01  1.00e-01  4.85e-02

(CVXPY) Jul 07 11:39:42 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:42 AM: Optimal value: 1.485e+01
(CVXPY) Jul 07 11:39:42 AM: Compilation took 4.701e-02 seconds
(CVXPY) Jul 07 11:39:42 AM: Solver (including time spent in interface) took 9.199e-01 seconds
(CVXPY) Jul 07 11:39:42 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:42 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:42 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:39:42 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:42 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:42 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:42 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:42 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:42 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:42 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:42 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:42 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:42 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:42 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:42 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:42 AM: Finished problem compilation (took 4.989e-02 seconds).
(CVXPY) Jul 07 11:39:42 AM: Invoking solver SCS  to obtain a solution.

    75| 1.97e-05  1.65e-07  2.78e-05  1.48e+01  1.00e-01  9.15e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.15e-01s = setup: 2.56e-02s + solve: 8.89e-01s
	 lin-sys: 5.48e-02s, cones: 8.15e-01s, accel: 4.85e-03s
------------------------------------------------------------------
objective = 14.849266
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 8.06e+00  3.20e-01  2.79e+02 -8.68e+01  1.00e-01  4.74e-02

(CVXPY) Jul 07 11:39:42 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:42 AM: Optimal value: 1.572e+01
(CVXPY) Jul 07 11:39:42 AM: Compilation took 4.989e-02 seconds
(CVXPY) Jul 07 11:39:42 AM: Solver (including time spent in interface) took 8.931e-01 seconds
(CVXPY) Jul 07 11:39:42 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:42 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:42 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:39:42 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:42 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:42 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:42 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:42 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:42 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:42 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:42 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:42 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:42 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:42 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:43 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:43 AM: Finished problem compilation (took 5.034e-02 seconds).
(CVXPY) Jul 07 11:39:43 AM: Invoking solver SCS  to obtain a solution.

    75| 1.95e-05  1.77e-07  2.54e-05  1.57e+01  1.00e-01  8.88e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.88e-01s = setup: 2.69e-02s + solve: 8.61e-01s
	 lin-sys: 5.52e-02s, cones: 7.88e-01s, accel: 4.97e-03s
------------------------------------------------------------------
objective = 15.724747
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 8.08e+00  3.21e-01  2.77e+02 -8.76e+01  1.00e-01  4.55e-02

(CVXPY) Jul 07 11:39:43 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:43 AM: Optimal value: 1.566e+01
(CVXPY) Jul 07 11:39:43 AM: Compilation took 5.034e-02 seconds
(CVXPY) Jul 07 11:39:43 AM: Solver (including time spent in interface) took 8.441e-01 seconds
(CVXPY) Jul 07 11:39:43 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:43 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:43 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:39:43 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:43 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:43 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:43 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:43 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:43 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:43 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:43 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:43 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:43 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:43 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:43 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:43 AM: Finished problem compilation (took 6.369e-02 seconds).
(CVXPY) Jul 07 11:39:43 AM: Invoking solver SCS  to obtain a solution.

    75| 1.64e-05  1.82e-07  2.57e-05  1.57e+01  1.00e-01  8.40e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.40e-01s = setup: 2.52e-02s + solve: 8.15e-01s
	 lin-sys: 5.57e-02s, cones: 7.41e-01s, accel: 4.92e-03s
------------------------------------------------------------------
objective = 15.655862
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 8.06e+00  3.20e-01  2.74e+02 -8.94e+01  1.00e-01  4.71e-02

(CVXPY) Jul 07 11:39:45 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:45 AM: Optimal value: 1.505e+01
(CVXPY) Jul 07 11:39:45 AM: Compilation took 6.369e-02 seconds
(CVXPY) Jul 07 11:39:45 AM: Solver (including time spent in interface) took 1.203e+00 seconds
(CVXPY) Jul 07 11:39:45 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:45 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:45 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:39:45 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:45 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:45 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:45 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:45 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:45 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:45 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:45 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:45 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:45 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:45 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:45 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:45 AM: Finished problem compilation (took 5.424e-02 seconds).
(CVXPY) Jul 07 11:39:45 AM: Invoking solver SCS  to obtain a solution.

    75| 1.77e-05  1.71e-07  2.70e-05  1.51e+01  1.00e-01  1.20e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.20e+00s = setup: 2.64e-02s + solve: 1.17e+00s
	 lin-sys: 5.65e-02s, cones: 1.10e+00s, accel: 4.43e-03s
------------------------------------------------------------------
objective = 15.051233
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.12e+01  4.20e-01  5.61e+02 -2.33e+02  1.00e-01  4.60e-02

(CVXPY) Jul 07 11:39:46 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:46 AM: Optimal value: 2.125e+01
(CVXPY) Jul 07 11:39:46 AM: Compilation took 5.424e-02 seconds
(CVXPY) Jul 07 11:39:46 AM: Solver (including time spent in interface) took 9.521e-01 seconds
(CVXPY) Jul 07 11:39:46 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:46 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:46 AM: DCP verification time: 0.0009 seconds.
(CVXPY) Jul 07 11:39:46 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:46 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:46 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:46 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:46 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:46 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:46 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:46 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:46 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:46 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:46 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:46 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:46 AM: Finished problem compilation (took 5.260e-02 seconds).
(CVXPY) Jul 07 11:39:46 AM: Invoking solver SCS  to obtain a solution.

    75| 2.91e-05  1.62e-07  2.87e-05  2.13e+01  1.00e-01  9.47e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.47e-01s = setup: 2.38e-02s + solve: 9.23e-01s
	 lin-sys: 5.43e-02s, cones: 8.49e-01s, accel: 5.73e-03s
------------------------------------------------------------------
objective = 21.253988
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.12e+01  4.16e-01  5.62e+02 -2.32e+02  1.00e-01  4.98e-02

(CVXPY) Jul 07 11:39:47 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:47 AM: Optimal value: 2.209e+01
(CVXPY) Jul 07 11:39:47 AM: Compilation took 5.260e-02 seconds
(CVXPY) Jul 07 11:39:47 AM: Solver (including time spent in interface) took 9.349e-01 seconds
(CVXPY) Jul 07 11:39:47 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:47 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:47 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:39:47 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:47 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:47 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:47 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:47 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:47 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:47 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:47 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:47 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:47 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:47 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:47 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:47 AM: Finished problem compilation (took 5.073e-02 seconds).
(CVXPY) Jul 07 11:39:47 AM: Invoking solver SCS  to obtain a solution.

    75| 2.67e-05  2.17e-07  3.03e-05  2.21e+01  1.00e-01  9.29e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.30e-01s = setup: 2.38e-02s + solve: 9.06e-01s
	 lin-sys: 5.92e-02s, cones: 8.27e-01s, accel: 5.52e-03s
------------------------------------------------------------------
objective = 22.085402
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.12e+01  4.17e-01  5.63e+02 -2.32e+02  1.00e-01  5.65e-02

(CVXPY) Jul 07 11:39:48 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:48 AM: Optimal value: 2.218e+01
(CVXPY) Jul 07 11:39:48 AM: Compilation took 5.073e-02 seconds
(CVXPY) Jul 07 11:39:48 AM: Solver (including time spent in interface) took 9.361e-01 seconds
(CVXPY) Jul 07 11:39:48 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:48 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:48 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:39:48 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:48 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:48 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:48 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:48 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:48 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:48 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:48 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:48 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:48 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:48 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:48 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:48 AM: Finished problem compilation (took 5.639e-02 seconds).
(CVXPY) Jul 07 11:39:48 AM: Invoking solver SCS  to obtain a solution.

    75| 2.79e-05  2.16e-07  3.08e-05  2.22e+01  1.00e-01  9.30e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.31e-01s = setup: 2.49e-02s + solve: 9.06e-01s
	 lin-sys: 6.19e-02s, cones: 8.24e-01s, accel: 4.70e-03s
------------------------------------------------------------------
objective = 22.175587
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.12e+01  4.16e-01  5.63e+02 -2.32e+02  1.00e-01  5.11e-02

(CVXPY) Jul 07 11:39:49 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:49 AM: Optimal value: 2.212e+01
(CVXPY) Jul 07 11:39:49 AM: Compilation took 5.639e-02 seconds
(CVXPY) Jul 07 11:39:49 AM: Solver (including time spent in interface) took 9.188e-01 seconds
(CVXPY) Jul 07 11:39:49 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:49 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:49 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:39:49 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:49 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:49 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:49 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:49 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:49 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:49 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:49 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:49 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:49 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:49 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:49 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:49 AM: Finished problem compilation (took 6.690e-02 seconds).
(CVXPY) Jul 07 11:39:49 AM: Invoking solver SCS  to obtain a solution.

    75| 2.72e-05  2.23e-07  3.07e-05  2.21e+01  1.00e-01  9.14e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.15e-01s = setup: 2.74e-02s + solve: 8.87e-01s
	 lin-sys: 5.50e-02s, cones: 8.11e-01s, accel: 4.98e-03s
------------------------------------------------------------------
objective = 22.118222
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.12e+01  4.19e-01  5.60e+02 -2.34e+02  1.00e-01  3.41e-02

(CVXPY) Jul 07 11:39:50 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:50 AM: Optimal value: 2.120e+01
(CVXPY) Jul 07 11:39:50 AM: Compilation took 6.690e-02 seconds
(CVXPY) Jul 07 11:39:50 AM: Solver (including time spent in interface) took 1.153e+00 seconds
(CVXPY) Jul 07 11:39:50 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:50 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:50 AM: DCP verification time: 0.0003 seconds.
(CVXPY) Jul 07 11:39:50 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:50 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:50 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:50 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:50 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:50 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:50 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:50 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:50 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:50 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:50 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:50 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:50 AM: Finished problem compilation (took 5.211e-02 seconds).
(CVXPY) Jul 07 11:39:50 AM: Invoking solver SCS  to obtain a solution.

    75| 2.59e-05  1.82e-07  3.15e-05  2.12e+01  1.00e-01  1.15e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.15e+00s = setup: 2.42e-02s + solve: 1.12e+00s
	 lin-sys: 5.92e-02s, cones: 1.04e+00s, accel: 5.44e-03s
------------------------------------------------------------------
objective = 21.197680
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.14e+01  4.29e-01  5.67e+02 -2.30e+02  1.00e-01  5.03e-02

(CVXPY) Jul 07 11:39:51 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:51 AM: Optimal value: 2.247e+01
(CVXPY) Jul 07 11:39:51 AM: Compilation took 5.211e-02 seconds
(CVXPY) Jul 07 11:39:51 AM: Solver (including time spent in interface) took 9.304e-01 seconds
(CVXPY) Jul 07 11:39:51 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:51 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:51 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:39:51 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:51 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:51 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:51 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:51 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:51 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:51 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:51 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:51 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:51 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:51 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:51 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:51 AM: Finished problem compilation (took 6.748e-02 seconds).
(CVXPY) Jul 07 11:39:51 AM: Invoking solver SCS  to obtain a solution.

    75| 2.54e-05  2.07e-07  3.05e-05  2.25e+01  1.00e-01  9.24e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.24e-01s = setup: 2.54e-02s + solve: 8.99e-01s
	 lin-sys: 6.04e-02s, cones: 8.18e-01s, accel: 5.00e-03s
------------------------------------------------------------------
objective = 22.465494
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.12e+01  4.15e-01  5.62e+02 -2.32e+02  1.00e-01  5.81e-02

(CVXPY) Jul 07 11:39:52 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:52 AM: Optimal value: 2.205e+01
(CVXPY) Jul 07 11:39:52 AM: Compilation took 6.748e-02 seconds
(CVXPY) Jul 07 11:39:52 AM: Solver (including time spent in interface) took 1.020e+00 seconds
(CVXPY) Jul 07 11:39:52 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:52 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:52 AM: DCP verification time: 0.0009 seconds.
(CVXPY) Jul 07 11:39:52 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:52 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:52 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:52 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:52 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:52 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:52 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:52 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:52 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:52 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:52 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:52 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:52 AM: Finished problem compilation (took 5.728e-02 seconds).
(CVXPY) Jul 07 11:39:52 AM: Invoking solver SCS  to obtain a solution.

    75| 2.62e-05  2.47e-07  3.37e-05  2.20e+01  1.00e-01  1.02e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.02e+00s = setup: 3.19e-02s + solve: 9.84e-01s
	 lin-sys: 6.47e-02s, cones: 8.93e-01s, accel: 7.15e-03s
------------------------------------------------------------------
objective = 22.049808
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.12e+01  4.16e-01  5.57e+02 -2.36e+02  1.00e-01  5.42e-02

(CVXPY) Jul 07 11:39:53 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:53 AM: Optimal value: 2.090e+01
(CVXPY) Jul 07 11:39:53 AM: Compilation took 5.728e-02 seconds
(CVXPY) Jul 07 11:39:53 AM: Solver (including time spent in interface) took 9.421e-01 seconds
(CVXPY) Jul 07 11:39:53 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:53 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:53 AM: DCP verification time: 0.0009 seconds.
(CVXPY) Jul 07 11:39:53 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:53 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:53 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:53 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:53 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:53 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:53 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:53 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:53 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:53 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:53 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:53 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:53 AM: Finished problem compilation (took 6.636e-02 seconds).
(CVXPY) Jul 07 11:39:53 AM: Invoking solver SCS  to obtain a solution.

    75| 2.64e-05  1.57e-07  2.87e-05  2.09e+01  1.00e-01  9.37e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.38e-01s = setup: 2.98e-02s + solve: 9.08e-01s
	 lin-sys: 5.42e-02s, cones: 8.34e-01s, accel: 4.62e-03s
------------------------------------------------------------------
objective = 20.902034
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.12e+01  4.14e-01  5.63e+02 -2.32e+02  1.00e-01  4.82e-02

(CVXPY) Jul 07 11:39:54 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:54 AM: Optimal value: 2.236e+01
(CVXPY) Jul 07 11:39:54 AM: Compilation took 6.636e-02 seconds
(CVXPY) Jul 07 11:39:54 AM: Solver (including time spent in interface) took 1.009e+00 seconds
(CVXPY) Jul 07 11:39:54 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:54 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:54 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:39:54 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:54 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:54 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:54 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:54 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:54 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:54 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:54 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:54 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:54 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:54 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:54 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:54 AM: Finished problem compilation (took 6.194e-02 seconds).
(CVXPY) Jul 07 11:39:54 AM: Invoking solver SCS  to obtain a solution.

    75| 2.53e-05  2.14e-07  3.00e-05  2.24e+01  1.00e-01  1.00e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.00e+00s = setup: 2.66e-02s + solve: 9.76e-01s
	 lin-sys: 5.27e-02s, cones: 9.05e-01s, accel: 5.17e-03s
------------------------------------------------------------------
objective = 22.355248
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.12e+01  4.18e-01  5.58e+02 -2.35e+02  1.00e-01  4.51e-02

(CVXPY) Jul 07 11:39:55 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:55 AM: Optimal value: 2.087e+01
(CVXPY) Jul 07 11:39:55 AM: Compilation took 6.194e-02 seconds
(CVXPY) Jul 07 11:39:55 AM: Solver (including time spent in interface) took 8.984e-01 seconds
(CVXPY) Jul 07 11:39:55 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:55 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:55 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:39:55 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:55 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:55 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:55 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:55 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:55 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:55 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:55 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:55 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:55 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:55 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:55 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:55 AM: Finished problem compilation (took 5.842e-02 seconds).
(CVXPY) Jul 07 11:39:55 AM: Invoking solver SCS  to obtain a solution.

    75| 2.58e-05  1.77e-07  3.21e-05  2.09e+01  1.00e-01  8.92e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.92e-01s = setup: 2.43e-02s + solve: 8.68e-01s
	 lin-sys: 5.35e-02s, cones: 7.97e-01s, accel: 4.81e-03s
------------------------------------------------------------------
objective = 20.866865
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.14e+01  4.31e-01  5.61e+02 -2.33e+02  1.00e-01  4.95e-02

(CVXPY) Jul 07 11:39:56 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:56 AM: Optimal value: 2.118e+01
(CVXPY) Jul 07 11:39:56 AM: Compilation took 5.842e-02 seconds
(CVXPY) Jul 07 11:39:56 AM: Solver (including time spent in interface) took 9.243e-01 seconds
(CVXPY) Jul 07 11:39:56 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:56 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:56 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:39:56 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:56 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:56 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:56 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:56 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:56 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:56 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:56 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:56 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:56 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:56 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:56 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:56 AM: Finished problem compilation (took 5.711e-02 seconds).
(CVXPY) Jul 07 11:39:56 AM: Invoking solver SCS  to obtain a solution.

    75| 2.61e-05  2.03e-07  3.18e-05  2.12e+01  1.00e-01  9.18e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.18e-01s = setup: 2.78e-02s + solve: 8.91e-01s
	 lin-sys: 5.47e-02s, cones: 8.17e-01s, accel: 4.43e-03s
------------------------------------------------------------------
objective = 21.178164
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.14e+01  4.29e-01  5.63e+02 -2.32e+02  1.00e-01  4.82e-02

(CVXPY) Jul 07 11:39:57 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:57 AM: Optimal value: 2.212e+01
(CVXPY) Jul 07 11:39:57 AM: Compilation took 5.711e-02 seconds
(CVXPY) Jul 07 11:39:57 AM: Solver (including time spent in interface) took 8.453e-01 seconds
(CVXPY) Jul 07 11:39:57 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:57 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:57 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:39:57 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:57 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:57 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:57 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:57 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:57 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:57 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:57 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:57 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:57 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:57 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:57 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:57 AM: Finished problem compilation (took 5.952e-02 seconds).
(CVXPY) Jul 07 11:39:57 AM: Invoking solver SCS  to obtain a solution.

    75| 2.74e-05  2.25e-07  3.15e-05  2.21e+01  1.00e-01  8.40e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.40e-01s = setup: 2.60e-02s + solve: 8.14e-01s
	 lin-sys: 5.62e-02s, cones: 7.39e-01s, accel: 5.16e-03s
------------------------------------------------------------------
objective = 22.121486
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.14e+01  4.28e-01  5.61e+02 -2.33e+02  1.00e-01  4.45e-02

(CVXPY) Jul 07 11:39:58 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:58 AM: Optimal value: 2.193e+01
(CVXPY) Jul 07 11:39:58 AM: Compilation took 5.952e-02 seconds
(CVXPY) Jul 07 11:39:58 AM: Solver (including time spent in interface) took 1.007e+00 seconds
(CVXPY) Jul 07 11:39:58 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:58 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:58 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:39:58 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:58 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:58 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:58 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:58 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:58 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:58 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:58 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:58 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:58 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:58 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:58 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:58 AM: Finished problem compilation (took 6.418e-02 seconds).
(CVXPY) Jul 07 11:39:58 AM: Invoking solver SCS  to obtain a solution.

    75| 2.71e-05  2.20e-07  3.12e-05  2.19e+01  1.00e-01  1.00e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.00e+00s = setup: 2.44e-02s + solve: 9.77e-01s
	 lin-sys: 5.52e-02s, cones: 9.01e-01s, accel: 7.83e-03s
------------------------------------------------------------------
objective = 21.930561
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.14e+01  4.30e-01  5.60e+02 -2.34e+02  1.00e-01  5.15e-02

(CVXPY) Jul 07 11:39:59 AM: Problem status: optimal
(CVXPY) Jul 07 11:39:59 AM: Optimal value: 2.071e+01
(CVXPY) Jul 07 11:39:59 AM: Compilation took 6.418e-02 seconds
(CVXPY) Jul 07 11:39:59 AM: Solver (including time spent in interface) took 9.356e-01 seconds
(CVXPY) Jul 07 11:39:59 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:39:59 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:39:59 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:39:59 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:39:59 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:39:59 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:39:59 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:39:59 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:39:59 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:39:59 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:39:59 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:39:59 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:39:59 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:39:59 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:39:59 AM: Applying reduction SCS
(CVXPY) Jul 07 11:39:59 AM: Finished problem compilation (took 5.424e-02 seconds).
(CVXPY) Jul 07 11:39:59 AM: Invoking solver SCS  to obtain a solution.

    75| 2.62e-05  1.91e-07  2.85e-05  2.07e+01  1.00e-01  9.30e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.31e-01s = setup: 2.64e-02s + solve: 9.04e-01s
	 lin-sys: 5.50e-02s, cones: 8.29e-01s, accel: 4.97e-03s
------------------------------------------------------------------
objective = 20.711493
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.14e+01  4.29e-01  5.67e+02 -2.30e+02  1.00e-01  4.46e-02

(CVXPY) Jul 07 11:40:00 AM: Problem status: optimal
(CVXPY) Jul 07 11:40:00 AM: Optimal value: 2.241e+01
(CVXPY) Jul 07 11:40:00 AM: Compilation took 5.424e-02 seconds
(CVXPY) Jul 07 11:40:00 AM: Solver (including time spent in interface) took 9.369e-01 seconds
(CVXPY) Jul 07 11:40:00 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:40:00 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:40:00 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:40:00 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:40:00 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:40:00 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:40:00 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:40:00 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:40:00 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:40:00 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:40:00 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:40:00 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:40:00 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:40:00 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:40:00 AM: Applying reduction SCS
(CVXPY) Jul 07 11:40:00 AM: Finished problem compilation (took 5.081e-02 seconds).
(CVXPY) Jul 07 11:40:00 AM: Invoking solver SCS  to obtain a solution.

    75| 2.71e-05  2.07e-07  3.00e-05  2.24e+01  1.00e-01  9.33e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.33e-01s = setup: 2.55e-02s + solve: 9.08e-01s
	 lin-sys: 5.59e-02s, cones: 8.32e-01s, accel: 5.08e-03s
------------------------------------------------------------------
objective = 22.409301
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.11e+01  4.12e-01  5.60e+02 -2.34e+02  1.00e-01  4.53e-02

(CVXPY) Jul 07 11:40:01 AM: Problem status: optimal
(CVXPY) Jul 07 11:40:01 AM: Optimal value: 2.191e+01
(CVXPY) Jul 07 11:40:01 AM: Compilation took 5.081e-02 seconds
(CVXPY) Jul 07 11:40:01 AM: Solver (including time spent in interface) took 9.053e-01 seconds
(CVXPY) Jul 07 11:40:01 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:40:01 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:40:01 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:40:01 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:40:01 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:40:01 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:40:01 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:40:01 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:40:01 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:40:01 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:40:01 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:40:01 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:40:01 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:40:01 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:40:01 AM: Applying reduction SCS
(CVXPY) Jul 07 11:40:01 AM: Finished problem compilation (took 5.319e-02 seconds).
(CVXPY) Jul 07 11:40:01 AM: Invoking solver SCS  to obtain a solution.

    75| 2.59e-05  2.57e-07  3.35e-05  2.19e+01  1.00e-01  9.00e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.01e-01s = setup: 2.39e-02s + solve: 8.77e-01s
	 lin-sys: 6.07e-02s, cones: 7.95e-01s, accel: 5.49e-03s
------------------------------------------------------------------
objective = 21.913828
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.14e+01  4.28e-01  5.59e+02 -2.34e+02  1.00e-01  4.59e-02

(CVXPY) Jul 07 11:40:02 AM: Problem status: optimal
(CVXPY) Jul 07 11:40:02 AM: Optimal value: 2.103e+01
(CVXPY) Jul 07 11:40:02 AM: Compilation took 5.319e-02 seconds
(CVXPY) Jul 07 11:40:02 AM: Solver (including time spent in interface) took 9.266e-01 seconds
(CVXPY) Jul 07 11:40:02 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:40:02 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:40:02 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:40:02 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:40:02 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:40:02 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:40:02 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:40:02 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:40:02 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:40:02 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:40:02 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:40:02 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:40:02 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:40:02 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:40:02 AM: Applying reduction SCS
(CVXPY) Jul 07 11:40:02 AM: Finished problem compilation (took 5.767e-02 seconds).
(CVXPY) Jul 07 11:40:02 AM: Invoking solver SCS  to obtain a solution.

    75| 2.51e-05  1.82e-07  3.24e-05  2.10e+01  1.00e-01  9.21e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.21e-01s = setup: 2.50e-02s + solve: 8.96e-01s
	 lin-sys: 5.22e-02s, cones: 8.25e-01s, accel: 4.26e-03s
------------------------------------------------------------------
objective = 21.034494
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.14e+01  4.30e-01  5.66e+02 -2.30e+02  1.00e-01  4.53e-02

(CVXPY) Jul 07 11:40:03 AM: Problem status: optimal
(CVXPY) Jul 07 11:40:03 AM: Optimal value: 2.237e+01
(CVXPY) Jul 07 11:40:03 AM: Compilation took 5.767e-02 seconds
(CVXPY) Jul 07 11:40:03 AM: Solver (including time spent in interface) took 9.316e-01 seconds
(CVXPY) Jul 07 11:40:03 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:40:03 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:40:03 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:40:03 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:40:03 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:40:03 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:40:03 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:40:03 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:40:03 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:40:03 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:40:03 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:40:03 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:40:03 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:40:03 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:40:03 AM: Applying reduction SCS
(CVXPY) Jul 07 11:40:03 AM: Finished problem compilation (took 5.670e-02 seconds).
(CVXPY) Jul 07 11:40:03 AM: Invoking solver SCS  to obtain a solution.

    75| 2.68e-05  2.28e-07  3.28e-05  2.24e+01  1.00e-01  9.27e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.27e-01s = setup: 2.52e-02s + solve: 9.02e-01s
	 lin-sys: 4.95e-02s, cones: 8.33e-01s, accel: 4.59e-03s
------------------------------------------------------------------
objective = 22.373983
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.14e+01  4.30e-01  5.64e+02 -2.31e+02  1.00e-01  5.00e-02

(CVXPY) Jul 07 11:40:04 AM: Problem status: optimal
(CVXPY) Jul 07 11:40:04 AM: Optimal value: 2.226e+01
(CVXPY) Jul 07 11:40:04 AM: Compilation took 5.670e-02 seconds
(CVXPY) Jul 07 11:40:04 AM: Solver (including time spent in interface) took 9.079e-01 seconds
(CVXPY) Jul 07 11:40:04 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:40:04 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:40:04 AM: DCP verification time: 0.0009 seconds.
(CVXPY) Jul 07 11:40:04 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:40:04 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:40:04 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:40:04 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:40:04 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:40:04 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:40:04 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:40:04 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:40:04 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:40:04 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:40:04 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:40:04 AM: Applying reduction SCS
(CVXPY) Jul 07 11:40:04 AM: Finished problem compilation (took 5.548e-02 seconds).
(CVXPY) Jul 07 11:40:04 AM: Invoking solver SCS  to obtain a solution.

    75| 2.70e-05  2.19e-07  3.06e-05  2.23e+01  1.00e-01  9.04e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.04e-01s = setup: 2.59e-02s + solve: 8.78e-01s
	 lin-sys: 5.34e-02s, cones: 8.05e-01s, accel: 5.26e-03s
------------------------------------------------------------------
objective = 22.262844
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.14e+01  4.29e-01  5.61e+02 -2.33e+02  1.00e-01  4.54e-02

(CVXPY) Jul 07 11:40:05 AM: Problem status: optimal
(CVXPY) Jul 07 11:40:05 AM: Optimal value: 2.135e+01
(CVXPY) Jul 07 11:40:05 AM: Compilation took 5.548e-02 seconds
(CVXPY) Jul 07 11:40:05 AM: Solver (including time spent in interface) took 1.011e+00 seconds
(CVXPY) Jul 07 11:40:05 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:40:05 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:40:05 AM: DCP verification time: 0.0012 seconds.
(CVXPY) Jul 07 11:40:05 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:40:05 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:40:05 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:40:05 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:40:05 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:40:05 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:40:05 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:40:05 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:40:05 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:40:05 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:40:05 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:40:05 AM: Applying reduction SCS
(CVXPY) Jul 07 11:40:05 AM: Finished problem compilation (took 6.082e-02 seconds).
(CVXPY) Jul 07 11:40:05 AM: Invoking solver SCS  to obtain a solution.

    75| 2.70e-05  1.86e-07  2.89e-05  2.13e+01  1.00e-01  1.01e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.01e+00s = setup: 2.38e-02s + solve: 9.82e-01s
	 lin-sys: 6.22e-02s, cones: 8.99e-01s, accel: 6.12e-03s
------------------------------------------------------------------
objective = 21.347126
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.46e+01  5.32e-01  9.63e+02 -4.34e+02  1.00e-01  4.80e-02

(CVXPY) Jul 07 11:40:07 AM: Problem status: optimal
(CVXPY) Jul 07 11:40:07 AM: Optimal value: 2.702e+01
(CVXPY) Jul 07 11:40:07 AM: Compilation took 6.082e-02 seconds
(CVXPY) Jul 07 11:40:07 AM: Solver (including time spent in interface) took 1.224e+00 seconds
(CVXPY) Jul 07 11:40:07 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:40:07 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:40:07 AM: DCP verification time: 0.0003 seconds.
(CVXPY) Jul 07 11:40:07 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:40:07 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:40:07 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:40:07 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:40:07 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:40:07 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:40:07 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:40:07 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:40:07 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:40:07 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:40:07 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:40:07 AM: Applying reduction SCS
(CVXPY) Jul 07 11:40:07 AM: Finished problem compilation (took 6.834e-02 seconds).
(CVXPY) Jul 07 11:40:07 AM: Invoking solver SCS  to obtain a solution.

   100| 2.45e-06  1.20e-08  2.10e-06  2.70e+01  1.00e-01  1.22e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.22e+00s = setup: 2.75e-02s + solve: 1.19e+00s
	 lin-sys: 6.42e-02s, cones: 1.10e+00s, accel: 8.09e-03s
------------------------------------------------------------------
objective = 27.017315
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.45e+01  5.27e-01  9.64e+02 -4.34e+02  1.00e-01  4.49e-02

(CVXPY) Jul 07 11:40:08 AM: Problem status: optimal
(CVXPY) Jul 07 11:40:08 AM: Optimal value: 2.814e+01
(CVXPY) Jul 07 11:40:08 AM: Compilation took 6.834e-02 seconds
(CVXPY) Jul 07 11:40:08 AM: Solver (including time spent in interface) took 8.285e-01 seconds
(CVXPY) Jul 07 11:40:08 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:40:08 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:40:08 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:40:08 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:40:08 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:40:08 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:40:08 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:40:08 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:40:08 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:40:08 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:40:08 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:40:08 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:40:08 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:40:08 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:40:08 AM: Applying reduction SCS
(CVXPY) Jul 07 11:40:08 AM: Finished problem compilation (took 6.187e-02 seconds).
(CVXPY) Jul 07 11:40:08 AM: Invoking solver SCS  to obtain a solution.

    75| 2.99e-05  2.59e-07  3.39e-05  2.81e+01  1.00e-01  8.20e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.21e-01s = setup: 2.27e-02s + solve: 7.98e-01s
	 lin-sys: 4.52e-02s, cones: 7.33e-01s, accel: 4.47e-03s
------------------------------------------------------------------
objective = 28.138626
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.46e+01  5.29e-01  9.65e+02 -4.33e+02  1.00e-01  7.44e-02

(CVXPY) Jul 07 11:40:09 AM: Problem status: optimal
(CVXPY) Jul 07 11:40:09 AM: Optimal value: 2.825e+01
(CVXPY) Jul 07 11:40:09 AM: Compilation took 6.187e-02 seconds
(CVXPY) Jul 07 11:40:09 AM: Solver (including time spent in interface) took 1.174e+00 seconds
(CVXPY) Jul 07 11:40:09 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:40:09 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:40:09 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:40:09 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:40:09 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:40:09 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:40:09 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:40:09 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:40:09 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:40:09 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:40:09 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:40:09 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:40:09 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:40:09 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:40:09 AM: Applying reduction SCS
(CVXPY) Jul 07 11:40:09 AM: Finished problem compilation (took 6.046e-02 seconds).
(CVXPY) Jul 07 11:40:09 AM: Invoking solver SCS  to obtain a solution.

   100| 2.73e-06  1.43e-08  2.04e-06  2.82e+01  1.00e-01  1.17e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.17e+00s = setup: 2.40e-02s + solve: 1.14e+00s
	 lin-sys: 7.91e-02s, cones: 1.04e+00s, accel: 9.12e-03s
------------------------------------------------------------------
objective = 28.249477
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.45e+01  5.27e-01  9.65e+02 -4.33e+02  1.00e-01  4.97e-02

(CVXPY) Jul 07 11:40:10 AM: Problem status: optimal
(CVXPY) Jul 07 11:40:10 AM: Optimal value: 2.818e+01
(CVXPY) Jul 07 11:40:10 AM: Compilation took 6.046e-02 seconds
(CVXPY) Jul 07 11:40:10 AM: Solver (including time spent in interface) took 1.428e+00 seconds
(CVXPY) Jul 07 11:40:10 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:40:10 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:40:10 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:40:10 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:40:10 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:40:10 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:40:10 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:40:10 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:40:10 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:40:10 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:40:10 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:40:10 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:40:10 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:40:10 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:40:10 AM: Applying reduction SCS
(CVXPY) Jul 07 11:40:10 AM: Finished problem compilation (took 5.841e-02 seconds).
(CVXPY) Jul 07 11:40:10 AM: Invoking solver SCS  to obtain a solution.

   100| 2.26e-06  1.45e-08  2.01e-06  2.82e+01  1.00e-01  1.42e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.42e+00s = setup: 2.74e-02s + solve: 1.39e+00s
	 lin-sys: 6.64e-02s, cones: 1.30e+00s, accel: 8.05e-03s
------------------------------------------------------------------
objective = 28.179069
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.46e+01  5.31e-01  9.62e+02 -4.35e+02  1.00e-01  4.85e-02

(CVXPY) Jul 07 11:40:12 AM: Problem status: optimal
(CVXPY) Jul 07 11:40:12 AM: Optimal value: 2.695e+01
(CVXPY) Jul 07 11:40:12 AM: Compilation took 5.841e-02 seconds
(CVXPY) Jul 07 11:40:12 AM: Solver (including time spent in interface) took 1.122e+00 seconds
(CVXPY) Jul 07 11:40:12 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:40:12 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:40:12 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:40:12 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:40:12 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:40:12 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:40:12 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:40:12 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:40:12 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:40:12 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:40:12 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:40:12 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:40:12 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:40:12 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:40:12 AM: Applying reduction SCS
(CVXPY) Jul 07 11:40:12 AM: Finished problem compilation (took 5.980e-02 seconds).
(CVXPY) Jul 07 11:40:12 AM: Invoking solver SCS  to obtain a solution.

   100| 2.95e-06  1.20e-08  2.09e-06  2.69e+01  1.00e-01  1.11e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.11e+00s = setup: 2.64e-02s + solve: 1.09e+00s
	 lin-sys: 6.51e-02s, cones: 9.95e-01s, accel: 7.02e-03s
------------------------------------------------------------------
objective = 26.948299
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.47e+01  5.40e-01  9.69e+02 -4.31e+02  1.00e-01  6.51e-02

(CVXPY) Jul 07 11:40:13 AM: Problem status: optimal
(CVXPY) Jul 07 11:40:13 AM: Optimal value: 2.865e+01
(CVXPY) Jul 07 11:40:13 AM: Compilation took 5.980e-02 seconds
(CVXPY) Jul 07 11:40:13 AM: Solver (including time spent in interface) took 1.167e+00 seconds
(CVXPY) Jul 07 11:40:13 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:40:13 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:40:13 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:40:13 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:40:13 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:40:13 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:40:13 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:40:13 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:40:13 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:40:13 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:40:13 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:40:13 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:40:13 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:40:13 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:40:13 AM: Applying reduction SCS
(CVXPY) Jul 07 11:40:13 AM: Finished problem compilation (took 5.857e-02 seconds).
(CVXPY) Jul 07 11:40:13 AM: Invoking solver SCS  to obtain a solution.

   100| 2.55e-06  1.43e-08  2.06e-06  2.86e+01  1.00e-01  1.16e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.16e+00s = setup: 2.52e-02s + solve: 1.14e+00s
	 lin-sys: 6.40e-02s, cones: 1.05e+00s, accel: 8.12e-03s
------------------------------------------------------------------
objective = 28.648811
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.45e+01  5.26e-01  9.64e+02 -4.34e+02  1.00e-01  5.12e-02

(CVXPY) Jul 07 11:40:14 AM: Problem status: optimal
(CVXPY) Jul 07 11:40:14 AM: Optimal value: 2.809e+01
(CVXPY) Jul 07 11:40:14 AM: Compilation took 5.857e-02 seconds
(CVXPY) Jul 07 11:40:14 AM: Solver (including time spent in interface) took 1.244e+00 seconds
(CVXPY) Jul 07 11:40:14 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:40:14 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:40:14 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:40:14 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:40:14 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:40:14 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:40:14 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:40:14 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:40:14 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:40:14 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:40:14 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:40:14 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:40:14 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:40:14 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:40:14 AM: Applying reduction SCS
(CVXPY) Jul 07 11:40:14 AM: Finished problem compilation (took 5.698e-02 seconds).
(CVXPY) Jul 07 11:40:14 AM: Invoking solver SCS  to obtain a solution.

   100| 2.52e-06  1.48e-08  2.05e-06  2.81e+01  1.00e-01  1.24e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.24e+00s = setup: 2.42e-02s + solve: 1.22e+00s
	 lin-sys: 6.45e-02s, cones: 1.12e+00s, accel: 7.31e-03s
------------------------------------------------------------------
objective = 28.094669
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.45e+01  5.27e-01  9.59e+02 -4.37e+02  1.00e-01  4.89e-02

(CVXPY) Jul 07 11:40:15 AM: Problem status: optimal
(CVXPY) Jul 07 11:40:15 AM: Optimal value: 2.654e+01
(CVXPY) Jul 07 11:40:15 AM: Compilation took 5.698e-02 seconds
(CVXPY) Jul 07 11:40:15 AM: Solver (including time spent in interface) took 1.195e+00 seconds
(CVXPY) Jul 07 11:40:15 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:40:15 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:40:15 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:40:15 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:40:15 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:40:15 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:40:15 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:40:15 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:40:15 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:40:15 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:40:15 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:40:15 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:40:15 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:40:15 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:40:16 AM: Applying reduction SCS
(CVXPY) Jul 07 11:40:16 AM: Finished problem compilation (took 5.711e-02 seconds).
(CVXPY) Jul 07 11:40:16 AM: Invoking solver SCS  to obtain a solution.

   100| 2.51e-06  1.15e-08  2.06e-06  2.65e+01  1.00e-01  1.19e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.19e+00s = setup: 2.40e-02s + solve: 1.17e+00s
	 lin-sys: 6.80e-02s, cones: 1.07e+00s, accel: 7.03e-03s
------------------------------------------------------------------
objective = 26.542652
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.45e+01  5.27e-01  9.66e+02 -4.33e+02  1.00e-01  4.75e-02

(CVXPY) Jul 07 11:40:16 AM: Problem status: optimal
(CVXPY) Jul 07 11:40:16 AM: Optimal value: 2.850e+01
(CVXPY) Jul 07 11:40:16 AM: Compilation took 5.711e-02 seconds
(CVXPY) Jul 07 11:40:16 AM: Solver (including time spent in interface) took 8.887e-01 seconds
(CVXPY) Jul 07 11:40:16 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:40:16 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:40:16 AM: DCP verification time: 0.0011 seconds.
(CVXPY) Jul 07 11:40:16 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:40:16 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:40:16 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:40:16 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:40:16 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:40:16 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:40:16 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:40:16 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:40:16 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:40:16 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:40:16 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:40:16 AM: Applying reduction SCS
(CVXPY) Jul 07 11:40:17 AM: Finished problem compilation (took 6.264e-02 seconds).
(CVXPY) Jul 07 11:40:17 AM: Invoking solver SCS  to obtain a solution.

    75| 3.03e-05  2.18e-07  3.03e-05  2.85e+01  1.00e-01  8.84e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.84e-01s = setup: 2.55e-02s + solve: 8.59e-01s
	 lin-sys: 4.92e-02s, cones: 7.87e-01s, accel: 5.84e-03s
------------------------------------------------------------------
objective = 28.497303
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.46e+01  5.29e-01  9.60e+02 -4.36e+02  1.00e-01  4.64e-02

(CVXPY) Jul 07 11:40:18 AM: Problem status: optimal
(CVXPY) Jul 07 11:40:18 AM: Optimal value: 2.650e+01
(CVXPY) Jul 07 11:40:18 AM: Compilation took 6.264e-02 seconds
(CVXPY) Jul 07 11:40:18 AM: Solver (including time spent in interface) took 1.035e+00 seconds
(CVXPY) Jul 07 11:40:18 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:40:18 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:40:18 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:40:18 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:40:18 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:40:18 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:40:18 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:40:18 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:40:18 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:40:18 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:40:18 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:40:18 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:40:18 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:40:18 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:40:18 AM: Applying reduction SCS
(CVXPY) Jul 07 11:40:18 AM: Finished problem compilation (took 6.627e-02 seconds).
(CVXPY) Jul 07 11:40:18 AM: Invoking solver SCS  to obtain a solution.

    75| 3.15e-05  2.01e-07  3.50e-05  2.65e+01  1.00e-01  1.03e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.03e+00s = setup: 2.35e-02s + solve: 1.01e+00s
	 lin-sys: 5.08e-02s, cones: 9.33e-01s, accel: 6.68e-03s
------------------------------------------------------------------
objective = 26.497563
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.47e+01  5.40e-01  9.64e+02 -4.34e+02  1.00e-01  5.01e-02

(CVXPY) Jul 07 11:40:19 AM: Problem status: optimal
(CVXPY) Jul 07 11:40:19 AM: Optimal value: 2.692e+01
(CVXPY) Jul 07 11:40:19 AM: Compilation took 6.627e-02 seconds
(CVXPY) Jul 07 11:40:19 AM: Solver (including time spent in interface) took 1.035e+00 seconds
(CVXPY) Jul 07 11:40:19 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:40:19 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:40:19 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:40:19 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:40:19 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:40:19 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:40:19 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:40:19 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:40:19 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:40:19 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:40:19 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:40:19 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:40:19 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:40:19 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:40:19 AM: Applying reduction SCS
(CVXPY) Jul 07 11:40:19 AM: Finished problem compilation (took 5.793e-02 seconds).
(CVXPY) Jul 07 11:40:19 AM: Invoking solver SCS  to obtain a solution.

    75| 3.08e-05  2.24e-07  3.47e-05  2.69e+01  1.00e-01  1.03e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.03e+00s = setup: 2.76e-02s + solve: 1.00e+00s
	 lin-sys: 4.89e-02s, cones: 9.34e-01s, accel: 5.31e-03s
------------------------------------------------------------------
objective = 26.916872
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.47e+01  5.38e-01  9.66e+02 -4.33e+02  1.00e-01  4.79e-02

(CVXPY) Jul 07 11:40:20 AM: Problem status: optimal
(CVXPY) Jul 07 11:40:20 AM: Optimal value: 2.817e+01
(CVXPY) Jul 07 11:40:20 AM: Compilation took 5.793e-02 seconds
(CVXPY) Jul 07 11:40:20 AM: Solver (including time spent in interface) took 1.018e+00 seconds
(CVXPY) Jul 07 11:40:20 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:40:20 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:40:20 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:40:20 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:40:20 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:40:20 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:40:20 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:40:20 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:40:20 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:40:20 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:40:20 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:40:20 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:40:20 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:40:20 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:40:20 AM: Applying reduction SCS
(CVXPY) Jul 07 11:40:20 AM: Finished problem compilation (took 5.722e-02 seconds).
(CVXPY) Jul 07 11:40:20 AM: Invoking solver SCS  to obtain a solution.

    75| 3.46e-05  2.41e-07  3.40e-05  2.82e+01  1.00e-01  1.01e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.01e+00s = setup: 2.61e-02s + solve: 9.87e-01s
	 lin-sys: 4.84e-02s, cones: 9.17e-01s, accel: 6.53e-03s
------------------------------------------------------------------
objective = 28.171899
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.46e+01  5.36e-01  9.63e+02 -4.34e+02  1.00e-01  4.81e-02

(CVXPY) Jul 07 11:40:21 AM: Problem status: optimal
(CVXPY) Jul 07 11:40:21 AM: Optimal value: 2.792e+01
(CVXPY) Jul 07 11:40:21 AM: Compilation took 5.722e-02 seconds
(CVXPY) Jul 07 11:40:21 AM: Solver (including time spent in interface) took 1.066e+00 seconds
(CVXPY) Jul 07 11:40:21 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:40:21 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:40:21 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:40:21 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:40:21 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:40:21 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:40:21 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:40:21 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:40:21 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:40:21 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:40:21 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:40:21 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:40:21 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:40:21 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:40:21 AM: Applying reduction SCS
(CVXPY) Jul 07 11:40:21 AM: Finished problem compilation (took 6.969e-02 seconds).
(CVXPY) Jul 07 11:40:21 AM: Invoking solver SCS  to obtain a solution.

   100| 2.19e-06  1.45e-08  2.06e-06  2.79e+01  1.00e-01  1.06e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.06e+00s = setup: 2.52e-02s + solve: 1.04e+00s
	 lin-sys: 6.25e-02s, cones: 9.45e-01s, accel: 8.05e-03s
------------------------------------------------------------------
objective = 27.916846
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.47e+01  5.39e-01  9.62e+02 -4.35e+02  1.00e-01  4.79e-02

(CVXPY) Jul 07 11:40:22 AM: Problem status: optimal
(CVXPY) Jul 07 11:40:22 AM: Optimal value: 2.629e+01
(CVXPY) Jul 07 11:40:22 AM: Compilation took 6.969e-02 seconds
(CVXPY) Jul 07 11:40:22 AM: Solver (including time spent in interface) took 1.198e+00 seconds
(CVXPY) Jul 07 11:40:22 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:40:22 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:40:22 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:40:22 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:40:22 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:40:22 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:40:22 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:40:22 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:40:22 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:40:22 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:40:22 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:40:22 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:40:22 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:40:22 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:40:22 AM: Applying reduction SCS
(CVXPY) Jul 07 11:40:22 AM: Finished problem compilation (took 5.783e-02 seconds).
(CVXPY) Jul 07 11:40:22 AM: Invoking solver SCS  to obtain a solution.

    75| 2.94e-05  2.30e-07  3.43e-05  2.63e+01  1.00e-01  1.19e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.19e+00s = setup: 2.40e-02s + solve: 1.17e+00s
	 lin-sys: 4.62e-02s, cones: 1.10e+00s, accel: 5.86e-03s
------------------------------------------------------------------
objective = 26.288559
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.47e+01  5.40e-01  9.69e+02 -4.31e+02  1.00e-01  4.71e-02

(CVXPY) Jul 07 11:40:24 AM: Problem status: optimal
(CVXPY) Jul 07 11:40:24 AM: Optimal value: 2.859e+01
(CVXPY) Jul 07 11:40:24 AM: Compilation took 5.783e-02 seconds
(CVXPY) Jul 07 11:40:24 AM: Solver (including time spent in interface) took 1.196e+00 seconds
(CVXPY) Jul 07 11:40:24 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:40:24 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:40:24 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:40:24 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:40:24 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:40:24 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:40:24 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:40:24 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:40:24 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:40:24 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:40:24 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:40:24 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:40:24 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:40:24 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:40:24 AM: Applying reduction SCS
(CVXPY) Jul 07 11:40:24 AM: Finished problem compilation (took 5.430e-02 seconds).
(CVXPY) Jul 07 11:40:24 AM: Invoking solver SCS  to obtain a solution.

   100| 2.36e-06  1.41e-08  2.02e-06  2.86e+01  1.00e-01  1.19e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.19e+00s = setup: 2.53e-02s + solve: 1.17e+00s
	 lin-sys: 6.28e-02s, cones: 1.08e+00s, accel: 8.95e-03s
------------------------------------------------------------------
objective = 28.585732
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.45e+01  5.23e-01  9.62e+02 -4.35e+02  1.00e-01  4.79e-02

(CVXPY) Jul 07 11:40:24 AM: Problem status: optimal
(CVXPY) Jul 07 11:40:24 AM: Optimal value: 2.792e+01
(CVXPY) Jul 07 11:40:24 AM: Compilation took 5.430e-02 seconds
(CVXPY) Jul 07 11:40:24 AM: Solver (including time spent in interface) took 8.798e-01 seconds
(CVXPY) Jul 07 11:40:24 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:40:24 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:40:24 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:40:24 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:40:24 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:40:24 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:40:24 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:40:24 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:40:24 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:40:24 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:40:24 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:40:24 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:40:25 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:40:25 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:40:25 AM: Applying reduction SCS
(CVXPY) Jul 07 11:40:25 AM: Finished problem compilation (took 5.709e-02 seconds).
(CVXPY) Jul 07 11:40:25 AM: Invoking solver SCS  to obtain a solution.

    75| 3.71e-05  2.61e-07  3.37e-05  2.79e+01  1.00e-01  8.75e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.75e-01s = setup: 2.54e-02s + solve: 8.50e-01s
	 lin-sys: 4.69e-02s, cones: 7.83e-01s, accel: 4.86e-03s
------------------------------------------------------------------
objective = 27.922694
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.47e+01  5.37e-01  9.61e+02 -4.35e+02  1.00e-01  4.41e-02

(CVXPY) Jul 07 11:40:26 AM: Problem status: optimal
(CVXPY) Jul 07 11:40:26 AM: Optimal value: 2.671e+01
(CVXPY) Jul 07 11:40:26 AM: Compilation took 5.709e-02 seconds
(CVXPY) Jul 07 11:40:26 AM: Solver (including time spent in interface) took 1.278e+00 seconds
(CVXPY) Jul 07 11:40:26 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:40:26 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:40:26 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:40:26 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:40:26 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:40:26 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:40:26 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:40:26 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:40:26 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:40:26 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:40:26 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:40:26 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:40:26 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:40:26 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:40:26 AM: Applying reduction SCS
(CVXPY) Jul 07 11:40:26 AM: Finished problem compilation (took 5.906e-02 seconds).
(CVXPY) Jul 07 11:40:26 AM: Invoking solver SCS  to obtain a solution.

   100| 3.00e-06  1.24e-08  2.20e-06  2.67e+01  1.00e-01  1.27e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.27e+00s = setup: 2.38e-02s + solve: 1.25e+00s
	 lin-sys: 6.95e-02s, cones: 1.15e+00s, accel: 7.31e-03s
------------------------------------------------------------------
objective = 26.711116
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.47e+01  5.39e-01  9.68e+02 -4.32e+02  1.00e-01  4.38e-02

(CVXPY) Jul 07 11:40:27 AM: Problem status: optimal
(CVXPY) Jul 07 11:40:27 AM: Optimal value: 2.853e+01
(CVXPY) Jul 07 11:40:27 AM: Compilation took 5.906e-02 seconds
(CVXPY) Jul 07 11:40:27 AM: Solver (including time spent in interface) took 1.114e+00 seconds
(CVXPY) Jul 07 11:40:27 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:40:27 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:40:27 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:40:27 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:40:27 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:40:27 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:40:27 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:40:27 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:40:27 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:40:27 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:40:27 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:40:27 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:40:27 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:40:27 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:40:27 AM: Applying reduction SCS
(CVXPY) Jul 07 11:40:27 AM: Finished problem compilation (took 5.792e-02 seconds).
(CVXPY) Jul 07 11:40:27 AM: Invoking solver SCS  to obtain a solution.

   100| 2.59e-06  1.38e-08  1.98e-06  2.85e+01  1.00e-01  1.11e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.11e+00s = setup: 2.27e-02s + solve: 1.09e+00s
	 lin-sys: 6.19e-02s, cones: 9.97e-01s, accel: 7.20e-03s
------------------------------------------------------------------
objective = 28.529337
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.47e+01  5.39e-01  9.67e+02 -4.32e+02  1.00e-01  5.17e-02

(CVXPY) Jul 07 11:40:28 AM: Problem status: optimal
(CVXPY) Jul 07 11:40:28 AM: Optimal value: 2.838e+01
(CVXPY) Jul 07 11:40:28 AM: Compilation took 5.792e-02 seconds
(CVXPY) Jul 07 11:40:28 AM: Solver (including time spent in interface) took 1.210e+00 seconds
(CVXPY) Jul 07 11:40:28 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:40:28 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:40:28 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:40:28 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:40:28 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:40:28 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:40:28 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:40:28 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:40:28 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:40:28 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:40:28 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:40:28 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:40:28 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:40:28 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:40:28 AM: Applying reduction SCS
(CVXPY) Jul 07 11:40:28 AM: Finished problem compilation (took 5.638e-02 seconds).
(CVXPY) Jul 07 11:40:28 AM: Invoking solver SCS  to obtain a solution.

   100| 2.50e-06  1.43e-08  2.05e-06  2.84e+01  1.00e-01  1.20e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.20e+00s = setup: 2.72e-02s + solve: 1.18e+00s
	 lin-sys: 6.38e-02s, cones: 1.09e+00s, accel: 7.59e-03s
------------------------------------------------------------------
objective = 28.376135
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.47e+01  5.38e-01  9.63e+02 -4.34e+02  1.00e-01  4.70e-02

(CVXPY) Jul 07 11:40:29 AM: Problem status: optimal
(CVXPY) Jul 07 11:40:29 AM: Optimal value: 2.713e+01
(CVXPY) Jul 07 11:40:29 AM: Compilation took 5.638e-02 seconds
(CVXPY) Jul 07 11:40:29 AM: Solver (including time spent in interface) took 8.356e-01 seconds
(CVXPY) Jul 07 11:40:29 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:40:29 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:40:29 AM: DCP verification time: 0.0010 seconds.
(CVXPY) Jul 07 11:40:29 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:40:29 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:40:29 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:40:29 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:40:29 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:40:29 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:40:29 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:40:29 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:40:29 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:40:29 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:40:29 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:40:29 AM: Applying reduction SCS
(CVXPY) Jul 07 11:40:29 AM: Finished problem compilation (took 7.354e-02 seconds).
(CVXPY) Jul 07 11:40:29 AM: Invoking solver SCS  to obtain a solution.

    75| 2.99e-05  2.23e-07  3.45e-05  2.71e+01  1.00e-01  8.30e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.30e-01s = setup: 2.56e-02s + solve: 8.05e-01s
	 lin-sys: 4.98e-02s, cones: 7.36e-01s, accel: 4.65e-03s
------------------------------------------------------------------
objective = 27.128612
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  7.02e-02  4.60e-01  1.90e+00  1.00e-01  5.05e-02

(CVXPY) Jul 07 11:40:32 AM: Problem status: optimal
(CVXPY) Jul 07 11:40:32 AM: Optimal value: 7.434e-17
(CVXPY) Jul 07 11:40:32 AM: Compilation took 7.354e-02 seconds
(CVXPY) Jul 07 11:40:32 AM: Solver (including time spent in interface) took 2.488e+00 seconds
(CVXPY) Jul 07 11:40:32 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:40:32 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:40:32 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:40:32 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:40:32 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:40:32 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:40:32 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:40:32 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:40:32 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:40:32 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:40:32 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:40:32 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:40:32 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:40:32 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:40:32 AM: Applying reduction SCS
(CVXPY) Jul 07 11:40:32 AM: Finished problem compilation (took 6.454e-02 seconds).
(CVXPY) Jul 07 11:40:32 AM: Invoking solver SCS  to obtain a solution.

   225| 4.29e-08  2.67e-13  5.92e-12  2.96e-12  1.30e-05  2.48e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.48e+00s = setup: 2.84e-02s + solve: 2.45e+00s
	 lin-sys: 1.47e-01s, cones: 2.25e+00s, accel: 1.33e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  1.30e-01  5.26e-02  2.75e+00  1.00e-01  3.91e-02

(CVXPY) Jul 07 11:40:34 AM: Problem status: optimal
(CVXPY) Jul 07 11:40:34 AM: Optimal value: 3.386e-17
(CVXPY) Jul 07 11:40:34 AM: Compilation took 6.454e-02 seconds
(CVXPY) Jul 07 11:40:34 AM: Solver (including time spent in interface) took 2.418e+00 seconds
(CVXPY) Jul 07 11:40:34 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:40:34 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:40:34 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:40:34 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:40:34 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:40:34 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:40:34 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:40:34 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:40:34 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:40:34 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:40:34 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:40:34 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:40:34 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:40:34 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:40:34 AM: Applying reduction SCS
(CVXPY) Jul 07 11:40:34 AM: Finished problem compilation (took 5.916e-02 seconds).
(CVXPY) Jul 07 11:40:34 AM: Invoking solver SCS  to obtain a solution.

   225| 4.71e-08  1.33e-13  5.51e-12  2.75e-12  6.98e-06  2.41e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.41e+00s = setup: 2.55e-02s + solve: 2.39e+00s
	 lin-sys: 1.42e-01s, cones: 2.19e+00s, accel: 1.47e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  1.24e-01  1.90e-01  2.79e+00  1.00e-01  3.61e-02

(CVXPY) Jul 07 11:40:37 AM: Problem status: optimal
(CVXPY) Jul 07 11:40:37 AM: Optimal value: 3.935e-17
(CVXPY) Jul 07 11:40:37 AM: Compilation took 5.916e-02 seconds
(CVXPY) Jul 07 11:40:37 AM: Solver (including time spent in interface) took 2.457e+00 seconds
(CVXPY) Jul 07 11:40:37 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:40:37 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:40:37 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:40:37 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:40:37 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:40:37 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:40:37 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:40:37 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:40:37 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:40:37 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:40:37 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:40:37 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:40:37 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:40:37 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:40:37 AM: Applying reduction SCS
(CVXPY) Jul 07 11:40:37 AM: Finished problem compilation (took 5.134e-02 seconds).
(CVXPY) Jul 07 11:40:37 AM: Invoking solver SCS  to obtain a solution.

   225| 4.68e-08  1.72e-13  5.45e-12  2.73e-12  7.83e-06  2.45e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.45e+00s = setup: 2.57e-02s + solve: 2.43e+00s
	 lin-sys: 1.39e-01s, cones: 2.23e+00s, accel: 1.54e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  1.26e-01  4.23e-02  2.86e+00  1.00e-01  5.24e-02

(CVXPY) Jul 07 11:40:39 AM: Problem status: optimal
(CVXPY) Jul 07 11:40:39 AM: Optimal value: 4.249e-17
(CVXPY) Jul 07 11:40:39 AM: Compilation took 5.134e-02 seconds
(CVXPY) Jul 07 11:40:39 AM: Solver (including time spent in interface) took 2.467e+00 seconds
(CVXPY) Jul 07 11:40:39 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:40:39 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:40:39 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:40:39 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:40:39 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:40:39 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:40:39 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:40:39 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:40:39 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:40:39 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:40:39 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:40:39 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:40:39 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:40:39 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:40:39 AM: Applying reduction SCS
(CVXPY) Jul 07 11:40:39 AM: Finished problem compilation (took 5.386e-02 seconds).
(CVXPY) Jul 07 11:40:39 AM: Invoking solver SCS  to obtain a solution.

   225| 4.71e-08  1.74e-13  5.39e-12  2.69e-12  7.53e-06  2.46e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.46e+00s = setup: 2.35e-02s + solve: 2.44e+00s
	 lin-sys: 1.34e-01s, cones: 2.25e+00s, accel: 1.69e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  7.02e-02  4.52e-01  1.90e+00  1.00e-01  5.21e-02

(CVXPY) Jul 07 11:40:42 AM: Problem status: optimal
(CVXPY) Jul 07 11:40:42 AM: Optimal value: 6.079e-17
(CVXPY) Jul 07 11:40:42 AM: Compilation took 5.386e-02 seconds
(CVXPY) Jul 07 11:40:42 AM: Solver (including time spent in interface) took 2.546e+00 seconds
(CVXPY) Jul 07 11:40:42 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:40:42 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:40:42 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:40:42 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:40:42 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:40:42 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:40:42 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:40:42 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:40:42 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:40:42 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:40:42 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:40:42 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:40:42 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:40:42 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:40:42 AM: Applying reduction SCS
(CVXPY) Jul 07 11:40:42 AM: Finished problem compilation (took 7.019e-02 seconds).
(CVXPY) Jul 07 11:40:42 AM: Invoking solver SCS  to obtain a solution.

   225| 4.27e-08  2.78e-13  5.59e-12  2.79e-12  1.30e-05  2.54e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.54e+00s = setup: 2.78e-02s + solve: 2.51e+00s
	 lin-sys: 1.40e-01s, cones: 2.32e+00s, accel: 1.37e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  1.22e-01  1.31e-01  3.10e+00  1.00e-01  5.06e-02

(CVXPY) Jul 07 11:40:45 AM: Problem status: optimal
(CVXPY) Jul 07 11:40:45 AM: Optimal value: 6.096e-17
(CVXPY) Jul 07 11:40:45 AM: Compilation took 7.019e-02 seconds
(CVXPY) Jul 07 11:40:45 AM: Solver (including time spent in interface) took 2.487e+00 seconds
(CVXPY) Jul 07 11:40:45 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:40:45 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:40:45 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:40:45 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:40:45 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:40:45 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:40:45 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:40:45 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:40:45 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:40:45 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:40:45 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:40:45 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:40:45 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:40:45 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:40:45 AM: Applying reduction SCS
(CVXPY) Jul 07 11:40:45 AM: Finished problem compilation (took 5.306e-02 seconds).
(CVXPY) Jul 07 11:40:45 AM: Invoking solver SCS  to obtain a solution.

   225| 4.80e-08  2.01e-13  6.50e-12  3.25e-12  7.96e-06  2.48e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.48e+00s = setup: 2.67e-02s + solve: 2.45e+00s
	 lin-sys: 1.43e-01s, cones: 2.26e+00s, accel: 1.59e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  1.29e-01  5.15e-02  2.82e+00  1.00e-01  5.61e-02

(CVXPY) Jul 07 11:40:47 AM: Problem status: optimal
(CVXPY) Jul 07 11:40:47 AM: Optimal value: 3.719e-17
(CVXPY) Jul 07 11:40:47 AM: Compilation took 5.306e-02 seconds
(CVXPY) Jul 07 11:40:47 AM: Solver (including time spent in interface) took 2.502e+00 seconds
(CVXPY) Jul 07 11:40:47 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:40:47 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:40:47 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:40:47 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:40:47 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:40:47 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:40:47 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:40:47 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:40:47 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:40:47 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:40:47 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:40:47 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:40:47 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:40:47 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:40:47 AM: Applying reduction SCS
(CVXPY) Jul 07 11:40:47 AM: Finished problem compilation (took 5.364e-02 seconds).
(CVXPY) Jul 07 11:40:47 AM: Invoking solver SCS  to obtain a solution.

   225| 4.80e-08  1.57e-13  5.37e-12  2.68e-12  7.13e-06  2.50e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.50e+00s = setup: 3.09e-02s + solve: 2.47e+00s
	 lin-sys: 1.42e-01s, cones: 2.27e+00s, accel: 1.50e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  7.02e-02  4.02e-01  1.69e+00  1.00e-01  4.96e-02

(CVXPY) Jul 07 11:40:50 AM: Problem status: optimal
(CVXPY) Jul 07 11:40:50 AM: Optimal value: 5.413e-17
(CVXPY) Jul 07 11:40:50 AM: Compilation took 5.364e-02 seconds
(CVXPY) Jul 07 11:40:50 AM: Solver (including time spent in interface) took 2.504e+00 seconds
(CVXPY) Jul 07 11:40:50 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:40:50 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:40:50 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:40:50 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:40:50 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:40:50 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:40:50 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:40:50 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:40:50 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:40:50 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:40:50 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:40:50 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:40:50 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:40:50 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:40:50 AM: Applying reduction SCS
(CVXPY) Jul 07 11:40:50 AM: Finished problem compilation (took 4.763e-02 seconds).
(CVXPY) Jul 07 11:40:50 AM: Invoking solver SCS  to obtain a solution.

   225| 4.25e-08  2.93e-13  4.43e-12  2.21e-12  1.27e-05  2.50e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.50e+00s = setup: 2.75e-02s + solve: 2.47e+00s
	 lin-sys: 1.40e-01s, cones: 2.28e+00s, accel: 1.39e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  1.30e-01  1.82e-01  2.91e+00  1.00e-01  4.88e-02

(CVXPY) Jul 07 11:40:52 AM: Problem status: optimal
(CVXPY) Jul 07 11:40:52 AM: Optimal value: 4.486e-17
(CVXPY) Jul 07 11:40:52 AM: Compilation took 4.763e-02 seconds
(CVXPY) Jul 07 11:40:52 AM: Solver (including time spent in interface) took 2.421e+00 seconds
(CVXPY) Jul 07 11:40:52 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:40:52 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:40:52 AM: DCP verification time: 0.0003 seconds.
(CVXPY) Jul 07 11:40:52 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:40:52 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:40:52 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:40:52 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:40:52 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:40:52 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:40:52 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:40:52 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:40:52 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:40:52 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:40:52 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:40:52 AM: Applying reduction SCS
(CVXPY) Jul 07 11:40:52 AM: Finished problem compilation (took 5.102e-02 seconds).
(CVXPY) Jul 07 11:40:52 AM: Invoking solver SCS  to obtain a solution.

   225| 4.71e-08  1.71e-13  5.32e-12  2.66e-12  7.14e-06  2.41e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.41e+00s = setup: 2.42e-02s + solve: 2.39e+00s
	 lin-sys: 1.35e-01s, cones: 2.20e+00s, accel: 1.39e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  7.02e-02  4.09e-01  1.64e+00  1.00e-01  4.74e-02

(CVXPY) Jul 07 11:40:55 AM: Problem status: optimal
(CVXPY) Jul 07 11:40:55 AM: Optimal value: 6.243e-17
(CVXPY) Jul 07 11:40:55 AM: Compilation took 5.102e-02 seconds
(CVXPY) Jul 07 11:40:55 AM: Solver (including time spent in interface) took 2.411e+00 seconds
(CVXPY) Jul 07 11:40:55 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:40:55 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:40:55 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:40:55 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:40:55 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:40:55 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:40:55 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:40:55 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:40:55 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:40:55 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:40:55 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:40:55 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:40:55 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:40:55 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:40:55 AM: Applying reduction SCS
(CVXPY) Jul 07 11:40:55 AM: Finished problem compilation (took 5.295e-02 seconds).
(CVXPY) Jul 07 11:40:55 AM: Invoking solver SCS  to obtain a solution.

   225| 4.27e-08  2.89e-13  5.64e-12  2.82e-12  1.29e-05  2.41e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.41e+00s = setup: 2.43e-02s + solve: 2.38e+00s
	 lin-sys: 1.36e-01s, cones: 2.19e+00s, accel: 1.56e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  7.02e-02  5.26e-01  1.84e+00  1.00e-01  4.76e-02

(CVXPY) Jul 07 11:40:57 AM: Problem status: optimal
(CVXPY) Jul 07 11:40:57 AM: Optimal value: 7.716e-17
(CVXPY) Jul 07 11:40:57 AM: Compilation took 5.295e-02 seconds
(CVXPY) Jul 07 11:40:57 AM: Solver (including time spent in interface) took 2.492e+00 seconds
(CVXPY) Jul 07 11:40:57 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:40:57 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:40:57 AM: DCP verification time: 0.0010 seconds.
(CVXPY) Jul 07 11:40:57 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:40:57 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:40:57 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:40:57 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:40:57 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:40:57 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:40:57 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:40:57 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:40:57 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:40:57 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:40:57 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:40:57 AM: Applying reduction SCS
(CVXPY) Jul 07 11:40:57 AM: Finished problem compilation (took 5.087e-02 seconds).
(CVXPY) Jul 07 11:40:57 AM: Invoking solver SCS  to obtain a solution.

   225| 4.32e-08  3.03e-13  6.89e-12  3.44e-12  1.30e-05  2.49e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.49e+00s = setup: 2.38e-02s + solve: 2.47e+00s
	 lin-sys: 1.39e-01s, cones: 2.27e+00s, accel: 1.44e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  1.27e-01  1.25e-01  2.72e+00  1.00e-01  3.91e-02

(CVXPY) Jul 07 11:41:00 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:00 AM: Optimal value: 5.283e-17
(CVXPY) Jul 07 11:41:00 AM: Compilation took 5.087e-02 seconds
(CVXPY) Jul 07 11:41:00 AM: Solver (including time spent in interface) took 2.442e+00 seconds
(CVXPY) Jul 07 11:41:00 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:00 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:00 AM: DCP verification time: 0.0009 seconds.
(CVXPY) Jul 07 11:41:00 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:00 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:00 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:00 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:00 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:00 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:00 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:00 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:00 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:00 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:00 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:00 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:00 AM: Finished problem compilation (took 5.808e-02 seconds).
(CVXPY) Jul 07 11:41:00 AM: Invoking solver SCS  to obtain a solution.

   225| 4.73e-08  1.82e-13  6.12e-12  3.06e-12  7.70e-06  2.44e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.44e+00s = setup: 2.62e-02s + solve: 2.41e+00s
	 lin-sys: 1.45e-01s, cones: 2.21e+00s, accel: 1.48e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  1.28e-01  6.58e-02  2.66e+00  1.00e-01  5.50e-02

(CVXPY) Jul 07 11:41:02 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:02 AM: Optimal value: 4.141e-17
(CVXPY) Jul 07 11:41:02 AM: Compilation took 5.808e-02 seconds
(CVXPY) Jul 07 11:41:02 AM: Solver (including time spent in interface) took 2.580e+00 seconds
(CVXPY) Jul 07 11:41:02 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:02 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:03 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:41:03 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:03 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:03 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:03 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:03 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:03 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:03 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:03 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:03 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:03 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:03 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:03 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:03 AM: Finished problem compilation (took 5.360e-02 seconds).
(CVXPY) Jul 07 11:41:03 AM: Invoking solver SCS  to obtain a solution.

   225| 4.72e-08  1.66e-13  5.36e-12  2.68e-12  7.45e-06  2.57e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.58e+00s = setup: 2.54e-02s + solve: 2.55e+00s
	 lin-sys: 1.45e-01s, cones: 2.35e+00s, accel: 1.37e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  7.02e-02  5.37e-01  1.57e+00  1.00e-01  4.93e-02

(CVXPY) Jul 07 11:41:05 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:05 AM: Optimal value: 7.624e-17
(CVXPY) Jul 07 11:41:05 AM: Compilation took 5.360e-02 seconds
(CVXPY) Jul 07 11:41:05 AM: Solver (including time spent in interface) took 2.676e+00 seconds
(CVXPY) Jul 07 11:41:05 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:05 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:05 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:41:05 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:05 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:05 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:05 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:05 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:05 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:05 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:05 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:05 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:05 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:05 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:05 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:05 AM: Finished problem compilation (took 5.868e-02 seconds).
(CVXPY) Jul 07 11:41:05 AM: Invoking solver SCS  to obtain a solution.

   225| 4.35e-08  3.10e-13  6.21e-12  3.10e-12  1.30e-05  2.67e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.67e+00s = setup: 2.41e-02s + solve: 2.65e+00s
	 lin-sys: 1.54e-01s, cones: 2.44e+00s, accel: 1.52e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  1.22e-01  2.79e-02  3.07e+00  1.00e-01  4.98e-02

(CVXPY) Jul 07 11:41:08 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:08 AM: Optimal value: 7.596e-17
(CVXPY) Jul 07 11:41:08 AM: Compilation took 5.868e-02 seconds
(CVXPY) Jul 07 11:41:08 AM: Solver (including time spent in interface) took 2.372e+00 seconds
(CVXPY) Jul 07 11:41:08 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:08 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:08 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:41:08 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:08 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:08 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:08 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:08 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:08 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:08 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:08 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:08 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:08 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:08 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:08 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:08 AM: Finished problem compilation (took 5.909e-02 seconds).
(CVXPY) Jul 07 11:41:08 AM: Invoking solver SCS  to obtain a solution.

   225| 4.84e-08  1.88e-13  6.27e-12  3.13e-12  7.94e-06  2.37e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.37e+00s = setup: 2.70e-02s + solve: 2.34e+00s
	 lin-sys: 1.38e-01s, cones: 2.15e+00s, accel: 1.49e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  1.32e-01  1.19e-01  2.69e+00  1.00e-01  4.87e-02

(CVXPY) Jul 07 11:41:10 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:10 AM: Optimal value: 3.902e-17
(CVXPY) Jul 07 11:41:10 AM: Compilation took 5.909e-02 seconds
(CVXPY) Jul 07 11:41:10 AM: Solver (including time spent in interface) took 2.410e+00 seconds
(CVXPY) Jul 07 11:41:10 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:10 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:10 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:41:10 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:10 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:10 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:10 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:10 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:10 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:10 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:10 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:10 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:10 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:10 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:10 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:10 AM: Finished problem compilation (took 8.708e-02 seconds).
(CVXPY) Jul 07 11:41:10 AM: Invoking solver SCS  to obtain a solution.

   225| 5.03e-08  1.55e-13  5.35e-12  2.68e-12  6.61e-06  2.41e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.41e+00s = setup: 2.54e-02s + solve: 2.38e+00s
	 lin-sys: 1.35e-01s, cones: 2.19e+00s, accel: 1.26e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  7.02e-02  3.62e-01  1.73e+00  1.00e-01  4.77e-02

(CVXPY) Jul 07 11:41:13 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:13 AM: Optimal value: 6.450e-17
(CVXPY) Jul 07 11:41:13 AM: Compilation took 8.708e-02 seconds
(CVXPY) Jul 07 11:41:13 AM: Solver (including time spent in interface) took 2.582e+00 seconds
(CVXPY) Jul 07 11:41:13 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:13 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:13 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:41:13 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:13 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:13 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:13 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:13 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:13 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:13 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:13 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:13 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:13 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:13 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:13 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:13 AM: Finished problem compilation (took 5.929e-02 seconds).
(CVXPY) Jul 07 11:41:13 AM: Invoking solver SCS  to obtain a solution.

   225| 4.39e-08  2.90e-13  5.63e-12  2.82e-12  1.27e-05  2.57e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.58e+00s = setup: 2.51e-02s + solve: 2.55e+00s
	 lin-sys: 1.48e-01s, cones: 2.34e+00s, accel: 1.45e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  1.25e-01  4.31e-02  3.02e+00  1.00e-01  4.76e-02

(CVXPY) Jul 07 11:41:16 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:16 AM: Optimal value: 4.811e-17
(CVXPY) Jul 07 11:41:16 AM: Compilation took 5.929e-02 seconds
(CVXPY) Jul 07 11:41:16 AM: Solver (including time spent in interface) took 2.522e+00 seconds
(CVXPY) Jul 07 11:41:16 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:16 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:16 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:41:16 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:16 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:16 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:16 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:16 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:16 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:16 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:16 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:16 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:16 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:16 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:16 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:16 AM: Finished problem compilation (took 7.241e-02 seconds).
(CVXPY) Jul 07 11:41:16 AM: Invoking solver SCS  to obtain a solution.

   225| 4.84e-08  1.78e-13  6.20e-12  3.10e-12  7.48e-06  2.52e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.52e+00s = setup: 2.41e-02s + solve: 2.49e+00s
	 lin-sys: 1.42e-01s, cones: 2.29e+00s, accel: 1.52e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  1.26e-01  4.63e-02  2.87e+00  1.00e-01  4.89e-02

(CVXPY) Jul 07 11:41:18 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:18 AM: Optimal value: 5.904e-17
(CVXPY) Jul 07 11:41:18 AM: Compilation took 7.241e-02 seconds
(CVXPY) Jul 07 11:41:18 AM: Solver (including time spent in interface) took 2.561e+00 seconds
(CVXPY) Jul 07 11:41:18 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:18 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:18 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:41:18 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:18 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:18 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:18 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:18 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:18 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:18 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:18 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:18 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:18 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:18 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:18 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:18 AM: Finished problem compilation (took 5.944e-02 seconds).
(CVXPY) Jul 07 11:41:18 AM: Invoking solver SCS  to obtain a solution.

   225| 4.90e-08  1.66e-13  6.43e-12  3.21e-12  7.40e-06  2.55e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.56e+00s = setup: 2.42e-02s + solve: 2.53e+00s
	 lin-sys: 1.78e-01s, cones: 2.30e+00s, accel: 1.31e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  7.02e-02  3.70e-01  1.94e+00  1.00e-01  5.33e-02

(CVXPY) Jul 07 11:41:21 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:21 AM: Optimal value: 7.024e-17
(CVXPY) Jul 07 11:41:21 AM: Compilation took 5.944e-02 seconds
(CVXPY) Jul 07 11:41:21 AM: Solver (including time spent in interface) took 2.505e+00 seconds
(CVXPY) Jul 07 11:41:21 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:21 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:21 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:41:21 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:21 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:21 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:21 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:21 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:21 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:21 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:21 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:21 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:21 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:21 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:21 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:21 AM: Finished problem compilation (took 5.638e-02 seconds).
(CVXPY) Jul 07 11:41:21 AM: Invoking solver SCS  to obtain a solution.

   225| 4.33e-08  2.61e-13  5.76e-12  2.88e-12  1.30e-05  2.50e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.50e+00s = setup: 2.78e-02s + solve: 2.47e+00s
	 lin-sys: 1.40e-01s, cones: 2.28e+00s, accel: 1.38e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.58e+00  1.28e-01  5.70e+01 -2.68e+01  1.00e-01  5.19e-02

(CVXPY) Jul 07 11:41:22 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:22 AM: Optimal value: 1.567e+00
(CVXPY) Jul 07 11:41:22 AM: Compilation took 5.638e-02 seconds
(CVXPY) Jul 07 11:41:22 AM: Solver (including time spent in interface) took 9.060e-01 seconds
(CVXPY) Jul 07 11:41:22 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:22 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:22 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:41:22 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:22 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:22 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:22 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:22 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:22 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:22 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:22 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:22 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:22 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:22 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:22 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:22 AM: Finished problem compilation (took 4.854e-02 seconds).
(CVXPY) Jul 07 11:41:22 AM: Invoking solver SCS  to obtain a solution.

    75| 4.02e-06  7.47e-09  8.59e-07  1.57e+00  1.00e-01  9.00e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.00e-01s = setup: 2.73e-02s + solve: 8.73e-01s
	 lin-sys: 5.14e-02s, cones: 7.99e-01s, accel: 6.24e-03s
------------------------------------------------------------------
objective = 1.567272
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 4.17e+00  1.70e-01  5.75e+01 -2.60e+01  1.00e-01  4.99e-02

(CVXPY) Jul 07 11:41:23 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:23 AM: Optimal value: 1.867e+00
(CVXPY) Jul 07 11:41:23 AM: Compilation took 4.854e-02 seconds
(CVXPY) Jul 07 11:41:23 AM: Solver (including time spent in interface) took 8.713e-01 seconds
(CVXPY) Jul 07 11:41:23 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:23 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:23 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:41:23 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:23 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:23 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:23 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:23 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:23 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:23 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:23 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:23 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:23 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:23 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:23 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:23 AM: Finished problem compilation (took 4.802e-02 seconds).
(CVXPY) Jul 07 11:41:23 AM: Invoking solver SCS  to obtain a solution.

    75| 6.00e-06  8.18e-09  8.02e-07  1.87e+00  1.00e-01  8.66e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.67e-01s = setup: 2.70e-02s + solve: 8.40e-01s
	 lin-sys: 4.62e-02s, cones: 7.74e-01s, accel: 5.56e-03s
------------------------------------------------------------------
objective = 1.867401
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 4.15e+00  1.69e-01  5.76e+01 -2.59e+01  1.00e-01  4.67e-02

(CVXPY) Jul 07 11:41:24 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:24 AM: Optimal value: 1.904e+00
(CVXPY) Jul 07 11:41:24 AM: Compilation took 4.802e-02 seconds
(CVXPY) Jul 07 11:41:24 AM: Solver (including time spent in interface) took 8.627e-01 seconds
(CVXPY) Jul 07 11:41:24 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:24 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:24 AM: DCP verification time: 0.0003 seconds.
(CVXPY) Jul 07 11:41:24 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:24 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:24 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:24 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:24 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:24 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:24 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:24 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:24 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:24 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:24 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:24 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:24 AM: Finished problem compilation (took 5.322e-02 seconds).
(CVXPY) Jul 07 11:41:24 AM: Invoking solver SCS  to obtain a solution.

    75| 2.47e-06  3.56e-09  2.75e-07  1.90e+00  1.00e-01  8.57e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.57e-01s = setup: 2.22e-02s + solve: 8.35e-01s
	 lin-sys: 4.48e-02s, cones: 7.69e-01s, accel: 4.65e-03s
------------------------------------------------------------------
objective = 1.903955
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 4.19e+00  1.71e-01  5.75e+01 -2.59e+01  1.00e-01  4.73e-02

(CVXPY) Jul 07 11:41:25 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:25 AM: Optimal value: 1.877e+00
(CVXPY) Jul 07 11:41:25 AM: Compilation took 5.322e-02 seconds
(CVXPY) Jul 07 11:41:25 AM: Solver (including time spent in interface) took 8.865e-01 seconds
(CVXPY) Jul 07 11:41:25 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:25 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:25 AM: DCP verification time: 0.0009 seconds.
(CVXPY) Jul 07 11:41:25 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:25 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:25 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:25 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:25 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:25 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:25 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:25 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:25 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:25 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:25 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:25 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:25 AM: Finished problem compilation (took 5.581e-02 seconds).
(CVXPY) Jul 07 11:41:25 AM: Invoking solver SCS  to obtain a solution.

    75| 3.96e-06  6.02e-09  6.22e-07  1.88e+00  1.00e-01  8.81e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.81e-01s = setup: 2.26e-02s + solve: 8.58e-01s
	 lin-sys: 4.68e-02s, cones: 7.93e-01s, accel: 4.57e-03s
------------------------------------------------------------------
objective = 1.877179
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.58e+00  1.28e-01  5.70e+01 -2.68e+01  1.00e-01  4.91e-02

(CVXPY) Jul 07 11:41:26 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:26 AM: Optimal value: 1.558e+00
(CVXPY) Jul 07 11:41:26 AM: Compilation took 5.581e-02 seconds
(CVXPY) Jul 07 11:41:26 AM: Solver (including time spent in interface) took 9.438e-01 seconds
(CVXPY) Jul 07 11:41:26 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:26 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:26 AM: DCP verification time: 0.0019 seconds.
(CVXPY) Jul 07 11:41:26 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:26 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:26 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:26 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:26 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:26 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:26 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:26 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:26 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:26 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:26 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:26 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:26 AM: Finished problem compilation (took 5.486e-02 seconds).
(CVXPY) Jul 07 11:41:26 AM: Invoking solver SCS  to obtain a solution.

    75| 4.93e-06  7.05e-09  1.00e-06  1.56e+00  1.00e-01  9.39e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.39e-01s = setup: 2.43e-02s + solve: 9.15e-01s
	 lin-sys: 6.93e-02s, cones: 8.25e-01s, accel: 4.85e-03s
------------------------------------------------------------------
objective = 1.557555
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 4.20e+00  1.72e-01  5.76e+01 -2.56e+01  1.00e-01  5.81e-02

(CVXPY) Jul 07 11:41:27 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:27 AM: Optimal value: 1.946e+00
(CVXPY) Jul 07 11:41:27 AM: Compilation took 5.486e-02 seconds
(CVXPY) Jul 07 11:41:27 AM: Solver (including time spent in interface) took 9.041e-01 seconds
(CVXPY) Jul 07 11:41:27 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:27 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:27 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:41:27 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:27 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:27 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:27 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:27 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:27 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:27 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:27 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:27 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:27 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:27 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:27 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:27 AM: Finished problem compilation (took 5.441e-02 seconds).
(CVXPY) Jul 07 11:41:27 AM: Invoking solver SCS  to obtain a solution.

    75| 6.20e-06  8.14e-09  9.67e-07  1.95e+00  1.00e-01  8.98e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.98e-01s = setup: 2.79e-02s + solve: 8.70e-01s
	 lin-sys: 5.09e-02s, cones: 8.01e-01s, accel: 4.67e-03s
------------------------------------------------------------------
objective = 1.946336
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 4.19e+00  1.72e-01  5.75e+01 -2.59e+01  1.00e-01  5.44e-02

(CVXPY) Jul 07 11:41:28 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:28 AM: Optimal value: 1.869e+00
(CVXPY) Jul 07 11:41:28 AM: Compilation took 5.441e-02 seconds
(CVXPY) Jul 07 11:41:28 AM: Solver (including time spent in interface) took 9.086e-01 seconds
(CVXPY) Jul 07 11:41:28 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:28 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:28 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:41:28 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:28 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:28 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:28 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:28 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:28 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:28 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:28 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:28 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:28 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:28 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:28 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:28 AM: Finished problem compilation (took 5.639e-02 seconds).
(CVXPY) Jul 07 11:41:28 AM: Invoking solver SCS  to obtain a solution.

    75| 5.21e-06  8.37e-09  9.07e-07  1.87e+00  1.00e-01  9.01e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.01e-01s = setup: 2.93e-02s + solve: 8.72e-01s
	 lin-sys: 4.93e-02s, cones: 7.98e-01s, accel: 8.18e-03s
------------------------------------------------------------------
objective = 1.869163
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.71e+01 -2.70e+01  1.00e-01  4.88e-02

(CVXPY) Jul 07 11:41:29 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:29 AM: Optimal value: 1.492e+00
(CVXPY) Jul 07 11:41:29 AM: Compilation took 5.639e-02 seconds
(CVXPY) Jul 07 11:41:29 AM: Solver (including time spent in interface) took 9.132e-01 seconds
(CVXPY) Jul 07 11:41:29 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:29 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:29 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:41:29 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:29 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:29 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:29 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:29 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:29 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:29 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:29 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:29 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:29 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:29 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:29 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:29 AM: Finished problem compilation (took 5.899e-02 seconds).
(CVXPY) Jul 07 11:41:29 AM: Invoking solver SCS  to obtain a solution.

    75| 5.44e-06  5.40e-09  9.85e-07  1.49e+00  1.00e-01  9.07e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.08e-01s = setup: 2.60e-02s + solve: 8.82e-01s
	 lin-sys: 5.39e-02s, cones: 8.09e-01s, accel: 4.92e-03s
------------------------------------------------------------------
objective = 1.491811
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 4.21e+00  1.73e-01  5.76e+01 -2.58e+01  1.00e-01  5.04e-02

(CVXPY) Jul 07 11:41:30 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:30 AM: Optimal value: 1.948e+00
(CVXPY) Jul 07 11:41:30 AM: Compilation took 5.899e-02 seconds
(CVXPY) Jul 07 11:41:30 AM: Solver (including time spent in interface) took 9.218e-01 seconds
(CVXPY) Jul 07 11:41:30 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:30 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:30 AM: DCP verification time: 0.0010 seconds.
(CVXPY) Jul 07 11:41:30 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:30 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:30 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:30 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:30 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:30 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:30 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:30 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:30 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:30 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:30 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:30 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:30 AM: Finished problem compilation (took 6.482e-02 seconds).
(CVXPY) Jul 07 11:41:30 AM: Invoking solver SCS  to obtain a solution.

    75| 4.60e-06  6.35e-09  9.09e-07  1.95e+00  1.00e-01  9.15e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.16e-01s = setup: 2.68e-02s + solve: 8.89e-01s
	 lin-sys: 5.03e-02s, cones: 8.19e-01s, accel: 4.92e-03s
------------------------------------------------------------------
objective = 1.947770
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.70e+01 -2.71e+01  1.00e-01  4.46e-02

(CVXPY) Jul 07 11:41:31 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:31 AM: Optimal value: 1.454e+00
(CVXPY) Jul 07 11:41:31 AM: Compilation took 6.482e-02 seconds
(CVXPY) Jul 07 11:41:31 AM: Solver (including time spent in interface) took 8.903e-01 seconds
(CVXPY) Jul 07 11:41:31 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:31 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:31 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:41:31 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:31 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:31 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:31 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:31 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:31 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:31 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:31 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:31 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:31 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:31 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:31 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:31 AM: Finished problem compilation (took 6.216e-02 seconds).
(CVXPY) Jul 07 11:41:31 AM: Invoking solver SCS  to obtain a solution.

    75| 3.80e-06  4.95e-09  7.62e-07  1.45e+00  1.00e-01  8.84e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.85e-01s = setup: 2.28e-02s + solve: 8.62e-01s
	 lin-sys: 4.64e-02s, cones: 7.94e-01s, accel: 5.97e-03s
------------------------------------------------------------------
objective = 1.454359
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.57e+00  1.27e-01  5.69e+01 -2.69e+01  1.00e-01  4.74e-02

(CVXPY) Jul 07 11:41:31 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:31 AM: Optimal value: 1.550e+00
(CVXPY) Jul 07 11:41:31 AM: Compilation took 6.216e-02 seconds
(CVXPY) Jul 07 11:41:31 AM: Solver (including time spent in interface) took 8.373e-01 seconds
(CVXPY) Jul 07 11:41:31 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:31 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:31 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:41:31 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:31 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:31 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:32 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:32 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:32 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:32 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:32 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:32 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:32 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:32 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:32 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:32 AM: Finished problem compilation (took 5.549e-02 seconds).
(CVXPY) Jul 07 11:41:32 AM: Invoking solver SCS  to obtain a solution.

    75| 4.58e-06  4.33e-09  9.04e-07  1.55e+00  1.00e-01  8.32e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.33e-01s = setup: 2.51e-02s + solve: 8.07e-01s
	 lin-sys: 4.54e-02s, cones: 7.38e-01s, accel: 4.52e-03s
------------------------------------------------------------------
objective = 1.550017
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 4.16e+00  1.69e-01  5.76e+01 -2.60e+01  1.00e-01  4.66e-02

(CVXPY) Jul 07 11:41:32 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:32 AM: Optimal value: 1.866e+00
(CVXPY) Jul 07 11:41:32 AM: Compilation took 5.549e-02 seconds
(CVXPY) Jul 07 11:41:32 AM: Solver (including time spent in interface) took 8.861e-01 seconds
(CVXPY) Jul 07 11:41:32 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:32 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:32 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:41:32 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:32 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:32 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:32 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:32 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:32 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:32 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:32 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:32 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:32 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:32 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:33 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:33 AM: Finished problem compilation (took 5.515e-02 seconds).
(CVXPY) Jul 07 11:41:33 AM: Invoking solver SCS  to obtain a solution.

    75| 6.06e-06  6.87e-09  1.01e-06  1.87e+00  1.00e-01  8.80e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.80e-01s = setup: 2.41e-02s + solve: 8.56e-01s
	 lin-sys: 4.55e-02s, cones: 7.91e-01s, accel: 4.57e-03s
------------------------------------------------------------------
objective = 1.865775
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 4.16e+00  1.69e-01  5.75e+01 -2.61e+01  1.00e-01  5.01e-02

(CVXPY) Jul 07 11:41:33 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:33 AM: Optimal value: 1.836e+00
(CVXPY) Jul 07 11:41:33 AM: Compilation took 5.515e-02 seconds
(CVXPY) Jul 07 11:41:33 AM: Solver (including time spent in interface) took 8.730e-01 seconds
(CVXPY) Jul 07 11:41:33 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:33 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:33 AM: DCP verification time: 0.0024 seconds.
(CVXPY) Jul 07 11:41:33 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:33 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:33 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:33 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:33 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:33 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:33 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:33 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:33 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:33 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:33 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:33 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:33 AM: Finished problem compilation (took 5.487e-02 seconds).
(CVXPY) Jul 07 11:41:33 AM: Invoking solver SCS  to obtain a solution.

    75| 2.41e-06  4.24e-09  5.89e-07  1.84e+00  1.00e-01  8.67e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.67e-01s = setup: 2.80e-02s + solve: 8.39e-01s
	 lin-sys: 4.53e-02s, cones: 7.73e-01s, accel: 5.79e-03s
------------------------------------------------------------------
objective = 1.836477
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.69e+01 -2.72e+01  1.00e-01  5.08e-02

(CVXPY) Jul 07 11:41:34 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:34 AM: Optimal value: 1.411e+00
(CVXPY) Jul 07 11:41:34 AM: Compilation took 5.487e-02 seconds
(CVXPY) Jul 07 11:41:34 AM: Solver (including time spent in interface) took 9.238e-01 seconds
(CVXPY) Jul 07 11:41:34 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:34 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:34 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:41:34 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:34 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:34 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:34 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:34 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:34 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:34 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:34 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:34 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:34 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:34 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:34 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:34 AM: Finished problem compilation (took 5.206e-02 seconds).
(CVXPY) Jul 07 11:41:34 AM: Invoking solver SCS  to obtain a solution.

    75| 4.10e-06  4.56e-09  8.07e-07  1.41e+00  1.00e-01  9.14e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.14e-01s = setup: 2.73e-02s + solve: 8.87e-01s
	 lin-sys: 4.52e-02s, cones: 8.23e-01s, accel: 5.07e-03s
------------------------------------------------------------------
objective = 1.411283
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 4.19e+00  1.71e-01  5.75e+01 -2.57e+01  1.00e-01  5.21e-02

(CVXPY) Jul 07 11:41:35 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:35 AM: Optimal value: 1.924e+00
(CVXPY) Jul 07 11:41:35 AM: Compilation took 5.206e-02 seconds
(CVXPY) Jul 07 11:41:35 AM: Solver (including time spent in interface) took 8.668e-01 seconds
(CVXPY) Jul 07 11:41:35 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:35 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:35 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:41:35 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:35 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:35 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:35 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:35 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:35 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:35 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:35 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:35 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:35 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:35 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:35 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:35 AM: Finished problem compilation (took 5.525e-02 seconds).
(CVXPY) Jul 07 11:41:35 AM: Invoking solver SCS  to obtain a solution.

    75| 2.64e-06  4.15e-09  4.90e-07  1.92e+00  1.00e-01  8.62e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.62e-01s = setup: 2.49e-02s + solve: 8.37e-01s
	 lin-sys: 4.84e-02s, cones: 7.67e-01s, accel: 6.10e-03s
------------------------------------------------------------------
objective = 1.924404
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 4.19e+00  1.71e-01  5.76e+01 -2.60e+01  1.00e-01  4.88e-02

(CVXPY) Jul 07 11:41:36 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:36 AM: Optimal value: 1.851e+00
(CVXPY) Jul 07 11:41:36 AM: Compilation took 5.525e-02 seconds
(CVXPY) Jul 07 11:41:36 AM: Solver (including time spent in interface) took 9.117e-01 seconds
(CVXPY) Jul 07 11:41:36 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:36 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:36 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:41:36 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:36 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:36 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:36 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:36 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:36 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:36 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:36 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:36 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:36 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:36 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:36 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:36 AM: Finished problem compilation (took 5.412e-02 seconds).
(CVXPY) Jul 07 11:41:36 AM: Invoking solver SCS  to obtain a solution.

    75| 3.24e-06  5.24e-09  6.52e-07  1.85e+00  1.00e-01  9.06e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.06e-01s = setup: 2.70e-02s + solve: 8.79e-01s
	 lin-sys: 5.10e-02s, cones: 8.10e-01s, accel: 4.35e-03s
------------------------------------------------------------------
objective = 1.850667
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.55e+00  1.26e-01  5.71e+01 -2.70e+01  1.00e-01  5.23e-02

(CVXPY) Jul 07 11:41:37 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:37 AM: Optimal value: 1.518e+00
(CVXPY) Jul 07 11:41:37 AM: Compilation took 5.412e-02 seconds
(CVXPY) Jul 07 11:41:37 AM: Solver (including time spent in interface) took 9.120e-01 seconds
(CVXPY) Jul 07 11:41:37 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:37 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:37 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:41:37 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:37 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:37 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:37 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:37 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:37 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:37 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:37 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:37 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:37 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:37 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:37 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:37 AM: Finished problem compilation (took 5.500e-02 seconds).
(CVXPY) Jul 07 11:41:37 AM: Invoking solver SCS  to obtain a solution.

    75| 4.31e-06  6.25e-09  8.42e-07  1.52e+00  1.00e-01  9.06e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.07e-01s = setup: 2.92e-02s + solve: 8.78e-01s
	 lin-sys: 4.91e-02s, cones: 8.09e-01s, accel: 4.97e-03s
------------------------------------------------------------------
objective = 1.518153
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 4.19e+00  1.72e-01  5.75e+01 -2.57e+01  1.00e-01  4.94e-02

(CVXPY) Jul 07 11:41:38 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:38 AM: Optimal value: 1.932e+00
(CVXPY) Jul 07 11:41:38 AM: Compilation took 5.500e-02 seconds
(CVXPY) Jul 07 11:41:38 AM: Solver (including time spent in interface) took 8.489e-01 seconds
(CVXPY) Jul 07 11:41:38 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:38 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:38 AM: DCP verification time: 0.0003 seconds.
(CVXPY) Jul 07 11:41:38 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:38 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:38 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:38 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:38 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:38 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:38 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:38 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:38 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:38 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:38 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:38 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:38 AM: Finished problem compilation (took 5.537e-02 seconds).
(CVXPY) Jul 07 11:41:38 AM: Invoking solver SCS  to obtain a solution.

    75| 4.27e-06  5.65e-09  6.45e-07  1.93e+00  1.00e-01  8.44e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.44e-01s = setup: 2.62e-02s + solve: 8.18e-01s
	 lin-sys: 4.72e-02s, cones: 7.51e-01s, accel: 5.39e-03s
------------------------------------------------------------------
objective = 1.931771
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 4.18e+00  1.71e-01  5.75e+01 -2.59e+01  1.00e-01  4.56e-02

(CVXPY) Jul 07 11:41:39 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:39 AM: Optimal value: 1.905e+00
(CVXPY) Jul 07 11:41:39 AM: Compilation took 5.537e-02 seconds
(CVXPY) Jul 07 11:41:39 AM: Solver (including time spent in interface) took 8.636e-01 seconds
(CVXPY) Jul 07 11:41:39 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:39 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:39 AM: DCP verification time: 0.0009 seconds.
(CVXPY) Jul 07 11:41:39 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:39 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:39 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:39 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:39 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:39 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:39 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:39 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:39 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:39 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:39 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:39 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:39 AM: Finished problem compilation (took 4.876e-02 seconds).
(CVXPY) Jul 07 11:41:39 AM: Invoking solver SCS  to obtain a solution.

    75| 5.07e-06  8.02e-09  1.02e-06  1.91e+00  1.00e-01  8.56e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.56e-01s = setup: 2.36e-02s + solve: 8.33e-01s
	 lin-sys: 4.53e-02s, cones: 7.70e-01s, accel: 4.64e-03s
------------------------------------------------------------------
objective = 1.905277
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.59e+00  1.29e-01  5.71e+01 -2.68e+01  1.00e-01  4.54e-02

(CVXPY) Jul 07 11:41:40 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:40 AM: Optimal value: 1.610e+00
(CVXPY) Jul 07 11:41:40 AM: Compilation took 4.876e-02 seconds
(CVXPY) Jul 07 11:41:40 AM: Solver (including time spent in interface) took 8.591e-01 seconds
(CVXPY) Jul 07 11:41:40 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:40 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:40 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:41:40 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:40 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:40 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:40 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:40 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:40 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:40 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:40 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:40 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:40 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:40 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:40 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:40 AM: Finished problem compilation (took 4.988e-02 seconds).
(CVXPY) Jul 07 11:41:40 AM: Invoking solver SCS  to obtain a solution.

    75| 4.65e-06  7.58e-09  9.47e-07  1.61e+00  1.00e-01  8.53e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.54e-01s = setup: 2.23e-02s + solve: 8.31e-01s
	 lin-sys: 4.37e-02s, cones: 7.69e-01s, accel: 5.16e-03s
------------------------------------------------------------------
objective = 1.610217
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.29e+02 -1.13e+02  1.00e-01  4.67e-02

(CVXPY) Jul 07 11:41:41 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:41 AM: Optimal value: 2.066e+00
(CVXPY) Jul 07 11:41:41 AM: Compilation took 4.988e-02 seconds
(CVXPY) Jul 07 11:41:41 AM: Solver (including time spent in interface) took 1.048e+00 seconds
(CVXPY) Jul 07 11:41:41 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:41 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:41 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:41:41 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:41 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:41 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:41 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:41 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:41 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:41 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:41 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:41 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:41 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:41 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:41 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:41 AM: Finished problem compilation (took 4.999e-02 seconds).
(CVXPY) Jul 07 11:41:41 AM: Invoking solver SCS  to obtain a solution.

    75| 1.14e-05  8.13e-09  9.61e-07  2.07e+00  1.00e-01  1.04e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.04e+00s = setup: 2.32e-02s + solve: 1.02e+00s
	 lin-sys: 4.46e-02s, cones: 9.56e-01s, accel: 6.15e-03s
------------------------------------------------------------------
objective = 2.066160
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.12e+02  1.00e-01  4.48e-02

(CVXPY) Jul 07 11:41:42 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:42 AM: Optimal value: 2.679e+00
(CVXPY) Jul 07 11:41:42 AM: Compilation took 4.999e-02 seconds
(CVXPY) Jul 07 11:41:42 AM: Solver (including time spent in interface) took 7.470e-01 seconds
(CVXPY) Jul 07 11:41:42 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:42 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:42 AM: DCP verification time: 0.0003 seconds.
(CVXPY) Jul 07 11:41:42 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:42 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:42 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:42 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:42 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:42 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:42 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:42 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:42 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:42 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:42 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:42 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:42 AM: Finished problem compilation (took 5.225e-02 seconds).
(CVXPY) Jul 07 11:41:42 AM: Invoking solver SCS  to obtain a solution.

    75| 1.03e-05  1.17e-08  7.27e-07  2.68e+00  1.00e-01  7.40e-01
------------------------------------------------------------------
status:  solved
timings: total: 7.41e-01s = setup: 2.22e-02s + solve: 7.19e-01s
	 lin-sys: 4.40e-02s, cones: 6.55e-01s, accel: 5.72e-03s
------------------------------------------------------------------
objective = 2.679472
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.12e+02  1.00e-01  4.75e-02

(CVXPY) Jul 07 11:41:43 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:43 AM: Optimal value: 2.734e+00
(CVXPY) Jul 07 11:41:43 AM: Compilation took 5.225e-02 seconds
(CVXPY) Jul 07 11:41:43 AM: Solver (including time spent in interface) took 7.272e-01 seconds
(CVXPY) Jul 07 11:41:43 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:43 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:43 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:41:43 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:43 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:43 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:43 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:43 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:43 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:43 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:43 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:43 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:43 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:43 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:43 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:43 AM: Finished problem compilation (took 4.730e-02 seconds).
(CVXPY) Jul 07 11:41:43 AM: Invoking solver SCS  to obtain a solution.

    75| 1.38e-05  2.02e-08  1.32e-06  2.73e+00  1.00e-01  7.21e-01
------------------------------------------------------------------
status:  solved
timings: total: 7.21e-01s = setup: 2.48e-02s + solve: 6.97e-01s
	 lin-sys: 4.50e-02s, cones: 6.31e-01s, accel: 5.03e-03s
------------------------------------------------------------------
objective = 2.734083
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.12e+02  1.00e-01  4.47e-02

(CVXPY) Jul 07 11:41:44 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:44 AM: Optimal value: 2.695e+00
(CVXPY) Jul 07 11:41:44 AM: Compilation took 4.730e-02 seconds
(CVXPY) Jul 07 11:41:44 AM: Solver (including time spent in interface) took 7.441e-01 seconds
(CVXPY) Jul 07 11:41:44 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:44 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:44 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:41:44 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:44 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:44 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:44 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:44 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:44 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:44 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:44 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:44 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:44 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:44 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:44 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:44 AM: Finished problem compilation (took 4.841e-02 seconds).
(CVXPY) Jul 07 11:41:44 AM: Invoking solver SCS  to obtain a solution.

    75| 1.33e-05  1.09e-08  1.03e-06  2.70e+00  1.00e-01  7.38e-01
------------------------------------------------------------------
status:  solved
timings: total: 7.38e-01s = setup: 2.24e-02s + solve: 7.16e-01s
	 lin-sys: 4.74e-02s, cones: 6.49e-01s, accel: 5.41e-03s
------------------------------------------------------------------
objective = 2.695007
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.29e+02 -1.13e+02  1.00e-01  4.90e-02

(CVXPY) Jul 07 11:41:45 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:45 AM: Optimal value: 2.053e+00
(CVXPY) Jul 07 11:41:45 AM: Compilation took 4.841e-02 seconds
(CVXPY) Jul 07 11:41:45 AM: Solver (including time spent in interface) took 7.716e-01 seconds
(CVXPY) Jul 07 11:41:45 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:45 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:45 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:41:45 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:45 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:45 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:45 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:45 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:45 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:45 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:45 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:45 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:45 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:45 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:45 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:45 AM: Finished problem compilation (took 4.739e-02 seconds).
(CVXPY) Jul 07 11:41:45 AM: Invoking solver SCS  to obtain a solution.

    75| 1.02e-05  8.28e-09  7.72e-07  2.05e+00  1.00e-01  7.67e-01
------------------------------------------------------------------
status:  solved
timings: total: 7.68e-01s = setup: 2.56e-02s + solve: 7.42e-01s
	 lin-sys: 4.59e-02s, cones: 6.76e-01s, accel: 5.57e-03s
------------------------------------------------------------------
objective = 2.052986
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.12e+02  1.00e-01  8.29e-02

(CVXPY) Jul 07 11:41:45 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:46 AM: Optimal value: 2.838e+00
(CVXPY) Jul 07 11:41:46 AM: Compilation took 4.739e-02 seconds
(CVXPY) Jul 07 11:41:46 AM: Solver (including time spent in interface) took 9.023e-01 seconds
(CVXPY) Jul 07 11:41:46 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:46 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:46 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:41:46 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:46 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:46 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:46 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:46 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:46 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:46 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:46 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:46 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:46 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:46 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:46 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:46 AM: Finished problem compilation (took 4.983e-02 seconds).
(CVXPY) Jul 07 11:41:46 AM: Invoking solver SCS  to obtain a solution.

    75| 1.04e-05  1.09e-08  7.24e-07  2.84e+00  1.00e-01  8.98e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.98e-01s = setup: 6.43e-02s + solve: 8.34e-01s
	 lin-sys: 4.49e-02s, cones: 7.70e-01s, accel: 4.90e-03s
------------------------------------------------------------------
objective = 2.837677
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.12e+02  1.00e-01  4.53e-02

(CVXPY) Jul 07 11:41:46 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:46 AM: Optimal value: 2.679e+00
(CVXPY) Jul 07 11:41:46 AM: Compilation took 4.983e-02 seconds
(CVXPY) Jul 07 11:41:46 AM: Solver (including time spent in interface) took 7.744e-01 seconds
(CVXPY) Jul 07 11:41:46 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:46 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:46 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:41:46 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:46 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:46 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:46 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:46 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:46 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:46 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:46 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:46 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:46 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:46 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:46 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:46 AM: Finished problem compilation (took 4.975e-02 seconds).
(CVXPY) Jul 07 11:41:46 AM: Invoking solver SCS  to obtain a solution.

    75| 1.27e-05  1.01e-08  1.04e-06  2.68e+00  1.00e-01  7.68e-01
------------------------------------------------------------------
status:  solved
timings: total: 7.68e-01s = setup: 2.28e-02s + solve: 7.45e-01s
	 lin-sys: 4.58e-02s, cones: 6.81e-01s, accel: 5.08e-03s
------------------------------------------------------------------
objective = 2.678879
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.29e+02 -1.13e+02  1.00e-01  4.76e-02

(CVXPY) Jul 07 11:41:47 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:47 AM: Optimal value: 1.905e+00
(CVXPY) Jul 07 11:41:47 AM: Compilation took 4.975e-02 seconds
(CVXPY) Jul 07 11:41:47 AM: Solver (including time spent in interface) took 8.375e-01 seconds
(CVXPY) Jul 07 11:41:47 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:47 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:47 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:41:47 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:47 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:47 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:47 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:47 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:47 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:47 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:47 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:47 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:47 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:47 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:47 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:47 AM: Finished problem compilation (took 5.700e-02 seconds).
(CVXPY) Jul 07 11:41:47 AM: Invoking solver SCS  to obtain a solution.

    75| 1.36e-05  7.72e-09  8.18e-07  1.91e+00  1.00e-01  8.33e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.33e-01s = setup: 2.46e-02s + solve: 8.09e-01s
	 lin-sys: 4.54e-02s, cones: 7.44e-01s, accel: 6.02e-03s
------------------------------------------------------------------
objective = 1.905258
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.12e+02  1.00e-01  4.84e-02

(CVXPY) Jul 07 11:41:48 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:48 AM: Optimal value: 2.814e+00
(CVXPY) Jul 07 11:41:48 AM: Compilation took 5.700e-02 seconds
(CVXPY) Jul 07 11:41:48 AM: Solver (including time spent in interface) took 7.635e-01 seconds
(CVXPY) Jul 07 11:41:48 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:48 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:48 AM: DCP verification time: 0.0010 seconds.
(CVXPY) Jul 07 11:41:48 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:48 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:48 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:48 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:48 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:48 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:48 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:48 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:48 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:48 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:48 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:48 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:48 AM: Finished problem compilation (took 5.329e-02 seconds).
(CVXPY) Jul 07 11:41:48 AM: Invoking solver SCS  to obtain a solution.

    75| 1.81e-05  1.55e-08  1.39e-06  2.81e+00  1.00e-01  7.57e-01
------------------------------------------------------------------
status:  solved
timings: total: 7.57e-01s = setup: 2.67e-02s + solve: 7.31e-01s
	 lin-sys: 5.07e-02s, cones: 6.60e-01s, accel: 4.89e-03s
------------------------------------------------------------------
objective = 2.813752
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.29e+02 -1.13e+02  1.00e-01  4.78e-02

(CVXPY) Jul 07 11:41:49 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:49 AM: Optimal value: 1.853e+00
(CVXPY) Jul 07 11:41:49 AM: Compilation took 5.329e-02 seconds
(CVXPY) Jul 07 11:41:49 AM: Solver (including time spent in interface) took 8.115e-01 seconds
(CVXPY) Jul 07 11:41:49 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:49 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:49 AM: DCP verification time: 0.0012 seconds.
(CVXPY) Jul 07 11:41:49 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:49 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:49 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:49 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:49 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:49 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:49 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:49 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:49 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:49 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:49 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:49 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:49 AM: Finished problem compilation (took 5.022e-02 seconds).
(CVXPY) Jul 07 11:41:49 AM: Invoking solver SCS  to obtain a solution.

    75| 3.18e-05  8.87e-09  2.30e-06  1.85e+00  1.00e-01  8.05e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.05e-01s = setup: 2.26e-02s + solve: 7.82e-01s
	 lin-sys: 4.75e-02s, cones: 7.16e-01s, accel: 4.47e-03s
------------------------------------------------------------------
objective = 1.852758
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.29e+02 -1.13e+02  1.00e-01  5.25e-02

(CVXPY) Jul 07 11:41:50 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:50 AM: Optimal value: 2.017e+00
(CVXPY) Jul 07 11:41:50 AM: Compilation took 5.022e-02 seconds
(CVXPY) Jul 07 11:41:50 AM: Solver (including time spent in interface) took 9.217e-01 seconds
(CVXPY) Jul 07 11:41:50 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:50 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:50 AM: DCP verification time: 0.0021 seconds.
(CVXPY) Jul 07 11:41:50 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:50 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:50 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:50 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:50 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:50 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:50 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:50 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:50 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:50 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:50 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:50 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:50 AM: Finished problem compilation (took 6.267e-02 seconds).
(CVXPY) Jul 07 11:41:50 AM: Invoking solver SCS  to obtain a solution.

    75| 1.40e-05  8.51e-09  9.95e-07  2.02e+00  1.00e-01  9.15e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.16e-01s = setup: 2.96e-02s + solve: 8.86e-01s
	 lin-sys: 4.79e-02s, cones: 8.19e-01s, accel: 5.26e-03s
------------------------------------------------------------------
objective = 2.016763
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.12e+02  1.00e-01  4.81e-02

(CVXPY) Jul 07 11:41:51 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:51 AM: Optimal value: 2.668e+00
(CVXPY) Jul 07 11:41:51 AM: Compilation took 6.267e-02 seconds
(CVXPY) Jul 07 11:41:51 AM: Solver (including time spent in interface) took 7.107e-01 seconds
(CVXPY) Jul 07 11:41:51 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:51 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:51 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:41:51 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:51 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:51 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:51 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:51 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:51 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:51 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:51 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:51 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:51 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:51 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:51 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:51 AM: Finished problem compilation (took 5.699e-02 seconds).
(CVXPY) Jul 07 11:41:51 AM: Invoking solver SCS  to obtain a solution.

    75| 2.27e-05  1.81e-08  1.37e-06  2.67e+00  1.00e-01  7.04e-01
------------------------------------------------------------------
status:  solved
timings: total: 7.04e-01s = setup: 2.63e-02s + solve: 6.78e-01s
	 lin-sys: 4.49e-02s, cones: 6.14e-01s, accel: 4.89e-03s
------------------------------------------------------------------
objective = 2.668261
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.12e+02  1.00e-01  4.74e-02

(CVXPY) Jul 07 11:41:52 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:52 AM: Optimal value: 2.614e+00
(CVXPY) Jul 07 11:41:52 AM: Compilation took 5.699e-02 seconds
(CVXPY) Jul 07 11:41:52 AM: Solver (including time spent in interface) took 7.551e-01 seconds
(CVXPY) Jul 07 11:41:52 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:52 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:52 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:41:52 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:52 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:52 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:52 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:52 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:52 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:52 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:52 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:52 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:52 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:52 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:52 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:52 AM: Finished problem compilation (took 6.321e-02 seconds).
(CVXPY) Jul 07 11:41:52 AM: Invoking solver SCS  to obtain a solution.

    75| 1.57e-05  1.74e-08  1.31e-06  2.61e+00  1.00e-01  7.48e-01
------------------------------------------------------------------
status:  solved
timings: total: 7.48e-01s = setup: 2.53e-02s + solve: 7.23e-01s
	 lin-sys: 4.79e-02s, cones: 6.56e-01s, accel: 4.75e-03s
------------------------------------------------------------------
objective = 2.614453
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.29e+02 -1.13e+02  1.00e-01  4.83e-02

(CVXPY) Jul 07 11:41:53 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:53 AM: Optimal value: 1.772e+00
(CVXPY) Jul 07 11:41:53 AM: Compilation took 6.321e-02 seconds
(CVXPY) Jul 07 11:41:53 AM: Solver (including time spent in interface) took 8.368e-01 seconds
(CVXPY) Jul 07 11:41:53 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:53 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:53 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:41:53 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:53 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:53 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:53 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:53 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:53 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:53 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:53 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:53 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:53 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:53 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:53 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:53 AM: Finished problem compilation (took 5.822e-02 seconds).
(CVXPY) Jul 07 11:41:53 AM: Invoking solver SCS  to obtain a solution.

    75| 9.90e-06  4.31e-09  7.24e-07  1.77e+00  1.00e-01  8.32e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.32e-01s = setup: 2.38e-02s + solve: 8.08e-01s
	 lin-sys: 5.00e-02s, cones: 7.37e-01s, accel: 5.35e-03s
------------------------------------------------------------------
objective = 1.771863
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.12e+02  1.00e-01  4.49e-02

(CVXPY) Jul 07 11:41:53 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:53 AM: Optimal value: 2.810e+00
(CVXPY) Jul 07 11:41:53 AM: Compilation took 5.822e-02 seconds
(CVXPY) Jul 07 11:41:53 AM: Solver (including time spent in interface) took 8.026e-01 seconds
(CVXPY) Jul 07 11:41:53 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:53 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:53 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:41:53 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:53 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:53 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:53 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:53 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:53 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:53 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:53 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:53 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:53 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:53 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:53 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:54 AM: Finished problem compilation (took 6.008e-02 seconds).
(CVXPY) Jul 07 11:41:54 AM: Invoking solver SCS  to obtain a solution.

    75| 1.39e-05  1.39e-08  1.12e-06  2.81e+00  1.00e-01  7.96e-01
------------------------------------------------------------------
status:  solved
timings: total: 7.97e-01s = setup: 2.36e-02s + solve: 7.73e-01s
	 lin-sys: 4.77e-02s, cones: 7.07e-01s, accel: 4.31e-03s
------------------------------------------------------------------
objective = 2.810269
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.12e+02  1.00e-01  4.82e-02

(CVXPY) Jul 07 11:41:54 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:54 AM: Optimal value: 2.643e+00
(CVXPY) Jul 07 11:41:54 AM: Compilation took 6.008e-02 seconds
(CVXPY) Jul 07 11:41:54 AM: Solver (including time spent in interface) took 7.467e-01 seconds
(CVXPY) Jul 07 11:41:54 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:54 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:54 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:41:54 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:54 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:54 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:54 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:54 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:54 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:54 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:54 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:54 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:54 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:54 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:54 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:54 AM: Finished problem compilation (took 5.330e-02 seconds).
(CVXPY) Jul 07 11:41:54 AM: Invoking solver SCS  to obtain a solution.

    75| 1.54e-05  1.24e-08  1.22e-06  2.64e+00  1.00e-01  7.39e-01
------------------------------------------------------------------
status:  solved
timings: total: 7.39e-01s = setup: 2.63e-02s + solve: 7.13e-01s
	 lin-sys: 4.81e-02s, cones: 6.47e-01s, accel: 4.94e-03s
------------------------------------------------------------------
objective = 2.642611
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.29e+02 -1.13e+02  1.00e-01  6.04e-02

(CVXPY) Jul 07 11:41:55 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:55 AM: Optimal value: 1.972e+00
(CVXPY) Jul 07 11:41:55 AM: Compilation took 5.330e-02 seconds
(CVXPY) Jul 07 11:41:55 AM: Solver (including time spent in interface) took 9.311e-01 seconds
(CVXPY) Jul 07 11:41:55 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:55 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:55 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:41:55 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:55 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:55 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:55 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:55 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:55 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:55 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:55 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:55 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:55 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:55 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:55 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:55 AM: Finished problem compilation (took 6.334e-02 seconds).
(CVXPY) Jul 07 11:41:55 AM: Invoking solver SCS  to obtain a solution.

    75| 7.91e-06  6.22e-09  6.76e-07  1.97e+00  1.00e-01  9.26e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.26e-01s = setup: 3.84e-02s + solve: 8.87e-01s
	 lin-sys: 4.52e-02s, cones: 8.20e-01s, accel: 7.45e-03s
------------------------------------------------------------------
objective = 1.971837
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.12e+02  1.00e-01  4.61e-02

(CVXPY) Jul 07 11:41:56 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:56 AM: Optimal value: 2.812e+00
(CVXPY) Jul 07 11:41:56 AM: Compilation took 6.334e-02 seconds
(CVXPY) Jul 07 11:41:56 AM: Solver (including time spent in interface) took 7.486e-01 seconds
(CVXPY) Jul 07 11:41:56 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:56 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:56 AM: DCP verification time: 0.0010 seconds.
(CVXPY) Jul 07 11:41:56 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:56 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:56 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:56 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:56 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:56 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:56 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:56 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:56 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:56 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:56 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:56 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:56 AM: Finished problem compilation (took 6.273e-02 seconds).
(CVXPY) Jul 07 11:41:56 AM: Invoking solver SCS  to obtain a solution.

    75| 1.41e-05  1.22e-08  1.07e-06  2.81e+00  1.00e-01  7.43e-01
------------------------------------------------------------------
status:  solved
timings: total: 7.44e-01s = setup: 2.50e-02s + solve: 7.19e-01s
	 lin-sys: 4.73e-02s, cones: 6.52e-01s, accel: 5.10e-03s
------------------------------------------------------------------
objective = 2.811701
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.12e+02  1.00e-01  4.62e-02

(CVXPY) Jul 07 11:41:57 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:57 AM: Optimal value: 2.737e+00
(CVXPY) Jul 07 11:41:57 AM: Compilation took 6.273e-02 seconds
(CVXPY) Jul 07 11:41:57 AM: Solver (including time spent in interface) took 7.655e-01 seconds
(CVXPY) Jul 07 11:41:57 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:57 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:57 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:41:57 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:57 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:57 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:57 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:57 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:57 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:57 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:57 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:57 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:57 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:57 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:57 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:57 AM: Finished problem compilation (took 5.868e-02 seconds).
(CVXPY) Jul 07 11:41:57 AM: Invoking solver SCS  to obtain a solution.

    75| 1.38e-05  1.33e-08  1.25e-06  2.74e+00  1.00e-01  7.55e-01
------------------------------------------------------------------
status:  solved
timings: total: 7.56e-01s = setup: 2.56e-02s + solve: 7.30e-01s
	 lin-sys: 4.49e-02s, cones: 6.67e-01s, accel: 4.68e-03s
------------------------------------------------------------------
objective = 2.736775
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.29e+02 -1.13e+02  1.00e-01  4.62e-02

(CVXPY) Jul 07 11:41:58 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:58 AM: Optimal value: 2.140e+00
(CVXPY) Jul 07 11:41:58 AM: Compilation took 5.868e-02 seconds
(CVXPY) Jul 07 11:41:58 AM: Solver (including time spent in interface) took 7.870e-01 seconds
(CVXPY) Jul 07 11:41:58 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:58 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:58 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:41:58 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:58 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:58 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:58 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:58 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:58 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:58 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:58 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:58 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:58 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:58 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:58 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:58 AM: Finished problem compilation (took 5.761e-02 seconds).
(CVXPY) Jul 07 11:41:58 AM: Invoking solver SCS  to obtain a solution.

    75| 8.41e-06  7.02e-09  7.97e-07  2.14e+00  1.00e-01  7.81e-01
------------------------------------------------------------------
status:  solved
timings: total: 7.81e-01s = setup: 2.45e-02s + solve: 7.57e-01s
	 lin-sys: 4.46e-02s, cones: 6.94e-01s, accel: 5.13e-03s
------------------------------------------------------------------
objective = 2.139680
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.57e+02  1.00e-01  5.88e-02

(CVXPY) Jul 07 11:41:59 AM: Problem status: optimal
(CVXPY) Jul 07 11:41:59 AM: Optimal value: 2.313e+00
(CVXPY) Jul 07 11:41:59 AM: Compilation took 5.761e-02 seconds
(CVXPY) Jul 07 11:41:59 AM: Solver (including time spent in interface) took 8.957e-01 seconds
(CVXPY) Jul 07 11:41:59 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:41:59 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:41:59 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:41:59 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:41:59 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:41:59 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:41:59 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:41:59 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:41:59 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:41:59 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:41:59 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:41:59 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:41:59 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:41:59 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:41:59 AM: Applying reduction SCS
(CVXPY) Jul 07 11:41:59 AM: Finished problem compilation (took 5.749e-02 seconds).
(CVXPY) Jul 07 11:41:59 AM: Invoking solver SCS  to obtain a solution.

    75| 2.29e-05  5.63e-09  1.26e-06  2.31e+00  1.00e-01  8.88e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.89e-01s = setup: 4.52e-02s + solve: 8.44e-01s
	 lin-sys: 4.32e-02s, cones: 7.82e-01s, accel: 4.85e-03s
------------------------------------------------------------------
objective = 2.313114
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.56e+02  1.00e-01  4.70e-02

(CVXPY) Jul 07 11:42:00 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:00 AM: Optimal value: 3.216e+00
(CVXPY) Jul 07 11:42:00 AM: Compilation took 5.749e-02 seconds
(CVXPY) Jul 07 11:42:00 AM: Solver (including time spent in interface) took 7.948e-01 seconds
(CVXPY) Jul 07 11:42:00 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:00 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:00 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:42:00 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:00 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:00 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:00 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:00 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:00 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:00 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:00 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:00 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:00 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:00 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:00 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:00 AM: Finished problem compilation (took 6.742e-02 seconds).
(CVXPY) Jul 07 11:42:00 AM: Invoking solver SCS  to obtain a solution.

    75| 1.73e-05  1.11e-08  8.74e-07  3.22e+00  1.00e-01  7.88e-01
------------------------------------------------------------------
status:  solved
timings: total: 7.88e-01s = setup: 2.51e-02s + solve: 7.63e-01s
	 lin-sys: 4.63e-02s, cones: 6.97e-01s, accel: 5.12e-03s
------------------------------------------------------------------
objective = 3.215728
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.56e+02  1.00e-01  4.56e-02

(CVXPY) Jul 07 11:42:01 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:01 AM: Optimal value: 3.293e+00
(CVXPY) Jul 07 11:42:01 AM: Compilation took 6.742e-02 seconds
(CVXPY) Jul 07 11:42:01 AM: Solver (including time spent in interface) took 7.802e-01 seconds
(CVXPY) Jul 07 11:42:01 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:01 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:01 AM: DCP verification time: 0.0015 seconds.
(CVXPY) Jul 07 11:42:01 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:01 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:01 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:01 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:01 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:01 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:01 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:01 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:01 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:01 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:01 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:01 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:01 AM: Finished problem compilation (took 5.916e-02 seconds).
(CVXPY) Jul 07 11:42:01 AM: Invoking solver SCS  to obtain a solution.

    75| 3.04e-05  1.98e-08  1.60e-06  3.29e+00  1.00e-01  7.74e-01
------------------------------------------------------------------
status:  solved
timings: total: 7.74e-01s = setup: 2.36e-02s + solve: 7.51e-01s
	 lin-sys: 4.78e-02s, cones: 6.84e-01s, accel: 5.09e-03s
------------------------------------------------------------------
objective = 3.292510
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.56e+02  1.00e-01  4.94e-02

(CVXPY) Jul 07 11:42:01 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:01 AM: Optimal value: 3.253e+00
(CVXPY) Jul 07 11:42:01 AM: Compilation took 5.916e-02 seconds
(CVXPY) Jul 07 11:42:01 AM: Solver (including time spent in interface) took 8.147e-01 seconds
(CVXPY) Jul 07 11:42:01 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:01 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:01 AM: DCP verification time: 0.0012 seconds.
(CVXPY) Jul 07 11:42:01 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:01 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:01 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:01 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:01 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:01 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:01 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:01 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:01 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:01 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:01 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:02 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:02 AM: Finished problem compilation (took 5.739e-02 seconds).
(CVXPY) Jul 07 11:42:02 AM: Invoking solver SCS  to obtain a solution.

    75| 3.02e-05  2.27e-08  1.39e-06  3.25e+00  1.00e-01  8.07e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.07e-01s = setup: 2.63e-02s + solve: 7.81e-01s
	 lin-sys: 4.93e-02s, cones: 7.13e-01s, accel: 4.72e-03s
------------------------------------------------------------------
objective = 3.252885
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.57e+02  1.00e-01  4.90e-02

(CVXPY) Jul 07 11:42:02 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:02 AM: Optimal value: 2.305e+00
(CVXPY) Jul 07 11:42:02 AM: Compilation took 5.739e-02 seconds
(CVXPY) Jul 07 11:42:02 AM: Solver (including time spent in interface) took 9.135e-01 seconds
(CVXPY) Jul 07 11:42:02 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:02 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:02 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:42:02 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:02 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:02 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:02 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:02 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:02 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:02 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:02 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:02 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:02 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:03 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:03 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:03 AM: Finished problem compilation (took 5.951e-02 seconds).
(CVXPY) Jul 07 11:42:03 AM: Invoking solver SCS  to obtain a solution.

    75| 3.04e-05  9.90e-09  1.44e-06  2.30e+00  1.00e-01  9.07e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.08e-01s = setup: 2.45e-02s + solve: 8.83e-01s
	 lin-sys: 5.38e-02s, cones: 8.10e-01s, accel: 4.86e-03s
------------------------------------------------------------------
objective = 2.304881
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.55e+02  1.00e-01  6.73e-02

(CVXPY) Jul 07 11:42:04 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:04 AM: Optimal value: 3.458e+00
(CVXPY) Jul 07 11:42:04 AM: Compilation took 5.951e-02 seconds
(CVXPY) Jul 07 11:42:04 AM: Solver (including time spent in interface) took 1.439e+00 seconds
(CVXPY) Jul 07 11:42:04 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:04 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:04 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:42:04 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:04 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:04 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:04 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:04 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:04 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:04 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:04 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:04 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:04 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:04 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:04 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:04 AM: Finished problem compilation (took 5.982e-02 seconds).
(CVXPY) Jul 07 11:42:04 AM: Invoking solver SCS  to obtain a solution.

    75| 1.52e-05  9.82e-09  6.24e-07  3.46e+00  1.00e-01  1.43e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.44e+00s = setup: 2.52e-02s + solve: 1.41e+00s
	 lin-sys: 5.00e-02s, cones: 1.34e+00s, accel: 5.32e-03s
------------------------------------------------------------------
objective = 3.457591
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.56e+02  1.00e-01  5.85e-02

(CVXPY) Jul 07 11:42:05 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:05 AM: Optimal value: 3.228e+00
(CVXPY) Jul 07 11:42:05 AM: Compilation took 5.982e-02 seconds
(CVXPY) Jul 07 11:42:05 AM: Solver (including time spent in interface) took 8.170e-01 seconds
(CVXPY) Jul 07 11:42:05 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:05 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:05 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:42:05 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:05 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:05 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:05 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:05 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:05 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:05 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:05 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:05 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:05 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:05 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:05 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:05 AM: Finished problem compilation (took 5.941e-02 seconds).
(CVXPY) Jul 07 11:42:05 AM: Invoking solver SCS  to obtain a solution.

    75| 2.01e-05  1.46e-08  1.03e-06  3.23e+00  1.00e-01  8.11e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.12e-01s = setup: 3.34e-02s + solve: 7.78e-01s
	 lin-sys: 5.08e-02s, cones: 7.08e-01s, accel: 4.66e-03s
------------------------------------------------------------------
objective = 3.227985
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.57e+02  1.00e-01  4.96e-02

(CVXPY) Jul 07 11:42:06 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:06 AM: Optimal value: 2.100e+00
(CVXPY) Jul 07 11:42:06 AM: Compilation took 5.941e-02 seconds
(CVXPY) Jul 07 11:42:06 AM: Solver (including time spent in interface) took 1.085e+00 seconds
(CVXPY) Jul 07 11:42:06 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:06 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:06 AM: DCP verification time: 0.0003 seconds.
(CVXPY) Jul 07 11:42:06 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:06 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:06 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:06 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:06 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:06 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:06 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:06 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:06 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:06 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:06 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:06 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:06 AM: Finished problem compilation (took 5.795e-02 seconds).
(CVXPY) Jul 07 11:42:06 AM: Invoking solver SCS  to obtain a solution.

    75| 2.05e-05  4.28e-09  8.75e-07  2.10e+00  1.00e-01  1.08e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.08e+00s = setup: 2.70e-02s + solve: 1.05e+00s
	 lin-sys: 5.94e-02s, cones: 9.69e-01s, accel: 7.70e-03s
------------------------------------------------------------------
objective = 2.100341
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.56e+02  1.00e-01  4.96e-02

(CVXPY) Jul 07 11:42:07 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:07 AM: Optimal value: 3.397e+00
(CVXPY) Jul 07 11:42:07 AM: Compilation took 5.795e-02 seconds
(CVXPY) Jul 07 11:42:07 AM: Solver (including time spent in interface) took 9.227e-01 seconds
(CVXPY) Jul 07 11:42:07 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:07 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:07 AM: DCP verification time: 0.0012 seconds.
(CVXPY) Jul 07 11:42:07 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:07 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:07 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:07 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:07 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:07 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:07 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:07 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:07 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:07 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:07 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:07 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:07 AM: Finished problem compilation (took 8.758e-02 seconds).
(CVXPY) Jul 07 11:42:07 AM: Invoking solver SCS  to obtain a solution.

    75| 3.17e-05  1.98e-08  1.41e-06  3.40e+00  1.00e-01  9.16e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.17e-01s = setup: 2.77e-02s + solve: 8.89e-01s
	 lin-sys: 6.41e-02s, cones: 8.02e-01s, accel: 6.47e-03s
------------------------------------------------------------------
objective = 3.396809
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.57e+02  1.00e-01  7.02e-02

(CVXPY) Jul 07 11:42:08 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:08 AM: Optimal value: 2.051e+00
(CVXPY) Jul 07 11:42:08 AM: Compilation took 8.758e-02 seconds
(CVXPY) Jul 07 11:42:08 AM: Solver (including time spent in interface) took 1.264e+00 seconds
(CVXPY) Jul 07 11:42:08 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:08 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:08 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:42:08 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:08 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:08 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:08 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:08 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:08 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:08 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:09 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:09 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:09 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:09 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:09 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:09 AM: Finished problem compilation (took 7.124e-02 seconds).
(CVXPY) Jul 07 11:42:09 AM: Invoking solver SCS  to obtain a solution.

    75| 3.27e-05  7.44e-09  1.22e-06  2.05e+00  1.00e-01  1.26e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.26e+00s = setup: 3.41e-02s + solve: 1.22e+00s
	 lin-sys: 6.99e-02s, cones: 1.12e+00s, accel: 6.91e-03s
------------------------------------------------------------------
objective = 2.050491
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.57e+02  1.00e-01  7.29e-02

(CVXPY) Jul 07 11:42:10 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:10 AM: Optimal value: 2.234e+00
(CVXPY) Jul 07 11:42:10 AM: Compilation took 7.124e-02 seconds
(CVXPY) Jul 07 11:42:10 AM: Solver (including time spent in interface) took 1.060e+00 seconds
(CVXPY) Jul 07 11:42:10 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:10 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:10 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:42:10 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:10 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:10 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:10 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:10 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:10 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:10 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:10 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:10 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:10 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:10 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:10 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:10 AM: Finished problem compilation (took 8.085e-02 seconds).
(CVXPY) Jul 07 11:42:10 AM: Invoking solver SCS  to obtain a solution.

    75| 3.07e-05  8.05e-09  1.26e-06  2.23e+00  1.00e-01  1.06e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.06e+00s = setup: 3.58e-02s + solve: 1.02e+00s
	 lin-sys: 6.17e-02s, cones: 9.35e-01s, accel: 5.67e-03s
------------------------------------------------------------------
objective = 2.233678
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.56e+02  1.00e-01  5.69e-02

(CVXPY) Jul 07 11:42:11 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:11 AM: Optimal value: 3.204e+00
(CVXPY) Jul 07 11:42:11 AM: Compilation took 8.085e-02 seconds
(CVXPY) Jul 07 11:42:11 AM: Solver (including time spent in interface) took 9.571e-01 seconds
(CVXPY) Jul 07 11:42:11 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:11 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:11 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:42:11 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:11 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:11 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:11 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:11 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:11 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:11 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:11 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:11 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:11 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:11 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:11 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:11 AM: Finished problem compilation (took 8.713e-02 seconds).
(CVXPY) Jul 07 11:42:11 AM: Invoking solver SCS  to obtain a solution.

    75| 3.02e-05  2.03e-08  1.09e-06  3.20e+00  1.00e-01  9.46e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.46e-01s = setup: 3.33e-02s + solve: 9.13e-01s
	 lin-sys: 6.33e-02s, cones: 8.26e-01s, accel: 5.66e-03s
------------------------------------------------------------------
objective = 3.203725
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.56e+02  1.00e-01  7.00e-02

(CVXPY) Jul 07 11:42:12 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:12 AM: Optimal value: 3.131e+00
(CVXPY) Jul 07 11:42:12 AM: Compilation took 8.713e-02 seconds
(CVXPY) Jul 07 11:42:12 AM: Solver (including time spent in interface) took 9.719e-01 seconds
(CVXPY) Jul 07 11:42:12 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:12 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:12 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:42:12 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:12 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:12 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:12 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:12 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:12 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:12 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:12 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:12 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:12 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:12 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:12 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:12 AM: Finished problem compilation (took 7.797e-02 seconds).
(CVXPY) Jul 07 11:42:12 AM: Invoking solver SCS  to obtain a solution.

    75| 2.88e-05  2.21e-08  1.33e-06  3.13e+00  1.00e-01  9.66e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.66e-01s = setup: 4.04e-02s + solve: 9.26e-01s
	 lin-sys: 6.63e-02s, cones: 8.35e-01s, accel: 7.04e-03s
------------------------------------------------------------------
objective = 3.130929
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.57e+02  1.00e-01  6.45e-02

(CVXPY) Jul 07 11:42:13 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:13 AM: Optimal value: 1.925e+00
(CVXPY) Jul 07 11:42:13 AM: Compilation took 7.797e-02 seconds
(CVXPY) Jul 07 11:42:13 AM: Solver (including time spent in interface) took 1.125e+00 seconds
(CVXPY) Jul 07 11:42:13 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:13 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:13 AM: DCP verification time: 0.0010 seconds.
(CVXPY) Jul 07 11:42:13 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:13 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:13 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:13 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:13 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:13 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:13 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:13 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:13 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:13 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:13 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:13 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:13 AM: Finished problem compilation (took 8.726e-02 seconds).
(CVXPY) Jul 07 11:42:13 AM: Invoking solver SCS  to obtain a solution.

    75| 1.71e-05  3.06e-09  9.66e-07  1.93e+00  1.00e-01  1.12e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.12e+00s = setup: 3.49e-02s + solve: 1.08e+00s
	 lin-sys: 8.64e-02s, cones: 9.68e-01s, accel: 5.09e-03s
------------------------------------------------------------------
objective = 1.925386
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.55e+02  1.00e-01  6.89e-02

(CVXPY) Jul 07 11:42:15 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:15 AM: Optimal value: 3.417e+00
(CVXPY) Jul 07 11:42:15 AM: Compilation took 8.726e-02 seconds
(CVXPY) Jul 07 11:42:15 AM: Solver (including time spent in interface) took 1.681e+00 seconds
(CVXPY) Jul 07 11:42:15 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:15 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:15 AM: DCP verification time: 0.0013 seconds.
(CVXPY) Jul 07 11:42:15 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:15 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:15 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:15 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:15 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:15 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:15 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:15 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:15 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:15 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:15 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:15 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:15 AM: Finished problem compilation (took 1.223e-01 seconds).
(CVXPY) Jul 07 11:42:15 AM: Invoking solver SCS  to obtain a solution.

    75| 2.03e-05  1.38e-08  9.42e-07  3.42e+00  1.00e-01  1.67e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.67e+00s = setup: 3.70e-02s + solve: 1.64e+00s
	 lin-sys: 7.40e-02s, cones: 1.53e+00s, accel: 8.49e-03s
------------------------------------------------------------------
objective = 3.417248
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.56e+02  1.00e-01  6.91e-02

(CVXPY) Jul 07 11:42:16 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:16 AM: Optimal value: 3.171e+00
(CVXPY) Jul 07 11:42:16 AM: Compilation took 1.223e-01 seconds
(CVXPY) Jul 07 11:42:16 AM: Solver (including time spent in interface) took 1.120e+00 seconds
(CVXPY) Jul 07 11:42:16 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:16 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:16 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:42:16 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:16 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:16 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:16 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:16 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:16 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:16 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:16 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:16 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:16 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:16 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:16 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:16 AM: Finished problem compilation (took 8.172e-02 seconds).
(CVXPY) Jul 07 11:42:16 AM: Invoking solver SCS  to obtain a solution.

    75| 3.03e-05  2.17e-08  1.34e-06  3.17e+00  1.00e-01  1.11e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.11e+00s = setup: 3.49e-02s + solve: 1.08e+00s
	 lin-sys: 7.40e-02s, cones: 9.77e-01s, accel: 5.62e-03s
------------------------------------------------------------------
objective = 3.171283
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.57e+02  1.00e-01  6.11e-02

(CVXPY) Jul 07 11:42:18 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:18 AM: Optimal value: 2.202e+00
(CVXPY) Jul 07 11:42:18 AM: Compilation took 8.172e-02 seconds
(CVXPY) Jul 07 11:42:18 AM: Solver (including time spent in interface) took 1.267e+00 seconds
(CVXPY) Jul 07 11:42:18 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:18 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:18 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:42:18 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:18 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:18 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:18 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:18 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:18 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:18 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:18 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:18 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:18 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:18 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:18 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:18 AM: Finished problem compilation (took 7.280e-02 seconds).
(CVXPY) Jul 07 11:42:18 AM: Invoking solver SCS  to obtain a solution.

    75| 3.13e-05  8.29e-09  1.35e-06  2.20e+00  1.00e-01  1.26e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.26e+00s = setup: 3.34e-02s + solve: 1.23e+00s
	 lin-sys: 8.88e-02s, cones: 1.11e+00s, accel: 6.82e-03s
------------------------------------------------------------------
objective = 2.202354
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.56e+02  1.00e-01  7.16e-02

(CVXPY) Jul 07 11:42:19 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:19 AM: Optimal value: 3.406e+00
(CVXPY) Jul 07 11:42:19 AM: Compilation took 7.280e-02 seconds
(CVXPY) Jul 07 11:42:19 AM: Solver (including time spent in interface) took 9.948e-01 seconds
(CVXPY) Jul 07 11:42:19 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:19 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:19 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:42:19 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:19 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:19 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:19 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:19 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:19 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:19 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:19 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:19 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:19 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:19 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:19 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:19 AM: Finished problem compilation (took 8.331e-02 seconds).
(CVXPY) Jul 07 11:42:19 AM: Invoking solver SCS  to obtain a solution.

    75| 2.03e-05  1.30e-08  9.61e-07  3.41e+00  1.00e-01  9.86e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.87e-01s = setup: 3.49e-02s + solve: 9.52e-01s
	 lin-sys: 6.76e-02s, cones: 8.61e-01s, accel: 5.36e-03s
------------------------------------------------------------------
objective = 3.406457
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.56e+02  1.00e-01  6.78e-02

(CVXPY) Jul 07 11:42:20 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:20 AM: Optimal value: 3.295e+00
(CVXPY) Jul 07 11:42:20 AM: Compilation took 8.331e-02 seconds
(CVXPY) Jul 07 11:42:20 AM: Solver (including time spent in interface) took 1.197e+00 seconds
(CVXPY) Jul 07 11:42:20 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:20 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:20 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:42:20 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:20 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:20 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:20 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:20 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:20 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:20 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:20 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:20 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:20 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:20 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:20 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:20 AM: Finished problem compilation (took 7.589e-02 seconds).
(CVXPY) Jul 07 11:42:20 AM: Invoking solver SCS  to obtain a solution.

    75| 2.02e-05  1.39e-08  1.04e-06  3.30e+00  1.00e-01  1.19e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.19e+00s = setup: 3.49e-02s + solve: 1.15e+00s
	 lin-sys: 8.23e-02s, cones: 1.04e+00s, accel: 1.38e-02s
------------------------------------------------------------------
objective = 3.295006
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.57e+02  1.00e-01  1.08e-01

(CVXPY) Jul 07 11:42:21 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:21 AM: Optimal value: 2.422e+00
(CVXPY) Jul 07 11:42:21 AM: Compilation took 7.589e-02 seconds
(CVXPY) Jul 07 11:42:21 AM: Solver (including time spent in interface) took 1.029e+00 seconds
(CVXPY) Jul 07 11:42:21 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:21 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:21 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:42:21 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:21 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:21 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:21 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:21 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:21 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:21 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:21 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:21 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:21 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:21 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:21 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:21 AM: Finished problem compilation (took 8.030e-02 seconds).
(CVXPY) Jul 07 11:42:21 AM: Invoking solver SCS  to obtain a solution.

    75| 3.25e-05  9.01e-09  1.76e-06  2.42e+00  1.00e-01  1.02e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.02e+00s = setup: 7.67e-02s + solve: 9.46e-01s
	 lin-sys: 6.64e-02s, cones: 8.53e-01s, accel: 7.98e-03s
------------------------------------------------------------------
objective = 2.421586
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.58e+02  1.00e-01  1.18e-01

(CVXPY) Jul 07 11:42:23 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:23 AM: Optimal value: 2.445e+00
(CVXPY) Jul 07 11:42:23 AM: Compilation took 8.030e-02 seconds
(CVXPY) Jul 07 11:42:23 AM: Solver (including time spent in interface) took 1.426e+00 seconds
(CVXPY) Jul 07 11:42:23 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:23 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:23 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:42:23 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:23 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:23 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:23 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:23 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:23 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:23 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:23 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:23 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:23 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:23 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:23 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:23 AM: Finished problem compilation (took 7.914e-02 seconds).
(CVXPY) Jul 07 11:42:23 AM: Invoking solver SCS  to obtain a solution.

    75| 2.37e-05  3.58e-09  7.61e-07  2.44e+00  1.00e-01  1.42e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.42e+00s = setup: 8.36e-02s + solve: 1.34e+00s
	 lin-sys: 7.51e-02s, cones: 1.23e+00s, accel: 6.92e-03s
------------------------------------------------------------------
objective = 2.444471
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.57e+02  1.00e-01  6.35e-02

(CVXPY) Jul 07 11:42:24 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:24 AM: Optimal value: 3.593e+00
(CVXPY) Jul 07 11:42:24 AM: Compilation took 7.914e-02 seconds
(CVXPY) Jul 07 11:42:24 AM: Solver (including time spent in interface) took 1.001e+00 seconds
(CVXPY) Jul 07 11:42:24 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:24 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:24 AM: DCP verification time: 0.0010 seconds.
(CVXPY) Jul 07 11:42:24 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:24 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:24 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:24 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:24 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:24 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:24 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:24 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:24 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:24 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:24 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:24 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:24 AM: Finished problem compilation (took 7.655e-02 seconds).
(CVXPY) Jul 07 11:42:24 AM: Invoking solver SCS  to obtain a solution.

    75| 1.78e-05  9.34e-09  5.26e-07  3.59e+00  1.00e-01  9.95e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.95e-01s = setup: 3.24e-02s + solve: 9.63e-01s
	 lin-sys: 6.72e-02s, cones: 8.72e-01s, accel: 5.05e-03s
------------------------------------------------------------------
objective = 3.593442
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.57e+02  1.00e-01  6.49e-02

(CVXPY) Jul 07 11:42:25 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:25 AM: Optimal value: 3.697e+00
(CVXPY) Jul 07 11:42:25 AM: Compilation took 7.655e-02 seconds
(CVXPY) Jul 07 11:42:25 AM: Solver (including time spent in interface) took 9.966e-01 seconds
(CVXPY) Jul 07 11:42:25 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:25 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:25 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:42:25 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:25 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:25 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:25 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:25 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:25 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:25 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:25 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:25 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:25 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:25 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:25 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:25 AM: Finished problem compilation (took 8.332e-02 seconds).
(CVXPY) Jul 07 11:42:25 AM: Invoking solver SCS  to obtain a solution.

    75| 3.07e-05  1.83e-08  9.65e-07  3.70e+00  1.00e-01  9.90e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.90e-01s = setup: 3.56e-02s + solve: 9.54e-01s
	 lin-sys: 5.70e-02s, cones: 8.74e-01s, accel: 5.51e-03s
------------------------------------------------------------------
objective = 3.696619
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.57e+02  1.00e-01  8.76e-02

(CVXPY) Jul 07 11:42:26 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:26 AM: Optimal value: 3.652e+00
(CVXPY) Jul 07 11:42:26 AM: Compilation took 8.332e-02 seconds
(CVXPY) Jul 07 11:42:26 AM: Solver (including time spent in interface) took 1.013e+00 seconds
(CVXPY) Jul 07 11:42:26 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:26 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:26 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:42:26 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:26 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:26 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:26 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:26 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:26 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:26 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:26 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:26 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:26 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:26 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:26 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:26 AM: Finished problem compilation (took 6.293e-02 seconds).
(CVXPY) Jul 07 11:42:26 AM: Invoking solver SCS  to obtain a solution.

    75| 3.03e-05  2.06e-08  8.29e-07  3.65e+00  1.00e-01  1.01e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.01e+00s = setup: 5.28e-02s + solve: 9.53e-01s
	 lin-sys: 5.70e-02s, cones: 8.74e-01s, accel: 5.84e-03s
------------------------------------------------------------------
objective = 3.652295
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.58e+02  1.00e-01  4.83e-02

(CVXPY) Jul 07 11:42:27 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:27 AM: Optimal value: 2.434e+00
(CVXPY) Jul 07 11:42:27 AM: Compilation took 6.293e-02 seconds
(CVXPY) Jul 07 11:42:27 AM: Solver (including time spent in interface) took 9.478e-01 seconds
(CVXPY) Jul 07 11:42:27 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:27 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:27 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:42:27 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:27 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:27 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:27 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:27 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:27 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:27 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:27 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:27 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:27 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:27 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:27 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:27 AM: Finished problem compilation (took 5.854e-02 seconds).
(CVXPY) Jul 07 11:42:27 AM: Invoking solver SCS  to obtain a solution.

    75| 3.11e-05  6.56e-09  8.68e-07  2.43e+00  1.00e-01  9.41e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.41e-01s = setup: 2.60e-02s + solve: 9.15e-01s
	 lin-sys: 5.05e-02s, cones: 8.44e-01s, accel: 7.34e-03s
------------------------------------------------------------------
objective = 2.434334
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.57e+02  1.00e-01  4.78e-02

(CVXPY) Jul 07 11:42:28 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:28 AM: Optimal value: 3.917e+00
(CVXPY) Jul 07 11:42:28 AM: Compilation took 5.854e-02 seconds
(CVXPY) Jul 07 11:42:28 AM: Solver (including time spent in interface) took 1.098e+00 seconds
(CVXPY) Jul 07 11:42:28 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:28 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:28 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:42:28 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:28 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:28 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:28 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:28 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:28 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:28 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:28 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:28 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:28 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:28 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:28 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:28 AM: Finished problem compilation (took 7.941e-02 seconds).
(CVXPY) Jul 07 11:42:28 AM: Invoking solver SCS  to obtain a solution.

    75| 1.53e-05  8.46e-09  3.71e-07  3.92e+00  1.00e-01  1.09e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.09e+00s = setup: 2.42e-02s + solve: 1.07e+00s
	 lin-sys: 5.11e-02s, cones: 9.95e-01s, accel: 6.13e-03s
------------------------------------------------------------------
objective = 3.917145
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.57e+02  1.00e-01  6.10e-02

(CVXPY) Jul 07 11:42:29 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:29 AM: Optimal value: 3.621e+00
(CVXPY) Jul 07 11:42:29 AM: Compilation took 7.941e-02 seconds
(CVXPY) Jul 07 11:42:29 AM: Solver (including time spent in interface) took 8.453e-01 seconds
(CVXPY) Jul 07 11:42:29 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:29 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:29 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:42:29 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:29 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:29 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:29 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:29 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:29 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:29 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:29 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:29 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:29 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:29 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:29 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:29 AM: Finished problem compilation (took 6.036e-02 seconds).
(CVXPY) Jul 07 11:42:29 AM: Invoking solver SCS  to obtain a solution.

    75| 2.04e-05  1.29e-08  6.13e-07  3.62e+00  1.00e-01  8.39e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.39e-01s = setup: 2.21e-02s + solve: 8.17e-01s
	 lin-sys: 5.39e-02s, cones: 7.20e-01s, accel: 6.79e-03s
------------------------------------------------------------------
objective = 3.621278
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.58e+02  1.00e-01  4.45e-02

(CVXPY) Jul 07 11:42:30 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:30 AM: Optimal value: 2.195e+00
(CVXPY) Jul 07 11:42:30 AM: Compilation took 6.036e-02 seconds
(CVXPY) Jul 07 11:42:30 AM: Solver (including time spent in interface) took 9.971e-01 seconds
(CVXPY) Jul 07 11:42:30 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:30 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:30 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:42:30 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:30 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:30 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:30 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:30 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:30 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:30 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:30 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:30 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:30 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:30 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:30 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:30 AM: Finished problem compilation (took 6.259e-02 seconds).
(CVXPY) Jul 07 11:42:30 AM: Invoking solver SCS  to obtain a solution.

    75| 2.11e-05  2.72e-09  5.29e-07  2.19e+00  1.00e-01  9.91e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.92e-01s = setup: 2.36e-02s + solve: 9.68e-01s
	 lin-sys: 4.86e-02s, cones: 8.96e-01s, accel: 9.09e-03s
------------------------------------------------------------------
objective = 2.194765
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.57e+02  1.00e-01  4.89e-02

(CVXPY) Jul 07 11:42:31 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:31 AM: Optimal value: 3.821e+00
(CVXPY) Jul 07 11:42:31 AM: Compilation took 6.259e-02 seconds
(CVXPY) Jul 07 11:42:31 AM: Solver (including time spent in interface) took 8.841e-01 seconds
(CVXPY) Jul 07 11:42:31 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:31 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:31 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:42:31 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:31 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:31 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:31 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:31 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:31 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:31 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:31 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:31 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:31 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:31 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:31 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:31 AM: Finished problem compilation (took 6.065e-02 seconds).
(CVXPY) Jul 07 11:42:31 AM: Invoking solver SCS  to obtain a solution.

    75| 3.20e-05  1.82e-08  8.47e-07  3.82e+00  1.00e-01  8.77e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.78e-01s = setup: 2.68e-02s + solve: 8.51e-01s
	 lin-sys: 4.80e-02s, cones: 7.81e-01s, accel: 5.03e-03s
------------------------------------------------------------------
objective = 3.820742
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.58e+02  1.00e-01  4.88e-02

(CVXPY) Jul 07 11:42:32 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:32 AM: Optimal value: 2.153e+00
(CVXPY) Jul 07 11:42:32 AM: Compilation took 6.065e-02 seconds
(CVXPY) Jul 07 11:42:32 AM: Solver (including time spent in interface) took 1.134e+00 seconds
(CVXPY) Jul 07 11:42:32 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:32 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:32 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:42:32 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:32 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:32 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:32 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:32 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:32 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:32 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:32 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:32 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:32 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:32 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:32 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:32 AM: Finished problem compilation (took 6.488e-02 seconds).
(CVXPY) Jul 07 11:42:32 AM: Invoking solver SCS  to obtain a solution.

    75| 3.33e-05  4.72e-09  7.31e-07  2.15e+00  1.00e-01  1.13e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.13e+00s = setup: 2.67e-02s + solve: 1.10e+00s
	 lin-sys: 5.16e-02s, cones: 1.03e+00s, accel: 5.52e-03s
------------------------------------------------------------------
objective = 2.153009
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.58e+02  1.00e-01  4.43e-02

(CVXPY) Jul 07 11:42:33 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:33 AM: Optimal value: 2.339e+00
(CVXPY) Jul 07 11:42:33 AM: Compilation took 6.488e-02 seconds
(CVXPY) Jul 07 11:42:33 AM: Solver (including time spent in interface) took 9.906e-01 seconds
(CVXPY) Jul 07 11:42:33 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:33 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:33 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:42:33 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:33 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:33 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:33 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:34 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:34 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:34 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:34 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:34 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:34 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:34 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:34 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:34 AM: Finished problem compilation (took 5.923e-02 seconds).
(CVXPY) Jul 07 11:42:34 AM: Invoking solver SCS  to obtain a solution.

    75| 3.14e-05  4.99e-09  7.65e-07  2.34e+00  1.00e-01  9.84e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.84e-01s = setup: 2.33e-02s + solve: 9.61e-01s
	 lin-sys: 4.57e-02s, cones: 8.95e-01s, accel: 5.76e-03s
------------------------------------------------------------------
objective = 2.338900
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.57e+02  1.00e-01  5.12e-02

(CVXPY) Jul 07 11:42:34 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:34 AM: Optimal value: 3.591e+00
(CVXPY) Jul 07 11:42:34 AM: Compilation took 5.923e-02 seconds
(CVXPY) Jul 07 11:42:34 AM: Solver (including time spent in interface) took 7.783e-01 seconds
(CVXPY) Jul 07 11:42:34 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:34 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:34 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:42:34 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:34 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:34 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:34 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:34 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:34 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:34 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:34 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:34 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:34 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:34 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:34 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:34 AM: Finished problem compilation (took 5.515e-02 seconds).
(CVXPY) Jul 07 11:42:34 AM: Invoking solver SCS  to obtain a solution.

    75| 3.04e-05  1.84e-08  6.48e-07  3.59e+00  1.00e-01  7.74e-01
------------------------------------------------------------------
status:  solved
timings: total: 7.74e-01s = setup: 3.00e-02s + solve: 7.44e-01s
	 lin-sys: 4.80e-02s, cones: 6.78e-01s, accel: 4.63e-03s
------------------------------------------------------------------
objective = 3.590830
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.57e+02  1.00e-01  6.74e-02

(CVXPY) Jul 07 11:42:35 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:35 AM: Optimal value: 3.497e+00
(CVXPY) Jul 07 11:42:35 AM: Compilation took 5.515e-02 seconds
(CVXPY) Jul 07 11:42:35 AM: Solver (including time spent in interface) took 8.377e-01 seconds
(CVXPY) Jul 07 11:42:35 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:35 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:35 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:42:35 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:35 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:35 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:35 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:35 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:35 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:35 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:35 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:35 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:35 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:35 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:35 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:35 AM: Finished problem compilation (took 5.872e-02 seconds).
(CVXPY) Jul 07 11:42:35 AM: Invoking solver SCS  to obtain a solution.

    75| 2.89e-05  1.98e-08  7.96e-07  3.50e+00  1.00e-01  8.32e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.33e-01s = setup: 2.50e-02s + solve: 8.08e-01s
	 lin-sys: 4.51e-02s, cones: 7.42e-01s, accel: 4.82e-03s
------------------------------------------------------------------
objective = 3.496559
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.58e+02  1.00e-01  4.71e-02

(CVXPY) Jul 07 11:42:36 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:36 AM: Optimal value: 1.991e+00
(CVXPY) Jul 07 11:42:36 AM: Compilation took 5.872e-02 seconds
(CVXPY) Jul 07 11:42:36 AM: Solver (including time spent in interface) took 1.103e+00 seconds
(CVXPY) Jul 07 11:42:36 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:36 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:36 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:42:36 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:36 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:36 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:36 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:36 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:36 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:36 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:36 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:36 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:37 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:37 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:37 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:37 AM: Finished problem compilation (took 5.594e-02 seconds).
(CVXPY) Jul 07 11:42:37 AM: Invoking solver SCS  to obtain a solution.

    75| 1.65e-05  1.25e-09  5.85e-07  1.99e+00  1.00e-01  1.10e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.10e+00s = setup: 2.36e-02s + solve: 1.07e+00s
	 lin-sys: 5.29e-02s, cones: 1.00e+00s, accel: 5.78e-03s
------------------------------------------------------------------
objective = 1.990474
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.57e+02  1.00e-01  4.97e-02

(CVXPY) Jul 07 11:42:38 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:38 AM: Optimal value: 3.858e+00
(CVXPY) Jul 07 11:42:38 AM: Compilation took 5.594e-02 seconds
(CVXPY) Jul 07 11:42:38 AM: Solver (including time spent in interface) took 1.197e+00 seconds
(CVXPY) Jul 07 11:42:38 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:38 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:38 AM: DCP verification time: 0.0003 seconds.
(CVXPY) Jul 07 11:42:38 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:38 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:38 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:38 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:38 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:38 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:38 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:38 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:38 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:38 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:38 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:38 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:38 AM: Finished problem compilation (took 5.414e-02 seconds).
(CVXPY) Jul 07 11:42:38 AM: Invoking solver SCS  to obtain a solution.

    75| 2.07e-05  1.22e-08  5.65e-07  3.86e+00  1.00e-01  1.19e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.19e+00s = setup: 2.64e-02s + solve: 1.17e+00s
	 lin-sys: 4.92e-02s, cones: 1.09e+00s, accel: 8.33e-03s
------------------------------------------------------------------
objective = 3.857625
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.57e+02  1.00e-01  5.10e-02

(CVXPY) Jul 07 11:42:39 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:39 AM: Optimal value: 3.548e+00
(CVXPY) Jul 07 11:42:39 AM: Compilation took 5.414e-02 seconds
(CVXPY) Jul 07 11:42:39 AM: Solver (including time spent in interface) took 8.504e-01 seconds
(CVXPY) Jul 07 11:42:39 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:39 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:39 AM: DCP verification time: 0.0016 seconds.
(CVXPY) Jul 07 11:42:39 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:39 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:39 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:39 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:39 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:39 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:39 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:39 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:39 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:39 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:39 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:39 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:39 AM: Finished problem compilation (took 5.385e-02 seconds).
(CVXPY) Jul 07 11:42:39 AM: Invoking solver SCS  to obtain a solution.

    75| 3.04e-05  1.96e-08  7.99e-07  3.55e+00  1.00e-01  8.44e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.44e-01s = setup: 2.47e-02s + solve: 8.19e-01s
	 lin-sys: 4.90e-02s, cones: 7.50e-01s, accel: 5.91e-03s
------------------------------------------------------------------
objective = 3.548188
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.58e+02  1.00e-01  5.16e-02

(CVXPY) Jul 07 11:42:40 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:40 AM: Optimal value: 2.332e+00
(CVXPY) Jul 07 11:42:40 AM: Compilation took 5.385e-02 seconds
(CVXPY) Jul 07 11:42:40 AM: Solver (including time spent in interface) took 9.390e-01 seconds
(CVXPY) Jul 07 11:42:40 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:40 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:40 AM: DCP verification time: 0.0009 seconds.
(CVXPY) Jul 07 11:42:40 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:40 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:40 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:40 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:40 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:40 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:40 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:40 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:40 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:40 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:40 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:40 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:40 AM: Finished problem compilation (took 5.414e-02 seconds).
(CVXPY) Jul 07 11:42:40 AM: Invoking solver SCS  to obtain a solution.

    75| 3.18e-05  5.66e-09  8.13e-07  2.33e+00  1.00e-01  9.34e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.34e-01s = setup: 2.85e-02s + solve: 9.05e-01s
	 lin-sys: 4.34e-02s, cones: 8.42e-01s, accel: 5.02e-03s
------------------------------------------------------------------
objective = 2.331766
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.57e+02  1.00e-01  5.15e-02

(CVXPY) Jul 07 11:42:41 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:41 AM: Optimal value: 3.836e+00
(CVXPY) Jul 07 11:42:41 AM: Compilation took 5.414e-02 seconds
(CVXPY) Jul 07 11:42:41 AM: Solver (including time spent in interface) took 8.588e-01 seconds
(CVXPY) Jul 07 11:42:41 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:41 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:41 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:42:41 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:41 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:41 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:41 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:41 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:41 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:41 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:41 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:41 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:41 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:41 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:41 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:41 AM: Finished problem compilation (took 5.838e-02 seconds).
(CVXPY) Jul 07 11:42:41 AM: Invoking solver SCS  to obtain a solution.

    75| 2.06e-05  1.11e-08  5.76e-07  3.84e+00  1.00e-01  8.53e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.53e-01s = setup: 2.49e-02s + solve: 8.28e-01s
	 lin-sys: 4.84e-02s, cones: 7.60e-01s, accel: 6.43e-03s
------------------------------------------------------------------
objective = 3.836168
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.57e+02  1.00e-01  5.16e-02

(CVXPY) Jul 07 11:42:42 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:42 AM: Optimal value: 3.696e+00
(CVXPY) Jul 07 11:42:42 AM: Compilation took 5.838e-02 seconds
(CVXPY) Jul 07 11:42:42 AM: Solver (including time spent in interface) took 9.562e-01 seconds
(CVXPY) Jul 07 11:42:42 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:42 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:42 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:42:42 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:42 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:42 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:42 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:42 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:42 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:42 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:42 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:42 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:42 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:42 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:42 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:42 AM: Finished problem compilation (took 6.291e-02 seconds).
(CVXPY) Jul 07 11:42:42 AM: Invoking solver SCS  to obtain a solution.

    75| 2.06e-05  1.23e-08  6.23e-07  3.70e+00  1.00e-01  9.48e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.48e-01s = setup: 2.41e-02s + solve: 9.24e-01s
	 lin-sys: 4.81e-02s, cones: 8.54e-01s, accel: 7.46e-03s
------------------------------------------------------------------
objective = 3.696469
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.58e+02  1.00e-01  5.39e-02

(CVXPY) Jul 07 11:42:43 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:43 AM: Optimal value: 2.586e+00
(CVXPY) Jul 07 11:42:43 AM: Compilation took 6.291e-02 seconds
(CVXPY) Jul 07 11:42:43 AM: Solver (including time spent in interface) took 9.823e-01 seconds
(CVXPY) Jul 07 11:42:43 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:43 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:43 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:42:43 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:43 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:43 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:43 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:43 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:43 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:43 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:43 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:43 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:43 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:43 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:43 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:43 AM: Finished problem compilation (took 5.570e-02 seconds).
(CVXPY) Jul 07 11:42:43 AM: Invoking solver SCS  to obtain a solution.

    75| 3.33e-05  6.63e-09  1.07e-06  2.59e+00  1.00e-01  9.77e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.77e-01s = setup: 3.03e-02s + solve: 9.47e-01s
	 lin-sys: 4.76e-02s, cones: 8.78e-01s, accel: 4.89e-03s
------------------------------------------------------------------
objective = 2.585754
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  2.66e-02  5.06e-02  3.45e-01  1.00e-01  5.27e-02
   250| 1.09e-04  5.60e-08  2.82e-06  2.82e-06  9.80e-06  3.08e+00

(CVXPY) Jul 07 11:42:46 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:46 AM: Optimal value: 7.549e-07
(CVXPY) Jul 07 11:42:46 AM: Compilation took 5.570e-02 seconds
(CVXPY) Jul 07 11:42:46 AM: Solver (including time spent in interface) took 3.644e+00 seconds
(CVXPY) Jul 07 11:42:46 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:46 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:46 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:42:46 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:46 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:46 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:46 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:46 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:46 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:46 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:46 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:47 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:47 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:47 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:47 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:47 AM: Finished problem compilation (took 5.615e-02 seconds).
(CVXPY) Jul 07 11:42:47 AM: Invoking solver SCS  to obtain a solution.

   300| 3.05e-05  3.18e-08  1.57e-06  1.54e-06  9.80e-06  3.64e+00
------------------------------------------------------------------
status:  solved
timings: total: 3.64e+00s = setup: 2.41e-02s + solve: 3.61e+00s
	 lin-sys: 1.80e-01s, cones: 3.37e+00s, accel: 1.90e-02s
------------------------------------------------------------------
objective = 0.000002
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  5.89e-02  1.37e-01  6.06e-01  1.00e-01  5.10e-02
   250| 1.13e-04  4.63e-08  2.31e-06  2.31e-06  7.82e-06  3.07e+00

(CVXPY) Jul 07 11:42:50 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:50 AM: Optimal value: 6.115e-07
(CVXPY) Jul 07 11:42:50 AM: Compilation took 5.615e-02 seconds
(CVXPY) Jul 07 11:42:50 AM: Solver (including time spent in interface) took 3.930e+00 seconds
(CVXPY) Jul 07 11:42:50 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:50 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:50 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:42:50 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:51 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:51 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:51 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:51 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:51 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:51 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:51 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:51 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:51 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:51 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:51 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:51 AM: Finished problem compilation (took 1.148e-01 seconds).
(CVXPY) Jul 07 11:42:51 AM: Invoking solver SCS  to obtain a solution.

   300| 3.05e-05  2.53e-08  1.29e-06  1.26e-06  7.82e-06  3.92e+00
------------------------------------------------------------------
status:  solved
timings: total: 3.92e+00s = setup: 2.53e-02s + solve: 3.89e+00s
	 lin-sys: 2.11e-01s, cones: 3.61e+00s, accel: 2.32e-02s
------------------------------------------------------------------
objective = 0.000001
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  5.68e-02  1.22e-01  6.51e-01  1.00e-01  1.02e-01
   250| 1.13e-04  4.80e-08  2.42e-06  2.44e-06  8.08e-06  4.35e+00

(CVXPY) Jul 07 11:42:56 AM: Problem status: optimal
(CVXPY) Jul 07 11:42:56 AM: Optimal value: 6.517e-07
(CVXPY) Jul 07 11:42:56 AM: Compilation took 1.148e-01 seconds
(CVXPY) Jul 07 11:42:56 AM: Solver (including time spent in interface) took 5.074e+00 seconds
(CVXPY) Jul 07 11:42:56 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:42:56 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:42:56 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:42:56 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:42:56 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:42:56 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:42:56 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:42:56 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:42:56 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:42:56 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:42:56 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:42:56 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:42:56 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:42:56 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:42:56 AM: Applying reduction SCS
(CVXPY) Jul 07 11:42:56 AM: Finished problem compilation (took 1.126e-01 seconds).
(CVXPY) Jul 07 11:42:56 AM: Invoking solver SCS  to obtain a solution.

   300| 3.08e-05  2.63e-08  1.36e-06  1.33e-06  8.08e-06  5.07e+00
------------------------------------------------------------------
status:  solved
timings: total: 5.07e+00s = setup: 4.90e-02s + solve: 5.02e+00s
	 lin-sys: 2.70e-01s, cones: 4.66e+00s, accel: 1.84e-02s
------------------------------------------------------------------
objective = 0.000001
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  5.80e-02  1.75e-01  6.09e-01  1.00e-01  8.64e-02
   250| 1.12e-04  4.73e-08  2.35e-06  2.36e-06  8.00e-06  4.16e+00

(CVXPY) Jul 07 11:43:01 AM: Problem status: optimal
(CVXPY) Jul 07 11:43:01 AM: Optimal value: 6.263e-07
(CVXPY) Jul 07 11:43:01 AM: Compilation took 1.126e-01 seconds
(CVXPY) Jul 07 11:43:01 AM: Solver (including time spent in interface) took 4.914e+00 seconds
(CVXPY) Jul 07 11:43:01 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:43:01 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:43:01 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:43:01 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:43:01 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:43:01 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:43:01 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:43:01 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:43:01 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:43:01 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:43:01 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:43:01 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:43:01 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:43:01 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:43:01 AM: Applying reduction SCS
(CVXPY) Jul 07 11:43:01 AM: Finished problem compilation (took 1.195e-01 seconds).
(CVXPY) Jul 07 11:43:01 AM: Invoking solver SCS  to obtain a solution.

   300| 3.06e-05  2.59e-08  1.32e-06  1.28e-06  8.00e-06  4.90e+00
------------------------------------------------------------------
status:  solved
timings: total: 4.90e+00s = setup: 4.26e-02s + solve: 4.86e+00s
	 lin-sys: 2.71e-01s, cones: 4.50e+00s, accel: 2.10e-02s
------------------------------------------------------------------
objective = 0.000001
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  2.68e-02  6.80e-02  3.38e-01  1.00e-01  1.03e-01
   250| 1.08e-04  5.67e-08  2.84e-06  2.82e-06  9.99e-06  4.14e+00

(CVXPY) Jul 07 11:43:06 AM: Problem status: optimal
(CVXPY) Jul 07 11:43:06 AM: Optimal value: 7.465e-07
(CVXPY) Jul 07 11:43:06 AM: Compilation took 1.195e-01 seconds
(CVXPY) Jul 07 11:43:06 AM: Solver (including time spent in interface) took 4.873e+00 seconds
(CVXPY) Jul 07 11:43:06 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:43:06 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:43:06 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:43:06 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:43:06 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:43:06 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:43:06 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:43:06 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:43:06 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:43:06 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:43:06 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:43:06 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:43:06 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:43:06 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:43:06 AM: Applying reduction SCS
(CVXPY) Jul 07 11:43:06 AM: Finished problem compilation (took 1.105e-01 seconds).
(CVXPY) Jul 07 11:43:06 AM: Invoking solver SCS  to obtain a solution.

   300| 3.02e-05  3.21e-08  1.58e-06  1.53e-06  9.99e-06  4.87e+00
------------------------------------------------------------------
status:  solved
timings: total: 4.87e+00s = setup: 5.69e-02s + solve: 4.81e+00s
	 lin-sys: 2.79e-01s, cones: 4.45e+00s, accel: 1.88e-02s
------------------------------------------------------------------
objective = 0.000002
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  5.54e-02  1.53e-01  7.01e-01  1.00e-01  9.45e-02
   250| 1.11e-04  5.99e-08  3.07e-06  3.03e-06  9.89e-06  3.68e+00

(CVXPY) Jul 07 11:43:10 AM: Problem status: optimal
(CVXPY) Jul 07 11:43:10 AM: Optimal value: 7.962e-07
(CVXPY) Jul 07 11:43:10 AM: Compilation took 1.105e-01 seconds
(CVXPY) Jul 07 11:43:10 AM: Solver (including time spent in interface) took 4.286e+00 seconds
(CVXPY) Jul 07 11:43:10 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:43:10 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:43:10 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:43:10 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:43:10 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:43:10 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:43:10 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:43:10 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:43:10 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:43:10 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:43:10 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:43:10 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:43:10 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:43:10 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:43:10 AM: Applying reduction SCS
(CVXPY) Jul 07 11:43:10 AM: Finished problem compilation (took 1.241e-01 seconds).
(CVXPY) Jul 07 11:43:10 AM: Invoking solver SCS  to obtain a solution.

   300| 3.12e-05  3.30e-08  1.70e-06  1.65e-06  9.89e-06  4.28e+00
------------------------------------------------------------------
status:  solved
timings: total: 4.28e+00s = setup: 4.94e-02s + solve: 4.23e+00s
	 lin-sys: 2.32e-01s, cones: 3.92e+00s, accel: 1.65e-02s
------------------------------------------------------------------
objective = 0.000002
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  5.93e-02  1.68e-01  6.06e-01  1.00e-01  9.39e-02
   250| 1.13e-04  4.63e-08  2.31e-06  2.31e-06  7.87e-06  3.86e+00

(CVXPY) Jul 07 11:43:15 AM: Problem status: optimal
(CVXPY) Jul 07 11:43:15 AM: Optimal value: 6.124e-07
(CVXPY) Jul 07 11:43:15 AM: Compilation took 1.241e-01 seconds
(CVXPY) Jul 07 11:43:15 AM: Solver (including time spent in interface) took 4.557e+00 seconds
(CVXPY) Jul 07 11:43:15 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:43:15 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:43:15 AM: DCP verification time: 0.0009 seconds.
(CVXPY) Jul 07 11:43:15 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:43:15 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:43:15 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:43:15 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:43:15 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:43:15 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:43:15 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:43:15 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:43:15 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:43:15 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:43:15 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:43:15 AM: Applying reduction SCS
(CVXPY) Jul 07 11:43:15 AM: Finished problem compilation (took 1.060e-01 seconds).
(CVXPY) Jul 07 11:43:15 AM: Invoking solver SCS  to obtain a solution.

   300| 3.03e-05  2.52e-08  1.29e-06  1.26e-06  7.87e-06  4.55e+00
------------------------------------------------------------------
status:  solved
timings: total: 4.55e+00s = setup: 4.85e-02s + solve: 4.50e+00s
	 lin-sys: 2.66e-01s, cones: 4.15e+00s, accel: 1.84e-02s
------------------------------------------------------------------
objective = 0.000001
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  2.66e-02  4.08e-02  3.08e-01  1.00e-01  1.35e-01
   250| 1.03e-04  4.90e-08  2.31e-06  2.34e-06  8.71e-06  4.07e+00

(CVXPY) Jul 07 11:43:20 AM: Problem status: optimal
(CVXPY) Jul 07 11:43:20 AM: Optimal value: 6.312e-07
(CVXPY) Jul 07 11:43:20 AM: Compilation took 1.060e-01 seconds
(CVXPY) Jul 07 11:43:20 AM: Solver (including time spent in interface) took 4.834e+00 seconds
(CVXPY) Jul 07 11:43:20 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:43:20 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:43:20 AM: DCP verification time: 0.0011 seconds.
(CVXPY) Jul 07 11:43:20 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:43:20 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:43:20 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:43:20 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:43:20 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:43:20 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:43:20 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:43:20 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:43:20 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:43:20 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:43:20 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:43:20 AM: Applying reduction SCS
(CVXPY) Jul 07 11:43:20 AM: Finished problem compilation (took 9.442e-02 seconds).
(CVXPY) Jul 07 11:43:20 AM: Invoking solver SCS  to obtain a solution.

   300| 2.97e-05  2.75e-08  1.30e-06  1.28e-06  8.71e-06  4.82e+00
------------------------------------------------------------------
status:  solved
timings: total: 4.82e+00s = setup: 8.06e-02s + solve: 4.74e+00s
	 lin-sys: 2.68e-01s, cones: 4.39e+00s, accel: 2.60e-02s
------------------------------------------------------------------
objective = 0.000001
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  5.76e-02  1.18e-01  6.79e-01  1.00e-01  9.85e-02
   250| 1.13e-04  4.61e-08  2.33e-06  2.32e-06  7.77e-06  4.63e+00

(CVXPY) Jul 07 11:43:26 AM: Problem status: optimal
(CVXPY) Jul 07 11:43:26 AM: Optimal value: 6.143e-07
(CVXPY) Jul 07 11:43:26 AM: Compilation took 9.442e-02 seconds
(CVXPY) Jul 07 11:43:26 AM: Solver (including time spent in interface) took 5.458e+00 seconds
(CVXPY) Jul 07 11:43:26 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:43:26 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:43:26 AM: DCP verification time: 0.0010 seconds.
(CVXPY) Jul 07 11:43:26 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:43:26 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:43:26 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:43:26 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:43:26 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:43:26 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:43:26 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:43:26 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:43:26 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:43:26 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:43:26 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:43:26 AM: Applying reduction SCS
(CVXPY) Jul 07 11:43:26 AM: Finished problem compilation (took 9.770e-02 seconds).
(CVXPY) Jul 07 11:43:26 AM: Invoking solver SCS  to obtain a solution.

   300| 3.04e-05  2.50e-08  1.30e-06  1.27e-06  7.77e-06  5.45e+00
------------------------------------------------------------------
status:  solved
timings: total: 5.45e+00s = setup: 5.05e-02s + solve: 5.40e+00s
	 lin-sys: 3.00e-01s, cones: 5.00e+00s, accel: 2.03e-02s
------------------------------------------------------------------
objective = 0.000001
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  2.66e-02  1.98e-02  3.10e-01  1.00e-01  9.36e-02
   250| 1.07e-04  4.95e-08  2.38e-06  2.41e-06  8.59e-06  4.48e+00

(CVXPY) Jul 07 11:43:31 AM: Problem status: optimal
(CVXPY) Jul 07 11:43:31 AM: Optimal value: 6.532e-07
(CVXPY) Jul 07 11:43:31 AM: Compilation took 9.770e-02 seconds
(CVXPY) Jul 07 11:43:31 AM: Solver (including time spent in interface) took 5.322e+00 seconds
(CVXPY) Jul 07 11:43:31 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:43:31 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:43:31 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:43:31 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:43:31 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:43:31 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:43:31 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:43:31 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:43:31 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:43:31 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:43:31 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:43:31 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:43:31 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:43:31 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:43:31 AM: Applying reduction SCS
(CVXPY) Jul 07 11:43:31 AM: Finished problem compilation (took 1.312e-01 seconds).
(CVXPY) Jul 07 11:43:31 AM: Invoking solver SCS  to obtain a solution.

   300| 3.03e-05  2.76e-08  1.34e-06  1.32e-06  8.59e-06  5.31e+00
------------------------------------------------------------------
status:  solved
timings: total: 5.31e+00s = setup: 4.72e-02s + solve: 5.27e+00s
	 lin-sys: 3.15e-01s, cones: 4.86e+00s, accel: 1.88e-02s
------------------------------------------------------------------
objective = 0.000001
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  2.66e-02  5.00e-02  3.18e-01  1.00e-01  9.17e-02
   250| 1.11e-04  6.51e-08  3.07e-06  3.05e-06  1.06e-05  3.67e+00

(CVXPY) Jul 07 11:43:36 AM: Problem status: optimal
(CVXPY) Jul 07 11:43:36 AM: Optimal value: 8.125e-07
(CVXPY) Jul 07 11:43:36 AM: Compilation took 1.312e-01 seconds
(CVXPY) Jul 07 11:43:36 AM: Solver (including time spent in interface) took 4.320e+00 seconds
(CVXPY) Jul 07 11:43:36 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:43:36 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:43:36 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:43:36 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:43:36 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:43:36 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:43:36 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:43:36 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:43:36 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:43:36 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:43:36 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:43:36 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:43:36 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:43:36 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:43:36 AM: Applying reduction SCS
(CVXPY) Jul 07 11:43:36 AM: Finished problem compilation (took 7.324e-02 seconds).
(CVXPY) Jul 07 11:43:36 AM: Invoking solver SCS  to obtain a solution.

   300| 3.00e-05  3.43e-08  1.71e-06  1.67e-06  1.06e-05  4.31e+00
------------------------------------------------------------------
status:  solved
timings: total: 4.31e+00s = setup: 4.80e-02s + solve: 4.26e+00s
	 lin-sys: 2.40e-01s, cones: 3.94e+00s, accel: 1.86e-02s
------------------------------------------------------------------
objective = 0.000002
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  5.70e-02  1.14e-01  6.24e-01  1.00e-01  6.28e-02
   250| 1.09e-04  5.49e-08  2.61e-06  2.62e-06  8.79e-06  3.88e+00

(CVXPY) Jul 07 11:43:40 AM: Problem status: optimal
(CVXPY) Jul 07 11:43:40 AM: Optimal value: 7.024e-07
(CVXPY) Jul 07 11:43:40 AM: Compilation took 7.324e-02 seconds
(CVXPY) Jul 07 11:43:40 AM: Solver (including time spent in interface) took 4.588e+00 seconds
(CVXPY) Jul 07 11:43:40 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:43:40 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:43:40 AM: DCP verification time: 0.0012 seconds.
(CVXPY) Jul 07 11:43:40 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:43:40 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:43:40 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:43:40 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:43:40 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:43:40 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:43:40 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:43:40 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:43:40 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:43:40 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:43:40 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:43:40 AM: Applying reduction SCS
(CVXPY) Jul 07 11:43:40 AM: Finished problem compilation (took 6.810e-02 seconds).
(CVXPY) Jul 07 11:43:40 AM: Invoking solver SCS  to obtain a solution.

   300| 3.10e-05  2.89e-08  1.46e-06  1.43e-06  8.79e-06  4.58e+00
------------------------------------------------------------------
status:  solved
timings: total: 4.58e+00s = setup: 3.20e-02s + solve: 4.55e+00s
	 lin-sys: 2.49e-01s, cones: 4.21e+00s, accel: 2.72e-02s
------------------------------------------------------------------
objective = 0.000001
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  5.80e-02  1.41e-01  5.85e-01  1.00e-01  6.32e-02
   250| 1.04e-04  5.55e-08  2.47e-06  2.47e-06  8.85e-06  3.78e+00

(CVXPY) Jul 07 11:43:45 AM: Problem status: optimal
(CVXPY) Jul 07 11:43:45 AM: Optimal value: 6.591e-07
(CVXPY) Jul 07 11:43:45 AM: Compilation took 6.810e-02 seconds
(CVXPY) Jul 07 11:43:45 AM: Solver (including time spent in interface) took 4.452e+00 seconds
(CVXPY) Jul 07 11:43:45 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:43:45 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:43:45 AM: DCP verification time: 0.0009 seconds.
(CVXPY) Jul 07 11:43:45 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:43:45 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:43:45 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:43:45 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:43:45 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:43:45 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:43:45 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:43:45 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:43:45 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:43:45 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:43:45 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:43:45 AM: Applying reduction SCS
(CVXPY) Jul 07 11:43:45 AM: Finished problem compilation (took 8.352e-02 seconds).
(CVXPY) Jul 07 11:43:45 AM: Invoking solver SCS  to obtain a solution.

   300| 2.99e-05  2.90e-08  1.39e-06  1.35e-06  8.85e-06  4.44e+00
------------------------------------------------------------------
status:  solved
timings: total: 4.44e+00s = setup: 3.18e-02s + solve: 4.40e+00s
	 lin-sys: 2.42e-01s, cones: 4.09e+00s, accel: 2.00e-02s
------------------------------------------------------------------
objective = 0.000001
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  2.66e-02  1.08e-02  2.75e-01  1.00e-01  6.67e-02
   250| 1.08e-04  5.68e-08  2.65e-06  2.68e-06  9.07e-06  3.74e+00

(CVXPY) Jul 07 11:43:49 AM: Problem status: optimal
(CVXPY) Jul 07 11:43:49 AM: Optimal value: 7.248e-07
(CVXPY) Jul 07 11:43:49 AM: Compilation took 8.352e-02 seconds
(CVXPY) Jul 07 11:43:49 AM: Solver (including time spent in interface) took 4.390e+00 seconds
(CVXPY) Jul 07 11:43:49 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:43:49 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:43:49 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:43:49 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:43:49 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:43:49 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:43:49 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:43:49 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:43:49 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:43:49 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:43:49 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:43:49 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:43:49 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:43:49 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:43:49 AM: Applying reduction SCS
(CVXPY) Jul 07 11:43:49 AM: Finished problem compilation (took 7.987e-02 seconds).
(CVXPY) Jul 07 11:43:49 AM: Invoking solver SCS  to obtain a solution.

   300| 3.14e-05  3.02e-08  1.49e-06  1.47e-06  9.07e-06  4.38e+00
------------------------------------------------------------------
status:  solved
timings: total: 4.38e+00s = setup: 3.66e-02s + solve: 4.35e+00s
	 lin-sys: 2.50e-01s, cones: 4.02e+00s, accel: 1.90e-02s
------------------------------------------------------------------
objective = 0.000001
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  5.62e-02  1.66e-01  6.60e-01  1.00e-01  7.69e-02
   250| 1.11e-04  5.90e-08  3.06e-06  3.02e-06  9.82e-06  3.96e+00

(CVXPY) Jul 07 11:43:54 AM: Problem status: optimal
(CVXPY) Jul 07 11:43:54 AM: Optimal value: 7.963e-07
(CVXPY) Jul 07 11:43:54 AM: Compilation took 7.987e-02 seconds
(CVXPY) Jul 07 11:43:54 AM: Solver (including time spent in interface) took 4.640e+00 seconds
(CVXPY) Jul 07 11:43:54 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:43:54 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:43:54 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:43:54 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:43:54 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:43:54 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:43:54 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:43:54 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:43:54 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:43:54 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:43:54 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:43:54 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:43:54 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:43:54 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:43:54 AM: Applying reduction SCS
(CVXPY) Jul 07 11:43:54 AM: Finished problem compilation (took 7.652e-02 seconds).
(CVXPY) Jul 07 11:43:54 AM: Invoking solver SCS  to obtain a solution.

   300| 3.12e-05  3.25e-08  1.69e-06  1.64e-06  9.82e-06  4.63e+00
------------------------------------------------------------------
status:  solved
timings: total: 4.63e+00s = setup: 3.30e-02s + solve: 4.60e+00s
	 lin-sys: 2.55e-01s, cones: 4.26e+00s, accel: 2.09e-02s
------------------------------------------------------------------
objective = 0.000002
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  5.99e-02  1.44e-01  6.01e-01  1.00e-01  6.91e-02
   250| 1.10e-04  4.31e-08  2.11e-06  2.12e-06  7.52e-06  4.11e+00

(CVXPY) Jul 07 11:43:59 AM: Problem status: optimal
(CVXPY) Jul 07 11:43:59 AM: Optimal value: 5.674e-07
(CVXPY) Jul 07 11:43:59 AM: Compilation took 7.652e-02 seconds
(CVXPY) Jul 07 11:43:59 AM: Solver (including time spent in interface) took 4.850e+00 seconds
(CVXPY) Jul 07 11:43:59 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:43:59 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:43:59 AM: DCP verification time: 0.0010 seconds.
(CVXPY) Jul 07 11:43:59 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:43:59 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:43:59 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:43:59 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:43:59 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:43:59 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:43:59 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:43:59 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:43:59 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:43:59 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:43:59 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:43:59 AM: Applying reduction SCS
(CVXPY) Jul 07 11:43:59 AM: Finished problem compilation (took 7.065e-02 seconds).
(CVXPY) Jul 07 11:43:59 AM: Invoking solver SCS  to obtain a solution.

   300| 2.92e-05  2.34e-08  1.19e-06  1.16e-06  7.52e-06  4.84e+00
------------------------------------------------------------------
status:  solved
timings: total: 4.84e+00s = setup: 3.88e-02s + solve: 4.81e+00s
	 lin-sys: 2.77e-01s, cones: 4.44e+00s, accel: 2.08e-02s
------------------------------------------------------------------
objective = 0.000001
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  2.82e-02  1.23e-02  3.47e-01  1.00e-01  7.65e-02
   250| 1.05e-04  5.61e-08  2.53e-06  2.55e-06  9.03e-06  4.00e+00

(CVXPY) Jul 07 11:44:04 AM: Problem status: optimal
(CVXPY) Jul 07 11:44:04 AM: Optimal value: 6.897e-07
(CVXPY) Jul 07 11:44:04 AM: Compilation took 7.065e-02 seconds
(CVXPY) Jul 07 11:44:04 AM: Solver (including time spent in interface) took 4.653e+00 seconds
(CVXPY) Jul 07 11:44:04 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:44:04 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:44:04 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:44:04 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:44:04 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:44:04 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:44:04 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:44:04 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:44:04 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:44:04 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:44:04 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:44:04 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:44:04 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:44:04 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:44:04 AM: Applying reduction SCS
(CVXPY) Jul 07 11:44:04 AM: Finished problem compilation (took 8.081e-02 seconds).
(CVXPY) Jul 07 11:44:04 AM: Invoking solver SCS  to obtain a solution.

   300| 3.03e-05  2.95e-08  1.41e-06  1.40e-06  9.03e-06  4.65e+00
------------------------------------------------------------------
status:  solved
timings: total: 4.65e+00s = setup: 4.36e-02s + solve: 4.60e+00s
	 lin-sys: 2.54e-01s, cones: 4.27e+00s, accel: 2.03e-02s
------------------------------------------------------------------
objective = 0.000001
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  5.74e-02  1.47e-01  6.59e-01  1.00e-01  8.12e-02
   250| 1.07e-04  5.87e-08  2.97e-06  2.91e-06  9.70e-06  3.70e+00

(CVXPY) Jul 07 11:44:08 AM: Problem status: optimal
(CVXPY) Jul 07 11:44:08 AM: Optimal value: 7.596e-07
(CVXPY) Jul 07 11:44:08 AM: Compilation took 8.081e-02 seconds
(CVXPY) Jul 07 11:44:08 AM: Solver (including time spent in interface) took 4.400e+00 seconds
(CVXPY) Jul 07 11:44:08 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:44:08 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:44:08 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:44:08 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:44:08 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:44:08 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:44:08 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:44:08 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:44:08 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:44:08 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:44:08 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:44:08 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:44:08 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:44:08 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:44:08 AM: Applying reduction SCS
(CVXPY) Jul 07 11:44:08 AM: Finished problem compilation (took 1.104e-01 seconds).
(CVXPY) Jul 07 11:44:08 AM: Invoking solver SCS  to obtain a solution.

   300| 3.07e-05  3.18e-08  1.64e-06  1.58e-06  9.70e-06  4.39e+00
------------------------------------------------------------------
status:  solved
timings: total: 4.39e+00s = setup: 4.79e-02s + solve: 4.34e+00s
	 lin-sys: 2.38e-01s, cones: 4.02e+00s, accel: 2.19e-02s
------------------------------------------------------------------
objective = 0.000002
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  5.75e-02  1.51e-01  6.25e-01  1.00e-01  8.03e-02
   250| 1.05e-04  5.81e-08  2.80e-06  2.78e-06  9.46e-06  3.91e+00

(CVXPY) Jul 07 11:44:13 AM: Problem status: optimal
(CVXPY) Jul 07 11:44:13 AM: Optimal value: 7.371e-07
(CVXPY) Jul 07 11:44:13 AM: Compilation took 1.104e-01 seconds
(CVXPY) Jul 07 11:44:13 AM: Solver (including time spent in interface) took 4.654e+00 seconds
(CVXPY) Jul 07 11:44:13 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:44:13 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:44:13 AM: DCP verification time: 0.0010 seconds.
(CVXPY) Jul 07 11:44:13 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:44:13 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:44:13 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:44:13 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:44:13 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:44:13 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:44:13 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:44:13 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:44:13 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:44:13 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:44:13 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:44:13 AM: Applying reduction SCS
(CVXPY) Jul 07 11:44:13 AM: Finished problem compilation (took 8.601e-02 seconds).
(CVXPY) Jul 07 11:44:13 AM: Invoking solver SCS  to obtain a solution.

   300| 3.05e-05  3.08e-08  1.56e-06  1.52e-06  9.46e-06  4.65e+00
------------------------------------------------------------------
status:  solved
timings: total: 4.65e+00s = setup: 4.36e-02s + solve: 4.60e+00s
	 lin-sys: 2.45e-01s, cones: 4.28e+00s, accel: 2.19e-02s
------------------------------------------------------------------
objective = 0.000002
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  2.76e-02  2.93e-02  3.83e-01  1.00e-01  8.38e-02
   250| 1.07e-04  5.78e-08  2.78e-06  2.78e-06  9.51e-06  3.21e+00

(CVXPY) Jul 07 11:44:17 AM: Problem status: optimal
(CVXPY) Jul 07 11:44:17 AM: Optimal value: 7.468e-07
(CVXPY) Jul 07 11:44:17 AM: Compilation took 8.601e-02 seconds
(CVXPY) Jul 07 11:44:17 AM: Solver (including time spent in interface) took 3.768e+00 seconds
(CVXPY) Jul 07 11:44:17 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:44:17 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:44:17 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:44:17 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:44:17 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:44:17 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:44:17 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:44:17 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:44:17 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:44:17 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:44:17 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:44:17 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:44:17 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:44:17 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:44:17 AM: Applying reduction SCS
(CVXPY) Jul 07 11:44:17 AM: Finished problem compilation (took 6.304e-02 seconds).
(CVXPY) Jul 07 11:44:17 AM: Invoking solver SCS  to obtain a solution.

   300| 3.09e-05  3.12e-08  1.55e-06  1.52e-06  9.51e-06  3.76e+00
------------------------------------------------------------------
status:  solved
timings: total: 3.76e+00s = setup: 4.49e-02s + solve: 3.72e+00s
	 lin-sys: 2.05e-01s, cones: 3.44e+00s, accel: 1.71e-02s
------------------------------------------------------------------
objective = 0.000002
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.84e+01  1.00e-01  6.21e-02

(CVXPY) Jul 07 11:44:18 AM: Problem status: optimal
(CVXPY) Jul 07 11:44:18 AM: Optimal value: 3.972e-01
(CVXPY) Jul 07 11:44:18 AM: Compilation took 6.304e-02 seconds
(CVXPY) Jul 07 11:44:18 AM: Solver (including time spent in interface) took 6.579e-01 seconds
(CVXPY) Jul 07 11:44:18 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:44:18 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:44:18 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:44:18 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:44:18 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:44:18 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:44:18 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:44:18 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:44:18 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:44:18 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:44:18 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:44:18 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:44:18 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:44:18 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:44:18 AM: Applying reduction SCS
(CVXPY) Jul 07 11:44:18 AM: Finished problem compilation (took 7.276e-02 seconds).
(CVXPY) Jul 07 11:44:18 AM: Invoking solver SCS  to obtain a solution.

    50| 2.29e-05  4.84e-08  2.26e-06  3.97e-01  1.00e-01  6.51e-01
------------------------------------------------------------------
status:  solved
timings: total: 6.52e-01s = setup: 3.18e-02s + solve: 6.20e-01s
	 lin-sys: 3.53e-02s, cones: 5.68e-01s, accel: 3.22e-03s
------------------------------------------------------------------
objective = 0.397241
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.73e+01 -2.81e+01  1.00e-01  7.47e-02

(CVXPY) Jul 07 11:44:19 AM: Problem status: optimal
(CVXPY) Jul 07 11:44:19 AM: Optimal value: 5.948e-01
(CVXPY) Jul 07 11:44:19 AM: Compilation took 7.276e-02 seconds
(CVXPY) Jul 07 11:44:19 AM: Solver (including time spent in interface) took 9.879e-01 seconds
(CVXPY) Jul 07 11:44:19 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:44:19 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:44:19 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:44:19 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:44:19 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:44:19 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:44:19 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:44:19 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:44:19 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:44:19 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:44:19 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:44:19 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:44:19 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:44:19 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:44:19 AM: Applying reduction SCS
(CVXPY) Jul 07 11:44:19 AM: Finished problem compilation (took 7.735e-02 seconds).
(CVXPY) Jul 07 11:44:19 AM: Invoking solver SCS  to obtain a solution.

    75| 2.35e-06  3.15e-09  2.86e-07  5.95e-01  1.00e-01  9.78e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.79e-01s = setup: 3.48e-02s + solve: 9.44e-01s
	 lin-sys: 6.49e-02s, cones: 8.54e-01s, accel: 7.21e-03s
------------------------------------------------------------------
objective = 0.594789
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.73e+01 -2.81e+01  1.00e-01  8.49e-02

(CVXPY) Jul 07 11:44:20 AM: Problem status: optimal
(CVXPY) Jul 07 11:44:20 AM: Optimal value: 6.356e-01
(CVXPY) Jul 07 11:44:20 AM: Compilation took 7.735e-02 seconds
(CVXPY) Jul 07 11:44:20 AM: Solver (including time spent in interface) took 1.034e+00 seconds
(CVXPY) Jul 07 11:44:20 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:44:20 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:44:20 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:44:20 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:44:20 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:44:20 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:44:20 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:44:20 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:44:20 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:44:20 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:44:20 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:44:20 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:44:20 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:44:20 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:44:20 AM: Applying reduction SCS
(CVXPY) Jul 07 11:44:20 AM: Finished problem compilation (took 7.274e-02 seconds).
(CVXPY) Jul 07 11:44:20 AM: Invoking solver SCS  to obtain a solution.

    75| 1.11e-06  4.30e-09  1.89e-07  6.36e-01  1.00e-01  1.03e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.03e+00s = setup: 4.72e-02s + solve: 9.80e-01s
	 lin-sys: 6.35e-02s, cones: 8.92e-01s, accel: 5.49e-03s
------------------------------------------------------------------
objective = 0.635603
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.73e+01 -2.81e+01  1.00e-01  6.23e-02

(CVXPY) Jul 07 11:44:21 AM: Problem status: optimal
(CVXPY) Jul 07 11:44:21 AM: Optimal value: 5.926e-01
(CVXPY) Jul 07 11:44:21 AM: Compilation took 7.274e-02 seconds
(CVXPY) Jul 07 11:44:21 AM: Solver (including time spent in interface) took 1.048e+00 seconds
(CVXPY) Jul 07 11:44:21 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:44:21 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:44:21 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:44:21 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:44:21 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:44:21 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:44:21 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:44:21 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:44:21 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:44:21 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:44:21 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:44:21 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:44:21 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:44:21 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:44:21 AM: Applying reduction SCS
(CVXPY) Jul 07 11:44:21 AM: Finished problem compilation (took 7.122e-02 seconds).
(CVXPY) Jul 07 11:44:21 AM: Invoking solver SCS  to obtain a solution.

    75| 1.09e-06  3.13e-09  1.86e-07  5.93e-01  1.00e-01  1.04e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.04e+00s = setup: 3.25e-02s + solve: 1.01e+00s
	 lin-sys: 6.45e-02s, cones: 9.19e-01s, accel: 6.00e-03s
------------------------------------------------------------------
objective = 0.592642
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.84e+01  1.00e-01  6.47e-02

(CVXPY) Jul 07 11:44:22 AM: Problem status: optimal
(CVXPY) Jul 07 11:44:22 AM: Optimal value: 3.963e-01
(CVXPY) Jul 07 11:44:22 AM: Compilation took 7.122e-02 seconds
(CVXPY) Jul 07 11:44:22 AM: Solver (including time spent in interface) took 7.349e-01 seconds
(CVXPY) Jul 07 11:44:22 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:44:22 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:44:22 AM: DCP verification time: 0.0009 seconds.
(CVXPY) Jul 07 11:44:22 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:44:22 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:44:22 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:44:22 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:44:22 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:44:22 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:44:22 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:44:22 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:44:22 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:44:22 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:44:22 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:44:22 AM: Applying reduction SCS
(CVXPY) Jul 07 11:44:22 AM: Finished problem compilation (took 7.347e-02 seconds).
(CVXPY) Jul 07 11:44:22 AM: Invoking solver SCS  to obtain a solution.

    50| 3.23e-05  1.00e-07  4.66e-06  3.96e-01  1.00e-01  7.27e-01
------------------------------------------------------------------
status:  solved
timings: total: 7.28e-01s = setup: 3.38e-02s + solve: 6.94e-01s
	 lin-sys: 4.11e-02s, cones: 6.38e-01s, accel: 3.04e-03s
------------------------------------------------------------------
objective = 0.396259
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.73e+01 -2.80e+01  1.00e-01  6.35e-02

(CVXPY) Jul 07 11:44:23 AM: Problem status: optimal
(CVXPY) Jul 07 11:44:23 AM: Optimal value: 6.413e-01
(CVXPY) Jul 07 11:44:23 AM: Compilation took 7.347e-02 seconds
(CVXPY) Jul 07 11:44:23 AM: Solver (including time spent in interface) took 9.938e-01 seconds
(CVXPY) Jul 07 11:44:23 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:44:23 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:44:23 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:44:23 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:44:23 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:44:23 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:44:23 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:44:23 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:44:23 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:44:23 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:44:23 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:44:23 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:44:23 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:44:23 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:44:23 AM: Applying reduction SCS
(CVXPY) Jul 07 11:44:23 AM: Finished problem compilation (took 7.962e-02 seconds).
(CVXPY) Jul 07 11:44:23 AM: Invoking solver SCS  to obtain a solution.

    75| 3.16e-06  3.69e-09  3.74e-07  6.41e-01  1.00e-01  9.86e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.86e-01s = setup: 3.34e-02s + solve: 9.53e-01s
	 lin-sys: 6.61e-02s, cones: 8.65e-01s, accel: 4.91e-03s
------------------------------------------------------------------
objective = 0.641337
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.73e+01 -2.81e+01  1.00e-01  9.08e-02

(CVXPY) Jul 07 11:44:24 AM: Problem status: optimal
(CVXPY) Jul 07 11:44:24 AM: Optimal value: 5.886e-01
(CVXPY) Jul 07 11:44:24 AM: Compilation took 7.962e-02 seconds
(CVXPY) Jul 07 11:44:24 AM: Solver (including time spent in interface) took 1.032e+00 seconds
(CVXPY) Jul 07 11:44:24 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:44:24 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:44:24 AM: DCP verification time: 0.0015 seconds.
(CVXPY) Jul 07 11:44:24 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:44:24 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:44:24 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:44:24 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:44:24 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:44:24 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:44:24 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:44:24 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:44:24 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:44:24 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:44:24 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:44:24 AM: Applying reduction SCS
(CVXPY) Jul 07 11:44:24 AM: Finished problem compilation (took 8.770e-02 seconds).
(CVXPY) Jul 07 11:44:24 AM: Invoking solver SCS  to obtain a solution.

    75| 2.52e-06  4.63e-09  3.70e-07  5.89e-01  1.00e-01  1.02e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.02e+00s = setup: 3.88e-02s + solve: 9.86e-01s
	 lin-sys: 6.33e-02s, cones: 9.00e-01s, accel: 5.22e-03s
------------------------------------------------------------------
objective = 0.588600
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.84e+01  1.00e-01  8.69e-02

(CVXPY) Jul 07 11:44:26 AM: Problem status: optimal
(CVXPY) Jul 07 11:44:26 AM: Optimal value: 3.724e-01
(CVXPY) Jul 07 11:44:26 AM: Compilation took 8.770e-02 seconds
(CVXPY) Jul 07 11:44:26 AM: Solver (including time spent in interface) took 1.235e+00 seconds
(CVXPY) Jul 07 11:44:26 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:44:26 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:44:26 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:44:26 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:44:26 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:44:26 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:44:26 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:44:26 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:44:26 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:44:26 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:44:26 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:44:26 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:44:26 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:44:26 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:44:26 AM: Applying reduction SCS
(CVXPY) Jul 07 11:44:26 AM: Finished problem compilation (took 7.832e-02 seconds).
(CVXPY) Jul 07 11:44:26 AM: Invoking solver SCS  to obtain a solution.

    75| 2.26e-06  2.42e-09  2.58e-07  3.72e-01  1.00e-01  1.23e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.23e+00s = setup: 5.04e-02s + solve: 1.18e+00s
	 lin-sys: 6.49e-02s, cones: 1.09e+00s, accel: 5.41e-03s
------------------------------------------------------------------
objective = 0.372435
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.73e+01 -2.80e+01  1.00e-01  8.86e-02

(CVXPY) Jul 07 11:44:27 AM: Problem status: optimal
(CVXPY) Jul 07 11:44:27 AM: Optimal value: 6.566e-01
(CVXPY) Jul 07 11:44:27 AM: Compilation took 7.832e-02 seconds
(CVXPY) Jul 07 11:44:27 AM: Solver (including time spent in interface) took 1.019e+00 seconds
(CVXPY) Jul 07 11:44:27 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:44:27 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:44:27 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:44:27 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:44:27 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:44:27 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:44:27 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:44:27 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:44:27 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:44:27 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:44:27 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:44:27 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:44:27 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:44:27 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:44:27 AM: Applying reduction SCS
(CVXPY) Jul 07 11:44:27 AM: Finished problem compilation (took 8.410e-02 seconds).
(CVXPY) Jul 07 11:44:27 AM: Invoking solver SCS  to obtain a solution.

    75| 1.28e-06  3.92e-09  2.32e-07  6.57e-01  1.00e-01  1.01e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.01e+00s = setup: 4.69e-02s + solve: 9.63e-01s
	 lin-sys: 6.05e-02s, cones: 8.78e-01s, accel: 5.83e-03s
------------------------------------------------------------------
objective = 0.656590
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.84e+01  1.00e-01  6.00e-02

(CVXPY) Jul 07 11:44:28 AM: Problem status: optimal
(CVXPY) Jul 07 11:44:28 AM: Optimal value: 3.750e-01
(CVXPY) Jul 07 11:44:28 AM: Compilation took 8.410e-02 seconds
(CVXPY) Jul 07 11:44:28 AM: Solver (including time spent in interface) took 7.824e-01 seconds
(CVXPY) Jul 07 11:44:28 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:44:28 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:44:28 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:44:28 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:44:28 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:44:28 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:44:28 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:44:28 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:44:28 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:44:28 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:44:28 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:44:28 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:44:28 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:44:28 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:44:28 AM: Applying reduction SCS
(CVXPY) Jul 07 11:44:28 AM: Finished problem compilation (took 7.954e-02 seconds).
(CVXPY) Jul 07 11:44:28 AM: Invoking solver SCS  to obtain a solution.

    50| 2.34e-05  5.94e-08  2.79e-06  3.75e-01  1.00e-01  7.75e-01
------------------------------------------------------------------
status:  solved
timings: total: 7.76e-01s = setup: 3.26e-02s + solve: 7.43e-01s
	 lin-sys: 4.24e-02s, cones: 6.83e-01s, accel: 3.10e-03s
------------------------------------------------------------------
objective = 0.375017
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.84e+01  1.00e-01  8.62e-02

(CVXPY) Jul 07 11:44:29 AM: Problem status: optimal
(CVXPY) Jul 07 11:44:29 AM: Optimal value: 3.851e-01
(CVXPY) Jul 07 11:44:29 AM: Compilation took 7.954e-02 seconds
(CVXPY) Jul 07 11:44:29 AM: Solver (including time spent in interface) took 9.501e-01 seconds
(CVXPY) Jul 07 11:44:29 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:44:29 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:44:29 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:44:29 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:44:29 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:44:29 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:44:29 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:44:29 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:44:29 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:44:29 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:44:29 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:44:29 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:44:29 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:44:29 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:44:29 AM: Applying reduction SCS
(CVXPY) Jul 07 11:44:29 AM: Finished problem compilation (took 7.304e-02 seconds).
(CVXPY) Jul 07 11:44:29 AM: Invoking solver SCS  to obtain a solution.

    75| 1.11e-06  2.86e-09  1.41e-07  3.85e-01  1.00e-01  9.42e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.42e-01s = setup: 3.95e-02s + solve: 9.03e-01s
	 lin-sys: 5.41e-02s, cones: 8.25e-01s, accel: 5.36e-03s
------------------------------------------------------------------
objective = 0.385074
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.73e+01 -2.81e+01  1.00e-01  6.27e-02

(CVXPY) Jul 07 11:44:30 AM: Problem status: optimal
(CVXPY) Jul 07 11:44:30 AM: Optimal value: 6.105e-01
(CVXPY) Jul 07 11:44:30 AM: Compilation took 7.304e-02 seconds
(CVXPY) Jul 07 11:44:30 AM: Solver (including time spent in interface) took 1.030e+00 seconds
(CVXPY) Jul 07 11:44:30 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:44:30 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:44:30 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:44:30 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:44:30 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:44:30 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:44:30 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:44:30 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:44:30 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:44:30 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:44:30 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:44:30 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:44:30 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:44:30 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:44:30 AM: Applying reduction SCS
(CVXPY) Jul 07 11:44:30 AM: Finished problem compilation (took 8.571e-02 seconds).
(CVXPY) Jul 07 11:44:30 AM: Invoking solver SCS  to obtain a solution.

    75| 2.89e-06  6.76e-09  4.11e-07  6.10e-01  1.00e-01  1.02e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.02e+00s = setup: 3.43e-02s + solve: 9.89e-01s
	 lin-sys: 6.46e-02s, cones: 9.02e-01s, accel: 5.18e-03s
------------------------------------------------------------------
objective = 0.610492
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.73e+01 -2.81e+01  1.00e-01  7.24e-02

(CVXPY) Jul 07 11:44:31 AM: Problem status: optimal
(CVXPY) Jul 07 11:44:31 AM: Optimal value: 5.845e-01
(CVXPY) Jul 07 11:44:31 AM: Compilation took 8.571e-02 seconds
(CVXPY) Jul 07 11:44:31 AM: Solver (including time spent in interface) took 1.052e+00 seconds
(CVXPY) Jul 07 11:44:31 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:44:31 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:44:31 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:44:31 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:44:31 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:44:31 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:44:31 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:44:31 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:44:31 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:44:31 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:44:31 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:44:31 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:44:31 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:44:31 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:44:31 AM: Applying reduction SCS
(CVXPY) Jul 07 11:44:31 AM: Finished problem compilation (took 9.054e-02 seconds).
(CVXPY) Jul 07 11:44:31 AM: Invoking solver SCS  to obtain a solution.

    75| 1.32e-06  4.43e-09  2.28e-07  5.85e-01  1.00e-01  1.04e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.04e+00s = setup: 3.76e-02s + solve: 1.00e+00s
	 lin-sys: 6.86e-02s, cones: 9.11e-01s, accel: 7.82e-03s
------------------------------------------------------------------
objective = 0.584522
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.85e+01  1.00e-01  8.52e-02

(CVXPY) Jul 07 11:44:32 AM: Problem status: optimal
(CVXPY) Jul 07 11:44:32 AM: Optimal value: 3.472e-01
(CVXPY) Jul 07 11:44:32 AM: Compilation took 9.054e-02 seconds
(CVXPY) Jul 07 11:44:32 AM: Solver (including time spent in interface) took 1.245e+00 seconds
(CVXPY) Jul 07 11:44:32 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:44:32 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:44:32 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:44:32 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:44:32 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:44:32 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:44:32 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:44:32 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:44:32 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:44:32 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:44:32 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:44:32 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:44:32 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:44:32 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:44:32 AM: Applying reduction SCS
(CVXPY) Jul 07 11:44:32 AM: Finished problem compilation (took 7.632e-02 seconds).
(CVXPY) Jul 07 11:44:32 AM: Invoking solver SCS  to obtain a solution.

    75| 1.96e-06  2.32e-09  1.86e-07  3.47e-01  1.00e-01  1.23e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.24e+00s = setup: 4.73e-02s + solve: 1.19e+00s
	 lin-sys: 5.74e-02s, cones: 1.11e+00s, accel: 5.51e-03s
------------------------------------------------------------------
objective = 0.347152
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.73e+01 -2.81e+01  1.00e-01  6.28e-02

(CVXPY) Jul 07 11:44:34 AM: Problem status: optimal
(CVXPY) Jul 07 11:44:34 AM: Optimal value: 6.193e-01
(CVXPY) Jul 07 11:44:34 AM: Compilation took 7.632e-02 seconds
(CVXPY) Jul 07 11:44:34 AM: Solver (including time spent in interface) took 1.116e+00 seconds
(CVXPY) Jul 07 11:44:34 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:44:34 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:44:34 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:44:34 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:44:34 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:44:34 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:44:34 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:44:34 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:44:34 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:44:34 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:44:34 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:44:34 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:44:34 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:44:34 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:44:34 AM: Applying reduction SCS
(CVXPY) Jul 07 11:44:34 AM: Finished problem compilation (took 7.123e-02 seconds).
(CVXPY) Jul 07 11:44:34 AM: Invoking solver SCS  to obtain a solution.

    75| 2.27e-06  5.68e-09  3.44e-07  6.19e-01  1.00e-01  1.11e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.11e+00s = setup: 3.32e-02s + solve: 1.08e+00s
	 lin-sys: 7.30e-02s, cones: 9.76e-01s, accel: 5.43e-03s
------------------------------------------------------------------
objective = 0.619263
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.73e+01 -2.81e+01  1.00e-01  6.99e-02

(CVXPY) Jul 07 11:44:35 AM: Problem status: optimal
(CVXPY) Jul 07 11:44:35 AM: Optimal value: 5.946e-01
(CVXPY) Jul 07 11:44:35 AM: Compilation took 7.123e-02 seconds
(CVXPY) Jul 07 11:44:35 AM: Solver (including time spent in interface) took 9.877e-01 seconds
(CVXPY) Jul 07 11:44:35 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:44:35 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:44:35 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:44:35 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:44:35 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:44:35 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:44:35 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:44:35 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:44:35 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:44:35 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:44:35 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:44:35 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:44:35 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:44:35 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:44:35 AM: Applying reduction SCS
(CVXPY) Jul 07 11:44:35 AM: Finished problem compilation (took 6.764e-02 seconds).
(CVXPY) Jul 07 11:44:35 AM: Invoking solver SCS  to obtain a solution.

    75| 1.32e-06  4.27e-09  2.49e-07  5.95e-01  1.00e-01  9.82e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.82e-01s = setup: 3.36e-02s + solve: 9.49e-01s
	 lin-sys: 6.47e-02s, cones: 8.61e-01s, accel: 5.12e-03s
------------------------------------------------------------------
objective = 0.594635
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.84e+01  1.00e-01  6.44e-02

(CVXPY) Jul 07 11:44:35 AM: Problem status: optimal
(CVXPY) Jul 07 11:44:35 AM: Optimal value: 4.156e-01
(CVXPY) Jul 07 11:44:35 AM: Compilation took 6.764e-02 seconds
(CVXPY) Jul 07 11:44:35 AM: Solver (including time spent in interface) took 7.083e-01 seconds
(CVXPY) Jul 07 11:44:35 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:44:35 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:44:35 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:44:35 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:44:35 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:44:35 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:44:35 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:44:35 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:44:35 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:44:35 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:44:36 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:44:36 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:44:36 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:44:36 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:44:36 AM: Applying reduction SCS
(CVXPY) Jul 07 11:44:36 AM: Finished problem compilation (took 8.640e-02 seconds).
(CVXPY) Jul 07 11:44:36 AM: Invoking solver SCS  to obtain a solution.

    50| 3.18e-05  9.14e-08  3.44e-06  4.16e-01  1.00e-01  7.02e-01
------------------------------------------------------------------
status:  solved
timings: total: 7.02e-01s = setup: 3.20e-02s + solve: 6.70e-01s
	 lin-sys: 3.95e-02s, cones: 6.15e-01s, accel: 3.79e-03s
------------------------------------------------------------------
objective = 0.415560
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.73e+01 -2.81e+01  1.00e-01  8.09e-02

(CVXPY) Jul 07 11:44:37 AM: Problem status: optimal
(CVXPY) Jul 07 11:44:37 AM: Optimal value: 6.316e-01
(CVXPY) Jul 07 11:44:37 AM: Compilation took 8.640e-02 seconds
(CVXPY) Jul 07 11:44:37 AM: Solver (including time spent in interface) took 1.040e+00 seconds
(CVXPY) Jul 07 11:44:37 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:44:37 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:44:37 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:44:37 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:44:37 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:44:37 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:44:37 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:44:37 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:44:37 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:44:37 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:44:37 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:44:37 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:44:37 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:44:37 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:44:37 AM: Applying reduction SCS
(CVXPY) Jul 07 11:44:37 AM: Finished problem compilation (took 8.523e-02 seconds).
(CVXPY) Jul 07 11:44:37 AM: Invoking solver SCS  to obtain a solution.

    75| 3.71e-06  5.53e-09  4.48e-07  6.32e-01  1.00e-01  1.03e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.03e+00s = setup: 4.13e-02s + solve: 9.92e-01s
	 lin-sys: 5.95e-02s, cones: 9.08e-01s, accel: 5.82e-03s
------------------------------------------------------------------
objective = 0.631612
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.73e+01 -2.81e+01  1.00e-01  8.70e-02

(CVXPY) Jul 07 11:44:38 AM: Problem status: optimal
(CVXPY) Jul 07 11:44:38 AM: Optimal value: 6.086e-01
(CVXPY) Jul 07 11:44:38 AM: Compilation took 8.523e-02 seconds
(CVXPY) Jul 07 11:44:38 AM: Solver (including time spent in interface) took 1.020e+00 seconds
(CVXPY) Jul 07 11:44:38 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:44:38 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:44:38 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:44:38 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:44:38 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:44:38 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:44:38 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:44:38 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:44:38 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:44:38 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:44:38 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:44:38 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:44:38 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:44:38 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:44:38 AM: Applying reduction SCS
(CVXPY) Jul 07 11:44:38 AM: Finished problem compilation (took 8.990e-02 seconds).
(CVXPY) Jul 07 11:44:38 AM: Invoking solver SCS  to obtain a solution.

    75| 2.70e-06  5.45e-09  4.36e-07  6.09e-01  1.00e-01  1.01e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.01e+00s = setup: 4.91e-02s + solve: 9.65e-01s
	 lin-sys: 6.03e-02s, cones: 8.80e-01s, accel: 7.38e-03s
------------------------------------------------------------------
objective = 0.608554
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.83e+01  1.00e-01  8.45e-02

(CVXPY) Jul 07 11:44:39 AM: Problem status: optimal
(CVXPY) Jul 07 11:44:39 AM: Optimal value: 4.517e-01
(CVXPY) Jul 07 11:44:39 AM: Compilation took 8.990e-02 seconds
(CVXPY) Jul 07 11:44:39 AM: Solver (including time spent in interface) took 6.986e-01 seconds
(CVXPY) Jul 07 11:44:39 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:44:39 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:44:39 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:44:39 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:44:39 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:44:39 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:44:39 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:44:39 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:44:39 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:44:39 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:44:39 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:44:39 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:44:39 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:44:39 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:44:39 AM: Applying reduction SCS
(CVXPY) Jul 07 11:44:39 AM: Finished problem compilation (took 7.561e-02 seconds).
(CVXPY) Jul 07 11:44:39 AM: Invoking solver SCS  to obtain a solution.

    50| 3.21e-05  1.02e-07  4.46e-06  4.52e-01  1.00e-01  6.93e-01
------------------------------------------------------------------
status:  solved
timings: total: 6.93e-01s = setup: 5.19e-02s + solve: 6.41e-01s
	 lin-sys: 4.18e-02s, cones: 5.71e-01s, accel: 1.14e-02s
------------------------------------------------------------------
objective = 0.451643
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  7.22e-02

(CVXPY) Jul 07 11:44:40 AM: Problem status: optimal
(CVXPY) Jul 07 11:44:40 AM: Optimal value: 4.715e-01
(CVXPY) Jul 07 11:44:40 AM: Compilation took 7.561e-02 seconds
(CVXPY) Jul 07 11:44:40 AM: Solver (including time spent in interface) took 1.185e+00 seconds
(CVXPY) Jul 07 11:44:40 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:44:40 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:44:40 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:44:40 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:44:40 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:44:40 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:44:40 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:44:40 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:44:40 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:44:40 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:44:40 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:44:40 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:44:40 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:44:40 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:44:40 AM: Applying reduction SCS
(CVXPY) Jul 07 11:44:40 AM: Finished problem compilation (took 7.168e-02 seconds).
(CVXPY) Jul 07 11:44:40 AM: Invoking solver SCS  to obtain a solution.

    75| 1.12e-05  7.57e-10  8.19e-07  4.72e-01  1.00e-01  1.18e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.18e+00s = setup: 3.76e-02s + solve: 1.14e+00s
	 lin-sys: 6.05e-02s, cones: 1.06e+00s, accel: 5.39e-03s
------------------------------------------------------------------
objective = 0.471508
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.14e+02  1.00e-01  6.80e-02

(CVXPY) Jul 07 11:44:41 AM: Problem status: optimal
(CVXPY) Jul 07 11:44:41 AM: Optimal value: 7.374e-01
(CVXPY) Jul 07 11:44:41 AM: Compilation took 7.168e-02 seconds
(CVXPY) Jul 07 11:44:41 AM: Solver (including time spent in interface) took 1.098e+00 seconds
(CVXPY) Jul 07 11:44:41 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:44:41 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:44:41 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:44:41 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:44:41 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:44:41 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:44:41 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:44:41 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:44:41 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:44:41 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:44:41 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:44:41 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:44:41 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:44:41 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:44:41 AM: Applying reduction SCS
(CVXPY) Jul 07 11:44:41 AM: Finished problem compilation (took 7.300e-02 seconds).
(CVXPY) Jul 07 11:44:41 AM: Invoking solver SCS  to obtain a solution.

    75| 7.71e-06  1.57e-09  4.24e-07  7.37e-01  1.00e-01  1.09e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.09e+00s = setup: 3.63e-02s + solve: 1.06e+00s
	 lin-sys: 8.17e-02s, cones: 9.50e-01s, accel: 5.67e-03s
------------------------------------------------------------------
objective = 0.737422
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.14e+02  1.00e-01  6.62e-02

(CVXPY) Jul 07 11:44:42 AM: Problem status: optimal
(CVXPY) Jul 07 11:44:42 AM: Optimal value: 8.056e-01
(CVXPY) Jul 07 11:44:42 AM: Compilation took 7.300e-02 seconds
(CVXPY) Jul 07 11:44:42 AM: Solver (including time spent in interface) took 1.114e+00 seconds
(CVXPY) Jul 07 11:44:42 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:44:42 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:44:42 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:44:42 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:44:42 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:44:42 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:44:42 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:44:42 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:44:42 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:44:42 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:44:42 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:44:42 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:44:42 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:44:42 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:44:42 AM: Applying reduction SCS
(CVXPY) Jul 07 11:44:42 AM: Finished problem compilation (took 7.377e-02 seconds).
(CVXPY) Jul 07 11:44:42 AM: Invoking solver SCS  to obtain a solution.

    75| 1.24e-05  7.13e-09  9.99e-07  8.06e-01  1.00e-01  1.11e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.11e+00s = setup: 3.32e-02s + solve: 1.07e+00s
	 lin-sys: 6.55e-02s, cones: 9.86e-01s, accel: 5.19e-03s
------------------------------------------------------------------
objective = 0.805641
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.14e+02  1.00e-01  6.46e-02

(CVXPY) Jul 07 11:44:44 AM: Problem status: optimal
(CVXPY) Jul 07 11:44:44 AM: Optimal value: 7.247e-01
(CVXPY) Jul 07 11:44:44 AM: Compilation took 7.377e-02 seconds
(CVXPY) Jul 07 11:44:44 AM: Solver (including time spent in interface) took 1.176e+00 seconds
(CVXPY) Jul 07 11:44:44 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:44:44 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:44:44 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:44:44 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:44:44 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:44:44 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:44:44 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:44:44 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:44:44 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:44:44 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:44:44 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:44:44 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:44:44 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:44:44 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:44:44 AM: Applying reduction SCS
(CVXPY) Jul 07 11:44:44 AM: Finished problem compilation (took 7.108e-02 seconds).
(CVXPY) Jul 07 11:44:44 AM: Invoking solver SCS  to obtain a solution.

    75| 1.15e-05  6.66e-09  8.48e-07  7.25e-01  1.00e-01  1.17e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.17e+00s = setup: 3.46e-02s + solve: 1.14e+00s
	 lin-sys: 6.35e-02s, cones: 1.04e+00s, accel: 6.37e-03s
------------------------------------------------------------------
objective = 0.724728
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  5.92e-02

(CVXPY) Jul 07 11:44:46 AM: Problem status: optimal
(CVXPY) Jul 07 11:44:46 AM: Optimal value: 4.483e-01
(CVXPY) Jul 07 11:44:46 AM: Compilation took 7.108e-02 seconds
(CVXPY) Jul 07 11:44:46 AM: Solver (including time spent in interface) took 2.163e+00 seconds
(CVXPY) Jul 07 11:44:46 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:44:46 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:44:46 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:44:46 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:44:46 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:44:46 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:44:46 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:44:46 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:44:46 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:44:46 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:44:46 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:44:46 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:44:46 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:44:46 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:44:46 AM: Applying reduction SCS
(CVXPY) Jul 07 11:44:46 AM: Finished problem compilation (took 7.597e-02 seconds).
(CVXPY) Jul 07 11:44:46 AM: Invoking solver SCS  to obtain a solution.

    75| 1.62e-05  7.48e-10  1.13e-06  4.48e-01  1.00e-01  2.16e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.16e+00s = setup: 3.04e-02s + solve: 2.13e+00s
	 lin-sys: 5.79e-02s, cones: 2.04e+00s, accel: 7.73e-03s
------------------------------------------------------------------
objective = 0.448305
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.14e+02  1.00e-01  1.05e-01

(CVXPY) Jul 07 11:44:47 AM: Problem status: optimal
(CVXPY) Jul 07 11:44:47 AM: Optimal value: 8.206e-01
(CVXPY) Jul 07 11:44:47 AM: Compilation took 7.597e-02 seconds
(CVXPY) Jul 07 11:44:47 AM: Solver (including time spent in interface) took 1.131e+00 seconds
(CVXPY) Jul 07 11:44:47 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:44:47 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:44:47 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:44:47 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:44:47 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:44:47 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:44:47 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:44:47 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:44:47 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:44:47 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:44:47 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:44:47 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:44:47 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:44:47 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:44:47 AM: Applying reduction SCS
(CVXPY) Jul 07 11:44:47 AM: Finished problem compilation (took 7.060e-02 seconds).
(CVXPY) Jul 07 11:44:47 AM: Invoking solver SCS  to obtain a solution.

    75| 6.40e-06  2.26e-09  3.14e-07  8.21e-01  1.00e-01  1.13e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.13e+00s = setup: 7.24e-02s + solve: 1.05e+00s
	 lin-sys: 6.37e-02s, cones: 9.65e-01s, accel: 5.10e-03s
------------------------------------------------------------------
objective = 0.820554
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.14e+02  1.00e-01  7.93e-02

(CVXPY) Jul 07 11:44:48 AM: Problem status: optimal
(CVXPY) Jul 07 11:44:48 AM: Optimal value: 7.208e-01
(CVXPY) Jul 07 11:44:48 AM: Compilation took 7.060e-02 seconds
(CVXPY) Jul 07 11:44:48 AM: Solver (including time spent in interface) took 1.206e+00 seconds
(CVXPY) Jul 07 11:44:48 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:44:48 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:44:48 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:44:48 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:44:48 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:44:48 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:44:48 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:44:48 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:44:48 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:44:48 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:44:48 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:44:48 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:44:48 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:44:48 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:44:48 AM: Applying reduction SCS
(CVXPY) Jul 07 11:44:48 AM: Finished problem compilation (took 7.128e-02 seconds).
(CVXPY) Jul 07 11:44:48 AM: Invoking solver SCS  to obtain a solution.

    75| 9.41e-06  4.65e-09  5.96e-07  7.21e-01  1.00e-01  1.20e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.20e+00s = setup: 4.22e-02s + solve: 1.16e+00s
	 lin-sys: 6.21e-02s, cones: 1.07e+00s, accel: 5.06e-03s
------------------------------------------------------------------
objective = 0.720821
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  8.59e-02

(CVXPY) Jul 07 11:44:50 AM: Problem status: optimal
(CVXPY) Jul 07 11:44:50 AM: Optimal value: 4.255e-01
(CVXPY) Jul 07 11:44:50 AM: Compilation took 7.128e-02 seconds
(CVXPY) Jul 07 11:44:50 AM: Solver (including time spent in interface) took 1.356e+00 seconds
(CVXPY) Jul 07 11:44:50 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:44:50 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:44:50 AM: DCP verification time: 0.0023 seconds.
(CVXPY) Jul 07 11:44:50 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:44:50 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:44:50 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:44:50 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:44:50 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:44:50 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:44:50 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:44:50 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:44:50 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:44:50 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:44:50 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:44:50 AM: Applying reduction SCS
(CVXPY) Jul 07 11:44:50 AM: Finished problem compilation (took 8.365e-02 seconds).
(CVXPY) Jul 07 11:44:50 AM: Invoking solver SCS  to obtain a solution.

    75| 1.05e-05  1.13e-09  5.03e-07  4.26e-01  1.00e-01  1.35e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.35e+00s = setup: 3.30e-02s + solve: 1.32e+00s
	 lin-sys: 6.50e-02s, cones: 1.23e+00s, accel: 5.07e-03s
------------------------------------------------------------------
objective = 0.425508
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.14e+02  1.00e-01  7.20e-02

(CVXPY) Jul 07 11:44:51 AM: Problem status: optimal
(CVXPY) Jul 07 11:44:51 AM: Optimal value: 8.358e-01
(CVXPY) Jul 07 11:44:51 AM: Compilation took 8.365e-02 seconds
(CVXPY) Jul 07 11:44:51 AM: Solver (including time spent in interface) took 1.109e+00 seconds
(CVXPY) Jul 07 11:44:51 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:44:51 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:44:51 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:44:51 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:44:51 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:44:51 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:44:51 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:44:51 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:44:51 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:44:51 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:44:51 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:44:51 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:44:51 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:44:51 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:44:51 AM: Applying reduction SCS
(CVXPY) Jul 07 11:44:51 AM: Finished problem compilation (took 7.581e-02 seconds).
(CVXPY) Jul 07 11:44:51 AM: Invoking solver SCS  to obtain a solution.

    75| 1.34e-05  6.86e-09  8.49e-07  8.36e-01  1.00e-01  1.10e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.10e+00s = setup: 3.89e-02s + solve: 1.06e+00s
	 lin-sys: 5.73e-02s, cones: 9.82e-01s, accel: 7.61e-03s
------------------------------------------------------------------
objective = 0.835779
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  6.65e-02

(CVXPY) Jul 07 11:44:52 AM: Problem status: optimal
(CVXPY) Jul 07 11:44:52 AM: Optimal value: 4.428e-01
(CVXPY) Jul 07 11:44:52 AM: Compilation took 7.581e-02 seconds
(CVXPY) Jul 07 11:44:52 AM: Solver (including time spent in interface) took 1.183e+00 seconds
(CVXPY) Jul 07 11:44:52 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:44:52 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:44:52 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:44:52 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:44:52 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:44:52 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:44:52 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:44:52 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:44:52 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:44:52 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:44:52 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:44:52 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:44:52 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:44:52 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:44:52 AM: Applying reduction SCS
(CVXPY) Jul 07 11:44:52 AM: Finished problem compilation (took 7.747e-02 seconds).
(CVXPY) Jul 07 11:44:52 AM: Invoking solver SCS  to obtain a solution.

    75| 1.36e-05  1.87e-09  7.60e-07  4.43e-01  1.00e-01  1.18e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.18e+00s = setup: 3.41e-02s + solve: 1.14e+00s
	 lin-sys: 6.17e-02s, cones: 1.06e+00s, accel: 5.13e-03s
------------------------------------------------------------------
objective = 0.442829
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  6.60e-02

(CVXPY) Jul 07 11:44:55 AM: Problem status: optimal
(CVXPY) Jul 07 11:44:55 AM: Optimal value: 4.356e-01
(CVXPY) Jul 07 11:44:55 AM: Compilation took 7.747e-02 seconds
(CVXPY) Jul 07 11:44:55 AM: Solver (including time spent in interface) took 2.317e+00 seconds
(CVXPY) Jul 07 11:44:55 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:44:55 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:44:55 AM: DCP verification time: 0.0009 seconds.
(CVXPY) Jul 07 11:44:55 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:44:55 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:44:55 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:44:55 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:44:55 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:44:55 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:44:55 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:44:55 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:44:55 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:44:55 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:44:55 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:44:55 AM: Applying reduction SCS
(CVXPY) Jul 07 11:44:55 AM: Finished problem compilation (took 1.313e-01 seconds).
(CVXPY) Jul 07 11:44:55 AM: Invoking solver SCS  to obtain a solution.

    75| 1.59e-05  7.51e-10  9.37e-07  4.36e-01  1.00e-01  2.31e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.31e+00s = setup: 3.02e-02s + solve: 2.28e+00s
	 lin-sys: 6.25e-02s, cones: 2.20e+00s, accel: 6.17e-03s
------------------------------------------------------------------
objective = 0.435570
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.14e+02  1.00e-01  1.05e-01

(CVXPY) Jul 07 11:44:56 AM: Problem status: optimal
(CVXPY) Jul 07 11:44:56 AM: Optimal value: 7.739e-01
(CVXPY) Jul 07 11:44:56 AM: Compilation took 1.313e-01 seconds
(CVXPY) Jul 07 11:44:56 AM: Solver (including time spent in interface) took 1.156e+00 seconds
(CVXPY) Jul 07 11:44:56 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:44:56 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:44:56 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:44:56 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:44:56 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:44:56 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:44:56 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:44:56 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:44:56 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:44:56 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:44:56 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:44:56 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:44:56 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:44:56 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:44:56 AM: Applying reduction SCS
(CVXPY) Jul 07 11:44:56 AM: Finished problem compilation (took 7.070e-02 seconds).
(CVXPY) Jul 07 11:44:56 AM: Invoking solver SCS  to obtain a solution.

    75| 1.20e-05  7.46e-09  5.96e-07  7.74e-01  1.00e-01  1.15e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.15e+00s = setup: 6.90e-02s + solve: 1.08e+00s
	 lin-sys: 6.01e-02s, cones: 9.94e-01s, accel: 5.35e-03s
------------------------------------------------------------------
objective = 0.773854
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.14e+02  1.00e-01  6.88e-02

(CVXPY) Jul 07 11:44:58 AM: Problem status: optimal
(CVXPY) Jul 07 11:44:58 AM: Optimal value: 7.204e-01
(CVXPY) Jul 07 11:44:58 AM: Compilation took 7.070e-02 seconds
(CVXPY) Jul 07 11:44:58 AM: Solver (including time spent in interface) took 1.324e+00 seconds
(CVXPY) Jul 07 11:44:58 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:44:58 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:44:58 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:44:58 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:44:58 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:44:58 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:44:58 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:44:58 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:44:58 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:44:58 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:44:58 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:44:58 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:44:58 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:44:58 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:44:58 AM: Applying reduction SCS
(CVXPY) Jul 07 11:44:58 AM: Finished problem compilation (took 7.509e-02 seconds).
(CVXPY) Jul 07 11:44:58 AM: Invoking solver SCS  to obtain a solution.

    75| 1.07e-05  6.84e-09  7.71e-07  7.20e-01  1.00e-01  1.32e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.32e+00s = setup: 3.52e-02s + solve: 1.28e+00s
	 lin-sys: 7.80e-02s, cones: 1.18e+00s, accel: 5.05e-03s
------------------------------------------------------------------
objective = 0.720413
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  8.04e-02

(CVXPY) Jul 07 11:44:59 AM: Problem status: optimal
(CVXPY) Jul 07 11:44:59 AM: Optimal value: 4.035e-01
(CVXPY) Jul 07 11:44:59 AM: Compilation took 7.509e-02 seconds
(CVXPY) Jul 07 11:44:59 AM: Solver (including time spent in interface) took 1.261e+00 seconds
(CVXPY) Jul 07 11:44:59 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:44:59 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:44:59 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:44:59 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:44:59 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:44:59 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:44:59 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:44:59 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:44:59 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:44:59 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:44:59 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:44:59 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:44:59 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:44:59 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:44:59 AM: Applying reduction SCS
(CVXPY) Jul 07 11:44:59 AM: Finished problem compilation (took 9.470e-02 seconds).
(CVXPY) Jul 07 11:44:59 AM: Invoking solver SCS  to obtain a solution.

    75| 5.86e-06  7.51e-10  5.15e-07  4.03e-01  1.00e-01  1.25e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.25e+00s = setup: 4.17e-02s + solve: 1.21e+00s
	 lin-sys: 6.43e-02s, cones: 1.12e+00s, accel: 5.64e-03s
------------------------------------------------------------------
objective = 0.403464
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.14e+02  1.00e-01  6.96e-02

(CVXPY) Jul 07 11:45:00 AM: Problem status: optimal
(CVXPY) Jul 07 11:45:00 AM: Optimal value: 7.783e-01
(CVXPY) Jul 07 11:45:00 AM: Compilation took 9.470e-02 seconds
(CVXPY) Jul 07 11:45:00 AM: Solver (including time spent in interface) took 1.213e+00 seconds
(CVXPY) Jul 07 11:45:00 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:45:00 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:45:00 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:45:00 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:45:00 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:45:00 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:45:00 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:45:00 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:45:00 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:45:00 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:45:00 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:45:00 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:45:00 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:45:00 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:45:00 AM: Applying reduction SCS
(CVXPY) Jul 07 11:45:00 AM: Finished problem compilation (took 7.219e-02 seconds).
(CVXPY) Jul 07 11:45:00 AM: Invoking solver SCS  to obtain a solution.

    75| 9.85e-06  4.24e-09  6.08e-07  7.78e-01  1.00e-01  1.21e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.21e+00s = setup: 3.62e-02s + solve: 1.17e+00s
	 lin-sys: 9.66e-02s, cones: 1.05e+00s, accel: 6.09e-03s
------------------------------------------------------------------
objective = 0.778255
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.14e+02  1.00e-01  6.67e-02

(CVXPY) Jul 07 11:45:01 AM: Problem status: optimal
(CVXPY) Jul 07 11:45:01 AM: Optimal value: 7.338e-01
(CVXPY) Jul 07 11:45:01 AM: Compilation took 7.219e-02 seconds
(CVXPY) Jul 07 11:45:01 AM: Solver (including time spent in interface) took 1.123e+00 seconds
(CVXPY) Jul 07 11:45:01 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:45:01 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:45:01 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:45:01 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:45:01 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:45:01 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:45:01 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:45:01 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:45:01 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:45:01 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:45:01 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:45:01 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:45:01 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:45:01 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:45:02 AM: Applying reduction SCS
(CVXPY) Jul 07 11:45:02 AM: Finished problem compilation (took 8.005e-02 seconds).
(CVXPY) Jul 07 11:45:02 AM: Invoking solver SCS  to obtain a solution.

    75| 1.20e-05  7.05e-09  7.62e-07  7.34e-01  1.00e-01  1.11e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.11e+00s = setup: 3.40e-02s + solve: 1.08e+00s
	 lin-sys: 6.98e-02s, cones: 9.85e-01s, accel: 6.79e-03s
------------------------------------------------------------------
objective = 0.733805
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  5.79e-02

(CVXPY) Jul 07 11:45:03 AM: Problem status: optimal
(CVXPY) Jul 07 11:45:03 AM: Optimal value: 4.980e-01
(CVXPY) Jul 07 11:45:03 AM: Compilation took 8.005e-02 seconds
(CVXPY) Jul 07 11:45:03 AM: Solver (including time spent in interface) took 1.233e+00 seconds
(CVXPY) Jul 07 11:45:03 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:45:03 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:45:03 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:45:03 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:45:03 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:45:03 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:45:03 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:45:03 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:45:03 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:45:03 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:45:03 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:45:03 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:45:03 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:45:03 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:45:03 AM: Applying reduction SCS
(CVXPY) Jul 07 11:45:03 AM: Finished problem compilation (took 6.420e-02 seconds).
(CVXPY) Jul 07 11:45:03 AM: Invoking solver SCS  to obtain a solution.

    75| 1.25e-05  2.83e-09  8.02e-07  4.98e-01  1.00e-01  1.23e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.23e+00s = setup: 3.07e-02s + solve: 1.20e+00s
	 lin-sys: 6.94e-02s, cones: 1.10e+00s, accel: 6.22e-03s
------------------------------------------------------------------
objective = 0.498011
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.14e+02  1.00e-01  7.07e-02

(CVXPY) Jul 07 11:45:04 AM: Problem status: optimal
(CVXPY) Jul 07 11:45:04 AM: Optimal value: 7.936e-01
(CVXPY) Jul 07 11:45:04 AM: Compilation took 6.420e-02 seconds
(CVXPY) Jul 07 11:45:04 AM: Solver (including time spent in interface) took 1.367e+00 seconds
(CVXPY) Jul 07 11:45:04 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:45:04 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:45:04 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:45:04 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:45:04 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:45:04 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:45:04 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:45:04 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:45:04 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:45:04 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:45:04 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:45:04 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:45:04 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:45:04 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:45:04 AM: Applying reduction SCS
(CVXPY) Jul 07 11:45:04 AM: Finished problem compilation (took 9.211e-02 seconds).
(CVXPY) Jul 07 11:45:04 AM: Invoking solver SCS  to obtain a solution.

    75| 9.73e-06  4.60e-09  5.43e-07  7.94e-01  1.00e-01  1.36e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.36e+00s = setup: 3.53e-02s + solve: 1.33e+00s
	 lin-sys: 7.21e-02s, cones: 1.15e+00s, accel: 8.61e-02s
------------------------------------------------------------------
objective = 0.793567
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.14e+02  1.00e-01  7.19e-02

(CVXPY) Jul 07 11:45:06 AM: Problem status: optimal
(CVXPY) Jul 07 11:45:06 AM: Optimal value: 7.555e-01
(CVXPY) Jul 07 11:45:06 AM: Compilation took 9.211e-02 seconds
(CVXPY) Jul 07 11:45:06 AM: Solver (including time spent in interface) took 1.202e+00 seconds
(CVXPY) Jul 07 11:45:06 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:45:06 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:45:06 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:45:06 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:45:06 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:45:06 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:45:06 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:45:06 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:45:06 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:45:06 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:45:06 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:45:06 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:45:06 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:45:06 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:45:06 AM: Applying reduction SCS
(CVXPY) Jul 07 11:45:06 AM: Finished problem compilation (took 7.204e-02 seconds).
(CVXPY) Jul 07 11:45:06 AM: Invoking solver SCS  to obtain a solution.

    75| 9.63e-06  4.71e-09  6.01e-07  7.55e-01  1.00e-01  1.20e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.20e+00s = setup: 3.59e-02s + solve: 1.16e+00s
	 lin-sys: 6.27e-02s, cones: 1.08e+00s, accel: 5.36e-03s
------------------------------------------------------------------
objective = 0.755483
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  7.25e-02

(CVXPY) Jul 07 11:45:07 AM: Problem status: optimal
(CVXPY) Jul 07 11:45:07 AM: Optimal value: 5.453e-01
(CVXPY) Jul 07 11:45:07 AM: Compilation took 7.204e-02 seconds
(CVXPY) Jul 07 11:45:07 AM: Solver (including time spent in interface) took 1.199e+00 seconds
(CVXPY) Jul 07 11:45:07 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:45:07 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:45:07 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:45:07 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:45:07 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:45:07 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:45:07 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:45:07 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:45:07 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:45:07 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:45:07 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:45:07 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:45:07 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:45:07 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:45:07 AM: Applying reduction SCS
(CVXPY) Jul 07 11:45:07 AM: Finished problem compilation (took 8.987e-02 seconds).
(CVXPY) Jul 07 11:45:07 AM: Invoking solver SCS  to obtain a solution.

    75| 1.52e-05  1.89e-09  1.18e-06  5.45e-01  1.00e-01  1.19e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.19e+00s = setup: 3.32e-02s + solve: 1.16e+00s
	 lin-sys: 6.98e-02s, cones: 1.06e+00s, accel: 7.88e-03s
------------------------------------------------------------------
objective = 0.545261
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.58e+02  1.00e-01  5.95e-02

(CVXPY) Jul 07 11:45:09 AM: Problem status: optimal
(CVXPY) Jul 07 11:45:09 AM: Optimal value: 4.743e-01
(CVXPY) Jul 07 11:45:09 AM: Compilation took 8.987e-02 seconds
(CVXPY) Jul 07 11:45:09 AM: Solver (including time spent in interface) took 2.324e+00 seconds
(CVXPY) Jul 07 11:45:09 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:45:09 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:45:09 AM: DCP verification time: 0.0010 seconds.
(CVXPY) Jul 07 11:45:09 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:45:09 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:45:09 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:45:09 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:45:09 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:45:09 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:45:09 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:45:09 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:45:09 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:45:09 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:45:09 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:45:09 AM: Applying reduction SCS
(CVXPY) Jul 07 11:45:09 AM: Finished problem compilation (took 9.183e-02 seconds).
(CVXPY) Jul 07 11:45:09 AM: Invoking solver SCS  to obtain a solution.

    75| 1.15e-05  7.57e-10  4.45e-07  4.74e-01  1.00e-01  2.32e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.32e+00s = setup: 3.58e-02s + solve: 2.28e+00s
	 lin-sys: 6.30e-02s, cones: 2.19e+00s, accel: 6.05e-03s
------------------------------------------------------------------
objective = 0.474304
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.58e+02  1.00e-01  7.14e-02

(CVXPY) Jul 07 11:45:12 AM: Problem status: optimal
(CVXPY) Jul 07 11:45:12 AM: Optimal value: 7.562e-01
(CVXPY) Jul 07 11:45:12 AM: Compilation took 9.183e-02 seconds
(CVXPY) Jul 07 11:45:12 AM: Solver (including time spent in interface) took 2.243e+00 seconds
(CVXPY) Jul 07 11:45:12 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:45:12 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:45:12 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:45:12 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:45:12 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:45:12 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:45:12 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:45:12 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:45:12 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:45:12 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:45:12 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:45:12 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:45:12 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:45:12 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:45:12 AM: Applying reduction SCS
(CVXPY) Jul 07 11:45:12 AM: Finished problem compilation (took 1.027e-01 seconds).
(CVXPY) Jul 07 11:45:12 AM: Invoking solver SCS  to obtain a solution.

    75| 6.57e-06  7.59e-10  2.57e-07  7.56e-01  1.00e-01  2.23e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.23e+00s = setup: 3.57e-02s + solve: 2.20e+00s
	 lin-sys: 6.46e-02s, cones: 2.11e+00s, accel: 5.90e-03s
------------------------------------------------------------------
objective = 0.756168
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.58e+02  1.00e-01  9.90e-02

(CVXPY) Jul 07 11:45:14 AM: Problem status: optimal
(CVXPY) Jul 07 11:45:14 AM: Optimal value: 8.361e-01
(CVXPY) Jul 07 11:45:14 AM: Compilation took 1.027e-01 seconds
(CVXPY) Jul 07 11:45:14 AM: Solver (including time spent in interface) took 2.330e+00 seconds
(CVXPY) Jul 07 11:45:14 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:45:14 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:45:14 AM: DCP verification time: 0.0009 seconds.
(CVXPY) Jul 07 11:45:14 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:45:14 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:45:14 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:45:14 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:45:14 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:45:14 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:45:14 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:45:14 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:45:14 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:45:14 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:45:14 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:45:14 AM: Applying reduction SCS
(CVXPY) Jul 07 11:45:14 AM: Finished problem compilation (took 8.976e-02 seconds).
(CVXPY) Jul 07 11:45:14 AM: Invoking solver SCS  to obtain a solution.

    75| 1.66e-05  7.66e-10  7.20e-07  8.36e-01  1.00e-01  2.32e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.32e+00s = setup: 5.75e-02s + solve: 2.26e+00s
	 lin-sys: 7.30e-02s, cones: 2.16e+00s, accel: 6.93e-03s
------------------------------------------------------------------
objective = 0.836098
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.58e+02  1.00e-01  6.64e-02

(CVXPY) Jul 07 11:45:17 AM: Problem status: optimal
(CVXPY) Jul 07 11:45:17 AM: Optimal value: 7.356e-01
(CVXPY) Jul 07 11:45:17 AM: Compilation took 8.976e-02 seconds
(CVXPY) Jul 07 11:45:17 AM: Solver (including time spent in interface) took 2.402e+00 seconds
(CVXPY) Jul 07 11:45:17 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:45:17 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:45:17 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:45:17 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:45:17 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:45:17 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:45:17 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:45:17 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:45:17 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:45:17 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:45:17 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:45:17 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:45:17 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:45:17 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:45:17 AM: Applying reduction SCS
(CVXPY) Jul 07 11:45:17 AM: Finished problem compilation (took 9.130e-02 seconds).
(CVXPY) Jul 07 11:45:17 AM: Invoking solver SCS  to obtain a solution.

    75| 1.67e-05  7.60e-10  6.43e-07  7.36e-01  1.00e-01  2.39e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.39e+00s = setup: 3.33e-02s + solve: 2.36e+00s
	 lin-sys: 6.13e-02s, cones: 2.28e+00s, accel: 6.07e-03s
------------------------------------------------------------------
objective = 0.735633
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.58e+02  1.00e-01  5.11e-02

(CVXPY) Jul 07 11:45:19 AM: Problem status: optimal
(CVXPY) Jul 07 11:45:19 AM: Optimal value: 4.483e-01
(CVXPY) Jul 07 11:45:19 AM: Compilation took 9.130e-02 seconds
(CVXPY) Jul 07 11:45:19 AM: Solver (including time spent in interface) took 2.195e+00 seconds
(CVXPY) Jul 07 11:45:19 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:45:19 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:45:19 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:45:19 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:45:19 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:45:19 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:45:19 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:45:19 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:45:19 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:45:19 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:45:19 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:45:19 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:45:19 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:45:19 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:45:19 AM: Applying reduction SCS
(CVXPY) Jul 07 11:45:19 AM: Finished problem compilation (took 6.860e-02 seconds).
(CVXPY) Jul 07 11:45:19 AM: Invoking solver SCS  to obtain a solution.

    75| 1.66e-05  7.48e-10  5.94e-07  4.48e-01  1.00e-01  2.19e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.19e+00s = setup: 2.70e-02s + solve: 2.16e+00s
	 lin-sys: 5.93e-02s, cones: 2.08e+00s, accel: 6.22e-03s
------------------------------------------------------------------
objective = 0.448305
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.58e+02  1.00e-01  6.76e-02

(CVXPY) Jul 07 11:45:21 AM: Problem status: optimal
(CVXPY) Jul 07 11:45:21 AM: Optimal value: 8.566e-01
(CVXPY) Jul 07 11:45:21 AM: Compilation took 6.860e-02 seconds
(CVXPY) Jul 07 11:45:21 AM: Solver (including time spent in interface) took 2.232e+00 seconds
(CVXPY) Jul 07 11:45:21 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:45:21 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:45:21 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:45:21 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:45:21 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:45:21 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:45:21 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:45:21 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:45:21 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:45:21 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:45:21 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:45:21 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:45:21 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:45:21 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:45:21 AM: Applying reduction SCS
(CVXPY) Jul 07 11:45:21 AM: Finished problem compilation (took 1.096e-01 seconds).
(CVXPY) Jul 07 11:45:21 AM: Invoking solver SCS  to obtain a solution.

    75| 6.29e-06  7.62e-10  2.30e-07  8.57e-01  1.00e-01  2.23e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.23e+00s = setup: 3.43e-02s + solve: 2.19e+00s
	 lin-sys: 6.46e-02s, cones: 2.10e+00s, accel: 5.92e-03s
------------------------------------------------------------------
objective = 0.856633
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.58e+02  1.00e-01  6.67e-02

(CVXPY) Jul 07 11:45:24 AM: Problem status: optimal
(CVXPY) Jul 07 11:45:24 AM: Optimal value: 7.330e-01
(CVXPY) Jul 07 11:45:24 AM: Compilation took 1.096e-01 seconds
(CVXPY) Jul 07 11:45:24 AM: Solver (including time spent in interface) took 2.239e+00 seconds
(CVXPY) Jul 07 11:45:24 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:45:24 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:45:24 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:45:24 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:45:24 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:45:24 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:45:24 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:45:24 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:45:24 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:45:24 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:45:24 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:45:24 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:45:24 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:45:24 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:45:24 AM: Applying reduction SCS
(CVXPY) Jul 07 11:45:24 AM: Finished problem compilation (took 9.323e-02 seconds).
(CVXPY) Jul 07 11:45:24 AM: Invoking solver SCS  to obtain a solution.

    75| 1.16e-05  7.55e-10  4.33e-07  7.33e-01  1.00e-01  2.23e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.23e+00s = setup: 3.53e-02s + solve: 2.20e+00s
	 lin-sys: 6.35e-02s, cones: 2.11e+00s, accel: 6.16e-03s
------------------------------------------------------------------
objective = 0.733022
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.58e+02  1.00e-01  8.44e-02

(CVXPY) Jul 07 11:45:26 AM: Problem status: optimal
(CVXPY) Jul 07 11:45:26 AM: Optimal value: 4.255e-01
(CVXPY) Jul 07 11:45:26 AM: Compilation took 9.323e-02 seconds
(CVXPY) Jul 07 11:45:26 AM: Solver (including time spent in interface) took 2.389e+00 seconds
(CVXPY) Jul 07 11:45:26 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:45:26 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:45:26 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:45:26 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:45:26 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:45:26 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:45:26 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:45:26 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:45:26 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:45:26 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:45:26 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:45:26 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:45:26 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:45:26 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:45:26 AM: Applying reduction SCS
(CVXPY) Jul 07 11:45:26 AM: Finished problem compilation (took 8.543e-02 seconds).
(CVXPY) Jul 07 11:45:26 AM: Invoking solver SCS  to obtain a solution.

    75| 1.13e-05  7.53e-10  3.33e-07  4.26e-01  1.00e-01  2.38e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.38e+00s = setup: 4.94e-02s + solve: 2.33e+00s
	 lin-sys: 6.10e-02s, cones: 2.24e+00s, accel: 9.87e-03s
------------------------------------------------------------------
objective = 0.425535
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.58e+02  1.00e-01  7.94e-02

(CVXPY) Jul 07 11:45:29 AM: Problem status: optimal
(CVXPY) Jul 07 11:45:29 AM: Optimal value: 8.714e-01
(CVXPY) Jul 07 11:45:29 AM: Compilation took 8.543e-02 seconds
(CVXPY) Jul 07 11:45:29 AM: Solver (including time spent in interface) took 2.258e+00 seconds
(CVXPY) Jul 07 11:45:29 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:45:29 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:45:29 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:45:29 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:45:29 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:45:29 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:45:29 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:45:29 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:45:29 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:45:29 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:45:29 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:45:29 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:45:29 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:45:29 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:45:29 AM: Applying reduction SCS
(CVXPY) Jul 07 11:45:29 AM: Finished problem compilation (took 6.790e-02 seconds).
(CVXPY) Jul 07 11:45:29 AM: Invoking solver SCS  to obtain a solution.

    75| 1.64e-05  7.52e-10  5.80e-07  8.71e-01  1.00e-01  2.25e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.25e+00s = setup: 4.89e-02s + solve: 2.20e+00s
	 lin-sys: 7.00e-02s, cones: 2.11e+00s, accel: 5.57e-03s
------------------------------------------------------------------
objective = 0.871369
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.58e+02  1.00e-01  5.25e-02

(CVXPY) Jul 07 11:45:31 AM: Problem status: optimal
(CVXPY) Jul 07 11:45:31 AM: Optimal value: 4.439e-01
(CVXPY) Jul 07 11:45:31 AM: Compilation took 6.790e-02 seconds
(CVXPY) Jul 07 11:45:31 AM: Solver (including time spent in interface) took 2.386e+00 seconds
(CVXPY) Jul 07 11:45:31 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:45:31 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:45:31 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:45:31 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:45:31 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:45:31 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:45:31 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:45:31 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:45:31 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:45:31 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:45:31 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:45:31 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:45:31 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:45:31 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:45:31 AM: Applying reduction SCS
(CVXPY) Jul 07 11:45:31 AM: Finished problem compilation (took 9.745e-02 seconds).
(CVXPY) Jul 07 11:45:31 AM: Invoking solver SCS  to obtain a solution.

    75| 1.63e-05  7.54e-10  4.96e-07  4.44e-01  1.00e-01  2.38e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.38e+00s = setup: 3.45e-02s + solve: 2.34e+00s
	 lin-sys: 6.35e-02s, cones: 2.26e+00s, accel: 5.56e-03s
------------------------------------------------------------------
objective = 0.443863
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.58e+02  1.00e-01  7.26e-02

(CVXPY) Jul 07 11:45:34 AM: Problem status: optimal
(CVXPY) Jul 07 11:45:34 AM: Optimal value: 4.356e-01
(CVXPY) Jul 07 11:45:34 AM: Compilation took 9.745e-02 seconds
(CVXPY) Jul 07 11:45:34 AM: Solver (including time spent in interface) took 2.346e+00 seconds
(CVXPY) Jul 07 11:45:34 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:45:34 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:45:34 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:45:34 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:45:34 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:45:34 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:45:34 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:45:34 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:45:34 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:45:34 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:45:34 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:45:34 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:45:34 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:45:34 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:45:34 AM: Applying reduction SCS
(CVXPY) Jul 07 11:45:34 AM: Finished problem compilation (took 9.600e-02 seconds).
(CVXPY) Jul 07 11:45:34 AM: Invoking solver SCS  to obtain a solution.

    75| 1.63e-05  7.52e-10  4.92e-07  4.36e-01  1.00e-01  2.34e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.34e+00s = setup: 3.98e-02s + solve: 2.30e+00s
	 lin-sys: 6.41e-02s, cones: 2.21e+00s, accel: 4.97e-03s
------------------------------------------------------------------
objective = 0.435570
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.58e+02  1.00e-01  6.91e-02

(CVXPY) Jul 07 11:45:36 AM: Problem status: optimal
(CVXPY) Jul 07 11:45:36 AM: Optimal value: 8.074e-01
(CVXPY) Jul 07 11:45:36 AM: Compilation took 9.600e-02 seconds
(CVXPY) Jul 07 11:45:36 AM: Solver (including time spent in interface) took 2.191e+00 seconds
(CVXPY) Jul 07 11:45:36 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:45:36 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:45:36 AM: DCP verification time: 0.0014 seconds.
(CVXPY) Jul 07 11:45:36 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:45:36 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:45:36 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:45:36 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:45:36 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:45:36 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:45:36 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:45:36 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:45:36 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:45:36 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:45:36 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:45:36 AM: Applying reduction SCS
(CVXPY) Jul 07 11:45:36 AM: Finished problem compilation (took 7.108e-02 seconds).
(CVXPY) Jul 07 11:45:36 AM: Invoking solver SCS  to obtain a solution.

    75| 1.66e-05  7.65e-10  5.40e-07  8.07e-01  1.00e-01  2.18e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.18e+00s = setup: 3.39e-02s + solve: 2.15e+00s
	 lin-sys: 6.24e-02s, cones: 2.06e+00s, accel: 8.63e-03s
------------------------------------------------------------------
objective = 0.807348
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.58e+02  1.00e-01  6.85e-02

(CVXPY) Jul 07 11:45:38 AM: Problem status: optimal
(CVXPY) Jul 07 11:45:38 AM: Optimal value: 7.365e-01
(CVXPY) Jul 07 11:45:38 AM: Compilation took 7.108e-02 seconds
(CVXPY) Jul 07 11:45:38 AM: Solver (including time spent in interface) took 2.356e+00 seconds
(CVXPY) Jul 07 11:45:38 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:45:38 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:45:38 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:45:38 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:45:38 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:45:38 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:45:38 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:45:38 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:45:38 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:45:38 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:45:38 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:45:38 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:45:38 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:45:38 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:45:38 AM: Applying reduction SCS
(CVXPY) Jul 07 11:45:38 AM: Finished problem compilation (took 7.477e-02 seconds).
(CVXPY) Jul 07 11:45:38 AM: Invoking solver SCS  to obtain a solution.

    75| 1.66e-05  7.64e-10  6.66e-07  7.37e-01  1.00e-01  2.35e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.35e+00s = setup: 3.69e-02s + solve: 2.31e+00s
	 lin-sys: 7.05e-02s, cones: 2.21e+00s, accel: 8.10e-03s
------------------------------------------------------------------
objective = 0.736528
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.58e+02  1.00e-01  6.71e-02

(CVXPY) Jul 07 11:45:41 AM: Problem status: optimal
(CVXPY) Jul 07 11:45:41 AM: Optimal value: 4.039e-01
(CVXPY) Jul 07 11:45:41 AM: Compilation took 7.477e-02 seconds
(CVXPY) Jul 07 11:45:41 AM: Solver (including time spent in interface) took 2.433e+00 seconds
(CVXPY) Jul 07 11:45:41 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:45:41 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:45:41 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:45:41 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:45:41 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:45:41 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:45:41 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:45:41 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:45:41 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:45:41 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:45:41 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:45:41 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:45:41 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:45:41 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:45:41 AM: Applying reduction SCS
(CVXPY) Jul 07 11:45:41 AM: Finished problem compilation (took 9.237e-02 seconds).
(CVXPY) Jul 07 11:45:41 AM: Invoking solver SCS  to obtain a solution.

    75| 6.12e-06  7.51e-10  2.86e-07  4.04e-01  1.00e-01  2.42e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.42e+00s = setup: 3.47e-02s + solve: 2.39e+00s
	 lin-sys: 6.13e-02s, cones: 2.30e+00s, accel: 6.51e-03s
------------------------------------------------------------------
objective = 0.403846
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.58e+02  1.00e-01  6.68e-02

(CVXPY) Jul 07 11:45:43 AM: Problem status: optimal
(CVXPY) Jul 07 11:45:43 AM: Optimal value: 8.039e-01
(CVXPY) Jul 07 11:45:43 AM: Compilation took 9.237e-02 seconds
(CVXPY) Jul 07 11:45:43 AM: Solver (including time spent in interface) took 2.249e+00 seconds
(CVXPY) Jul 07 11:45:43 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:45:43 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:45:43 AM: DCP verification time: 0.0011 seconds.
(CVXPY) Jul 07 11:45:43 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:45:43 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:45:43 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:45:43 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:45:43 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:45:43 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:45:43 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:45:43 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:45:43 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:45:43 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:45:43 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:45:43 AM: Applying reduction SCS
(CVXPY) Jul 07 11:45:43 AM: Finished problem compilation (took 8.904e-02 seconds).
(CVXPY) Jul 07 11:45:43 AM: Invoking solver SCS  to obtain a solution.

    75| 1.11e-05  7.61e-10  4.11e-07  8.04e-01  1.00e-01  2.24e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.24e+00s = setup: 3.54e-02s + solve: 2.21e+00s
	 lin-sys: 5.94e-02s, cones: 2.13e+00s, accel: 4.76e-03s
------------------------------------------------------------------
objective = 0.803927
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.58e+02  1.00e-01  6.47e-02

(CVXPY) Jul 07 11:45:46 AM: Problem status: optimal
(CVXPY) Jul 07 11:45:46 AM: Optimal value: 7.489e-01
(CVXPY) Jul 07 11:45:46 AM: Compilation took 8.904e-02 seconds
(CVXPY) Jul 07 11:45:46 AM: Solver (including time spent in interface) took 2.417e+00 seconds
(CVXPY) Jul 07 11:45:46 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:45:46 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:45:46 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:45:46 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:45:46 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:45:46 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:45:46 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:45:46 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:45:46 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:45:46 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:45:46 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:45:46 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:45:46 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:45:46 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:45:46 AM: Applying reduction SCS
(CVXPY) Jul 07 11:45:46 AM: Finished problem compilation (took 9.193e-02 seconds).
(CVXPY) Jul 07 11:45:46 AM: Invoking solver SCS  to obtain a solution.

    75| 1.62e-05  7.54e-10  5.78e-07  7.49e-01  1.00e-01  2.41e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.41e+00s = setup: 3.83e-02s + solve: 2.37e+00s
	 lin-sys: 7.21e-02s, cones: 2.28e+00s, accel: 5.55e-03s
------------------------------------------------------------------
objective = 0.748909
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.58e+02  1.00e-01  6.95e-02

(CVXPY) Jul 07 11:45:48 AM: Problem status: optimal
(CVXPY) Jul 07 11:45:48 AM: Optimal value: 5.013e-01
(CVXPY) Jul 07 11:45:48 AM: Compilation took 9.193e-02 seconds
(CVXPY) Jul 07 11:45:48 AM: Solver (including time spent in interface) took 2.351e+00 seconds
(CVXPY) Jul 07 11:45:48 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:45:48 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:45:48 AM: DCP verification time: 0.0009 seconds.
(CVXPY) Jul 07 11:45:48 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:45:48 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:45:48 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:45:48 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:45:48 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:45:48 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:45:48 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:45:48 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:45:48 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:45:48 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:45:48 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:45:48 AM: Applying reduction SCS
(CVXPY) Jul 07 11:45:48 AM: Finished problem compilation (took 7.444e-02 seconds).
(CVXPY) Jul 07 11:45:48 AM: Invoking solver SCS  to obtain a solution.

    75| 1.62e-05  7.54e-10  5.68e-07  5.01e-01  1.00e-01  2.35e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.35e+00s = setup: 3.66e-02s + solve: 2.31e+00s
	 lin-sys: 6.51e-02s, cones: 2.22e+00s, accel: 6.64e-03s
------------------------------------------------------------------
objective = 0.501311
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.58e+02  1.00e-01  6.88e-02

(CVXPY) Jul 07 11:45:51 AM: Problem status: optimal
(CVXPY) Jul 07 11:45:51 AM: Optimal value: 8.201e-01
(CVXPY) Jul 07 11:45:51 AM: Compilation took 7.444e-02 seconds
(CVXPY) Jul 07 11:45:51 AM: Solver (including time spent in interface) took 2.330e+00 seconds
(CVXPY) Jul 07 11:45:51 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:45:51 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:45:51 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:45:51 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:45:51 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:45:51 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:45:51 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:45:51 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:45:51 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:45:51 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:45:51 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:45:51 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:45:51 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:45:51 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:45:51 AM: Applying reduction SCS
(CVXPY) Jul 07 11:45:51 AM: Finished problem compilation (took 9.764e-02 seconds).
(CVXPY) Jul 07 11:45:51 AM: Invoking solver SCS  to obtain a solution.

    75| 1.13e-05  7.58e-10  3.91e-07  8.20e-01  1.00e-01  2.32e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.32e+00s = setup: 3.38e-02s + solve: 2.29e+00s
	 lin-sys: 8.29e-02s, cones: 2.18e+00s, accel: 7.46e-03s
------------------------------------------------------------------
objective = 0.820046
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.58e+02  1.00e-01  6.84e-02

(CVXPY) Jul 07 11:45:53 AM: Problem status: optimal
(CVXPY) Jul 07 11:45:53 AM: Optimal value: 7.762e-01
(CVXPY) Jul 07 11:45:53 AM: Compilation took 9.764e-02 seconds
(CVXPY) Jul 07 11:45:53 AM: Solver (including time spent in interface) took 2.285e+00 seconds
(CVXPY) Jul 07 11:45:53 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:45:53 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:45:53 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:45:53 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:45:53 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:45:53 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:45:53 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:45:53 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:45:53 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:45:53 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:45:53 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:45:53 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:45:53 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:45:53 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:45:53 AM: Applying reduction SCS
(CVXPY) Jul 07 11:45:53 AM: Finished problem compilation (took 7.139e-02 seconds).
(CVXPY) Jul 07 11:45:53 AM: Invoking solver SCS  to obtain a solution.

    75| 1.14e-05  7.61e-10  4.30e-07  7.76e-01  1.00e-01  2.28e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.28e+00s = setup: 3.43e-02s + solve: 2.24e+00s
	 lin-sys: 6.47e-02s, cones: 2.16e+00s, accel: 5.92e-03s
------------------------------------------------------------------
objective = 0.776229
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.58e+02  1.00e-01  7.65e-02

(CVXPY) Jul 07 11:45:55 AM: Problem status: optimal
(CVXPY) Jul 07 11:45:55 AM: Optimal value: 5.500e-01
(CVXPY) Jul 07 11:45:55 AM: Compilation took 7.139e-02 seconds
(CVXPY) Jul 07 11:45:55 AM: Solver (including time spent in interface) took 2.278e+00 seconds
(CVXPY) Jul 07 11:45:55 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:45:55 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:45:55 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:45:55 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:45:55 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:45:55 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:45:55 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:45:55 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:45:55 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:45:55 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:45:55 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:45:55 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:45:56 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:45:56 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:45:56 AM: Applying reduction SCS
(CVXPY) Jul 07 11:45:56 AM: Finished problem compilation (took 6.067e-02 seconds).
(CVXPY) Jul 07 11:45:56 AM: Invoking solver SCS  to obtain a solution.

    75| 1.68e-05  7.59e-10  6.58e-07  5.50e-01  1.00e-01  2.27e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.27e+00s = setup: 4.33e-02s + solve: 2.23e+00s
	 lin-sys: 5.87e-02s, cones: 2.15e+00s, accel: 6.23e-03s
------------------------------------------------------------------
objective = 0.550036
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.59e+02  1.00e-01  4.71e-02

(CVXPY) Jul 07 11:45:58 AM: Problem status: optimal
(CVXPY) Jul 07 11:45:58 AM: Optimal value: 4.743e-01
(CVXPY) Jul 07 11:45:58 AM: Compilation took 6.067e-02 seconds
(CVXPY) Jul 07 11:45:58 AM: Solver (including time spent in interface) took 1.996e+00 seconds
(CVXPY) Jul 07 11:45:58 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:45:58 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:45:58 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:45:58 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:45:58 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:45:58 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:45:58 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:45:58 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:45:58 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:45:58 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:45:58 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:45:58 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:45:58 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:45:58 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:45:58 AM: Applying reduction SCS
(CVXPY) Jul 07 11:45:58 AM: Finished problem compilation (took 5.811e-02 seconds).
(CVXPY) Jul 07 11:45:58 AM: Invoking solver SCS  to obtain a solution.

    75| 1.16e-05  7.57e-10  2.62e-07  4.74e-01  1.00e-01  1.99e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.99e+00s = setup: 2.94e-02s + solve: 1.96e+00s
	 lin-sys: 5.47e-02s, cones: 1.89e+00s, accel: 5.58e-03s
------------------------------------------------------------------
objective = 0.474304
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.59e+02  1.00e-01  5.05e-02

(CVXPY) Jul 07 11:46:00 AM: Problem status: optimal
(CVXPY) Jul 07 11:46:00 AM: Optimal value: 7.562e-01
(CVXPY) Jul 07 11:46:00 AM: Compilation took 5.811e-02 seconds
(CVXPY) Jul 07 11:46:00 AM: Solver (including time spent in interface) took 1.936e+00 seconds
(CVXPY) Jul 07 11:46:00 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:46:00 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:46:00 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:46:00 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:46:00 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:46:00 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:46:00 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:46:00 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:46:00 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:46:00 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:46:00 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:46:00 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:46:00 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:46:00 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:46:00 AM: Applying reduction SCS
(CVXPY) Jul 07 11:46:00 AM: Finished problem compilation (took 5.555e-02 seconds).
(CVXPY) Jul 07 11:46:00 AM: Invoking solver SCS  to obtain a solution.

    75| 6.63e-06  7.59e-10  1.50e-07  7.56e-01  1.00e-01  1.93e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.93e+00s = setup: 2.34e-02s + solve: 1.91e+00s
	 lin-sys: 5.43e-02s, cones: 1.83e+00s, accel: 4.95e-03s
------------------------------------------------------------------
objective = 0.756168
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.59e+02  1.00e-01  6.33e-02

(CVXPY) Jul 07 11:46:02 AM: Problem status: optimal
(CVXPY) Jul 07 11:46:02 AM: Optimal value: 8.361e-01
(CVXPY) Jul 07 11:46:02 AM: Compilation took 5.555e-02 seconds
(CVXPY) Jul 07 11:46:02 AM: Solver (including time spent in interface) took 2.424e+00 seconds
(CVXPY) Jul 07 11:46:02 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:46:02 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:46:02 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:46:02 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:46:02 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:46:02 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:46:02 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:46:02 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:46:02 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:46:02 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:46:02 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:46:02 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:46:02 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:46:02 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:46:02 AM: Applying reduction SCS
(CVXPY) Jul 07 11:46:02 AM: Finished problem compilation (took 9.456e-02 seconds).
(CVXPY) Jul 07 11:46:02 AM: Invoking solver SCS  to obtain a solution.

    75| 1.68e-05  7.66e-10  4.30e-07  8.36e-01  1.00e-01  2.42e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.42e+00s = setup: 3.81e-02s + solve: 2.38e+00s
	 lin-sys: 6.37e-02s, cones: 2.29e+00s, accel: 6.00e-03s
------------------------------------------------------------------
objective = 0.836098
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.59e+02  1.00e-01  7.02e-02

(CVXPY) Jul 07 11:46:05 AM: Problem status: optimal
(CVXPY) Jul 07 11:46:05 AM: Optimal value: 7.356e-01
(CVXPY) Jul 07 11:46:05 AM: Compilation took 9.456e-02 seconds
(CVXPY) Jul 07 11:46:05 AM: Solver (including time spent in interface) took 2.514e+00 seconds
(CVXPY) Jul 07 11:46:05 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:46:05 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:46:05 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:46:05 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:46:05 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:46:05 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:46:05 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:46:05 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:46:05 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:46:05 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:46:05 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:46:05 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:46:05 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:46:05 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:46:05 AM: Applying reduction SCS
(CVXPY) Jul 07 11:46:05 AM: Finished problem compilation (took 7.506e-02 seconds).
(CVXPY) Jul 07 11:46:05 AM: Invoking solver SCS  to obtain a solution.

    75| 1.69e-05  7.60e-10  3.82e-07  7.36e-01  1.00e-01  2.51e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.51e+00s = setup: 3.74e-02s + solve: 2.47e+00s
	 lin-sys: 7.31e-02s, cones: 2.37e+00s, accel: 6.54e-03s
------------------------------------------------------------------
objective = 0.735633
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.59e+02  1.00e-01  6.75e-02

(CVXPY) Jul 07 11:46:07 AM: Problem status: optimal
(CVXPY) Jul 07 11:46:07 AM: Optimal value: 4.483e-01
(CVXPY) Jul 07 11:46:07 AM: Compilation took 7.506e-02 seconds
(CVXPY) Jul 07 11:46:07 AM: Solver (including time spent in interface) took 2.395e+00 seconds
(CVXPY) Jul 07 11:46:07 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:46:07 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:46:07 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:46:07 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:46:07 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:46:07 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:46:07 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:46:07 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:46:07 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:46:07 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:46:07 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:46:07 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:46:07 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:46:07 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:46:07 AM: Applying reduction SCS
(CVXPY) Jul 07 11:46:07 AM: Finished problem compilation (took 8.903e-02 seconds).
(CVXPY) Jul 07 11:46:07 AM: Invoking solver SCS  to obtain a solution.

    75| 1.68e-05  7.48e-10  3.51e-07  4.48e-01  1.00e-01  2.39e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.39e+00s = setup: 3.77e-02s + solve: 2.35e+00s
	 lin-sys: 7.04e-02s, cones: 2.25e+00s, accel: 8.90e-03s
------------------------------------------------------------------
objective = 0.448305
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.59e+02  1.00e-01  6.89e-02

(CVXPY) Jul 07 11:46:10 AM: Problem status: optimal
(CVXPY) Jul 07 11:46:10 AM: Optimal value: 8.566e-01
(CVXPY) Jul 07 11:46:10 AM: Compilation took 8.903e-02 seconds
(CVXPY) Jul 07 11:46:10 AM: Solver (including time spent in interface) took 2.492e+00 seconds
(CVXPY) Jul 07 11:46:10 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:46:10 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:46:10 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:46:10 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:46:10 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:46:10 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:46:10 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:46:10 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:46:10 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:46:10 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:46:10 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:46:10 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:46:10 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:46:10 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:46:10 AM: Applying reduction SCS
(CVXPY) Jul 07 11:46:10 AM: Finished problem compilation (took 7.515e-02 seconds).
(CVXPY) Jul 07 11:46:10 AM: Invoking solver SCS  to obtain a solution.

    75| 6.35e-06  7.62e-10  1.34e-07  8.57e-01  1.00e-01  2.48e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.48e+00s = setup: 3.51e-02s + solve: 2.45e+00s
	 lin-sys: 6.03e-02s, cones: 2.36e+00s, accel: 7.11e-03s
------------------------------------------------------------------
objective = 0.856633
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.59e+02  1.00e-01  9.68e-02

(CVXPY) Jul 07 11:46:12 AM: Problem status: optimal
(CVXPY) Jul 07 11:46:12 AM: Optimal value: 7.330e-01
(CVXPY) Jul 07 11:46:12 AM: Compilation took 7.515e-02 seconds
(CVXPY) Jul 07 11:46:12 AM: Solver (including time spent in interface) took 2.479e+00 seconds
(CVXPY) Jul 07 11:46:12 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:46:12 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:46:12 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:46:12 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:46:12 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:46:12 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:46:12 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:46:12 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:46:12 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:46:12 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:46:12 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:46:12 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:46:12 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:46:12 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:46:13 AM: Applying reduction SCS
(CVXPY) Jul 07 11:46:13 AM: Finished problem compilation (took 1.044e-01 seconds).
(CVXPY) Jul 07 11:46:13 AM: Invoking solver SCS  to obtain a solution.

    75| 1.17e-05  7.55e-10  2.55e-07  7.33e-01  1.00e-01  2.47e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.47e+00s = setup: 5.97e-02s + solve: 2.41e+00s
	 lin-sys: 6.59e-02s, cones: 2.32e+00s, accel: 6.61e-03s
------------------------------------------------------------------
objective = 0.733022
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.59e+02  1.00e-01  6.09e-02

(CVXPY) Jul 07 11:46:15 AM: Problem status: optimal
(CVXPY) Jul 07 11:46:15 AM: Optimal value: 4.255e-01
(CVXPY) Jul 07 11:46:15 AM: Compilation took 1.044e-01 seconds
(CVXPY) Jul 07 11:46:15 AM: Solver (including time spent in interface) took 2.408e+00 seconds
(CVXPY) Jul 07 11:46:15 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:46:15 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:46:15 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:46:15 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:46:15 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:46:15 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:46:15 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:46:15 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:46:15 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:46:15 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:46:15 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:46:15 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:46:15 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:46:15 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:46:15 AM: Applying reduction SCS
(CVXPY) Jul 07 11:46:15 AM: Finished problem compilation (took 1.027e-01 seconds).
(CVXPY) Jul 07 11:46:15 AM: Invoking solver SCS  to obtain a solution.

    75| 1.14e-05  7.53e-10  1.95e-07  4.26e-01  1.00e-01  2.40e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.40e+00s = setup: 3.35e-02s + solve: 2.37e+00s
	 lin-sys: 6.41e-02s, cones: 2.28e+00s, accel: 5.92e-03s
------------------------------------------------------------------
objective = 0.425536
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.59e+02  1.00e-01  7.24e-02

(CVXPY) Jul 07 11:46:18 AM: Problem status: optimal
(CVXPY) Jul 07 11:46:18 AM: Optimal value: 8.714e-01
(CVXPY) Jul 07 11:46:18 AM: Compilation took 1.027e-01 seconds
(CVXPY) Jul 07 11:46:18 AM: Solver (including time spent in interface) took 2.519e+00 seconds
(CVXPY) Jul 07 11:46:18 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:46:18 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:46:18 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:46:18 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:46:18 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:46:18 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:46:18 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:46:18 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:46:18 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:46:18 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:46:18 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:46:18 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:46:18 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:46:18 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:46:18 AM: Applying reduction SCS
(CVXPY) Jul 07 11:46:18 AM: Finished problem compilation (took 9.564e-02 seconds).
(CVXPY) Jul 07 11:46:18 AM: Invoking solver SCS  to obtain a solution.

    75| 1.66e-05  7.53e-10  3.45e-07  8.71e-01  1.00e-01  2.51e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.51e+00s = setup: 3.58e-02s + solve: 2.48e+00s
	 lin-sys: 6.29e-02s, cones: 2.39e+00s, accel: 5.91e-03s
------------------------------------------------------------------
objective = 0.871369
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.59e+02  1.00e-01  5.42e-02

(CVXPY) Jul 07 11:46:20 AM: Problem status: optimal
(CVXPY) Jul 07 11:46:20 AM: Optimal value: 4.439e-01
(CVXPY) Jul 07 11:46:20 AM: Compilation took 9.564e-02 seconds
(CVXPY) Jul 07 11:46:20 AM: Solver (including time spent in interface) took 2.356e+00 seconds
(CVXPY) Jul 07 11:46:20 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:46:20 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:46:20 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:46:20 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:46:20 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:46:20 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:46:20 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:46:20 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:46:20 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:46:20 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:46:20 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:46:20 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:46:20 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:46:20 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:46:20 AM: Applying reduction SCS
(CVXPY) Jul 07 11:46:20 AM: Finished problem compilation (took 6.880e-02 seconds).
(CVXPY) Jul 07 11:46:20 AM: Invoking solver SCS  to obtain a solution.

    75| 1.65e-05  7.54e-10  2.93e-07  4.44e-01  1.00e-01  2.35e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.35e+00s = setup: 3.71e-02s + solve: 2.31e+00s
	 lin-sys: 6.32e-02s, cones: 2.22e+00s, accel: 5.91e-03s
------------------------------------------------------------------
objective = 0.443863
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.59e+02  1.00e-01  6.92e-02

(CVXPY) Jul 07 11:46:23 AM: Problem status: optimal
(CVXPY) Jul 07 11:46:23 AM: Optimal value: 4.356e-01
(CVXPY) Jul 07 11:46:23 AM: Compilation took 6.880e-02 seconds
(CVXPY) Jul 07 11:46:23 AM: Solver (including time spent in interface) took 2.460e+00 seconds
(CVXPY) Jul 07 11:46:23 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:46:23 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:46:23 AM: DCP verification time: 0.0003 seconds.
(CVXPY) Jul 07 11:46:23 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:46:23 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:46:23 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:46:23 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:46:23 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:46:23 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:46:23 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:46:23 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:46:23 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:46:23 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:46:23 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:46:23 AM: Applying reduction SCS
(CVXPY) Jul 07 11:46:23 AM: Finished problem compilation (took 5.089e-02 seconds).
(CVXPY) Jul 07 11:46:23 AM: Invoking solver SCS  to obtain a solution.

    75| 1.65e-05  7.52e-10  2.90e-07  4.36e-01  1.00e-01  2.46e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.46e+00s = setup: 3.72e-02s + solve: 2.42e+00s
	 lin-sys: 8.41e-02s, cones: 2.31e+00s, accel: 7.86e-03s
------------------------------------------------------------------
objective = 0.435570
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.59e+02  1.00e-01  5.32e-02

(CVXPY) Jul 07 11:46:25 AM: Problem status: optimal
(CVXPY) Jul 07 11:46:25 AM: Optimal value: 8.074e-01
(CVXPY) Jul 07 11:46:25 AM: Compilation took 5.089e-02 seconds
(CVXPY) Jul 07 11:46:25 AM: Solver (including time spent in interface) took 1.900e+00 seconds
(CVXPY) Jul 07 11:46:25 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:46:25 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:46:25 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:46:25 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:46:25 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:46:25 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:46:25 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:46:25 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:46:25 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:46:25 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:46:25 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:46:25 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:46:25 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:46:25 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:46:25 AM: Applying reduction SCS
(CVXPY) Jul 07 11:46:25 AM: Finished problem compilation (took 5.642e-02 seconds).
(CVXPY) Jul 07 11:46:25 AM: Invoking solver SCS  to obtain a solution.

    75| 1.68e-05  7.66e-10  3.21e-07  8.07e-01  1.00e-01  1.90e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.90e+00s = setup: 2.88e-02s + solve: 1.87e+00s
	 lin-sys: 5.06e-02s, cones: 1.79e+00s, accel: 6.94e-03s
------------------------------------------------------------------
objective = 0.807348
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.59e+02  1.00e-01  5.04e-02

(CVXPY) Jul 07 11:46:27 AM: Problem status: optimal
(CVXPY) Jul 07 11:46:27 AM: Optimal value: 7.365e-01
(CVXPY) Jul 07 11:46:27 AM: Compilation took 5.642e-02 seconds
(CVXPY) Jul 07 11:46:27 AM: Solver (including time spent in interface) took 1.858e+00 seconds
(CVXPY) Jul 07 11:46:27 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:46:27 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:46:27 AM: DCP verification time: 0.0003 seconds.
(CVXPY) Jul 07 11:46:27 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:46:27 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:46:27 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:46:27 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:46:27 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:46:27 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:46:27 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:46:27 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:46:27 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:46:27 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:46:27 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:46:27 AM: Applying reduction SCS
(CVXPY) Jul 07 11:46:27 AM: Finished problem compilation (took 5.571e-02 seconds).
(CVXPY) Jul 07 11:46:27 AM: Invoking solver SCS  to obtain a solution.

    75| 1.68e-05  7.64e-10  3.96e-07  7.37e-01  1.00e-01  1.85e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.85e+00s = setup: 2.60e-02s + solve: 1.83e+00s
	 lin-sys: 5.29e-02s, cones: 1.75e+00s, accel: 5.43e-03s
------------------------------------------------------------------
objective = 0.736528
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.59e+02  1.00e-01  4.95e-02

(CVXPY) Jul 07 11:46:28 AM: Problem status: optimal
(CVXPY) Jul 07 11:46:28 AM: Optimal value: 4.039e-01
(CVXPY) Jul 07 11:46:28 AM: Compilation took 5.571e-02 seconds
(CVXPY) Jul 07 11:46:28 AM: Solver (including time spent in interface) took 1.833e+00 seconds
(CVXPY) Jul 07 11:46:29 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:46:29 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:46:29 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:46:29 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:46:29 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:46:29 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:46:29 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:46:29 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:46:29 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:46:29 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:46:29 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:46:29 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:46:29 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:46:29 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:46:29 AM: Applying reduction SCS
(CVXPY) Jul 07 11:46:29 AM: Finished problem compilation (took 5.314e-02 seconds).
(CVXPY) Jul 07 11:46:29 AM: Invoking solver SCS  to obtain a solution.

    75| 6.16e-06  7.51e-10  1.67e-07  4.04e-01  1.00e-01  1.83e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.83e+00s = setup: 2.22e-02s + solve: 1.81e+00s
	 lin-sys: 4.83e-02s, cones: 1.74e+00s, accel: 5.12e-03s
------------------------------------------------------------------
objective = 0.403846
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.59e+02  1.00e-01  4.78e-02

(CVXPY) Jul 07 11:46:30 AM: Problem status: optimal
(CVXPY) Jul 07 11:46:30 AM: Optimal value: 8.039e-01
(CVXPY) Jul 07 11:46:30 AM: Compilation took 5.314e-02 seconds
(CVXPY) Jul 07 11:46:30 AM: Solver (including time spent in interface) took 1.863e+00 seconds
(CVXPY) Jul 07 11:46:30 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:46:30 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:46:30 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:46:30 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:46:30 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:46:30 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:46:30 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:46:30 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:46:30 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:46:30 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:46:30 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:46:30 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:46:30 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:46:30 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:46:31 AM: Applying reduction SCS
(CVXPY) Jul 07 11:46:31 AM: Finished problem compilation (took 5.475e-02 seconds).
(CVXPY) Jul 07 11:46:31 AM: Invoking solver SCS  to obtain a solution.

    75| 1.13e-05  7.61e-10  2.43e-07  8.04e-01  1.00e-01  1.86e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.86e+00s = setup: 2.57e-02s + solve: 1.83e+00s
	 lin-sys: 5.73e-02s, cones: 1.75e+00s, accel: 5.74e-03s
------------------------------------------------------------------
objective = 0.803927
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.59e+02  1.00e-01  4.87e-02

(CVXPY) Jul 07 11:46:32 AM: Problem status: optimal
(CVXPY) Jul 07 11:46:32 AM: Optimal value: 7.489e-01
(CVXPY) Jul 07 11:46:32 AM: Compilation took 5.475e-02 seconds
(CVXPY) Jul 07 11:46:32 AM: Solver (including time spent in interface) took 1.815e+00 seconds
(CVXPY) Jul 07 11:46:32 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:46:32 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:46:32 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:46:32 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:46:32 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:46:32 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:46:32 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:46:32 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:46:32 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:46:32 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:46:32 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:46:32 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:46:32 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:46:32 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:46:32 AM: Applying reduction SCS
(CVXPY) Jul 07 11:46:32 AM: Finished problem compilation (took 6.366e-02 seconds).
(CVXPY) Jul 07 11:46:32 AM: Invoking solver SCS  to obtain a solution.

    75| 1.64e-05  7.54e-10  3.43e-07  7.49e-01  1.00e-01  1.81e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.81e+00s = setup: 2.54e-02s + solve: 1.78e+00s
	 lin-sys: 5.42e-02s, cones: 1.71e+00s, accel: 7.09e-03s
------------------------------------------------------------------
objective = 0.748909
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.59e+02  1.00e-01  4.72e-02

(CVXPY) Jul 07 11:46:34 AM: Problem status: optimal
(CVXPY) Jul 07 11:46:34 AM: Optimal value: 5.013e-01
(CVXPY) Jul 07 11:46:34 AM: Compilation took 6.366e-02 seconds
(CVXPY) Jul 07 11:46:34 AM: Solver (including time spent in interface) took 2.007e+00 seconds
(CVXPY) Jul 07 11:46:34 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:46:34 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:46:34 AM: DCP verification time: 0.0023 seconds.
(CVXPY) Jul 07 11:46:34 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:46:34 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:46:34 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:46:34 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:46:34 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:46:34 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:46:34 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:46:34 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:46:34 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:46:34 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:46:34 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:46:34 AM: Applying reduction SCS
(CVXPY) Jul 07 11:46:35 AM: Finished problem compilation (took 6.713e-02 seconds).
(CVXPY) Jul 07 11:46:35 AM: Invoking solver SCS  to obtain a solution.

    75| 1.64e-05  7.54e-10  3.37e-07  5.01e-01  1.00e-01  2.00e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.00e+00s = setup: 2.36e-02s + solve: 1.98e+00s
	 lin-sys: 5.85e-02s, cones: 1.89e+00s, accel: 1.03e-02s
------------------------------------------------------------------
objective = 0.501311
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.59e+02  1.00e-01  5.61e-02

(CVXPY) Jul 07 11:46:37 AM: Problem status: optimal
(CVXPY) Jul 07 11:46:37 AM: Optimal value: 8.201e-01
(CVXPY) Jul 07 11:46:37 AM: Compilation took 6.713e-02 seconds
(CVXPY) Jul 07 11:46:37 AM: Solver (including time spent in interface) took 2.091e+00 seconds
(CVXPY) Jul 07 11:46:37 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:46:37 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:46:37 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:46:37 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:46:37 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:46:37 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:46:37 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:46:37 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:46:37 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:46:37 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:46:37 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:46:37 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:46:37 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:46:37 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:46:37 AM: Applying reduction SCS
(CVXPY) Jul 07 11:46:37 AM: Finished problem compilation (took 5.739e-02 seconds).
(CVXPY) Jul 07 11:46:37 AM: Invoking solver SCS  to obtain a solution.

    75| 1.14e-05  7.59e-10  2.31e-07  8.20e-01  1.00e-01  2.08e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.09e+00s = setup: 3.06e-02s + solve: 2.06e+00s
	 lin-sys: 5.33e-02s, cones: 1.98e+00s, accel: 5.19e-03s
------------------------------------------------------------------
objective = 0.820046
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.59e+02  1.00e-01  5.54e-02

(CVXPY) Jul 07 11:46:39 AM: Problem status: optimal
(CVXPY) Jul 07 11:46:39 AM: Optimal value: 7.762e-01
(CVXPY) Jul 07 11:46:39 AM: Compilation took 5.739e-02 seconds
(CVXPY) Jul 07 11:46:39 AM: Solver (including time spent in interface) took 1.964e+00 seconds
(CVXPY) Jul 07 11:46:39 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:46:39 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:46:39 AM: DCP verification time: 0.0009 seconds.
(CVXPY) Jul 07 11:46:39 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:46:39 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:46:39 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:46:39 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:46:39 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:46:39 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:46:39 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:46:39 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:46:39 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:46:39 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:46:39 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:46:39 AM: Applying reduction SCS
(CVXPY) Jul 07 11:46:39 AM: Finished problem compilation (took 5.511e-02 seconds).
(CVXPY) Jul 07 11:46:39 AM: Invoking solver SCS  to obtain a solution.

    75| 1.15e-05  7.61e-10  2.54e-07  7.76e-01  1.00e-01  1.96e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.96e+00s = setup: 2.85e-02s + solve: 1.93e+00s
	 lin-sys: 5.11e-02s, cones: 1.86e+00s, accel: 5.31e-03s
------------------------------------------------------------------
objective = 0.776229
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.59e+02  1.00e-01  5.37e-02

(CVXPY) Jul 07 11:46:41 AM: Problem status: optimal
(CVXPY) Jul 07 11:46:41 AM: Optimal value: 5.501e-01
(CVXPY) Jul 07 11:46:41 AM: Compilation took 5.511e-02 seconds
(CVXPY) Jul 07 11:46:41 AM: Solver (including time spent in interface) took 2.478e+00 seconds
(CVXPY) Jul 07 11:46:41 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:46:41 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:46:41 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:46:41 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:46:41 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:46:41 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:46:41 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:46:41 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:46:41 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:46:41 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:46:41 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:46:41 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:46:41 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:46:41 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:46:41 AM: Applying reduction SCS
(CVXPY) Jul 07 11:46:41 AM: Finished problem compilation (took 6.994e-02 seconds).
(CVXPY) Jul 07 11:46:41 AM: Invoking solver SCS  to obtain a solution.

    75| 1.70e-05  7.59e-10  3.92e-07  5.50e-01  1.00e-01  2.47e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.47e+00s = setup: 2.41e-02s + solve: 2.45e+00s
	 lin-sys: 6.24e-02s, cones: 2.36e+00s, accel: 5.88e-03s
------------------------------------------------------------------
objective = 0.550036
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  1.89e-02  1.37e-02  1.44e-01  1.00e-01  6.91e-02
   250| 9.96e-05  4.11e-08  8.65e-07  8.88e-07  9.12e-06  3.88e+00

(CVXPY) Jul 07 11:46:46 AM: Problem status: optimal
(CVXPY) Jul 07 11:46:46 AM: Optimal value: 2.429e-07
(CVXPY) Jul 07 11:46:46 AM: Compilation took 6.994e-02 seconds
(CVXPY) Jul 07 11:46:46 AM: Solver (including time spent in interface) took 4.676e+00 seconds
(CVXPY) Jul 07 11:46:46 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:46:46 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:46:46 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:46:46 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:46:46 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:46:46 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:46:46 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:46:46 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:46:46 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:46:46 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:46:46 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:46:46 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:46:46 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:46:46 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:46:46 AM: Applying reduction SCS
(CVXPY) Jul 07 11:46:46 AM: Finished problem compilation (took 7.728e-02 seconds).
(CVXPY) Jul 07 11:46:46 AM: Invoking solver SCS  to obtain a solution.

   300| 2.52e-05  2.26e-08  4.61e-07  4.73e-07  9.12e-06  4.67e+00
------------------------------------------------------------------
status:  solved
timings: total: 4.67e+00s = setup: 3.40e-02s + solve: 4.64e+00s
	 lin-sys: 2.72e-01s, cones: 4.28e+00s, accel: 2.60e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  3.49e-02  6.55e-02  2.31e-01  1.00e-01  7.34e-02
   250| 9.37e-05  4.85e-08  1.06e-06  1.04e-06  1.07e-05  3.97e+00

(CVXPY) Jul 07 11:46:51 AM: Problem status: optimal
(CVXPY) Jul 07 11:46:51 AM: Optimal value: 2.703e-07
(CVXPY) Jul 07 11:46:51 AM: Compilation took 7.728e-02 seconds
(CVXPY) Jul 07 11:46:51 AM: Solver (including time spent in interface) took 4.591e+00 seconds
(CVXPY) Jul 07 11:46:51 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:46:51 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:46:51 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:46:51 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:46:51 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:46:51 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:46:51 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:46:51 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:46:51 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:46:51 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:46:51 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:46:51 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:46:51 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:46:51 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:46:51 AM: Applying reduction SCS
(CVXPY) Jul 07 11:46:51 AM: Finished problem compilation (took 5.459e-02 seconds).
(CVXPY) Jul 07 11:46:51 AM: Invoking solver SCS  to obtain a solution.

   300| 2.36e-05  2.63e-08  5.56e-07  5.48e-07  1.07e-05  4.59e+00
------------------------------------------------------------------
status:  solved
timings: total: 4.59e+00s = setup: 3.70e-02s + solve: 4.55e+00s
	 lin-sys: 2.31e-01s, cones: 4.24e+00s, accel: 2.35e-02s
------------------------------------------------------------------
objective = 0.000001
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  3.45e-02  6.78e-02  2.54e-01  1.00e-01  5.37e-02
   250| 9.36e-05  4.66e-08  9.77e-07  9.93e-07  1.03e-05  3.17e+00

(CVXPY) Jul 07 11:46:55 AM: Problem status: optimal
(CVXPY) Jul 07 11:46:55 AM: Optimal value: 2.712e-07
(CVXPY) Jul 07 11:46:55 AM: Compilation took 5.459e-02 seconds
(CVXPY) Jul 07 11:46:55 AM: Solver (including time spent in interface) took 3.732e+00 seconds
(CVXPY) Jul 07 11:46:55 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:46:55 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:46:55 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:46:55 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:46:55 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:46:55 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:46:55 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:46:55 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:46:55 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:46:55 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:46:55 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:46:55 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:46:55 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:46:55 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:46:55 AM: Applying reduction SCS
(CVXPY) Jul 07 11:46:55 AM: Finished problem compilation (took 5.539e-02 seconds).
(CVXPY) Jul 07 11:46:55 AM: Invoking solver SCS  to obtain a solution.

   300| 2.39e-05  2.57e-08  5.27e-07  5.34e-07  1.03e-05  3.73e+00
------------------------------------------------------------------
status:  solved
timings: total: 3.73e+00s = setup: 2.63e-02s + solve: 3.70e+00s
	 lin-sys: 1.87e-01s, cones: 3.44e+00s, accel: 2.15e-02s
------------------------------------------------------------------
objective = 0.000001
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  3.48e-02  7.83e-02  2.20e-01  1.00e-01  4.69e-02
   250| 9.29e-05  5.00e-08  1.12e-06  1.08e-06  1.10e-05  3.12e+00

(CVXPY) Jul 07 11:46:58 AM: Problem status: optimal
(CVXPY) Jul 07 11:46:58 AM: Optimal value: 2.767e-07
(CVXPY) Jul 07 11:46:58 AM: Compilation took 5.539e-02 seconds
(CVXPY) Jul 07 11:46:58 AM: Solver (including time spent in interface) took 3.682e+00 seconds
(CVXPY) Jul 07 11:46:58 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:46:58 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:46:58 AM: DCP verification time: 0.0003 seconds.
(CVXPY) Jul 07 11:46:58 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:46:58 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:46:58 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:46:58 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:46:58 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:46:58 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:46:58 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:46:58 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:46:58 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:46:58 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:46:58 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:46:58 AM: Applying reduction SCS
(CVXPY) Jul 07 11:46:58 AM: Finished problem compilation (took 5.224e-02 seconds).
(CVXPY) Jul 07 11:46:58 AM: Invoking solver SCS  to obtain a solution.

   300| 2.31e-05  2.69e-08  5.83e-07  5.68e-07  1.10e-05  3.68e+00
------------------------------------------------------------------
status:  solved
timings: total: 3.68e+00s = setup: 2.26e-02s + solve: 3.65e+00s
	 lin-sys: 1.84e-01s, cones: 3.39e+00s, accel: 2.14e-02s
------------------------------------------------------------------
objective = 0.000001
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  1.89e-02  2.18e-02  1.35e-01  1.00e-01  5.16e-02
   250| 9.78e-05  4.06e-08  8.52e-07  8.75e-07  9.23e-06  3.16e+00

(CVXPY) Jul 07 11:47:02 AM: Problem status: optimal
(CVXPY) Jul 07 11:47:02 AM: Optimal value: 2.406e-07
(CVXPY) Jul 07 11:47:02 AM: Compilation took 5.224e-02 seconds
(CVXPY) Jul 07 11:47:02 AM: Solver (including time spent in interface) took 3.713e+00 seconds
(CVXPY) Jul 07 11:47:02 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:47:02 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:47:02 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:47:02 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:47:02 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:47:02 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:47:02 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:47:02 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:47:02 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:47:02 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:47:02 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:47:02 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:47:02 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:47:02 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:47:02 AM: Applying reduction SCS
(CVXPY) Jul 07 11:47:02 AM: Finished problem compilation (took 4.831e-02 seconds).
(CVXPY) Jul 07 11:47:02 AM: Invoking solver SCS  to obtain a solution.

   300| 2.47e-05  2.25e-08  4.53e-07  4.67e-07  9.23e-06  3.71e+00
------------------------------------------------------------------
status:  solved
timings: total: 3.71e+00s = setup: 2.77e-02s + solve: 3.68e+00s
	 lin-sys: 1.80e-01s, cones: 3.43e+00s, accel: 1.98e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  3.47e-02  8.92e-02  2.68e-01  1.00e-01  4.78e-02
   250| 9.58e-05  5.51e-08  1.24e-06  1.23e-06  1.13e-05  3.47e+00

(CVXPY) Jul 07 11:47:06 AM: Problem status: optimal
(CVXPY) Jul 07 11:47:06 AM: Optimal value: 3.200e-07
(CVXPY) Jul 07 11:47:06 AM: Compilation took 4.831e-02 seconds
(CVXPY) Jul 07 11:47:06 AM: Solver (including time spent in interface) took 4.208e+00 seconds
(CVXPY) Jul 07 11:47:06 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:47:06 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:47:06 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:47:06 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:47:06 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:47:06 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:47:06 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:47:06 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:47:06 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:47:06 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:47:06 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:47:06 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:47:06 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:47:06 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:47:06 AM: Applying reduction SCS
(CVXPY) Jul 07 11:47:06 AM: Finished problem compilation (took 8.889e-02 seconds).
(CVXPY) Jul 07 11:47:06 AM: Invoking solver SCS  to obtain a solution.

   300| 2.42e-05  2.98e-08  6.58e-07  6.49e-07  1.13e-05  4.20e+00
------------------------------------------------------------------
status:  solved
timings: total: 4.20e+00s = setup: 2.26e-02s + solve: 4.18e+00s
	 lin-sys: 2.27e-01s, cones: 3.88e+00s, accel: 1.83e-02s
------------------------------------------------------------------
objective = 0.000001
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  3.52e-02  7.53e-02  2.21e-01  1.00e-01  7.37e-02
   250| 9.32e-05  4.95e-08  1.09e-06  1.06e-06  1.09e-05  4.47e+00

(CVXPY) Jul 07 11:47:12 AM: Problem status: optimal
(CVXPY) Jul 07 11:47:12 AM: Optimal value: 2.724e-07
(CVXPY) Jul 07 11:47:12 AM: Compilation took 8.889e-02 seconds
(CVXPY) Jul 07 11:47:12 AM: Solver (including time spent in interface) took 5.269e+00 seconds
(CVXPY) Jul 07 11:47:12 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:47:12 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:47:12 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:47:12 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:47:12 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:47:12 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:47:12 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:47:12 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:47:12 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:47:12 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:47:12 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:47:12 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:47:12 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:47:12 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:47:12 AM: Applying reduction SCS
(CVXPY) Jul 07 11:47:12 AM: Finished problem compilation (took 8.486e-02 seconds).
(CVXPY) Jul 07 11:47:12 AM: Invoking solver SCS  to obtain a solution.

   300| 2.33e-05  2.67e-08  5.68e-07  5.56e-07  1.09e-05  5.26e+00
------------------------------------------------------------------
status:  solved
timings: total: 5.26e+00s = setup: 4.37e-02s + solve: 5.22e+00s
	 lin-sys: 2.83e-01s, cones: 4.84e+00s, accel: 1.96e-02s
------------------------------------------------------------------
objective = 0.000001
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  1.51e-02  1.02e-02  1.30e-01  1.00e-01  8.27e-02
   250| 9.48e-05  3.48e-08  6.36e-07  6.71e-07  7.59e-06  4.42e+00

(CVXPY) Jul 07 11:47:17 AM: Problem status: optimal
(CVXPY) Jul 07 11:47:17 AM: Optimal value: 1.903e-07
(CVXPY) Jul 07 11:47:17 AM: Compilation took 8.486e-02 seconds
(CVXPY) Jul 07 11:47:17 AM: Solver (including time spent in interface) took 5.227e+00 seconds
(CVXPY) Jul 07 11:47:17 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:47:17 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:47:17 AM: DCP verification time: 0.0013 seconds.
(CVXPY) Jul 07 11:47:17 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:47:17 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:47:17 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:47:17 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:47:17 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:47:17 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:47:17 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:47:17 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:47:17 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:47:17 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:47:17 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:47:17 AM: Applying reduction SCS
(CVXPY) Jul 07 11:47:17 AM: Finished problem compilation (took 9.079e-02 seconds).
(CVXPY) Jul 07 11:47:17 AM: Invoking solver SCS  to obtain a solution.

   300| 2.43e-05  1.70e-08  3.39e-07  3.60e-07  7.59e-06  5.22e+00
------------------------------------------------------------------
status:  solved
timings: total: 5.22e+00s = setup: 4.38e-02s + solve: 5.18e+00s
	 lin-sys: 2.85e-01s, cones: 4.80e+00s, accel: 1.93e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  3.52e-02  7.02e-02  2.67e-01  1.00e-01  9.64e-02
   250| 9.48e-05  4.86e-08  1.07e-06  1.06e-06  1.06e-05  4.59e+00

(CVXPY) Jul 07 11:47:23 AM: Problem status: optimal
(CVXPY) Jul 07 11:47:23 AM: Optimal value: 2.809e-07
(CVXPY) Jul 07 11:47:23 AM: Compilation took 9.079e-02 seconds
(CVXPY) Jul 07 11:47:23 AM: Solver (including time spent in interface) took 5.441e+00 seconds
(CVXPY) Jul 07 11:47:23 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:47:23 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:47:23 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:47:23 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:47:23 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:47:23 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:47:23 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:47:23 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:47:23 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:47:23 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:47:23 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:47:23 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:47:23 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:47:23 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:47:23 AM: Applying reduction SCS

   300| 2.37e-05  2.66e-08  5.68e-07  5.65e-07  1.06e-05  5.43e+00
------------------------------------------------------------------
status:  solved
timings: total: 5.43e+00s = setup: 4.94e-02s + solve: 5.38e+00s
	 lin-sys: 2.90e-01s, cones: 5.01e+00s, accel: 1.97e-02s
------------------------------------------------------------------
objective = 0.000001
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Jul 07 11:47:23 AM: Finished problem compilation (took 1.612e-01 seconds).
(CVXPY) Jul 07 11:47:23 AM: Invoking solver SCS  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  1.87e-02  5.95e-03  1.37e-01  1.00e-01  9.50e-02
   250| 9.51e-05  3.43e-08  6.03e-07  6.54e-07  7.14e-06  4.41e+00

(CVXPY) Jul 07 11:47:28 AM: Problem status: optimal
(CVXPY) Jul 07 11:47:28 AM: Optimal value: 1.908e-07
(CVXPY) Jul 07 11:47:28 AM: Compilation took 1.612e-01 seconds
(CVXPY) Jul 07 11:47:28 AM: Solver (including time spent in interface) took 5.200e+00 seconds
(CVXPY) Jul 07 11:47:28 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:47:28 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:47:28 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:47:28 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:47:28 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:47:28 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:47:28 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:47:28 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:47:28 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:47:28 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:47:28 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:47:28 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:47:28 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:47:28 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:47:28 AM: Applying reduction SCS
(CVXPY) Jul 07 11:47:28 AM: Finished problem compilation (took 1.145e-01 seconds).
(CVXPY) Jul 07 11:47:28 AM: Invoking solver SCS  to obtain a solution.

   300| 2.48e-05  1.69e-08  3.26e-07  3.54e-07  7.14e-06  5.19e+00
------------------------------------------------------------------
status:  solved
timings: total: 5.19e+00s = setup: 5.56e-02s + solve: 5.14e+00s
	 lin-sys: 2.83e-01s, cones: 4.77e+00s, accel: 1.99e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  1.86e-02  1.30e-02  1.31e-01  1.00e-01  1.01e-01
   250| 9.99e-05  4.42e-08  8.62e-07  8.86e-07  8.80e-06  4.66e+00

(CVXPY) Jul 07 11:47:34 AM: Problem status: optimal
(CVXPY) Jul 07 11:47:34 AM: Optimal value: 2.427e-07
(CVXPY) Jul 07 11:47:34 AM: Compilation took 1.145e-01 seconds
(CVXPY) Jul 07 11:47:34 AM: Solver (including time spent in interface) took 5.459e+00 seconds
(CVXPY) Jul 07 11:47:34 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:47:34 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:47:34 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:47:34 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:47:34 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:47:34 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:47:34 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:47:34 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:47:34 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:47:34 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:47:34 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:47:34 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:47:34 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:47:34 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:47:34 AM: Applying reduction SCS
(CVXPY) Jul 07 11:47:34 AM: Finished problem compilation (took 8.656e-02 seconds).
(CVXPY) Jul 07 11:47:34 AM: Invoking solver SCS  to obtain a solution.

   300| 2.58e-05  2.33e-08  4.63e-07  4.74e-07  8.80e-06  5.45e+00
------------------------------------------------------------------
status:  solved
timings: total: 5.45e+00s = setup: 5.95e-02s + solve: 5.39e+00s
	 lin-sys: 2.94e-01s, cones: 5.01e+00s, accel: 1.97e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  3.47e-02  5.85e-02  2.45e-01  1.00e-01  7.76e-02
   250| 9.52e-05  4.78e-08  9.73e-07  9.86e-07  1.01e-05  4.86e+00

(CVXPY) Jul 07 11:47:39 AM: Problem status: optimal
(CVXPY) Jul 07 11:47:39 AM: Optimal value: 2.666e-07
(CVXPY) Jul 07 11:47:39 AM: Compilation took 8.656e-02 seconds
(CVXPY) Jul 07 11:47:39 AM: Solver (including time spent in interface) took 5.664e+00 seconds
(CVXPY) Jul 07 11:47:40 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:47:40 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:47:40 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:47:40 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:47:40 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:47:40 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:47:40 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:47:40 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:47:40 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:47:40 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:47:40 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:47:40 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:47:40 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:47:40 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:47:40 AM: Applying reduction SCS
(CVXPY) Jul 07 11:47:40 AM: Finished problem compilation (took 9.548e-02 seconds).
(CVXPY) Jul 07 11:47:40 AM: Invoking solver SCS  to obtain a solution.

   300| 2.44e-05  2.55e-08  5.22e-07  5.28e-07  1.01e-05  5.66e+00
------------------------------------------------------------------
status:  solved
timings: total: 5.66e+00s = setup: 4.02e-02s + solve: 5.62e+00s
	 lin-sys: 3.26e-01s, cones: 5.20e+00s, accel: 2.15e-02s
------------------------------------------------------------------
objective = 0.000001
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  3.46e-02  6.05e-02  2.20e-01  1.00e-01  8.46e-02
   250| 9.52e-05  4.84e-08  9.86e-07  9.75e-07  1.02e-05  4.37e+00

(CVXPY) Jul 07 11:47:45 AM: Problem status: optimal
(CVXPY) Jul 07 11:47:45 AM: Optimal value: 2.546e-07
(CVXPY) Jul 07 11:47:45 AM: Compilation took 9.548e-02 seconds
(CVXPY) Jul 07 11:47:45 AM: Solver (including time spent in interface) took 5.146e+00 seconds
(CVXPY) Jul 07 11:47:45 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:47:45 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:47:45 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:47:45 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:47:45 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:47:45 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:47:45 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:47:45 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:47:45 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:47:45 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:47:45 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:47:45 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:47:45 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:47:45 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:47:45 AM: Applying reduction SCS
(CVXPY) Jul 07 11:47:45 AM: Finished problem compilation (took 9.039e-02 seconds).
(CVXPY) Jul 07 11:47:45 AM: Invoking solver SCS  to obtain a solution.

   300| 2.39e-05  2.54e-08  5.18e-07  5.14e-07  1.02e-05  5.14e+00
------------------------------------------------------------------
status:  solved
timings: total: 5.14e+00s = setup: 4.06e-02s + solve: 5.10e+00s
	 lin-sys: 2.70e-01s, cones: 4.74e+00s, accel: 2.20e-02s
------------------------------------------------------------------
objective = 0.000001
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  1.85e-02  1.71e-03  1.25e-01  1.00e-01  8.78e-02
   250| 9.78e-05  3.62e-08  6.69e-07  7.19e-07  7.27e-06  4.52e+00

(CVXPY) Jul 07 11:47:50 AM: Problem status: optimal
(CVXPY) Jul 07 11:47:50 AM: Optimal value: 2.066e-07
(CVXPY) Jul 07 11:47:50 AM: Compilation took 9.039e-02 seconds
(CVXPY) Jul 07 11:47:50 AM: Solver (including time spent in interface) took 5.273e+00 seconds
(CVXPY) Jul 07 11:47:50 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:47:50 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:47:50 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:47:50 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:47:50 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:47:50 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:47:50 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:47:50 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:47:50 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:47:50 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:47:50 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:47:50 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:47:50 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:47:50 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:47:50 AM: Applying reduction SCS
(CVXPY) Jul 07 11:47:50 AM: Finished problem compilation (took 8.859e-02 seconds).
(CVXPY) Jul 07 11:47:50 AM: Invoking solver SCS  to obtain a solution.

   300| 2.55e-05  1.94e-08  3.63e-07  3.88e-07  7.27e-06  5.27e+00
------------------------------------------------------------------
status:  solved
timings: total: 5.27e+00s = setup: 4.53e-02s + solve: 5.22e+00s
	 lin-sys: 2.95e-01s, cones: 4.83e+00s, accel: 2.08e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  3.43e-02  8.09e-02  2.46e-01  1.00e-01  7.71e-02
   250| 9.50e-05  5.52e-08  1.28e-06  1.25e-06  1.13e-05  4.33e+00

(CVXPY) Jul 07 11:47:55 AM: Problem status: optimal
(CVXPY) Jul 07 11:47:55 AM: Optimal value: 3.220e-07
(CVXPY) Jul 07 11:47:55 AM: Compilation took 8.859e-02 seconds
(CVXPY) Jul 07 11:47:55 AM: Solver (including time spent in interface) took 5.150e+00 seconds
(CVXPY) Jul 07 11:47:55 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:47:55 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:47:55 AM: DCP verification time: 0.0015 seconds.
(CVXPY) Jul 07 11:47:55 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:47:55 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:47:55 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:47:55 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:47:55 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:47:55 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:47:55 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:47:55 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:47:55 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:47:56 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:47:56 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:47:56 AM: Applying reduction SCS
(CVXPY) Jul 07 11:47:56 AM: Finished problem compilation (took 8.158e-02 seconds).
(CVXPY) Jul 07 11:47:56 AM: Invoking solver SCS  to obtain a solution.

   300| 2.40e-05  2.98e-08  6.75e-07  6.60e-07  1.13e-05  5.15e+00
------------------------------------------------------------------
status:  solved
timings: total: 5.15e+00s = setup: 3.90e-02s + solve: 5.11e+00s
	 lin-sys: 2.78e-01s, cones: 4.75e+00s, accel: 1.81e-02s
------------------------------------------------------------------
objective = 0.000001
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  3.55e-02  6.74e-02  2.25e-01  1.00e-01  9.34e-02
   250| 9.10e-05  4.43e-08  9.38e-07  9.29e-07  1.04e-05  4.73e+00

(CVXPY) Jul 07 11:48:01 AM: Problem status: optimal
(CVXPY) Jul 07 11:48:01 AM: Optimal value: 3.178e-07
(CVXPY) Jul 07 11:48:01 AM: Compilation took 8.158e-02 seconds
(CVXPY) Jul 07 11:48:01 AM: Solver (including time spent in interface) took 5.181e+00 seconds
(CVXPY) Jul 07 11:48:01 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:48:01 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:48:01 AM: DCP verification time: 0.0034 seconds.
(CVXPY) Jul 07 11:48:01 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:48:01 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:48:01 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:48:01 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:48:01 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:48:01 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:48:01 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:48:01 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:48:01 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:48:01 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:48:01 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:48:01 AM: Applying reduction SCS
(CVXPY) Jul 07 11:48:01 AM: Finished problem compilation (took 8.984e-02 seconds).
(CVXPY) Jul 07 11:48:01 AM: Invoking solver SCS  to obtain a solution.

   275| 4.01e-05  3.22e-08  6.47e-07  6.41e-07  1.04e-05  5.17e+00
------------------------------------------------------------------
status:  solved
timings: total: 5.17e+00s = setup: 4.89e-02s + solve: 5.12e+00s
	 lin-sys: 2.85e-01s, cones: 4.75e+00s, accel: 2.21e-02s
------------------------------------------------------------------
objective = 0.000001
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  1.87e-02  9.06e-03  1.55e-01  1.00e-01  8.66e-02
   250| 9.57e-05  3.57e-08  6.33e-07  6.88e-07  7.20e-06  4.48e+00

(CVXPY) Jul 07 11:48:06 AM: Problem status: optimal
(CVXPY) Jul 07 11:48:06 AM: Optimal value: 2.002e-07
(CVXPY) Jul 07 11:48:06 AM: Compilation took 8.984e-02 seconds
(CVXPY) Jul 07 11:48:06 AM: Solver (including time spent in interface) took 5.327e+00 seconds
(CVXPY) Jul 07 11:48:06 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:48:06 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:48:06 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:48:06 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:48:06 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:48:06 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:48:06 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:48:06 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:48:06 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:48:06 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:48:06 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:48:06 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:48:06 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:48:06 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:48:06 AM: Applying reduction SCS
(CVXPY) Jul 07 11:48:06 AM: Finished problem compilation (took 9.440e-02 seconds).
(CVXPY) Jul 07 11:48:06 AM: Invoking solver SCS  to obtain a solution.

   300| 2.53e-05  1.91e-08  3.45e-07  3.73e-07  7.20e-06  5.32e+00
------------------------------------------------------------------
status:  solved
timings: total: 5.32e+00s = setup: 4.23e-02s + solve: 5.28e+00s
	 lin-sys: 3.02e-01s, cones: 4.89e+00s, accel: 1.80e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  3.50e-02  7.45e-02  2.51e-01  1.00e-01  8.92e-02
   250| 9.57e-05  5.37e-08  1.23e-06  1.21e-06  1.12e-05  4.45e+00

(CVXPY) Jul 07 11:48:12 AM: Problem status: optimal
(CVXPY) Jul 07 11:48:12 AM: Optimal value: 3.143e-07
(CVXPY) Jul 07 11:48:12 AM: Compilation took 9.440e-02 seconds
(CVXPY) Jul 07 11:48:12 AM: Solver (including time spent in interface) took 5.315e+00 seconds
(CVXPY) Jul 07 11:48:12 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:48:12 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:48:12 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:48:12 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:48:12 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:48:12 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:48:12 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:48:12 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:48:12 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:48:12 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:48:12 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:48:12 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:48:12 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:48:12 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:48:12 AM: Applying reduction SCS
(CVXPY) Jul 07 11:48:12 AM: Finished problem compilation (took 8.481e-02 seconds).
(CVXPY) Jul 07 11:48:12 AM: Invoking solver SCS  to obtain a solution.

   300| 2.40e-05  2.92e-08  6.51e-07  6.40e-07  1.12e-05  5.31e+00
------------------------------------------------------------------
status:  solved
timings: total: 5.31e+00s = setup: 4.16e-02s + solve: 5.27e+00s
	 lin-sys: 2.72e-01s, cones: 4.90e+00s, accel: 2.02e-02s
------------------------------------------------------------------
objective = 0.000001
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  3.47e-02  6.99e-02  2.35e-01  1.00e-01  7.85e-02
   250| 9.29e-05  5.19e-08  1.13e-06  1.12e-06  1.11e-05  4.55e+00

(CVXPY) Jul 07 11:48:17 AM: Problem status: optimal
(CVXPY) Jul 07 11:48:17 AM: Optimal value: 2.924e-07
(CVXPY) Jul 07 11:48:17 AM: Compilation took 8.481e-02 seconds
(CVXPY) Jul 07 11:48:17 AM: Solver (including time spent in interface) took 5.321e+00 seconds
(CVXPY) Jul 07 11:48:17 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:48:17 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:48:17 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:48:17 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:48:17 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:48:17 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:48:17 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:48:17 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:48:17 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:48:17 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:48:17 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:48:17 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:48:17 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:48:17 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:48:17 AM: Applying reduction SCS
(CVXPY) Jul 07 11:48:17 AM: Finished problem compilation (took 9.084e-02 seconds).
(CVXPY) Jul 07 11:48:17 AM: Invoking solver SCS  to obtain a solution.

   300| 2.33e-05  2.80e-08  6.01e-07  5.93e-07  1.11e-05  5.31e+00
------------------------------------------------------------------
status:  solved
timings: total: 5.31e+00s = setup: 4.34e-02s + solve: 5.27e+00s
	 lin-sys: 3.00e-01s, cones: 4.88e+00s, accel: 1.93e-02s
------------------------------------------------------------------
objective = 0.000001
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  1.95e-02  9.69e-03  1.67e-01  1.00e-01  9.17e-02
   250| 1.00e-04  3.72e-08  7.27e-07  7.70e-07  7.54e-06  4.51e+00

(CVXPY) Jul 07 11:48:23 AM: Problem status: optimal
(CVXPY) Jul 07 11:48:23 AM: Optimal value: 2.180e-07
(CVXPY) Jul 07 11:48:23 AM: Compilation took 9.084e-02 seconds
(CVXPY) Jul 07 11:48:23 AM: Solver (including time spent in interface) took 5.301e+00 seconds
(CVXPY) Jul 07 11:48:23 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:48:23 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:48:23 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:48:23 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:48:23 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:48:23 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:48:23 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:48:23 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:48:23 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:48:23 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:48:23 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:48:23 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:48:23 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:48:23 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:48:23 AM: Applying reduction SCS
(CVXPY) Jul 07 11:48:23 AM: Finished problem compilation (took 8.998e-02 seconds).
(CVXPY) Jul 07 11:48:23 AM: Invoking solver SCS  to obtain a solution.

   300| 2.60e-05  1.98e-08  3.91e-07  4.14e-07  7.54e-06  5.29e+00
------------------------------------------------------------------
status:  solved
timings: total: 5.29e+00s = setup: 4.91e-02s + solve: 5.24e+00s
	 lin-sys: 2.82e-01s, cones: 4.88e+00s, accel: 1.89e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.86e+01  1.00e-01  5.94e-02

(CVXPY) Jul 07 11:48:25 AM: Problem status: optimal
(CVXPY) Jul 07 11:48:25 AM: Optimal value: 1.893e-01
(CVXPY) Jul 07 11:48:25 AM: Compilation took 8.998e-02 seconds
(CVXPY) Jul 07 11:48:25 AM: Solver (including time spent in interface) took 2.306e+00 seconds
(CVXPY) Jul 07 11:48:25 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:48:25 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:48:25 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:48:25 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:48:25 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:48:25 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:48:25 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:48:25 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:48:25 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:48:25 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:48:25 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:48:25 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:48:25 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:48:25 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:48:25 AM: Applying reduction SCS
(CVXPY) Jul 07 11:48:25 AM: Finished problem compilation (took 1.312e-01 seconds).
(CVXPY) Jul 07 11:48:25 AM: Invoking solver SCS  to obtain a solution.

    75| 3.44e-06  3.68e-10  5.35e-07  1.89e-01  1.00e-01  2.30e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.30e+00s = setup: 3.62e-02s + solve: 2.26e+00s
	 lin-sys: 7.46e-02s, cones: 2.17e+00s, accel: 5.31e-03s
------------------------------------------------------------------
objective = 0.189275
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.85e+01  1.00e-01  8.41e-02

(CVXPY) Jul 07 11:48:27 AM: Problem status: optimal
(CVXPY) Jul 07 11:48:27 AM: Optimal value: 2.590e-01
(CVXPY) Jul 07 11:48:27 AM: Compilation took 1.312e-01 seconds
(CVXPY) Jul 07 11:48:27 AM: Solver (including time spent in interface) took 2.122e+00 seconds
(CVXPY) Jul 07 11:48:27 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:48:27 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:48:27 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:48:27 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:48:27 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:48:27 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:48:27 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:48:27 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:48:27 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:48:27 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:48:27 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:48:27 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:48:27 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:48:27 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:48:27 AM: Applying reduction SCS
(CVXPY) Jul 07 11:48:27 AM: Finished problem compilation (took 1.181e-01 seconds).
(CVXPY) Jul 07 11:48:27 AM: Invoking solver SCS  to obtain a solution.

    75| 1.92e-06  3.26e-10  2.46e-07  2.59e-01  1.00e-01  2.11e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.11e+00s = setup: 4.13e-02s + solve: 2.07e+00s
	 lin-sys: 8.17e-02s, cones: 1.96e+00s, accel: 5.78e-03s
------------------------------------------------------------------
objective = 0.258963
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.85e+01  1.00e-01  8.99e-02

(CVXPY) Jul 07 11:48:28 AM: Problem status: optimal
(CVXPY) Jul 07 11:48:28 AM: Optimal value: 2.932e-01
(CVXPY) Jul 07 11:48:28 AM: Compilation took 1.181e-01 seconds
(CVXPY) Jul 07 11:48:28 AM: Solver (including time spent in interface) took 1.056e+00 seconds
(CVXPY) Jul 07 11:48:28 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:48:28 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:48:28 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:48:28 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:48:28 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:48:28 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:48:28 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:48:28 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:48:28 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:48:28 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:48:28 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:48:28 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:48:29 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:48:29 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:48:29 AM: Applying reduction SCS
(CVXPY) Jul 07 11:48:29 AM: Finished problem compilation (took 1.018e-01 seconds).
(CVXPY) Jul 07 11:48:29 AM: Invoking solver SCS  to obtain a solution.

    50| 1.10e-05  3.00e-08  5.94e-07  2.93e-01  1.00e-01  1.05e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.05e+00s = setup: 5.55e-02s + solve: 9.94e-01s
	 lin-sys: 6.80e-02s, cones: 9.05e-01s, accel: 3.85e-03s
------------------------------------------------------------------
objective = 0.293222
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.85e+01  1.00e-01  8.85e-02

(CVXPY) Jul 07 11:48:30 AM: Problem status: optimal
(CVXPY) Jul 07 11:48:30 AM: Optimal value: 2.498e-01
(CVXPY) Jul 07 11:48:30 AM: Compilation took 1.018e-01 seconds
(CVXPY) Jul 07 11:48:30 AM: Solver (including time spent in interface) took 1.168e+00 seconds
(CVXPY) Jul 07 11:48:30 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:48:30 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:48:30 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:48:30 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:48:30 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:48:30 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:48:30 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:48:30 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:48:30 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:48:30 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:48:30 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:48:30 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:48:30 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:48:30 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:48:30 AM: Applying reduction SCS
(CVXPY) Jul 07 11:48:30 AM: Finished problem compilation (took 8.598e-02 seconds).
(CVXPY) Jul 07 11:48:30 AM: Invoking solver SCS  to obtain a solution.

    50| 1.44e-05  2.71e-08  7.97e-07  2.50e-01  1.00e-01  1.16e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.16e+00s = setup: 4.40e-02s + solve: 1.12e+00s
	 lin-sys: 6.05e-02s, cones: 1.04e+00s, accel: 3.34e-03s
------------------------------------------------------------------
objective = 0.249799
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.86e+01  1.00e-01  8.42e-02

(CVXPY) Jul 07 11:48:31 AM: Problem status: optimal
(CVXPY) Jul 07 11:48:31 AM: Optimal value: 1.769e-01
(CVXPY) Jul 07 11:48:31 AM: Compilation took 8.598e-02 seconds
(CVXPY) Jul 07 11:48:31 AM: Solver (including time spent in interface) took 1.157e+00 seconds
(CVXPY) Jul 07 11:48:31 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:48:31 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:48:31 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:48:31 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:48:31 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:48:31 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:48:31 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:48:31 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:48:31 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:48:31 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:48:31 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:48:31 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:48:31 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:48:31 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:48:31 AM: Applying reduction SCS
(CVXPY) Jul 07 11:48:31 AM: Finished problem compilation (took 9.120e-02 seconds).
(CVXPY) Jul 07 11:48:31 AM: Invoking solver SCS  to obtain a solution.

    50| 1.47e-05  2.11e-08  6.27e-07  1.77e-01  1.00e-01  1.15e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.15e+00s = setup: 4.09e-02s + solve: 1.11e+00s
	 lin-sys: 4.97e-02s, cones: 1.04e+00s, accel: 3.96e-03s
------------------------------------------------------------------
objective = 0.176900
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.85e+01  1.00e-01  1.11e-01

(CVXPY) Jul 07 11:48:34 AM: Problem status: optimal
(CVXPY) Jul 07 11:48:34 AM: Optimal value: 2.819e-01
(CVXPY) Jul 07 11:48:34 AM: Compilation took 9.120e-02 seconds
(CVXPY) Jul 07 11:48:34 AM: Solver (including time spent in interface) took 2.353e+00 seconds
(CVXPY) Jul 07 11:48:34 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:48:34 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:48:34 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:48:34 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:48:34 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:48:34 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:48:34 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:48:34 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:48:34 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:48:34 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:48:34 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:48:34 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:48:34 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:48:34 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:48:34 AM: Applying reduction SCS
(CVXPY) Jul 07 11:48:34 AM: Finished problem compilation (took 7.585e-02 seconds).
(CVXPY) Jul 07 11:48:34 AM: Invoking solver SCS  to obtain a solution.

    75| 2.00e-06  4.29e-10  2.08e-07  2.82e-01  1.00e-01  2.34e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.34e+00s = setup: 6.40e-02s + solve: 2.28e+00s
	 lin-sys: 8.74e-02s, cones: 2.17e+00s, accel: 5.61e-03s
------------------------------------------------------------------
objective = 0.281867
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.85e+01  1.00e-01  8.59e-02

(CVXPY) Jul 07 11:48:36 AM: Problem status: optimal
(CVXPY) Jul 07 11:48:36 AM: Optimal value: 2.479e-01
(CVXPY) Jul 07 11:48:36 AM: Compilation took 7.585e-02 seconds
(CVXPY) Jul 07 11:48:36 AM: Solver (including time spent in interface) took 2.236e+00 seconds
(CVXPY) Jul 07 11:48:36 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:48:36 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:48:36 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:48:36 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:48:36 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:48:36 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:48:36 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:48:36 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:48:36 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:48:36 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:48:36 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:48:36 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:48:36 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:48:36 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:48:36 AM: Applying reduction SCS
(CVXPY) Jul 07 11:48:36 AM: Finished problem compilation (took 1.589e-01 seconds).
(CVXPY) Jul 07 11:48:36 AM: Invoking solver SCS  to obtain a solution.

    75| 3.27e-06  1.42e-09  4.25e-07  2.48e-01  1.00e-01  2.23e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.23e+00s = setup: 4.10e-02s + solve: 2.19e+00s
	 lin-sys: 6.75e-02s, cones: 2.09e+00s, accel: 6.63e-03s
------------------------------------------------------------------
objective = 0.247857
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.86e+01  1.00e-01  8.13e-02

(CVXPY) Jul 07 11:48:38 AM: Problem status: optimal
(CVXPY) Jul 07 11:48:38 AM: Optimal value: 1.723e-01
(CVXPY) Jul 07 11:48:38 AM: Compilation took 1.589e-01 seconds
(CVXPY) Jul 07 11:48:38 AM: Solver (including time spent in interface) took 1.882e+00 seconds
(CVXPY) Jul 07 11:48:38 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:48:38 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:48:38 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:48:38 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:48:38 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:48:38 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:48:38 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:48:38 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:48:38 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:48:38 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:48:38 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:48:38 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:48:38 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:48:38 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:48:38 AM: Applying reduction SCS
(CVXPY) Jul 07 11:48:38 AM: Finished problem compilation (took 7.975e-02 seconds).
(CVXPY) Jul 07 11:48:38 AM: Invoking solver SCS  to obtain a solution.

    75| 3.12e-06  9.14e-10  3.21e-07  1.72e-01  1.00e-01  1.87e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.87e+00s = setup: 4.46e-02s + solve: 1.82e+00s
	 lin-sys: 6.62e-02s, cones: 1.73e+00s, accel: 6.66e-03s
------------------------------------------------------------------
objective = 0.172325
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.85e+01  1.00e-01  7.88e-02

(CVXPY) Jul 07 11:48:39 AM: Problem status: optimal
(CVXPY) Jul 07 11:48:39 AM: Optimal value: 3.026e-01
(CVXPY) Jul 07 11:48:39 AM: Compilation took 7.975e-02 seconds
(CVXPY) Jul 07 11:48:39 AM: Solver (including time spent in interface) took 8.730e-01 seconds
(CVXPY) Jul 07 11:48:39 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:48:39 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:48:39 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:48:39 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:48:39 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:48:39 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:48:39 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:48:39 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:48:39 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:48:39 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:48:39 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:48:39 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:48:39 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:48:39 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:48:39 AM: Applying reduction SCS
(CVXPY) Jul 07 11:48:39 AM: Finished problem compilation (took 8.351e-02 seconds).
(CVXPY) Jul 07 11:48:39 AM: Invoking solver SCS  to obtain a solution.

    50| 1.67e-05  2.28e-08  1.02e-06  3.03e-01  1.00e-01  8.66e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.66e-01s = setup: 4.32e-02s + solve: 8.23e-01s
	 lin-sys: 4.25e-02s, cones: 7.63e-01s, accel: 3.52e-03s
------------------------------------------------------------------
objective = 0.302630
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.86e+01  1.00e-01  7.65e-02

(CVXPY) Jul 07 11:48:41 AM: Problem status: optimal
(CVXPY) Jul 07 11:48:41 AM: Optimal value: 1.840e-01
(CVXPY) Jul 07 11:48:41 AM: Compilation took 8.351e-02 seconds
(CVXPY) Jul 07 11:48:41 AM: Solver (including time spent in interface) took 2.415e+00 seconds
(CVXPY) Jul 07 11:48:41 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:48:41 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:48:41 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:48:41 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:48:41 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:48:41 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:48:41 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:48:41 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:48:41 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:48:41 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:48:41 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:48:41 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:48:41 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:48:41 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:48:42 AM: Applying reduction SCS
(CVXPY) Jul 07 11:48:42 AM: Finished problem compilation (took 8.212e-02 seconds).
(CVXPY) Jul 07 11:48:42 AM: Invoking solver SCS  to obtain a solution.

    75| 3.62e-06  1.80e-09  4.42e-07  1.84e-01  1.00e-01  2.41e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.41e+00s = setup: 4.48e-02s + solve: 2.36e+00s
	 lin-sys: 7.00e-02s, cones: 2.26e+00s, accel: 5.56e-03s
------------------------------------------------------------------
objective = 0.183993
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.86e+01  1.00e-01  8.43e-02

(CVXPY) Jul 07 11:48:43 AM: Problem status: optimal
(CVXPY) Jul 07 11:48:43 AM: Optimal value: 1.764e-01
(CVXPY) Jul 07 11:48:43 AM: Compilation took 8.212e-02 seconds
(CVXPY) Jul 07 11:48:43 AM: Solver (including time spent in interface) took 1.222e+00 seconds
(CVXPY) Jul 07 11:48:43 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:48:43 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:48:43 AM: DCP verification time: 0.0009 seconds.
(CVXPY) Jul 07 11:48:43 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:48:43 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:48:43 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:48:43 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:48:43 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:48:43 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:48:43 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:48:43 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:48:43 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:48:43 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:48:43 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:48:43 AM: Applying reduction SCS
(CVXPY) Jul 07 11:48:43 AM: Finished problem compilation (took 9.212e-02 seconds).
(CVXPY) Jul 07 11:48:43 AM: Invoking solver SCS  to obtain a solution.

    50| 1.97e-05  7.39e-08  8.35e-07  1.76e-01  1.00e-01  1.21e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.21e+00s = setup: 4.20e-02s + solve: 1.17e+00s
	 lin-sys: 4.76e-02s, cones: 1.10e+00s, accel: 3.79e-03s
------------------------------------------------------------------
objective = 0.176415
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.85e+01  1.00e-01  7.59e-02

(CVXPY) Jul 07 11:48:45 AM: Problem status: optimal
(CVXPY) Jul 07 11:48:45 AM: Optimal value: 2.804e-01
(CVXPY) Jul 07 11:48:45 AM: Compilation took 9.212e-02 seconds
(CVXPY) Jul 07 11:48:45 AM: Solver (including time spent in interface) took 1.944e+00 seconds
(CVXPY) Jul 07 11:48:45 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:48:45 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:48:45 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:48:45 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:48:45 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:48:45 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:48:45 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:48:45 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:48:45 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:48:45 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:48:45 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:48:45 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:48:45 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:48:45 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:48:45 AM: Applying reduction SCS
(CVXPY) Jul 07 11:48:45 AM: Finished problem compilation (took 9.007e-02 seconds).
(CVXPY) Jul 07 11:48:45 AM: Invoking solver SCS  to obtain a solution.

    75| 3.62e-06  2.64e-09  3.90e-07  2.80e-01  1.00e-01  1.94e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.94e+00s = setup: 3.83e-02s + solve: 1.90e+00s
	 lin-sys: 8.19e-02s, cones: 1.79e+00s, accel: 6.12e-03s
------------------------------------------------------------------
objective = 0.280420
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.85e+01  1.00e-01  7.12e-02

(CVXPY) Jul 07 11:48:46 AM: Problem status: optimal
(CVXPY) Jul 07 11:48:46 AM: Optimal value: 2.580e-01
(CVXPY) Jul 07 11:48:46 AM: Compilation took 9.007e-02 seconds
(CVXPY) Jul 07 11:48:46 AM: Solver (including time spent in interface) took 8.856e-01 seconds
(CVXPY) Jul 07 11:48:46 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:48:46 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:48:46 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:48:46 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:48:46 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:48:46 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:48:46 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:48:46 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:48:46 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:48:46 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:48:46 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:48:46 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:48:46 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:48:46 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:48:46 AM: Applying reduction SCS
(CVXPY) Jul 07 11:48:46 AM: Finished problem compilation (took 8.933e-02 seconds).
(CVXPY) Jul 07 11:48:46 AM: Invoking solver SCS  to obtain a solution.

    50| 1.60e-05  2.84e-08  8.08e-07  2.58e-01  1.00e-01  8.80e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.80e-01s = setup: 3.58e-02s + solve: 8.45e-01s
	 lin-sys: 4.77e-02s, cones: 7.80e-01s, accel: 3.54e-03s
------------------------------------------------------------------
objective = 0.257990
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.75e+01 -2.86e+01  1.00e-01  8.04e-02

(CVXPY) Jul 07 11:48:47 AM: Problem status: optimal
(CVXPY) Jul 07 11:48:47 AM: Optimal value: 1.708e-01
(CVXPY) Jul 07 11:48:48 AM: Compilation took 8.933e-02 seconds
(CVXPY) Jul 07 11:48:48 AM: Solver (including time spent in interface) took 1.514e+00 seconds
(CVXPY) Jul 07 11:48:48 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:48:48 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:48:48 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:48:48 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:48:48 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:48:48 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:48:48 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:48:48 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:48:48 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:48:48 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:48:48 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:48:48 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:48:48 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:48:48 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:48:48 AM: Applying reduction SCS
(CVXPY) Jul 07 11:48:48 AM: Finished problem compilation (took 8.550e-02 seconds).
(CVXPY) Jul 07 11:48:48 AM: Invoking solver SCS  to obtain a solution.

    75| 2.03e-06  6.54e-10  3.03e-07  1.71e-01  1.00e-01  1.51e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.51e+00s = setup: 4.43e-02s + solve: 1.46e+00s
	 lin-sys: 7.73e-02s, cones: 1.36e+00s, accel: 5.47e-03s
------------------------------------------------------------------
objective = 0.170792
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.85e+01  1.00e-01  8.27e-02

(CVXPY) Jul 07 11:48:50 AM: Problem status: optimal
(CVXPY) Jul 07 11:48:50 AM: Optimal value: 2.683e-01
(CVXPY) Jul 07 11:48:50 AM: Compilation took 8.550e-02 seconds
(CVXPY) Jul 07 11:48:50 AM: Solver (including time spent in interface) took 1.986e+00 seconds
(CVXPY) Jul 07 11:48:50 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:48:50 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:48:50 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:48:50 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:48:50 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:48:50 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:48:50 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:48:50 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:48:50 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:48:50 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:48:50 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:48:50 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:48:50 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:48:50 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:48:50 AM: Applying reduction SCS
(CVXPY) Jul 07 11:48:50 AM: Finished problem compilation (took 7.540e-02 seconds).
(CVXPY) Jul 07 11:48:50 AM: Invoking solver SCS  to obtain a solution.

    75| 3.33e-06  1.10e-09  4.32e-07  2.68e-01  1.00e-01  1.98e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.98e+00s = setup: 4.32e-02s + solve: 1.94e+00s
	 lin-sys: 6.57e-02s, cones: 1.84e+00s, accel: 5.24e-03s
------------------------------------------------------------------
objective = 0.268262
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.85e+01  1.00e-01  7.29e-02

(CVXPY) Jul 07 11:48:51 AM: Problem status: optimal
(CVXPY) Jul 07 11:48:51 AM: Optimal value: 2.599e-01
(CVXPY) Jul 07 11:48:51 AM: Compilation took 7.540e-02 seconds
(CVXPY) Jul 07 11:48:51 AM: Solver (including time spent in interface) took 9.426e-01 seconds
(CVXPY) Jul 07 11:48:51 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:48:51 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:48:51 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:48:51 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:48:51 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:48:51 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:48:51 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:48:51 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:48:51 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:48:51 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:48:51 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:48:51 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:48:51 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:48:51 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:48:51 AM: Applying reduction SCS
(CVXPY) Jul 07 11:48:51 AM: Finished problem compilation (took 7.564e-02 seconds).
(CVXPY) Jul 07 11:48:51 AM: Invoking solver SCS  to obtain a solution.

    50| 1.77e-05  2.59e-08  1.01e-06  2.60e-01  1.00e-01  9.37e-01
------------------------------------------------------------------
status:  solved
timings: total: 9.38e-01s = setup: 3.91e-02s + solve: 8.99e-01s
	 lin-sys: 4.48e-02s, cones: 8.36e-01s, accel: 4.71e-03s
------------------------------------------------------------------
objective = 0.259938
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.86e+01  1.00e-01  7.30e-02

(CVXPY) Jul 07 11:48:52 AM: Problem status: optimal
(CVXPY) Jul 07 11:48:52 AM: Optimal value: 2.058e-01
(CVXPY) Jul 07 11:48:52 AM: Compilation took 7.564e-02 seconds
(CVXPY) Jul 07 11:48:52 AM: Solver (including time spent in interface) took 1.157e+00 seconds
(CVXPY) Jul 07 11:48:52 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:48:52 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:48:52 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:48:52 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:48:52 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:48:52 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:48:52 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:48:52 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:48:52 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:48:52 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:48:52 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:48:52 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:48:52 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:48:52 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:48:52 AM: Applying reduction SCS
(CVXPY) Jul 07 11:48:52 AM: Finished problem compilation (took 1.609e-01 seconds).
(CVXPY) Jul 07 11:48:52 AM: Invoking solver SCS  to obtain a solution.

    50| 1.73e-05  1.62e-08  5.66e-07  2.06e-01  1.00e-01  1.15e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.15e+00s = setup: 3.80e-02s + solve: 1.11e+00s
	 lin-sys: 5.13e-02s, cones: 1.04e+00s, accel: 4.61e-03s
------------------------------------------------------------------
objective = 0.205767
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.85e+01  1.00e-01  7.79e-02

(CVXPY) Jul 07 11:48:54 AM: Problem status: optimal
(CVXPY) Jul 07 11:48:54 AM: Optimal value: 2.785e-01
(CVXPY) Jul 07 11:48:54 AM: Compilation took 1.609e-01 seconds
(CVXPY) Jul 07 11:48:54 AM: Solver (including time spent in interface) took 2.297e+00 seconds
(CVXPY) Jul 07 11:48:54 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:48:54 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:48:54 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:48:54 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:48:54 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:48:54 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:48:54 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:48:54 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:48:54 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:48:54 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:48:54 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:48:54 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:48:54 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:48:54 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:48:55 AM: Applying reduction SCS
(CVXPY) Jul 07 11:48:55 AM: Finished problem compilation (took 8.854e-02 seconds).
(CVXPY) Jul 07 11:48:55 AM: Invoking solver SCS  to obtain a solution.

    75| 3.34e-06  1.21e-09  3.79e-07  2.79e-01  1.00e-01  2.29e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.29e+00s = setup: 4.02e-02s + solve: 2.25e+00s
	 lin-sys: 6.04e-02s, cones: 2.17e+00s, accel: 4.92e-03s
------------------------------------------------------------------
objective = 0.278547
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.85e+01  1.00e-01  7.06e-02

(CVXPY) Jul 07 11:48:56 AM: Problem status: optimal
(CVXPY) Jul 07 11:48:56 AM: Optimal value: 2.658e-01
(CVXPY) Jul 07 11:48:56 AM: Compilation took 8.854e-02 seconds
(CVXPY) Jul 07 11:48:56 AM: Solver (including time spent in interface) took 1.771e+00 seconds
(CVXPY) Jul 07 11:48:56 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:48:56 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:48:56 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:48:56 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:48:56 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:48:56 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:48:56 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:48:56 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:48:56 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:48:56 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:48:56 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:48:56 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:48:56 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:48:56 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:48:56 AM: Applying reduction SCS
(CVXPY) Jul 07 11:48:56 AM: Finished problem compilation (took 7.715e-02 seconds).
(CVXPY) Jul 07 11:48:56 AM: Invoking solver SCS  to obtain a solution.

    75| 3.32e-06  1.34e-09  4.29e-07  2.66e-01  1.00e-01  1.77e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.77e+00s = setup: 4.17e-02s + solve: 1.72e+00s
	 lin-sys: 6.80e-02s, cones: 1.64e+00s, accel: 4.43e-03s
------------------------------------------------------------------
objective = 0.265819
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.86e+01  1.00e-01  7.14e-02

(CVXPY) Jul 07 11:48:57 AM: Problem status: optimal
(CVXPY) Jul 07 11:48:57 AM: Optimal value: 2.252e-01
(CVXPY) Jul 07 11:48:57 AM: Compilation took 7.715e-02 seconds
(CVXPY) Jul 07 11:48:57 AM: Solver (including time spent in interface) took 1.043e+00 seconds
(CVXPY) Jul 07 11:48:57 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:48:58 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:48:58 AM: DCP verification time: 0.0016 seconds.
(CVXPY) Jul 07 11:48:58 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:48:58 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:48:58 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:48:58 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:48:58 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:48:58 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:48:58 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:48:58 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:48:58 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:48:58 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:48:58 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:48:58 AM: Applying reduction SCS
(CVXPY) Jul 07 11:48:58 AM: Finished problem compilation (took 9.942e-02 seconds).
(CVXPY) Jul 07 11:48:58 AM: Invoking solver SCS  to obtain a solution.

    50| 1.19e-05  2.49e-08  5.58e-07  2.25e-01  1.00e-01  1.04e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.04e+00s = setup: 3.96e-02s + solve: 9.97e-01s
	 lin-sys: 5.84e-02s, cones: 9.19e-01s, accel: 4.31e-03s
------------------------------------------------------------------
objective = 0.225217
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  5.96e-02

(CVXPY) Jul 07 11:49:01 AM: Problem status: optimal
(CVXPY) Jul 07 11:49:01 AM: Optimal value: 1.974e-01
(CVXPY) Jul 07 11:49:01 AM: Compilation took 9.942e-02 seconds
(CVXPY) Jul 07 11:49:01 AM: Solver (including time spent in interface) took 3.356e+00 seconds
(CVXPY) Jul 07 11:49:01 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:49:01 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:49:01 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:49:01 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:49:01 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:49:01 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:49:01 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:49:01 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:49:01 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:49:01 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:49:01 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:49:01 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:49:01 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:49:01 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:49:01 AM: Applying reduction SCS
(CVXPY) Jul 07 11:49:01 AM: Finished problem compilation (took 7.512e-02 seconds).
(CVXPY) Jul 07 11:49:01 AM: Invoking solver SCS  to obtain a solution.

    75| 3.62e-06  1.29e-10  2.24e-07  1.97e-01  1.00e-01  3.35e+00
------------------------------------------------------------------
status:  solved
timings: total: 3.35e+00s = setup: 3.68e-02s + solve: 3.32e+00s
	 lin-sys: 7.74e-02s, cones: 3.21e+00s, accel: 4.93e-03s
------------------------------------------------------------------
objective = 0.197383
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  6.68e-02

(CVXPY) Jul 07 11:49:04 AM: Problem status: optimal
(CVXPY) Jul 07 11:49:04 AM: Optimal value: 2.713e-01
(CVXPY) Jul 07 11:49:04 AM: Compilation took 7.512e-02 seconds
(CVXPY) Jul 07 11:49:04 AM: Solver (including time spent in interface) took 2.694e+00 seconds
(CVXPY) Jul 07 11:49:04 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:49:04 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:49:04 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:49:04 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:49:04 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:49:04 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:49:04 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:49:04 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:49:04 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:49:04 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:49:04 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:49:04 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:49:04 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:49:04 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:49:04 AM: Applying reduction SCS
(CVXPY) Jul 07 11:49:04 AM: Finished problem compilation (took 8.122e-02 seconds).
(CVXPY) Jul 07 11:49:04 AM: Invoking solver SCS  to obtain a solution.

    75| 2.20e-06  1.31e-10  1.03e-07  2.71e-01  1.00e-01  2.69e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.69e+00s = setup: 3.63e-02s + solve: 2.65e+00s
	 lin-sys: 7.58e-02s, cones: 2.55e+00s, accel: 4.54e-03s
------------------------------------------------------------------
objective = 0.271319
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  6.74e-02

(CVXPY) Jul 07 11:49:07 AM: Problem status: optimal
(CVXPY) Jul 07 11:49:07 AM: Optimal value: 3.093e-01
(CVXPY) Jul 07 11:49:07 AM: Compilation took 8.122e-02 seconds
(CVXPY) Jul 07 11:49:07 AM: Solver (including time spent in interface) took 2.639e+00 seconds
(CVXPY) Jul 07 11:49:07 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:49:07 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:49:07 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:49:07 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:49:07 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:49:07 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:49:07 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:49:07 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:49:07 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:49:07 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:49:07 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:49:07 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:49:07 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:49:07 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:49:07 AM: Applying reduction SCS
(CVXPY) Jul 07 11:49:07 AM: Finished problem compilation (took 8.660e-02 seconds).
(CVXPY) Jul 07 11:49:07 AM: Invoking solver SCS  to obtain a solution.

    75| 5.12e-06  1.37e-10  3.43e-07  3.09e-01  1.00e-01  2.63e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.63e+00s = setup: 3.46e-02s + solve: 2.60e+00s
	 lin-sys: 8.01e-02s, cones: 2.49e+00s, accel: 6.03e-03s
------------------------------------------------------------------
objective = 0.309265
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  8.87e-02

(CVXPY) Jul 07 11:49:09 AM: Problem status: optimal
(CVXPY) Jul 07 11:49:09 AM: Optimal value: 2.535e-01
(CVXPY) Jul 07 11:49:09 AM: Compilation took 8.660e-02 seconds
(CVXPY) Jul 07 11:49:09 AM: Solver (including time spent in interface) took 2.446e+00 seconds
(CVXPY) Jul 07 11:49:09 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:49:09 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:49:09 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:49:09 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:49:09 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:49:09 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:49:09 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:49:09 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:49:09 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:49:09 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:49:09 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:49:09 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:49:09 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:49:09 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:49:09 AM: Applying reduction SCS
(CVXPY) Jul 07 11:49:09 AM: Finished problem compilation (took 1.649e-01 seconds).
(CVXPY) Jul 07 11:49:09 AM: Invoking solver SCS  to obtain a solution.

    75| 5.19e-06  1.31e-10  3.08e-07  2.54e-01  1.00e-01  2.44e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.44e+00s = setup: 4.62e-02s + solve: 2.39e+00s
	 lin-sys: 6.49e-02s, cones: 2.31e+00s, accel: 4.49e-03s
------------------------------------------------------------------
objective = 0.253541
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  8.08e-02

(CVXPY) Jul 07 11:49:12 AM: Problem status: optimal
(CVXPY) Jul 07 11:49:12 AM: Optimal value: 1.776e-01
(CVXPY) Jul 07 11:49:12 AM: Compilation took 1.649e-01 seconds
(CVXPY) Jul 07 11:49:12 AM: Solver (including time spent in interface) took 2.806e+00 seconds
(CVXPY) Jul 07 11:49:12 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:49:12 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:49:12 AM: DCP verification time: 0.0017 seconds.
(CVXPY) Jul 07 11:49:12 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:49:12 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:49:12 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:49:12 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:49:12 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:49:12 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:49:12 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:49:12 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:49:12 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:49:12 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:49:12 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:49:12 AM: Applying reduction SCS
(CVXPY) Jul 07 11:49:12 AM: Finished problem compilation (took 9.796e-02 seconds).
(CVXPY) Jul 07 11:49:12 AM: Invoking solver SCS  to obtain a solution.

    75| 5.18e-06  1.20e-10  2.98e-07  1.78e-01  1.00e-01  2.80e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.80e+00s = setup: 4.80e-02s + solve: 2.75e+00s
	 lin-sys: 7.66e-02s, cones: 2.65e+00s, accel: 5.92e-03s
------------------------------------------------------------------
objective = 0.177605
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  7.95e-02

(CVXPY) Jul 07 11:49:15 AM: Problem status: optimal
(CVXPY) Jul 07 11:49:15 AM: Optimal value: 2.977e-01
(CVXPY) Jul 07 11:49:15 AM: Compilation took 9.796e-02 seconds
(CVXPY) Jul 07 11:49:15 AM: Solver (including time spent in interface) took 2.817e+00 seconds
(CVXPY) Jul 07 11:49:15 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:49:15 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:49:15 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:49:15 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:49:15 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:49:15 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:49:15 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:49:15 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:49:15 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:49:15 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:49:15 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:49:15 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:49:15 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:49:15 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:49:15 AM: Applying reduction SCS
(CVXPY) Jul 07 11:49:15 AM: Finished problem compilation (took 9.016e-02 seconds).
(CVXPY) Jul 07 11:49:15 AM: Invoking solver SCS  to obtain a solution.

    75| 1.96e-06  1.33e-10  8.87e-08  2.98e-01  1.00e-01  2.81e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.81e+00s = setup: 3.91e-02s + solve: 2.77e+00s
	 lin-sys: 6.78e-02s, cones: 2.67e+00s, accel: 1.12e-02s
------------------------------------------------------------------
objective = 0.297672
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  9.17e-02

(CVXPY) Jul 07 11:49:18 AM: Problem status: optimal
(CVXPY) Jul 07 11:49:18 AM: Optimal value: 2.527e-01
(CVXPY) Jul 07 11:49:18 AM: Compilation took 9.016e-02 seconds
(CVXPY) Jul 07 11:49:18 AM: Solver (including time spent in interface) took 2.835e+00 seconds
(CVXPY) Jul 07 11:49:18 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:49:18 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:49:18 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:49:18 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:49:18 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:49:18 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:49:18 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:49:18 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:49:18 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:49:18 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:49:18 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:49:18 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:49:18 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:49:18 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:49:18 AM: Applying reduction SCS
(CVXPY) Jul 07 11:49:18 AM: Finished problem compilation (took 8.690e-02 seconds).
(CVXPY) Jul 07 11:49:18 AM: Invoking solver SCS  to obtain a solution.

    75| 3.66e-06  1.26e-10  1.95e-07  2.53e-01  1.00e-01  2.83e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.83e+00s = setup: 4.64e-02s + solve: 2.78e+00s
	 lin-sys: 7.19e-02s, cones: 2.68e+00s, accel: 5.84e-03s
------------------------------------------------------------------
objective = 0.252743
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  9.03e-02

(CVXPY) Jul 07 11:49:21 AM: Problem status: optimal
(CVXPY) Jul 07 11:49:21 AM: Optimal value: 1.745e-01
(CVXPY) Jul 07 11:49:21 AM: Compilation took 8.690e-02 seconds
(CVXPY) Jul 07 11:49:21 AM: Solver (including time spent in interface) took 2.686e+00 seconds
(CVXPY) Jul 07 11:49:21 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:49:21 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:49:21 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:49:21 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:49:21 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:49:21 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:49:21 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:49:21 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:49:21 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:49:21 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:49:21 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:49:21 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:49:21 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:49:21 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:49:21 AM: Applying reduction SCS
(CVXPY) Jul 07 11:49:21 AM: Finished problem compilation (took 8.456e-02 seconds).
(CVXPY) Jul 07 11:49:21 AM: Invoking solver SCS  to obtain a solution.

    75| 3.57e-06  1.24e-10  1.56e-07  1.75e-01  1.00e-01  2.68e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.68e+00s = setup: 4.84e-02s + solve: 2.63e+00s
	 lin-sys: 8.29e-02s, cones: 2.52e+00s, accel: 6.54e-03s
------------------------------------------------------------------
objective = 0.174506
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  7.99e-02

(CVXPY) Jul 07 11:49:23 AM: Problem status: optimal
(CVXPY) Jul 07 11:49:23 AM: Optimal value: 3.190e-01
(CVXPY) Jul 07 11:49:23 AM: Compilation took 8.456e-02 seconds
(CVXPY) Jul 07 11:49:23 AM: Solver (including time spent in interface) took 2.312e+00 seconds
(CVXPY) Jul 07 11:49:23 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:49:23 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:49:23 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:49:23 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:49:23 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:49:23 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:49:23 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:49:23 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:49:23 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:49:23 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:49:23 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:49:23 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:49:23 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:49:23 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:49:23 AM: Applying reduction SCS
(CVXPY) Jul 07 11:49:23 AM: Finished problem compilation (took 7.741e-02 seconds).
(CVXPY) Jul 07 11:49:23 AM: Invoking solver SCS  to obtain a solution.

    75| 5.10e-06  1.24e-10  2.69e-07  3.19e-01  1.00e-01  2.31e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.31e+00s = setup: 3.99e-02s + solve: 2.27e+00s
	 lin-sys: 5.93e-02s, cones: 2.19e+00s, accel: 4.25e-03s
------------------------------------------------------------------
objective = 0.319042
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  7.42e-02

(CVXPY) Jul 07 11:49:26 AM: Problem status: optimal
(CVXPY) Jul 07 11:49:26 AM: Optimal value: 1.882e-01
(CVXPY) Jul 07 11:49:26 AM: Compilation took 7.741e-02 seconds
(CVXPY) Jul 07 11:49:26 AM: Solver (including time spent in interface) took 2.577e+00 seconds
(CVXPY) Jul 07 11:49:26 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:49:26 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:49:26 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:49:26 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:49:26 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:49:26 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:49:26 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:49:26 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:49:26 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:49:26 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:49:26 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:49:26 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:49:26 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:49:26 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:49:26 AM: Applying reduction SCS
(CVXPY) Jul 07 11:49:26 AM: Finished problem compilation (took 1.585e-01 seconds).
(CVXPY) Jul 07 11:49:26 AM: Invoking solver SCS  to obtain a solution.

    75| 5.06e-06  1.26e-10  2.44e-07  1.88e-01  1.00e-01  2.57e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.57e+00s = setup: 3.95e-02s + solve: 2.53e+00s
	 lin-sys: 6.28e-02s, cones: 2.45e+00s, accel: 5.74e-03s
------------------------------------------------------------------
objective = 0.188162
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  8.14e-02

(CVXPY) Jul 07 11:49:29 AM: Problem status: optimal
(CVXPY) Jul 07 11:49:29 AM: Optimal value: 1.777e-01
(CVXPY) Jul 07 11:49:29 AM: Compilation took 1.585e-01 seconds
(CVXPY) Jul 07 11:49:29 AM: Solver (including time spent in interface) took 2.640e+00 seconds
(CVXPY) Jul 07 11:49:29 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:49:29 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:49:29 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:49:29 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:49:29 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:49:29 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:49:29 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:49:29 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:49:29 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:49:29 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:49:29 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:49:29 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:49:29 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:49:29 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:49:29 AM: Applying reduction SCS
(CVXPY) Jul 07 11:49:29 AM: Finished problem compilation (took 8.171e-02 seconds).
(CVXPY) Jul 07 11:49:29 AM: Invoking solver SCS  to obtain a solution.

    75| 5.09e-06  1.24e-10  2.40e-07  1.78e-01  1.00e-01  2.63e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.64e+00s = setup: 4.62e-02s + solve: 2.59e+00s
	 lin-sys: 6.65e-02s, cones: 2.50e+00s, accel: 5.19e-03s
------------------------------------------------------------------
objective = 0.177720
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  7.75e-02

(CVXPY) Jul 07 11:49:31 AM: Problem status: optimal
(CVXPY) Jul 07 11:49:31 AM: Optimal value: 2.988e-01
(CVXPY) Jul 07 11:49:31 AM: Compilation took 8.171e-02 seconds
(CVXPY) Jul 07 11:49:31 AM: Solver (including time spent in interface) took 2.589e+00 seconds
(CVXPY) Jul 07 11:49:31 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:49:31 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:49:31 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:49:31 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:49:31 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:49:31 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:49:31 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:49:31 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:49:31 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:49:31 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:49:32 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:49:32 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:49:32 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:49:32 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:49:32 AM: Applying reduction SCS
(CVXPY) Jul 07 11:49:32 AM: Finished problem compilation (took 9.875e-02 seconds).
(CVXPY) Jul 07 11:49:32 AM: Invoking solver SCS  to obtain a solution.

    75| 5.15e-06  1.37e-10  2.38e-07  2.99e-01  1.00e-01  2.58e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.58e+00s = setup: 4.33e-02s + solve: 2.54e+00s
	 lin-sys: 6.58e-02s, cones: 2.45e+00s, accel: 4.83e-03s
------------------------------------------------------------------
objective = 0.298814
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  8.34e-02

(CVXPY) Jul 07 11:49:34 AM: Problem status: optimal
(CVXPY) Jul 07 11:49:34 AM: Optimal value: 2.661e-01
(CVXPY) Jul 07 11:49:34 AM: Compilation took 9.875e-02 seconds
(CVXPY) Jul 07 11:49:34 AM: Solver (including time spent in interface) took 2.709e+00 seconds
(CVXPY) Jul 07 11:49:34 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:49:34 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:49:34 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:49:34 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:49:34 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:49:34 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:49:34 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:49:34 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:49:34 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:49:34 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:49:34 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:49:34 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:49:34 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:49:34 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:49:34 AM: Applying reduction SCS
(CVXPY) Jul 07 11:49:34 AM: Finished problem compilation (took 8.364e-02 seconds).
(CVXPY) Jul 07 11:49:34 AM: Invoking solver SCS  to obtain a solution.

    75| 5.12e-06  1.36e-10  3.14e-07  2.66e-01  1.00e-01  2.70e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.70e+00s = setup: 4.28e-02s + solve: 2.66e+00s
	 lin-sys: 7.66e-02s, cones: 2.56e+00s, accel: 5.73e-03s
------------------------------------------------------------------
objective = 0.266067
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  9.37e-02

(CVXPY) Jul 07 11:49:38 AM: Problem status: optimal
(CVXPY) Jul 07 11:49:38 AM: Optimal value: 1.758e-01
(CVXPY) Jul 07 11:49:38 AM: Compilation took 8.364e-02 seconds
(CVXPY) Jul 07 11:49:38 AM: Solver (including time spent in interface) took 3.231e+00 seconds
(CVXPY) Jul 07 11:49:38 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:49:38 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:49:38 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:49:38 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:49:38 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:49:38 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:49:38 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:49:38 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:49:38 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:49:38 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:49:38 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:49:38 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:49:38 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:49:38 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:49:38 AM: Applying reduction SCS
(CVXPY) Jul 07 11:49:38 AM: Finished problem compilation (took 8.424e-02 seconds).
(CVXPY) Jul 07 11:49:38 AM: Invoking solver SCS  to obtain a solution.

    75| 2.21e-06  1.23e-10  1.38e-07  1.76e-01  1.00e-01  3.22e+00
------------------------------------------------------------------
status:  solved
timings: total: 3.22e+00s = setup: 4.78e-02s + solve: 3.18e+00s
	 lin-sys: 8.04e-02s, cones: 3.07e+00s, accel: 6.04e-03s
------------------------------------------------------------------
objective = 0.175754
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  7.52e-02

(CVXPY) Jul 07 11:49:41 AM: Problem status: optimal
(CVXPY) Jul 07 11:49:41 AM: Optimal value: 2.802e-01
(CVXPY) Jul 07 11:49:41 AM: Compilation took 8.424e-02 seconds
(CVXPY) Jul 07 11:49:41 AM: Solver (including time spent in interface) took 2.992e+00 seconds
(CVXPY) Jul 07 11:49:41 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:49:41 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:49:41 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:49:41 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:49:41 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:49:41 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:49:41 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:49:41 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:49:41 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:49:41 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:49:41 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:49:41 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:49:41 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:49:41 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:49:41 AM: Applying reduction SCS
(CVXPY) Jul 07 11:49:41 AM: Finished problem compilation (took 8.283e-02 seconds).
(CVXPY) Jul 07 11:49:41 AM: Invoking solver SCS  to obtain a solution.

    75| 3.55e-06  1.33e-10  1.89e-07  2.80e-01  1.00e-01  2.99e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.99e+00s = setup: 4.05e-02s + solve: 2.95e+00s
	 lin-sys: 7.39e-02s, cones: 2.85e+00s, accel: 5.06e-03s
------------------------------------------------------------------
objective = 0.280235
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  8.15e-02

(CVXPY) Jul 07 11:49:44 AM: Problem status: optimal
(CVXPY) Jul 07 11:49:44 AM: Optimal value: 2.672e-01
(CVXPY) Jul 07 11:49:44 AM: Compilation took 8.283e-02 seconds
(CVXPY) Jul 07 11:49:44 AM: Solver (including time spent in interface) took 2.733e+00 seconds
(CVXPY) Jul 07 11:49:44 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:49:44 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:49:44 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:49:44 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:49:44 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:49:44 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:49:44 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:49:44 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:49:44 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:49:44 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:49:44 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:49:44 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:49:44 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:49:44 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:49:44 AM: Applying reduction SCS

    75| 5.02e-06  1.25e-10  2.69e-07  2.67e-01  1.00e-01  2.73e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.73e+00s = setup: 4.32e-02s + solve: 2.68e+00s
	 lin-sys: 7.37e-02s, cones: 2.58e+00s, accel: 5.35e-03s
------------------------------------------------------------------
objective = 0.267156
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Jul 07 11:49:44 AM: Finished problem compilation (took 1.596e-01 seconds).
(CVXPY) Jul 07 11:49:44 AM: Invoking solver SCS  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  8.09e-02

(CVXPY) Jul 07 11:49:46 AM: Problem status: optimal
(CVXPY) Jul 07 11:49:46 AM: Optimal value: 2.128e-01
(CVXPY) Jul 07 11:49:46 AM: Compilation took 1.596e-01 seconds
(CVXPY) Jul 07 11:49:46 AM: Solver (including time spent in interface) took 2.250e+00 seconds
(CVXPY) Jul 07 11:49:46 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:49:46 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:49:46 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:49:46 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:49:46 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:49:46 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:49:46 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:49:46 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:49:46 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:49:46 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:49:46 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:49:46 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:49:46 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:49:46 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:49:46 AM: Applying reduction SCS
(CVXPY) Jul 07 11:49:46 AM: Finished problem compilation (took 7.051e-02 seconds).
(CVXPY) Jul 07 11:49:46 AM: Invoking solver SCS  to obtain a solution.

    75| 5.02e-06  1.25e-10  2.76e-07  2.13e-01  1.00e-01  2.24e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.24e+00s = setup: 4.18e-02s + solve: 2.20e+00s
	 lin-sys: 6.09e-02s, cones: 2.12e+00s, accel: 4.76e-03s
------------------------------------------------------------------
objective = 0.212813
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  6.87e-02

(CVXPY) Jul 07 11:49:49 AM: Problem status: optimal
(CVXPY) Jul 07 11:49:49 AM: Optimal value: 2.913e-01
(CVXPY) Jul 07 11:49:49 AM: Compilation took 7.051e-02 seconds
(CVXPY) Jul 07 11:49:49 AM: Solver (including time spent in interface) took 2.589e+00 seconds
(CVXPY) Jul 07 11:49:49 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:49:49 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:49:49 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:49:49 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:49:49 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:49:49 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:49:49 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:49:49 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:49:49 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:49:49 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:49:49 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:49:49 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:49:49 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:49:49 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:49:49 AM: Applying reduction SCS
(CVXPY) Jul 07 11:49:49 AM: Finished problem compilation (took 8.397e-02 seconds).
(CVXPY) Jul 07 11:49:49 AM: Invoking solver SCS  to obtain a solution.

    75| 3.59e-06  1.30e-10  1.68e-07  2.91e-01  1.00e-01  2.58e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.58e+00s = setup: 4.01e-02s + solve: 2.54e+00s
	 lin-sys: 6.69e-02s, cones: 2.45e+00s, accel: 5.46e-03s
------------------------------------------------------------------
objective = 0.291347
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  9.25e-02

(CVXPY) Jul 07 11:49:52 AM: Problem status: optimal
(CVXPY) Jul 07 11:49:52 AM: Optimal value: 2.759e-01
(CVXPY) Jul 07 11:49:52 AM: Compilation took 8.397e-02 seconds
(CVXPY) Jul 07 11:49:52 AM: Solver (including time spent in interface) took 2.669e+00 seconds
(CVXPY) Jul 07 11:49:52 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:49:52 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:49:52 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:49:52 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:49:52 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:49:52 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:49:52 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:49:52 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:49:52 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:49:52 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:49:52 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:49:52 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:49:52 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:49:52 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:49:52 AM: Applying reduction SCS
(CVXPY) Jul 07 11:49:52 AM: Finished problem compilation (took 7.458e-02 seconds).
(CVXPY) Jul 07 11:49:52 AM: Invoking solver SCS  to obtain a solution.

    75| 3.63e-06  1.32e-10  1.93e-07  2.76e-01  1.00e-01  2.66e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.66e+00s = setup: 4.25e-02s + solve: 2.62e+00s
	 lin-sys: 6.96e-02s, cones: 2.52e+00s, accel: 5.44e-03s
------------------------------------------------------------------
objective = 0.275866
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  7.69e-02

(CVXPY) Jul 07 11:49:54 AM: Problem status: optimal
(CVXPY) Jul 07 11:49:54 AM: Optimal value: 2.347e-01
(CVXPY) Jul 07 11:49:54 AM: Compilation took 7.458e-02 seconds
(CVXPY) Jul 07 11:49:54 AM: Solver (including time spent in interface) took 2.661e+00 seconds
(CVXPY) Jul 07 11:49:54 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:49:54 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:49:54 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:49:54 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:49:54 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:49:54 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:49:54 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:49:54 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:49:54 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:49:54 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:49:54 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:49:54 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:49:54 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:49:54 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:49:54 AM: Applying reduction SCS
(CVXPY) Jul 07 11:49:54 AM: Finished problem compilation (took 8.546e-02 seconds).
(CVXPY) Jul 07 11:49:54 AM: Invoking solver SCS  to obtain a solution.

    75| 5.21e-06  1.30e-10  3.29e-07  2.35e-01  1.00e-01  2.65e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.65e+00s = setup: 3.74e-02s + solve: 2.62e+00s
	 lin-sys: 6.84e-02s, cones: 2.52e+00s, accel: 5.56e-03s
------------------------------------------------------------------
objective = 0.234675
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.58e+02  1.00e-01  6.49e-02

(CVXPY) Jul 07 11:49:57 AM: Problem status: optimal
(CVXPY) Jul 07 11:49:57 AM: Optimal value: 1.974e-01
(CVXPY) Jul 07 11:49:57 AM: Compilation took 8.546e-02 seconds
(CVXPY) Jul 07 11:49:57 AM: Solver (including time spent in interface) took 2.797e+00 seconds
(CVXPY) Jul 07 11:49:57 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:49:57 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:49:57 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:49:57 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:49:57 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:49:57 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:49:57 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:49:57 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:49:57 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:49:57 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:49:57 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:49:57 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:49:57 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:49:57 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:49:57 AM: Applying reduction SCS

    75| 3.68e-06  1.29e-10  1.20e-07  1.97e-01  1.00e-01  2.79e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.79e+00s = setup: 4.35e-02s + solve: 2.75e+00s
	 lin-sys: 7.16e-02s, cones: 2.65e+00s, accel: 6.00e-03s
------------------------------------------------------------------
objective = 0.197383
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Jul 07 11:49:57 AM: Finished problem compilation (took 1.511e-01 seconds).
(CVXPY) Jul 07 11:49:57 AM: Invoking solver SCS  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.58e+02  1.00e-01  8.57e-02

(CVXPY) Jul 07 11:50:00 AM: Problem status: optimal
(CVXPY) Jul 07 11:50:00 AM: Optimal value: 2.713e-01
(CVXPY) Jul 07 11:50:00 AM: Compilation took 1.511e-01 seconds
(CVXPY) Jul 07 11:50:00 AM: Solver (including time spent in interface) took 2.724e+00 seconds
(CVXPY) Jul 07 11:50:00 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:50:00 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:50:00 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:50:00 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:50:00 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:50:00 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:50:00 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:50:00 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:50:00 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:50:00 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:50:00 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:50:00 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:50:00 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:50:00 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:50:00 AM: Applying reduction SCS

    75| 2.22e-06  1.31e-10  5.75e-08  2.71e-01  1.00e-01  2.72e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.72e+00s = setup: 4.29e-02s + solve: 2.68e+00s
	 lin-sys: 7.22e-02s, cones: 2.58e+00s, accel: 4.97e-03s
------------------------------------------------------------------
objective = 0.271319
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Jul 07 11:50:00 AM: Finished problem compilation (took 1.761e-01 seconds).
(CVXPY) Jul 07 11:50:00 AM: Invoking solver SCS  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.58e+02  1.00e-01  8.09e-02

(CVXPY) Jul 07 11:50:03 AM: Problem status: optimal
(CVXPY) Jul 07 11:50:03 AM: Optimal value: 3.093e-01
(CVXPY) Jul 07 11:50:03 AM: Compilation took 1.761e-01 seconds
(CVXPY) Jul 07 11:50:03 AM: Solver (including time spent in interface) took 2.698e+00 seconds
(CVXPY) Jul 07 11:50:03 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:50:03 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:50:03 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:50:03 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:50:03 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:50:03 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:50:03 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:50:03 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:50:03 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:50:03 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:50:03 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:50:03 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:50:03 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:50:03 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:50:03 AM: Applying reduction SCS
(CVXPY) Jul 07 11:50:03 AM: Finished problem compilation (took 7.953e-02 seconds).
(CVXPY) Jul 07 11:50:03 AM: Invoking solver SCS  to obtain a solution.

    75| 5.23e-06  1.37e-10  1.82e-07  3.09e-01  1.00e-01  2.69e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.69e+00s = setup: 4.37e-02s + solve: 2.65e+00s
	 lin-sys: 7.26e-02s, cones: 2.54e+00s, accel: 1.29e-02s
------------------------------------------------------------------
objective = 0.309265
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.58e+02  1.00e-01  9.72e-02

(CVXPY) Jul 07 11:50:06 AM: Problem status: optimal
(CVXPY) Jul 07 11:50:06 AM: Optimal value: 2.535e-01
(CVXPY) Jul 07 11:50:06 AM: Compilation took 7.953e-02 seconds
(CVXPY) Jul 07 11:50:06 AM: Solver (including time spent in interface) took 2.722e+00 seconds
(CVXPY) Jul 07 11:50:06 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:50:06 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:50:06 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:50:06 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:50:06 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:50:06 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:50:06 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:50:06 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:50:06 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:50:06 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:50:06 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:50:06 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:50:06 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:50:06 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:50:06 AM: Applying reduction SCS
(CVXPY) Jul 07 11:50:06 AM: Finished problem compilation (took 9.612e-02 seconds).
(CVXPY) Jul 07 11:50:06 AM: Invoking solver SCS  to obtain a solution.

    75| 5.29e-06  1.31e-10  1.63e-07  2.54e-01  1.00e-01  2.72e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.72e+00s = setup: 4.88e-02s + solve: 2.67e+00s
	 lin-sys: 7.73e-02s, cones: 2.56e+00s, accel: 6.25e-03s
------------------------------------------------------------------
objective = 0.253541
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.58e+02  1.00e-01  9.22e-02

(CVXPY) Jul 07 11:50:09 AM: Problem status: optimal
(CVXPY) Jul 07 11:50:09 AM: Optimal value: 1.776e-01
(CVXPY) Jul 07 11:50:09 AM: Compilation took 9.612e-02 seconds
(CVXPY) Jul 07 11:50:09 AM: Solver (including time spent in interface) took 2.742e+00 seconds
(CVXPY) Jul 07 11:50:09 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:50:09 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:50:09 AM: DCP verification time: 0.0010 seconds.
(CVXPY) Jul 07 11:50:09 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:50:09 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:50:09 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:50:09 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:50:09 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:50:09 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:50:09 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:50:09 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:50:09 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:50:09 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:50:09 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:50:09 AM: Applying reduction SCS
(CVXPY) Jul 07 11:50:09 AM: Finished problem compilation (took 9.582e-02 seconds).
(CVXPY) Jul 07 11:50:09 AM: Invoking solver SCS  to obtain a solution.

    75| 5.28e-06  1.20e-10  1.57e-07  1.78e-01  1.00e-01  2.73e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.73e+00s = setup: 5.10e-02s + solve: 2.68e+00s
	 lin-sys: 7.89e-02s, cones: 2.58e+00s, accel: 5.23e-03s
------------------------------------------------------------------
objective = 0.177605
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.58e+02  1.00e-01  1.11e-01

(CVXPY) Jul 07 11:50:12 AM: Problem status: optimal
(CVXPY) Jul 07 11:50:12 AM: Optimal value: 2.977e-01
(CVXPY) Jul 07 11:50:12 AM: Compilation took 9.582e-02 seconds
(CVXPY) Jul 07 11:50:12 AM: Solver (including time spent in interface) took 3.062e+00 seconds
(CVXPY) Jul 07 11:50:12 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:50:12 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:50:12 AM: DCP verification time: 0.0014 seconds.
(CVXPY) Jul 07 11:50:12 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:50:12 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:50:12 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:50:12 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:50:12 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:50:12 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:50:12 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:50:12 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:50:12 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:50:12 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:50:12 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:50:12 AM: Applying reduction SCS

    75| 1.98e-06  1.33e-10  5.03e-08  2.98e-01  1.00e-01  3.05e+00
------------------------------------------------------------------
status:  solved
timings: total: 3.05e+00s = setup: 5.36e-02s + solve: 3.00e+00s
	 lin-sys: 7.20e-02s, cones: 2.90e+00s, accel: 5.24e-03s
------------------------------------------------------------------
objective = 0.297672
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------

(CVXPY) Jul 07 11:50:12 AM: Finished problem compilation (took 1.643e-01 seconds).
(CVXPY) Jul 07 11:50:12 AM: Invoking solver SCS  to obtain a solution.

-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.58e+02  1.00e-01  9.72e-02

(CVXPY) Jul 07 11:50:15 AM: Problem status: optimal
(CVXPY) Jul 07 11:50:15 AM: Optimal value: 2.527e-01
(CVXPY) Jul 07 11:50:15 AM: Compilation took 1.643e-01 seconds
(CVXPY) Jul 07 11:50:15 AM: Solver (including time spent in interface) took 2.566e+00 seconds
(CVXPY) Jul 07 11:50:15 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:50:15 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:50:15 AM: DCP verification time: 0.0014 seconds.
(CVXPY) Jul 07 11:50:15 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:50:15 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:50:15 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:50:15 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:50:15 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:50:15 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:50:15 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:50:15 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:50:15 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:50:15 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:50:15 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:50:15 AM: Applying reduction SCS
(CVXPY) Jul 07 11:50:15 AM: Finished problem compilation (took 7.142e-02 seconds).
(CVXPY) Jul 07 11:50:15 AM: Invoking solver SCS  to obtain a solution.

    75| 3.71e-06  1.26e-10  1.04e-07  2.53e-01  1.00e-01  2.56e+00
------------------------------------------------------------------
status:  solved
timings: total: 2.56e+00s = setup: 5.21e-02s + solve: 2.51e+00s
	 lin-sys: 7.87e-02s, cones: 2.41e+00s, accel: 5.13e-03s
------------------------------------------------------------------
objective = 0.252743
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.58e+02  1.00e-01  4.65e-02

(CVXPY) Jul 07 11:50:17 AM: Problem status: optimal
(CVXPY) Jul 07 11:50:17 AM: Optimal value: 1.745e-01
(CVXPY) Jul 07 11:50:17 AM: Compilation took 7.142e-02 seconds
(CVXPY) Jul 07 11:50:17 AM: Solver (including time spent in interface) took 1.882e+00 seconds
(CVXPY) Jul 07 11:50:17 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:50:17 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:50:17 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:50:17 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:50:17 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:50:17 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:50:17 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:50:17 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:50:17 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:50:17 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:50:17 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:50:17 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:50:17 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:50:17 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:50:17 AM: Applying reduction SCS
(CVXPY) Jul 07 11:50:17 AM: Finished problem compilation (took 5.805e-02 seconds).
(CVXPY) Jul 07 11:50:17 AM: Invoking solver SCS  to obtain a solution.

    75| 3.61e-06  1.24e-10  8.43e-08  1.75e-01  1.00e-01  1.88e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.88e+00s = setup: 2.39e-02s + solve: 1.85e+00s
	 lin-sys: 5.10e-02s, cones: 1.78e+00s, accel: 5.12e-03s
------------------------------------------------------------------
objective = 0.174506
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.58e+02  1.00e-01  5.15e-02

(CVXPY) Jul 07 11:50:18 AM: Problem status: optimal
(CVXPY) Jul 07 11:50:18 AM: Optimal value: 3.190e-01
(CVXPY) Jul 07 11:50:18 AM: Compilation took 5.805e-02 seconds
(CVXPY) Jul 07 11:50:18 AM: Solver (including time spent in interface) took 1.674e+00 seconds
(CVXPY) Jul 07 11:50:19 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:50:19 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:50:19 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:50:19 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:50:19 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:50:19 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:50:19 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:50:19 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:50:19 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:50:19 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:50:19 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:50:19 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:50:19 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:50:19 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:50:19 AM: Applying reduction SCS
(CVXPY) Jul 07 11:50:19 AM: Finished problem compilation (took 5.171e-02 seconds).
(CVXPY) Jul 07 11:50:19 AM: Invoking solver SCS  to obtain a solution.

    75| 5.19e-06  1.24e-10  1.43e-07  3.19e-01  1.00e-01  1.67e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.67e+00s = setup: 2.63e-02s + solve: 1.64e+00s
	 lin-sys: 5.16e-02s, cones: 1.57e+00s, accel: 5.37e-03s
------------------------------------------------------------------
objective = 0.319043
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.58e+02  1.00e-01  4.00e-02

(CVXPY) Jul 07 11:50:20 AM: Problem status: optimal
(CVXPY) Jul 07 11:50:20 AM: Optimal value: 1.882e-01
(CVXPY) Jul 07 11:50:20 AM: Compilation took 5.171e-02 seconds
(CVXPY) Jul 07 11:50:20 AM: Solver (including time spent in interface) took 1.848e+00 seconds
(CVXPY) Jul 07 11:50:20 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:50:20 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:50:20 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:50:20 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:50:20 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:50:20 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:50:20 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:50:20 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:50:20 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:50:20 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:50:20 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:50:20 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:50:20 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:50:20 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:50:20 AM: Applying reduction SCS
(CVXPY) Jul 07 11:50:20 AM: Finished problem compilation (took 5.269e-02 seconds).
(CVXPY) Jul 07 11:50:20 AM: Invoking solver SCS  to obtain a solution.

    75| 5.15e-06  1.26e-10  1.30e-07  1.88e-01  1.00e-01  1.84e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.84e+00s = setup: 2.51e-02s + solve: 1.82e+00s
	 lin-sys: 4.62e-02s, cones: 1.75e+00s, accel: 4.54e-03s
------------------------------------------------------------------
objective = 0.188162
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.58e+02  1.00e-01  4.81e-02

(CVXPY) Jul 07 11:50:22 AM: Problem status: optimal
(CVXPY) Jul 07 11:50:22 AM: Optimal value: 1.777e-01
(CVXPY) Jul 07 11:50:22 AM: Compilation took 5.269e-02 seconds
(CVXPY) Jul 07 11:50:22 AM: Solver (including time spent in interface) took 1.698e+00 seconds
(CVXPY) Jul 07 11:50:22 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:50:22 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:50:22 AM: DCP verification time: 0.0010 seconds.
(CVXPY) Jul 07 11:50:22 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:50:22 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:50:22 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:50:22 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:50:22 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:50:22 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:50:22 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:50:22 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:50:22 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:50:22 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:50:22 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:50:22 AM: Applying reduction SCS
(CVXPY) Jul 07 11:50:22 AM: Finished problem compilation (took 5.123e-02 seconds).
(CVXPY) Jul 07 11:50:22 AM: Invoking solver SCS  to obtain a solution.

    75| 5.18e-06  1.24e-10  1.27e-07  1.78e-01  1.00e-01  1.69e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.69e+00s = setup: 2.41e-02s + solve: 1.67e+00s
	 lin-sys: 4.73e-02s, cones: 1.60e+00s, accel: 4.63e-03s
------------------------------------------------------------------
objective = 0.177721
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.58e+02  1.00e-01  4.92e-02

(CVXPY) Jul 07 11:50:24 AM: Problem status: optimal
(CVXPY) Jul 07 11:50:24 AM: Optimal value: 2.988e-01
(CVXPY) Jul 07 11:50:24 AM: Compilation took 5.123e-02 seconds
(CVXPY) Jul 07 11:50:24 AM: Solver (including time spent in interface) took 1.844e+00 seconds
(CVXPY) Jul 07 11:50:24 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:50:24 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:50:24 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:50:24 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:50:24 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:50:24 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:50:24 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:50:24 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:50:24 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:50:24 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:50:24 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:50:24 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:50:24 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:50:24 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:50:24 AM: Applying reduction SCS
(CVXPY) Jul 07 11:50:24 AM: Finished problem compilation (took 4.933e-02 seconds).
(CVXPY) Jul 07 11:50:24 AM: Invoking solver SCS  to obtain a solution.

    75| 5.24e-06  1.37e-10  1.27e-07  2.99e-01  1.00e-01  1.84e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.84e+00s = setup: 2.52e-02s + solve: 1.81e+00s
	 lin-sys: 5.42e-02s, cones: 1.74e+00s, accel: 5.43e-03s
------------------------------------------------------------------
objective = 0.298814
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.58e+02  1.00e-01  4.82e-02

(CVXPY) Jul 07 11:50:26 AM: Problem status: optimal
(CVXPY) Jul 07 11:50:26 AM: Optimal value: 2.661e-01
(CVXPY) Jul 07 11:50:26 AM: Compilation took 4.933e-02 seconds
(CVXPY) Jul 07 11:50:26 AM: Solver (including time spent in interface) took 1.636e+00 seconds
(CVXPY) Jul 07 11:50:26 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:50:26 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:50:26 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:50:26 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:50:26 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:50:26 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:50:26 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:50:26 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:50:26 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:50:26 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:50:26 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:50:26 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:50:26 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:50:26 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:50:26 AM: Applying reduction SCS
(CVXPY) Jul 07 11:50:26 AM: Finished problem compilation (took 4.920e-02 seconds).
(CVXPY) Jul 07 11:50:26 AM: Invoking solver SCS  to obtain a solution.

    75| 5.22e-06  1.36e-10  1.66e-07  2.66e-01  1.00e-01  1.63e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.63e+00s = setup: 2.46e-02s + solve: 1.61e+00s
	 lin-sys: 4.72e-02s, cones: 1.54e+00s, accel: 5.34e-03s
------------------------------------------------------------------
objective = 0.266067
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.58e+02  1.00e-01  4.62e-02

(CVXPY) Jul 07 11:50:28 AM: Problem status: optimal
(CVXPY) Jul 07 11:50:28 AM: Optimal value: 1.758e-01
(CVXPY) Jul 07 11:50:28 AM: Compilation took 4.920e-02 seconds
(CVXPY) Jul 07 11:50:28 AM: Solver (including time spent in interface) took 1.840e+00 seconds
(CVXPY) Jul 07 11:50:28 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:50:28 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:50:28 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:50:28 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:50:28 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:50:28 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:50:28 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:50:28 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:50:28 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:50:28 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:50:28 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:50:28 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:50:28 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:50:28 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:50:28 AM: Applying reduction SCS
(CVXPY) Jul 07 11:50:28 AM: Finished problem compilation (took 7.511e-02 seconds).
(CVXPY) Jul 07 11:50:28 AM: Invoking solver SCS  to obtain a solution.

    75| 2.23e-06  1.23e-10  7.54e-08  1.76e-01  1.00e-01  1.84e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.84e+00s = setup: 2.19e-02s + solve: 1.81e+00s
	 lin-sys: 5.34e-02s, cones: 1.74e+00s, accel: 4.66e-03s
------------------------------------------------------------------
objective = 0.175754
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.58e+02  1.00e-01  4.68e-02

(CVXPY) Jul 07 11:50:30 AM: Problem status: optimal
(CVXPY) Jul 07 11:50:30 AM: Optimal value: 2.802e-01
(CVXPY) Jul 07 11:50:30 AM: Compilation took 7.511e-02 seconds
(CVXPY) Jul 07 11:50:30 AM: Solver (including time spent in interface) took 1.853e+00 seconds
(CVXPY) Jul 07 11:50:30 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:50:30 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:50:30 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:50:30 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:50:30 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:50:30 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:50:30 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:50:30 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:50:30 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:50:30 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:50:30 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:50:30 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:50:30 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:50:30 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:50:30 AM: Applying reduction SCS
(CVXPY) Jul 07 11:50:30 AM: Finished problem compilation (took 5.090e-02 seconds).
(CVXPY) Jul 07 11:50:30 AM: Invoking solver SCS  to obtain a solution.

    75| 3.61e-06  1.33e-10  1.02e-07  2.80e-01  1.00e-01  1.85e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.85e+00s = setup: 3.29e-02s + solve: 1.81e+00s
	 lin-sys: 4.74e-02s, cones: 1.75e+00s, accel: 4.76e-03s
------------------------------------------------------------------
objective = 0.280235
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.58e+02  1.00e-01  4.85e-02

(CVXPY) Jul 07 11:50:31 AM: Problem status: optimal
(CVXPY) Jul 07 11:50:31 AM: Optimal value: 2.672e-01
(CVXPY) Jul 07 11:50:31 AM: Compilation took 5.090e-02 seconds
(CVXPY) Jul 07 11:50:31 AM: Solver (including time spent in interface) took 1.718e+00 seconds
(CVXPY) Jul 07 11:50:31 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:50:31 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:50:31 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:50:31 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:50:31 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:50:31 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:50:32 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:50:32 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:50:32 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:50:32 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:50:32 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:50:32 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:50:32 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:50:32 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:50:32 AM: Applying reduction SCS
(CVXPY) Jul 07 11:50:32 AM: Finished problem compilation (took 5.802e-02 seconds).
(CVXPY) Jul 07 11:50:32 AM: Invoking solver SCS  to obtain a solution.

    75| 5.12e-06  1.25e-10  1.43e-07  2.67e-01  1.00e-01  1.71e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.71e+00s = setup: 2.77e-02s + solve: 1.69e+00s
	 lin-sys: 4.75e-02s, cones: 1.61e+00s, accel: 6.34e-03s
------------------------------------------------------------------
objective = 0.267156
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.58e+02  1.00e-01  4.60e-02

(CVXPY) Jul 07 11:50:33 AM: Problem status: optimal
(CVXPY) Jul 07 11:50:33 AM: Optimal value: 2.128e-01
(CVXPY) Jul 07 11:50:33 AM: Compilation took 5.802e-02 seconds
(CVXPY) Jul 07 11:50:33 AM: Solver (including time spent in interface) took 1.715e+00 seconds
(CVXPY) Jul 07 11:50:33 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:50:33 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:50:33 AM: DCP verification time: 0.0003 seconds.
(CVXPY) Jul 07 11:50:33 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:50:33 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:50:33 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:50:33 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:50:33 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:50:33 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:50:33 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:50:33 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:50:33 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:50:33 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:50:33 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:50:33 AM: Applying reduction SCS
(CVXPY) Jul 07 11:50:33 AM: Finished problem compilation (took 5.264e-02 seconds).
(CVXPY) Jul 07 11:50:33 AM: Invoking solver SCS  to obtain a solution.

    75| 5.12e-06  1.25e-10  1.46e-07  2.13e-01  1.00e-01  1.71e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.71e+00s = setup: 2.43e-02s + solve: 1.69e+00s
	 lin-sys: 5.12e-02s, cones: 1.61e+00s, accel: 5.13e-03s
------------------------------------------------------------------
objective = 0.212813
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.58e+02  1.00e-01  5.13e-02

(CVXPY) Jul 07 11:50:35 AM: Problem status: optimal
(CVXPY) Jul 07 11:50:35 AM: Optimal value: 2.913e-01
(CVXPY) Jul 07 11:50:35 AM: Compilation took 5.264e-02 seconds
(CVXPY) Jul 07 11:50:35 AM: Solver (including time spent in interface) took 1.717e+00 seconds
(CVXPY) Jul 07 11:50:35 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:50:35 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:50:35 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:50:35 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:50:35 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:50:35 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:50:35 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:50:35 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:50:35 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:50:35 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:50:35 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:50:35 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:50:35 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:50:35 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:50:35 AM: Applying reduction SCS
(CVXPY) Jul 07 11:50:35 AM: Finished problem compilation (took 5.620e-02 seconds).
(CVXPY) Jul 07 11:50:35 AM: Invoking solver SCS  to obtain a solution.

    75| 3.64e-06  1.30e-10  9.11e-08  2.91e-01  1.00e-01  1.71e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.71e+00s = setup: 2.39e-02s + solve: 1.69e+00s
	 lin-sys: 5.51e-02s, cones: 1.60e+00s, accel: 5.55e-03s
------------------------------------------------------------------
objective = 0.291347
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.58e+02  1.00e-01  5.13e-02

(CVXPY) Jul 07 11:50:37 AM: Problem status: optimal
(CVXPY) Jul 07 11:50:37 AM: Optimal value: 2.759e-01
(CVXPY) Jul 07 11:50:37 AM: Compilation took 5.620e-02 seconds
(CVXPY) Jul 07 11:50:37 AM: Solver (including time spent in interface) took 1.695e+00 seconds
(CVXPY) Jul 07 11:50:37 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:50:37 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:50:37 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:50:37 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:50:37 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:50:37 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:50:37 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:50:37 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:50:37 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:50:37 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:50:37 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:50:37 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:50:37 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:50:37 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:50:37 AM: Applying reduction SCS
(CVXPY) Jul 07 11:50:37 AM: Finished problem compilation (took 4.940e-02 seconds).
(CVXPY) Jul 07 11:50:37 AM: Invoking solver SCS  to obtain a solution.

    75| 3.68e-06  1.32e-10  1.04e-07  2.76e-01  1.00e-01  1.69e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.69e+00s = setup: 2.45e-02s + solve: 1.67e+00s
	 lin-sys: 6.11e-02s, cones: 1.59e+00s, accel: 5.21e-03s
------------------------------------------------------------------
objective = 0.275866
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.06e+01  3.75e-01  5.17e+02 -2.58e+02  1.00e-01  4.89e-02

(CVXPY) Jul 07 11:50:39 AM: Problem status: optimal
(CVXPY) Jul 07 11:50:39 AM: Optimal value: 2.347e-01
(CVXPY) Jul 07 11:50:39 AM: Compilation took 4.940e-02 seconds
(CVXPY) Jul 07 11:50:39 AM: Solver (including time spent in interface) took 1.665e+00 seconds
(CVXPY) Jul 07 11:50:39 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:50:39 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:50:39 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:50:39 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:50:39 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:50:39 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:50:39 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:50:39 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:50:39 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:50:39 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:50:39 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:50:39 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:50:39 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:50:39 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:50:39 AM: Applying reduction SCS
(CVXPY) Jul 07 11:50:39 AM: Finished problem compilation (took 4.835e-02 seconds).
(CVXPY) Jul 07 11:50:39 AM: Invoking solver SCS  to obtain a solution.

    75| 5.32e-06  1.30e-10  1.74e-07  2.35e-01  1.00e-01  1.66e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.66e+00s = setup: 2.52e-02s + solve: 1.63e+00s
	 lin-sys: 4.96e-02s, cones: 1.56e+00s, accel: 7.00e-03s
------------------------------------------------------------------
objective = 0.234675
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.59e+02  1.00e-01  3.98e-02

(CVXPY) Jul 07 11:50:40 AM: Problem status: optimal
(CVXPY) Jul 07 11:50:40 AM: Optimal value: 1.974e-01
(CVXPY) Jul 07 11:50:40 AM: Compilation took 4.835e-02 seconds
(CVXPY) Jul 07 11:50:40 AM: Solver (including time spent in interface) took 1.829e+00 seconds
(CVXPY) Jul 07 11:50:41 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:50:41 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:50:41 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:50:41 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:50:41 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:50:41 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:50:41 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:50:41 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:50:41 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:50:41 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:50:41 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:50:41 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:50:41 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:50:41 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:50:41 AM: Applying reduction SCS
(CVXPY) Jul 07 11:50:41 AM: Finished problem compilation (took 5.643e-02 seconds).
(CVXPY) Jul 07 11:50:41 AM: Invoking solver SCS  to obtain a solution.

    75| 3.71e-06  1.29e-10  6.71e-08  1.97e-01  1.00e-01  1.82e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.82e+00s = setup: 2.52e-02s + solve: 1.80e+00s
	 lin-sys: 4.83e-02s, cones: 1.73e+00s, accel: 4.76e-03s
------------------------------------------------------------------
objective = 0.197383
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.59e+02  1.00e-01  5.02e-02

(CVXPY) Jul 07 11:50:42 AM: Problem status: optimal
(CVXPY) Jul 07 11:50:42 AM: Optimal value: 2.713e-01
(CVXPY) Jul 07 11:50:42 AM: Compilation took 5.643e-02 seconds
(CVXPY) Jul 07 11:50:42 AM: Solver (including time spent in interface) took 1.730e+00 seconds
(CVXPY) Jul 07 11:50:42 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:50:42 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:50:42 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:50:42 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:50:42 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:50:42 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:50:42 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:50:42 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:50:42 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:50:42 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:50:42 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:50:42 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:50:42 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:50:42 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:50:42 AM: Applying reduction SCS
(CVXPY) Jul 07 11:50:42 AM: Finished problem compilation (took 5.727e-02 seconds).
(CVXPY) Jul 07 11:50:42 AM: Invoking solver SCS  to obtain a solution.

    75| 2.23e-06  1.31e-10  3.01e-08  2.71e-01  1.00e-01  1.72e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.72e+00s = setup: 2.57e-02s + solve: 1.70e+00s
	 lin-sys: 4.76e-02s, cones: 1.63e+00s, accel: 4.89e-03s
------------------------------------------------------------------
objective = 0.271319
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.59e+02  1.00e-01  4.98e-02

(CVXPY) Jul 07 11:50:44 AM: Problem status: optimal
(CVXPY) Jul 07 11:50:44 AM: Optimal value: 3.093e-01
(CVXPY) Jul 07 11:50:44 AM: Compilation took 5.727e-02 seconds
(CVXPY) Jul 07 11:50:44 AM: Solver (including time spent in interface) took 1.706e+00 seconds
(CVXPY) Jul 07 11:50:44 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:50:44 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:50:44 AM: DCP verification time: 0.0003 seconds.
(CVXPY) Jul 07 11:50:44 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:50:44 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:50:44 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:50:44 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:50:44 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:50:44 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:50:44 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:50:44 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:50:44 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:50:44 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:50:44 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:50:44 AM: Applying reduction SCS
(CVXPY) Jul 07 11:50:44 AM: Finished problem compilation (took 5.257e-02 seconds).
(CVXPY) Jul 07 11:50:44 AM: Invoking solver SCS  to obtain a solution.

    75| 5.28e-06  1.37e-10  1.04e-07  3.09e-01  1.00e-01  1.70e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.70e+00s = setup: 2.60e-02s + solve: 1.68e+00s
	 lin-sys: 5.19e-02s, cones: 1.60e+00s, accel: 5.84e-03s
------------------------------------------------------------------
objective = 0.309265
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.59e+02  1.00e-01  4.93e-02

(CVXPY) Jul 07 11:50:46 AM: Problem status: optimal
(CVXPY) Jul 07 11:50:46 AM: Optimal value: 2.535e-01
(CVXPY) Jul 07 11:50:46 AM: Compilation took 5.257e-02 seconds
(CVXPY) Jul 07 11:50:46 AM: Solver (including time spent in interface) took 1.700e+00 seconds
(CVXPY) Jul 07 11:50:46 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:50:46 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:50:46 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:50:46 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:50:46 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:50:46 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:50:46 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:50:46 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:50:46 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:50:46 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:50:46 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:50:46 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:50:46 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:50:46 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:50:46 AM: Applying reduction SCS
(CVXPY) Jul 07 11:50:46 AM: Finished problem compilation (took 5.139e-02 seconds).
(CVXPY) Jul 07 11:50:46 AM: Invoking solver SCS  to obtain a solution.

    75| 5.33e-06  1.31e-10  9.29e-08  2.54e-01  1.00e-01  1.70e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.70e+00s = setup: 2.42e-02s + solve: 1.67e+00s
	 lin-sys: 4.85e-02s, cones: 1.60e+00s, accel: 7.17e-03s
------------------------------------------------------------------
objective = 0.253541
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.59e+02  1.00e-01  4.74e-02

(CVXPY) Jul 07 11:50:48 AM: Problem status: optimal
(CVXPY) Jul 07 11:50:48 AM: Optimal value: 1.776e-01
(CVXPY) Jul 07 11:50:48 AM: Compilation took 5.139e-02 seconds
(CVXPY) Jul 07 11:50:48 AM: Solver (including time spent in interface) took 1.649e+00 seconds
(CVXPY) Jul 07 11:50:48 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:50:48 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:50:48 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:50:48 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:50:48 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:50:48 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:50:48 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:50:48 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:50:48 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:50:48 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:50:48 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:50:48 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:50:48 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:50:48 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:50:48 AM: Applying reduction SCS
(CVXPY) Jul 07 11:50:48 AM: Finished problem compilation (took 4.650e-02 seconds).
(CVXPY) Jul 07 11:50:48 AM: Invoking solver SCS  to obtain a solution.

    75| 5.32e-06  1.20e-10  8.94e-08  1.78e-01  1.00e-01  1.64e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.64e+00s = setup: 2.41e-02s + solve: 1.62e+00s
	 lin-sys: 5.01e-02s, cones: 1.55e+00s, accel: 1.06e-02s
------------------------------------------------------------------
objective = 0.177605
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.59e+02  1.00e-01  3.95e-02

(CVXPY) Jul 07 11:50:49 AM: Problem status: optimal
(CVXPY) Jul 07 11:50:49 AM: Optimal value: 2.977e-01
(CVXPY) Jul 07 11:50:49 AM: Compilation took 4.650e-02 seconds
(CVXPY) Jul 07 11:50:49 AM: Solver (including time spent in interface) took 1.772e+00 seconds
(CVXPY) Jul 07 11:50:49 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:50:49 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:50:49 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:50:49 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:50:49 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:50:49 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:50:49 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:50:49 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:50:49 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:50:49 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:50:49 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:50:49 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:50:49 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:50:49 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:50:49 AM: Applying reduction SCS
(CVXPY) Jul 07 11:50:50 AM: Finished problem compilation (took 4.755e-02 seconds).
(CVXPY) Jul 07 11:50:50 AM: Invoking solver SCS  to obtain a solution.

    75| 1.98e-06  1.33e-10  2.59e-08  2.98e-01  1.00e-01  1.77e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.77e+00s = setup: 2.51e-02s + solve: 1.74e+00s
	 lin-sys: 4.51e-02s, cones: 1.68e+00s, accel: 6.03e-03s
------------------------------------------------------------------
objective = 0.297672
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.59e+02  1.00e-01  4.82e-02

(CVXPY) Jul 07 11:50:51 AM: Problem status: optimal
(CVXPY) Jul 07 11:50:51 AM: Optimal value: 2.527e-01
(CVXPY) Jul 07 11:50:51 AM: Compilation took 4.755e-02 seconds
(CVXPY) Jul 07 11:50:51 AM: Solver (including time spent in interface) took 1.644e+00 seconds
(CVXPY) Jul 07 11:50:51 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:50:51 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:50:51 AM: DCP verification time: 0.0003 seconds.
(CVXPY) Jul 07 11:50:51 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:50:51 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:50:51 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:50:51 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:50:51 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:50:51 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:50:51 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:50:51 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:50:51 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:50:51 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:50:51 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:50:51 AM: Applying reduction SCS
(CVXPY) Jul 07 11:50:51 AM: Finished problem compilation (took 4.660e-02 seconds).
(CVXPY) Jul 07 11:50:51 AM: Invoking solver SCS  to obtain a solution.

    75| 3.74e-06  1.26e-10  5.80e-08  2.53e-01  1.00e-01  1.64e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.64e+00s = setup: 2.46e-02s + solve: 1.61e+00s
	 lin-sys: 4.70e-02s, cones: 1.55e+00s, accel: 5.04e-03s
------------------------------------------------------------------
objective = 0.252743
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.59e+02  1.00e-01  4.98e-02

(CVXPY) Jul 07 11:50:53 AM: Problem status: optimal
(CVXPY) Jul 07 11:50:53 AM: Optimal value: 1.745e-01
(CVXPY) Jul 07 11:50:53 AM: Compilation took 4.660e-02 seconds
(CVXPY) Jul 07 11:50:53 AM: Solver (including time spent in interface) took 1.667e+00 seconds
(CVXPY) Jul 07 11:50:53 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:50:53 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:50:53 AM: DCP verification time: 0.0003 seconds.
(CVXPY) Jul 07 11:50:53 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:50:53 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:50:53 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:50:53 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:50:53 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:50:53 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:50:53 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:50:53 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:50:53 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:50:53 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:50:53 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:50:53 AM: Applying reduction SCS
(CVXPY) Jul 07 11:50:53 AM: Finished problem compilation (took 5.156e-02 seconds).
(CVXPY) Jul 07 11:50:53 AM: Invoking solver SCS  to obtain a solution.

    75| 3.63e-06  1.24e-10  4.60e-08  1.75e-01  1.00e-01  1.66e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.66e+00s = setup: 2.24e-02s + solve: 1.64e+00s
	 lin-sys: 5.13e-02s, cones: 1.56e+00s, accel: 5.43e-03s
------------------------------------------------------------------
objective = 0.174506
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.59e+02  1.00e-01  4.83e-02

(CVXPY) Jul 07 11:50:55 AM: Problem status: optimal
(CVXPY) Jul 07 11:50:55 AM: Optimal value: 3.190e-01
(CVXPY) Jul 07 11:50:55 AM: Compilation took 5.156e-02 seconds
(CVXPY) Jul 07 11:50:55 AM: Solver (including time spent in interface) took 1.658e+00 seconds
(CVXPY) Jul 07 11:50:55 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:50:55 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:50:55 AM: DCP verification time: 0.0009 seconds.
(CVXPY) Jul 07 11:50:55 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:50:55 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:50:55 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:50:55 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:50:55 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:50:55 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:50:55 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:50:55 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:50:55 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:50:55 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:50:55 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:50:55 AM: Applying reduction SCS
(CVXPY) Jul 07 11:50:55 AM: Finished problem compilation (took 5.195e-02 seconds).
(CVXPY) Jul 07 11:50:55 AM: Invoking solver SCS  to obtain a solution.

    75| 5.23e-06  1.24e-10  8.12e-08  3.19e-01  1.00e-01  1.65e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.65e+00s = setup: 2.58e-02s + solve: 1.63e+00s
	 lin-sys: 4.51e-02s, cones: 1.56e+00s, accel: 5.02e-03s
------------------------------------------------------------------
objective = 0.319043
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.59e+02  1.00e-01  4.03e-02

(CVXPY) Jul 07 11:50:56 AM: Problem status: optimal
(CVXPY) Jul 07 11:50:56 AM: Optimal value: 1.882e-01
(CVXPY) Jul 07 11:50:56 AM: Compilation took 5.195e-02 seconds
(CVXPY) Jul 07 11:50:56 AM: Solver (including time spent in interface) took 1.727e+00 seconds
(CVXPY) Jul 07 11:50:56 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:50:56 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:50:56 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:50:56 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:50:56 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:50:56 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:50:56 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:50:56 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:50:56 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:50:56 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:50:56 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:50:56 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:50:56 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:50:56 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:50:56 AM: Applying reduction SCS
(CVXPY) Jul 07 11:50:56 AM: Finished problem compilation (took 5.184e-02 seconds).
(CVXPY) Jul 07 11:50:56 AM: Invoking solver SCS  to obtain a solution.

    75| 5.18e-06  1.26e-10  7.31e-08  1.88e-01  1.00e-01  1.72e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.72e+00s = setup: 2.50e-02s + solve: 1.70e+00s
	 lin-sys: 4.62e-02s, cones: 1.63e+00s, accel: 4.70e-03s
------------------------------------------------------------------
objective = 0.188162
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.59e+02  1.00e-01  4.81e-02

(CVXPY) Jul 07 11:50:58 AM: Problem status: optimal
(CVXPY) Jul 07 11:50:58 AM: Optimal value: 1.777e-01
(CVXPY) Jul 07 11:50:58 AM: Compilation took 5.184e-02 seconds
(CVXPY) Jul 07 11:50:58 AM: Solver (including time spent in interface) took 1.679e+00 seconds
(CVXPY) Jul 07 11:50:58 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:50:58 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:50:58 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:50:58 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:50:58 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:50:58 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:50:58 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:50:58 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:50:58 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:50:58 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:50:58 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:50:58 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:50:58 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:50:58 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:50:58 AM: Applying reduction SCS
(CVXPY) Jul 07 11:50:58 AM: Finished problem compilation (took 4.966e-02 seconds).
(CVXPY) Jul 07 11:50:58 AM: Invoking solver SCS  to obtain a solution.

    75| 5.21e-06  1.24e-10  7.16e-08  1.78e-01  1.00e-01  1.67e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.67e+00s = setup: 2.59e-02s + solve: 1.65e+00s
	 lin-sys: 5.02e-02s, cones: 1.58e+00s, accel: 4.27e-03s
------------------------------------------------------------------
objective = 0.177721
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.59e+02  1.00e-01  4.78e-02

(CVXPY) Jul 07 11:51:00 AM: Problem status: optimal
(CVXPY) Jul 07 11:51:00 AM: Optimal value: 2.988e-01
(CVXPY) Jul 07 11:51:00 AM: Compilation took 4.966e-02 seconds
(CVXPY) Jul 07 11:51:00 AM: Solver (including time spent in interface) took 1.801e+00 seconds
(CVXPY) Jul 07 11:51:00 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:51:00 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:51:00 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:51:00 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:51:00 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:51:00 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:51:00 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:51:00 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:51:00 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:51:00 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:51:00 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:51:00 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:51:00 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:51:00 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:51:00 AM: Applying reduction SCS
(CVXPY) Jul 07 11:51:00 AM: Finished problem compilation (took 4.963e-02 seconds).
(CVXPY) Jul 07 11:51:00 AM: Invoking solver SCS  to obtain a solution.

    75| 5.28e-06  1.37e-10  7.14e-08  2.99e-01  1.00e-01  1.79e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.79e+00s = setup: 2.31e-02s + solve: 1.77e+00s
	 lin-sys: 4.68e-02s, cones: 1.70e+00s, accel: 5.63e-03s
------------------------------------------------------------------
objective = 0.298814
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.59e+02  1.00e-01  4.79e-02

(CVXPY) Jul 07 11:51:02 AM: Problem status: optimal
(CVXPY) Jul 07 11:51:02 AM: Optimal value: 2.661e-01
(CVXPY) Jul 07 11:51:02 AM: Compilation took 4.963e-02 seconds
(CVXPY) Jul 07 11:51:02 AM: Solver (including time spent in interface) took 1.645e+00 seconds
(CVXPY) Jul 07 11:51:02 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:51:02 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:51:02 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:51:02 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:51:02 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:51:02 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:51:02 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:51:02 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:51:02 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:51:02 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:51:02 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:51:02 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:51:02 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:51:02 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:51:02 AM: Applying reduction SCS
(CVXPY) Jul 07 11:51:02 AM: Finished problem compilation (took 5.672e-02 seconds).
(CVXPY) Jul 07 11:51:02 AM: Invoking solver SCS  to obtain a solution.

    75| 5.27e-06  1.36e-10  9.47e-08  2.66e-01  1.00e-01  1.64e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.64e+00s = setup: 2.40e-02s + solve: 1.62e+00s
	 lin-sys: 4.79e-02s, cones: 1.55e+00s, accel: 5.21e-03s
------------------------------------------------------------------
objective = 0.266067
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.59e+02  1.00e-01  5.40e-02

(CVXPY) Jul 07 11:51:04 AM: Problem status: optimal
(CVXPY) Jul 07 11:51:04 AM: Optimal value: 1.758e-01
(CVXPY) Jul 07 11:51:04 AM: Compilation took 5.672e-02 seconds
(CVXPY) Jul 07 11:51:04 AM: Solver (including time spent in interface) took 1.823e+00 seconds
(CVXPY) Jul 07 11:51:04 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:51:04 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:51:04 AM: DCP verification time: 0.0003 seconds.
(CVXPY) Jul 07 11:51:04 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:51:04 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:51:04 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:51:04 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:51:04 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:51:04 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:51:04 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:51:04 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:51:04 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:51:04 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:51:04 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:51:04 AM: Applying reduction SCS
(CVXPY) Jul 07 11:51:04 AM: Finished problem compilation (took 4.986e-02 seconds).
(CVXPY) Jul 07 11:51:04 AM: Invoking solver SCS  to obtain a solution.

    75| 2.24e-06  1.23e-10  4.07e-08  1.76e-01  1.00e-01  1.82e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.82e+00s = setup: 2.69e-02s + solve: 1.79e+00s
	 lin-sys: 4.77e-02s, cones: 1.72e+00s, accel: 4.72e-03s
------------------------------------------------------------------
objective = 0.175754
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.59e+02  1.00e-01  4.17e-02

(CVXPY) Jul 07 11:51:06 AM: Problem status: optimal
(CVXPY) Jul 07 11:51:06 AM: Optimal value: 2.802e-01
(CVXPY) Jul 07 11:51:06 AM: Compilation took 4.986e-02 seconds
(CVXPY) Jul 07 11:51:06 AM: Solver (including time spent in interface) took 1.901e+00 seconds
(CVXPY) Jul 07 11:51:06 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:51:06 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:51:06 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:51:06 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:51:06 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:51:06 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:51:06 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:51:06 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:51:06 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:51:06 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:51:06 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:51:06 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:51:06 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:51:06 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:51:06 AM: Applying reduction SCS
(CVXPY) Jul 07 11:51:06 AM: Finished problem compilation (took 5.734e-02 seconds).
(CVXPY) Jul 07 11:51:06 AM: Invoking solver SCS  to obtain a solution.

    75| 3.63e-06  1.33e-10  5.63e-08  2.80e-01  1.00e-01  1.90e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.90e+00s = setup: 2.73e-02s + solve: 1.87e+00s
	 lin-sys: 5.41e-02s, cones: 1.79e+00s, accel: 4.73e-03s
------------------------------------------------------------------
objective = 0.280235
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.59e+02  1.00e-01  5.48e-02

(CVXPY) Jul 07 11:51:07 AM: Problem status: optimal
(CVXPY) Jul 07 11:51:07 AM: Optimal value: 2.672e-01
(CVXPY) Jul 07 11:51:07 AM: Compilation took 5.734e-02 seconds
(CVXPY) Jul 07 11:51:07 AM: Solver (including time spent in interface) took 1.730e+00 seconds
(CVXPY) Jul 07 11:51:07 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:51:07 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:51:07 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:51:07 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:51:07 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:51:07 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:51:07 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:51:07 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:51:07 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:51:07 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:51:08 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:51:08 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:51:08 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:51:08 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:51:08 AM: Applying reduction SCS
(CVXPY) Jul 07 11:51:08 AM: Finished problem compilation (took 5.413e-02 seconds).
(CVXPY) Jul 07 11:51:08 AM: Invoking solver SCS  to obtain a solution.

    75| 5.15e-06  1.25e-10  8.10e-08  2.67e-01  1.00e-01  1.72e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.72e+00s = setup: 2.98e-02s + solve: 1.69e+00s
	 lin-sys: 4.85e-02s, cones: 1.62e+00s, accel: 5.37e-03s
------------------------------------------------------------------
objective = 0.267156
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.59e+02  1.00e-01  5.10e-02

(CVXPY) Jul 07 11:51:09 AM: Problem status: optimal
(CVXPY) Jul 07 11:51:09 AM: Optimal value: 2.128e-01
(CVXPY) Jul 07 11:51:09 AM: Compilation took 5.413e-02 seconds
(CVXPY) Jul 07 11:51:09 AM: Solver (including time spent in interface) took 1.729e+00 seconds
(CVXPY) Jul 07 11:51:09 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:51:09 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:51:09 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:51:09 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:51:09 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:51:09 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:51:09 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:51:09 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:51:09 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:51:09 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:51:09 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:51:09 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:51:09 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:51:09 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:51:09 AM: Applying reduction SCS
(CVXPY) Jul 07 11:51:09 AM: Finished problem compilation (took 5.878e-02 seconds).
(CVXPY) Jul 07 11:51:09 AM: Invoking solver SCS  to obtain a solution.

    75| 5.16e-06  1.25e-10  8.30e-08  2.13e-01  1.00e-01  1.72e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.72e+00s = setup: 2.55e-02s + solve: 1.70e+00s
	 lin-sys: 5.04e-02s, cones: 1.63e+00s, accel: 5.75e-03s
------------------------------------------------------------------
objective = 0.212813
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.59e+02  1.00e-01  5.23e-02

(CVXPY) Jul 07 11:51:11 AM: Problem status: optimal
(CVXPY) Jul 07 11:51:11 AM: Optimal value: 2.914e-01
(CVXPY) Jul 07 11:51:11 AM: Compilation took 5.878e-02 seconds
(CVXPY) Jul 07 11:51:11 AM: Solver (including time spent in interface) took 1.737e+00 seconds
(CVXPY) Jul 07 11:51:11 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:51:11 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:51:11 AM: DCP verification time: 0.0011 seconds.
(CVXPY) Jul 07 11:51:11 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:51:11 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:51:11 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:51:11 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:51:11 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:51:11 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:51:11 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:51:11 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:51:11 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:51:11 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:51:11 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:51:11 AM: Applying reduction SCS
(CVXPY) Jul 07 11:51:11 AM: Finished problem compilation (took 5.439e-02 seconds).
(CVXPY) Jul 07 11:51:11 AM: Invoking solver SCS  to obtain a solution.

    75| 3.66e-06  1.30e-10  5.01e-08  2.91e-01  1.00e-01  1.73e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.73e+00s = setup: 2.70e-02s + solve: 1.70e+00s
	 lin-sys: 5.33e-02s, cones: 1.63e+00s, accel: 4.84e-03s
------------------------------------------------------------------
objective = 0.291347
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.59e+02  1.00e-01  5.08e-02

(CVXPY) Jul 07 11:51:13 AM: Problem status: optimal
(CVXPY) Jul 07 11:51:13 AM: Optimal value: 2.759e-01
(CVXPY) Jul 07 11:51:13 AM: Compilation took 5.439e-02 seconds
(CVXPY) Jul 07 11:51:13 AM: Solver (including time spent in interface) took 1.797e+00 seconds
(CVXPY) Jul 07 11:51:13 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:51:13 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:51:13 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:51:13 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:51:13 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:51:13 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:51:13 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:51:13 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:51:13 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:51:13 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:51:13 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:51:13 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:51:13 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:51:13 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:51:13 AM: Applying reduction SCS
(CVXPY) Jul 07 11:51:13 AM: Finished problem compilation (took 5.421e-02 seconds).
(CVXPY) Jul 07 11:51:13 AM: Invoking solver SCS  to obtain a solution.

    75| 3.71e-06  1.32e-10  5.76e-08  2.76e-01  1.00e-01  1.79e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.79e+00s = setup: 2.76e-02s + solve: 1.76e+00s
	 lin-sys: 4.62e-02s, cones: 1.70e+00s, accel: 5.23e-03s
------------------------------------------------------------------
objective = 0.275866
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 1.41e+01  5.00e-01  9.19e+02 -4.59e+02  1.00e-01  5.27e-02

(CVXPY) Jul 07 11:51:15 AM: Problem status: optimal
(CVXPY) Jul 07 11:51:15 AM: Optimal value: 2.347e-01
(CVXPY) Jul 07 11:51:15 AM: Compilation took 5.421e-02 seconds
(CVXPY) Jul 07 11:51:15 AM: Solver (including time spent in interface) took 1.758e+00 seconds
(CVXPY) Jul 07 11:51:15 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:51:15 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:51:15 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:51:15 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:51:15 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:51:15 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:51:15 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:51:15 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:51:15 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:51:15 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:51:15 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:51:15 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:51:15 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:51:15 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:51:15 AM: Applying reduction SCS
(CVXPY) Jul 07 11:51:15 AM: Finished problem compilation (took 5.561e-02 seconds).
(CVXPY) Jul 07 11:51:15 AM: Invoking solver SCS  to obtain a solution.

    75| 5.37e-06  1.30e-10  9.98e-08  2.35e-01  1.00e-01  1.75e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.75e+00s = setup: 2.74e-02s + solve: 1.73e+00s
	 lin-sys: 5.10e-02s, cones: 1.65e+00s, accel: 4.65e-03s
------------------------------------------------------------------
objective = 0.234675
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  1.77e-02  1.13e-02  8.06e-02  1.00e-01  5.27e-02
   250| 9.03e-05  4.18e-08  3.26e-07  3.74e-07  7.72e-06  3.14e+00

(CVXPY) Jul 07 11:51:19 AM: Problem status: optimal
(CVXPY) Jul 07 11:51:19 AM: Optimal value: 1.119e-07
(CVXPY) Jul 07 11:51:19 AM: Compilation took 5.561e-02 seconds
(CVXPY) Jul 07 11:51:19 AM: Solver (including time spent in interface) took 3.727e+00 seconds
(CVXPY) Jul 07 11:51:19 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:51:19 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:51:19 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:51:19 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:51:19 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:51:19 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:51:19 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:51:19 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:51:19 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:51:19 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:51:19 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:51:19 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:51:19 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:51:19 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:51:19 AM: Applying reduction SCS
(CVXPY) Jul 07 11:51:19 AM: Finished problem compilation (took 5.274e-02 seconds).
(CVXPY) Jul 07 11:51:19 AM: Invoking solver SCS  to obtain a solution.

   300| 2.34e-05  1.95e-08  1.84e-07  2.04e-07  7.72e-06  3.72e+00
------------------------------------------------------------------
status:  solved
timings: total: 3.72e+00s = setup: 2.63e-02s + solve: 3.70e+00s
	 lin-sys: 1.91e-01s, cones: 3.44e+00s, accel: 1.86e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  2.80e-02  4.17e-02  1.16e-01  1.00e-01  4.99e-02
   250| 9.32e-05  5.42e-08  5.06e-07  5.28e-07  9.77e-06  3.25e+00

(CVXPY) Jul 07 11:51:22 AM: Problem status: optimal
(CVXPY) Jul 07 11:51:22 AM: Optimal value: 1.885e-07
(CVXPY) Jul 07 11:51:22 AM: Compilation took 5.274e-02 seconds
(CVXPY) Jul 07 11:51:22 AM: Solver (including time spent in interface) took 3.542e+00 seconds
(CVXPY) Jul 07 11:51:22 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:51:22 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:51:22 AM: DCP verification time: 0.0010 seconds.
(CVXPY) Jul 07 11:51:22 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:51:22 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:51:22 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:51:22 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:51:22 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:51:22 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:51:22 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:51:22 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:51:22 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:51:22 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:51:22 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:51:22 AM: Applying reduction SCS
(CVXPY) Jul 07 11:51:22 AM: Finished problem compilation (took 5.061e-02 seconds).
(CVXPY) Jul 07 11:51:22 AM: Invoking solver SCS  to obtain a solution.

   275| 3.90e-05  3.48e-08  3.53e-07  3.65e-07  9.77e-06  3.54e+00
------------------------------------------------------------------
status:  solved
timings: total: 3.54e+00s = setup: 2.31e-02s + solve: 3.51e+00s
	 lin-sys: 1.82e-01s, cones: 3.27e+00s, accel: 1.76e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  2.77e-02  4.41e-02  1.29e-01  1.00e-01  5.25e-02
   250| 9.03e-05  5.21e-08  4.65e-07  4.83e-07  9.61e-06  3.21e+00

(CVXPY) Jul 07 11:51:26 AM: Problem status: optimal
(CVXPY) Jul 07 11:51:26 AM: Optimal value: 1.713e-07
(CVXPY) Jul 07 11:51:26 AM: Compilation took 5.061e-02 seconds
(CVXPY) Jul 07 11:51:26 AM: Solver (including time spent in interface) took 3.504e+00 seconds
(CVXPY) Jul 07 11:51:26 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:51:26 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:51:26 AM: DCP verification time: 0.0003 seconds.
(CVXPY) Jul 07 11:51:26 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:51:26 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:51:26 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:51:26 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:51:26 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:51:26 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:51:26 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:51:26 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:51:26 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:51:26 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:51:26 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:51:26 AM: Applying reduction SCS
(CVXPY) Jul 07 11:51:26 AM: Finished problem compilation (took 5.687e-02 seconds).
(CVXPY) Jul 07 11:51:26 AM: Invoking solver SCS  to obtain a solution.

   275| 3.75e-05  3.31e-08  3.24e-07  3.33e-07  9.61e-06  3.50e+00
------------------------------------------------------------------
status:  solved
timings: total: 3.50e+00s = setup: 2.58e-02s + solve: 3.47e+00s
	 lin-sys: 1.75e-01s, cones: 3.23e+00s, accel: 1.75e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  2.79e-02  4.39e-02  1.06e-01  1.00e-01  4.78e-02
   250| 9.60e-05  5.38e-08  5.33e-07  5.51e-07  9.65e-06  3.09e+00

(CVXPY) Jul 07 11:51:30 AM: Problem status: optimal
(CVXPY) Jul 07 11:51:30 AM: Optimal value: 1.468e-07
(CVXPY) Jul 07 11:51:30 AM: Compilation took 5.687e-02 seconds
(CVXPY) Jul 07 11:51:30 AM: Solver (including time spent in interface) took 3.697e+00 seconds
(CVXPY) Jul 07 11:51:30 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:51:30 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:51:30 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:51:30 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:51:30 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:51:30 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:51:30 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:51:30 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:51:30 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:51:30 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:51:30 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:51:30 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:51:30 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:51:30 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:51:30 AM: Applying reduction SCS
(CVXPY) Jul 07 11:51:30 AM: Finished problem compilation (took 5.703e-02 seconds).
(CVXPY) Jul 07 11:51:30 AM: Invoking solver SCS  to obtain a solution.

   300| 2.13e-05  2.45e-08  2.86e-07  2.90e-07  9.65e-06  3.69e+00
------------------------------------------------------------------
status:  solved
timings: total: 3.69e+00s = setup: 2.64e-02s + solve: 3.67e+00s
	 lin-sys: 1.87e-01s, cones: 3.40e+00s, accel: 2.72e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  1.66e-02  1.52e-02  7.26e-02  1.00e-01  4.87e-02
   250| 9.09e-05  4.22e-08  3.30e-07  3.78e-07  7.97e-06  3.13e+00

(CVXPY) Jul 07 11:51:33 AM: Problem status: optimal
(CVXPY) Jul 07 11:51:33 AM: Optimal value: 1.124e-07
(CVXPY) Jul 07 11:51:33 AM: Compilation took 5.703e-02 seconds
(CVXPY) Jul 07 11:51:33 AM: Solver (including time spent in interface) took 3.709e+00 seconds
(CVXPY) Jul 07 11:51:33 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:51:33 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:51:33 AM: DCP verification time: 0.0003 seconds.
(CVXPY) Jul 07 11:51:33 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:51:33 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:51:33 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:51:33 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:51:33 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:51:33 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:51:33 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:51:33 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:51:33 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:51:33 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:51:33 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:51:33 AM: Applying reduction SCS
(CVXPY) Jul 07 11:51:33 AM: Finished problem compilation (took 5.361e-02 seconds).
(CVXPY) Jul 07 11:51:33 AM: Invoking solver SCS  to obtain a solution.

   300| 2.28e-05  1.96e-08  1.85e-07  2.05e-07  7.97e-06  3.71e+00
------------------------------------------------------------------
status:  solved
timings: total: 3.71e+00s = setup: 2.43e-02s + solve: 3.68e+00s
	 lin-sys: 1.86e-01s, cones: 3.43e+00s, accel: 1.83e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  2.79e-02  5.93e-02  1.32e-01  1.00e-01  5.76e-02
   250| 9.72e-05  5.47e-08  5.68e-07  5.92e-07  9.86e-06  3.15e+00

(CVXPY) Jul 07 11:51:37 AM: Problem status: optimal
(CVXPY) Jul 07 11:51:37 AM: Optimal value: 1.611e-07
(CVXPY) Jul 07 11:51:37 AM: Compilation took 5.361e-02 seconds
(CVXPY) Jul 07 11:51:37 AM: Solver (including time spent in interface) took 3.750e+00 seconds
(CVXPY) Jul 07 11:51:37 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:51:37 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:51:37 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:51:37 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:51:37 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:51:37 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:51:37 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:51:37 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:51:37 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:51:37 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:51:37 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:51:37 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:51:37 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:51:37 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:51:37 AM: Applying reduction SCS
(CVXPY) Jul 07 11:51:37 AM: Finished problem compilation (took 5.749e-02 seconds).
(CVXPY) Jul 07 11:51:37 AM: Invoking solver SCS  to obtain a solution.

   300| 2.19e-05  2.48e-08  3.07e-07  3.15e-07  9.86e-06  3.74e+00
------------------------------------------------------------------
status:  solved
timings: total: 3.74e+00s = setup: 2.93e-02s + solve: 3.72e+00s
	 lin-sys: 1.86e-01s, cones: 3.45e+00s, accel: 2.34e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  2.83e-02  4.36e-02  1.07e-01  1.00e-01  5.00e-02
   250| 9.54e-05  5.39e-08  5.24e-07  5.44e-07  9.73e-06  3.24e+00

(CVXPY) Jul 07 11:51:41 AM: Problem status: optimal
(CVXPY) Jul 07 11:51:41 AM: Optimal value: 1.465e-07
(CVXPY) Jul 07 11:51:41 AM: Compilation took 5.749e-02 seconds
(CVXPY) Jul 07 11:51:41 AM: Solver (including time spent in interface) took 3.835e+00 seconds
(CVXPY) Jul 07 11:51:41 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:51:41 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:51:41 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:51:41 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:51:41 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:51:41 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:51:41 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:51:41 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:51:41 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:51:41 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:51:41 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:51:41 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:51:41 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:51:41 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:51:41 AM: Applying reduction SCS
(CVXPY) Jul 07 11:51:41 AM: Finished problem compilation (took 4.810e-02 seconds).
(CVXPY) Jul 07 11:51:41 AM: Invoking solver SCS  to obtain a solution.

   300| 2.11e-05  2.46e-08  2.83e-07  2.88e-07  9.73e-06  3.83e+00
------------------------------------------------------------------
status:  solved
timings: total: 3.83e+00s = setup: 2.60e-02s + solve: 3.80e+00s
	 lin-sys: 1.86e-01s, cones: 3.55e+00s, accel: 1.97e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  1.27e-02  1.20e-02  7.32e-02  1.00e-01  4.90e-02
   250| 8.25e-05  2.66e-08  2.43e-07  2.96e-07  7.36e-06  3.07e+00

(CVXPY) Jul 07 11:51:45 AM: Problem status: optimal
(CVXPY) Jul 07 11:51:45 AM: Optimal value: 1.211e-07
(CVXPY) Jul 07 11:51:45 AM: Compilation took 4.810e-02 seconds
(CVXPY) Jul 07 11:51:45 AM: Solver (including time spent in interface) took 3.345e+00 seconds
(CVXPY) Jul 07 11:51:45 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:51:45 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:51:45 AM: DCP verification time: 0.0013 seconds.
(CVXPY) Jul 07 11:51:45 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:51:45 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:51:45 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:51:45 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:51:45 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:51:45 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:51:45 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:51:45 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:51:45 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:51:45 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:51:45 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:51:45 AM: Applying reduction SCS
(CVXPY) Jul 07 11:51:45 AM: Finished problem compilation (took 5.510e-02 seconds).
(CVXPY) Jul 07 11:51:45 AM: Invoking solver SCS  to obtain a solution.

   275| 3.39e-05  1.95e-08  1.76e-07  2.09e-07  7.36e-06  3.34e+00
------------------------------------------------------------------
status:  solved
timings: total: 3.34e+00s = setup: 2.40e-02s + solve: 3.32e+00s
	 lin-sys: 1.72e-01s, cones: 3.08e+00s, accel: 1.76e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  2.83e-02  4.91e-02  1.36e-01  1.00e-01  6.61e-02
   250| 9.35e-05  5.56e-08  5.17e-07  5.39e-07  9.91e-06  3.25e+00

(CVXPY) Jul 07 11:51:48 AM: Problem status: optimal
(CVXPY) Jul 07 11:51:48 AM: Optimal value: 1.922e-07
(CVXPY) Jul 07 11:51:48 AM: Compilation took 5.510e-02 seconds
(CVXPY) Jul 07 11:51:48 AM: Solver (including time spent in interface) took 3.559e+00 seconds
(CVXPY) Jul 07 11:51:48 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:51:48 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:51:48 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:51:48 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:51:48 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:51:48 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:51:48 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:51:48 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:51:48 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:51:48 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:51:48 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:51:48 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:51:48 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:51:48 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:51:48 AM: Applying reduction SCS
(CVXPY) Jul 07 11:51:48 AM: Finished problem compilation (took 5.437e-02 seconds).
(CVXPY) Jul 07 11:51:48 AM: Invoking solver SCS  to obtain a solution.

   275| 3.90e-05  3.59e-08  3.61e-07  3.73e-07  9.91e-06  3.55e+00
------------------------------------------------------------------
status:  solved
timings: total: 3.55e+00s = setup: 4.34e-02s + solve: 3.51e+00s
	 lin-sys: 1.73e-01s, cones: 3.27e+00s, accel: 1.88e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  1.63e-02  1.17e-02  7.82e-02  1.00e-01  5.15e-02
   250| 8.12e-05  2.49e-08  2.25e-07  2.79e-07  6.92e-06  3.87e+00

(CVXPY) Jul 07 11:51:53 AM: Problem status: optimal
(CVXPY) Jul 07 11:51:53 AM: Optimal value: 1.151e-07
(CVXPY) Jul 07 11:51:53 AM: Compilation took 5.437e-02 seconds
(CVXPY) Jul 07 11:51:53 AM: Solver (including time spent in interface) took 4.241e+00 seconds
(CVXPY) Jul 07 11:51:53 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:51:53 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:51:53 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:51:53 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:51:53 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:51:53 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:51:53 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:51:53 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:51:53 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:51:53 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:51:53 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:51:53 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:51:53 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:51:53 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:51:53 AM: Applying reduction SCS
(CVXPY) Jul 07 11:51:53 AM: Finished problem compilation (took 7.127e-02 seconds).
(CVXPY) Jul 07 11:51:53 AM: Invoking solver SCS  to obtain a solution.

   275| 3.41e-05  1.89e-08  1.64e-07  1.97e-07  6.92e-06  4.23e+00
------------------------------------------------------------------
status:  solved
timings: total: 4.23e+00s = setup: 2.59e-02s + solve: 4.21e+00s
	 lin-sys: 2.13e-01s, cones: 3.92e+00s, accel: 1.94e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  1.63e-02  1.12e-02  7.25e-02  1.00e-01  6.37e-02
   250| 8.90e-05  3.99e-08  2.99e-07  3.54e-07  7.41e-06  3.43e+00

(CVXPY) Jul 07 11:51:57 AM: Problem status: optimal
(CVXPY) Jul 07 11:51:57 AM: Optimal value: 1.087e-07
(CVXPY) Jul 07 11:51:57 AM: Compilation took 7.127e-02 seconds
(CVXPY) Jul 07 11:51:57 AM: Solver (including time spent in interface) took 4.018e+00 seconds
(CVXPY) Jul 07 11:51:57 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:51:57 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:51:57 AM: DCP verification time: 0.0010 seconds.
(CVXPY) Jul 07 11:51:57 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:51:57 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:51:57 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:51:57 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:51:57 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:51:57 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:51:57 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:51:57 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:51:57 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:51:57 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:51:57 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:51:57 AM: Applying reduction SCS
(CVXPY) Jul 07 11:51:57 AM: Finished problem compilation (took 5.424e-02 seconds).
(CVXPY) Jul 07 11:51:57 AM: Invoking solver SCS  to obtain a solution.

   300| 2.38e-05  1.90e-08  1.72e-07  1.94e-07  7.41e-06  4.01e+00
------------------------------------------------------------------
status:  solved
timings: total: 4.01e+00s = setup: 3.51e-02s + solve: 3.98e+00s
	 lin-sys: 2.01e-01s, cones: 3.70e+00s, accel: 2.29e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  2.79e-02  4.03e-02  1.26e-01  1.00e-01  5.13e-02
   250| 9.15e-05  5.24e-08  4.57e-07  4.85e-07  9.49e-06  4.02e+00

(CVXPY) Jul 07 11:52:01 AM: Problem status: optimal
(CVXPY) Jul 07 11:52:01 AM: Optimal value: 1.757e-07
(CVXPY) Jul 07 11:52:01 AM: Compilation took 5.424e-02 seconds
(CVXPY) Jul 07 11:52:01 AM: Solver (including time spent in interface) took 4.324e+00 seconds
(CVXPY) Jul 07 11:52:01 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:52:01 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:52:01 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:52:01 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:52:01 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:52:01 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:52:01 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:52:01 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:52:01 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:52:01 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:52:01 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:52:01 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:52:01 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:52:01 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:52:01 AM: Applying reduction SCS
(CVXPY) Jul 07 11:52:01 AM: Finished problem compilation (took 6.397e-02 seconds).
(CVXPY) Jul 07 11:52:01 AM: Invoking solver SCS  to obtain a solution.

   275| 3.80e-05  3.30e-08  3.21e-07  3.36e-07  9.49e-06  4.32e+00
------------------------------------------------------------------
status:  solved
timings: total: 4.32e+00s = setup: 2.73e-02s + solve: 4.29e+00s
	 lin-sys: 2.21e-01s, cones: 4.00e+00s, accel: 2.02e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  2.77e-02  3.72e-02  1.11e-01  1.00e-01  5.59e-02
   250| 9.14e-05  5.38e-08  4.72e-07  5.00e-07  9.72e-06  4.08e+00

(CVXPY) Jul 07 11:52:06 AM: Problem status: optimal
(CVXPY) Jul 07 11:52:06 AM: Optimal value: 1.808e-07
(CVXPY) Jul 07 11:52:06 AM: Compilation took 6.397e-02 seconds
(CVXPY) Jul 07 11:52:06 AM: Solver (including time spent in interface) took 4.392e+00 seconds
(CVXPY) Jul 07 11:52:06 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:52:06 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:52:06 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:52:06 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:52:06 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:52:06 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:52:06 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:52:06 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:52:06 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:52:06 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:52:06 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:52:06 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:52:06 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:52:06 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:52:06 AM: Applying reduction SCS
(CVXPY) Jul 07 11:52:06 AM: Finished problem compilation (took 5.055e-02 seconds).
(CVXPY) Jul 07 11:52:06 AM: Invoking solver SCS  to obtain a solution.

   275| 3.82e-05  3.44e-08  3.32e-07  3.47e-07  9.72e-06  4.39e+00
------------------------------------------------------------------
status:  solved
timings: total: 4.39e+00s = setup: 2.87e-02s + solve: 4.36e+00s
	 lin-sys: 2.06e-01s, cones: 4.06e+00s, accel: 1.94e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  1.73e-02  6.45e-03  7.30e-02  1.00e-01  5.17e-02
   250| 8.20e-05  2.50e-08  2.31e-07  2.88e-07  6.81e-06  3.49e+00

(CVXPY) Jul 07 11:52:10 AM: Problem status: optimal
(CVXPY) Jul 07 11:52:10 AM: Optimal value: 9.287e-08
(CVXPY) Jul 07 11:52:10 AM: Compilation took 5.055e-02 seconds
(CVXPY) Jul 07 11:52:10 AM: Solver (including time spent in interface) took 4.097e+00 seconds
(CVXPY) Jul 07 11:52:10 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:52:10 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:52:10 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:52:10 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:52:10 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:52:10 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:52:10 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:52:10 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:52:10 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:52:10 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:52:10 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:52:10 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:52:10 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:52:10 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:52:10 AM: Applying reduction SCS
(CVXPY) Jul 07 11:52:10 AM: Finished problem compilation (took 5.718e-02 seconds).
(CVXPY) Jul 07 11:52:10 AM: Invoking solver SCS  to obtain a solution.

   300| 2.35e-05  1.48e-08  1.36e-07  1.61e-07  6.81e-06  4.09e+00
------------------------------------------------------------------
status:  solved
timings: total: 4.09e+00s = setup: 2.58e-02s + solve: 4.07e+00s
	 lin-sys: 2.06e-01s, cones: 3.78e+00s, accel: 2.61e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  2.76e-02  5.11e-02  1.21e-01  1.00e-01  5.24e-02
   250| 9.84e-05  5.46e-08  5.85e-07  6.02e-07  9.80e-06  3.18e+00

(CVXPY) Jul 07 11:52:14 AM: Problem status: optimal
(CVXPY) Jul 07 11:52:14 AM: Optimal value: 1.610e-07
(CVXPY) Jul 07 11:52:14 AM: Compilation took 5.718e-02 seconds
(CVXPY) Jul 07 11:52:14 AM: Solver (including time spent in interface) took 3.747e+00 seconds
(CVXPY) Jul 07 11:52:14 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:52:14 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:52:14 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:52:14 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:52:14 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:52:14 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:52:14 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:52:14 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:52:14 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:52:14 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:52:14 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:52:14 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:52:14 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:52:14 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:52:14 AM: Applying reduction SCS
(CVXPY) Jul 07 11:52:14 AM: Finished problem compilation (took 5.416e-02 seconds).
(CVXPY) Jul 07 11:52:14 AM: Invoking solver SCS  to obtain a solution.

   300| 2.17e-05  2.47e-08  3.14e-07  3.18e-07  9.80e-06  3.74e+00
------------------------------------------------------------------
status:  solved
timings: total: 3.74e+00s = setup: 2.84e-02s + solve: 3.71e+00s
	 lin-sys: 1.81e-01s, cones: 3.46e+00s, accel: 1.97e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  2.85e-02  4.00e-02  1.12e-01  1.00e-01  4.86e-02
   250| 9.23e-05  5.42e-08  4.80e-07  4.98e-07  9.72e-06  3.14e+00

(CVXPY) Jul 07 11:52:17 AM: Problem status: optimal
(CVXPY) Jul 07 11:52:17 AM: Optimal value: 1.758e-07
(CVXPY) Jul 07 11:52:17 AM: Compilation took 5.416e-02 seconds
(CVXPY) Jul 07 11:52:17 AM: Solver (including time spent in interface) took 3.426e+00 seconds
(CVXPY) Jul 07 11:52:17 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:52:17 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:52:17 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:52:17 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:52:17 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:52:17 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:52:17 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:52:17 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:52:17 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:52:17 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:52:17 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:52:17 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:52:17 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:52:17 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:52:17 AM: Applying reduction SCS
(CVXPY) Jul 07 11:52:17 AM: Finished problem compilation (took 5.121e-02 seconds).
(CVXPY) Jul 07 11:52:17 AM: Invoking solver SCS  to obtain a solution.

   275| 3.82e-05  3.45e-08  3.34e-07  3.43e-07  9.72e-06  3.42e+00
------------------------------------------------------------------
status:  solved
timings: total: 3.42e+00s = setup: 2.47e-02s + solve: 3.40e+00s
	 lin-sys: 1.73e-01s, cones: 3.16e+00s, accel: 1.80e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  1.63e-02  1.40e-02  8.77e-02  1.00e-01  4.98e-02
   250| 8.29e-05  2.68e-08  2.43e-07  2.97e-07  7.21e-06  3.22e+00

(CVXPY) Jul 07 11:52:21 AM: Problem status: optimal
(CVXPY) Jul 07 11:52:21 AM: Optimal value: 9.360e-08
(CVXPY) Jul 07 11:52:21 AM: Compilation took 5.121e-02 seconds
(CVXPY) Jul 07 11:52:21 AM: Solver (including time spent in interface) took 3.828e+00 seconds
(CVXPY) Jul 07 11:52:21 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:52:21 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:52:21 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:52:21 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:52:21 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:52:21 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:52:21 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:52:21 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:52:21 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:52:21 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:52:21 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:52:21 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:52:21 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:52:21 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:52:21 AM: Applying reduction SCS
(CVXPY) Jul 07 11:52:21 AM: Finished problem compilation (took 5.774e-02 seconds).
(CVXPY) Jul 07 11:52:21 AM: Invoking solver SCS  to obtain a solution.

   300| 2.26e-05  1.54e-08  1.41e-07  1.64e-07  7.21e-06  3.82e+00
------------------------------------------------------------------
status:  solved
timings: total: 3.82e+00s = setup: 2.59e-02s + solve: 3.80e+00s
	 lin-sys: 1.87e-01s, cones: 3.53e+00s, accel: 1.94e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  2.81e-02  4.93e-02  1.26e-01  1.00e-01  4.99e-02
   250| 9.74e-05  5.43e-08  5.68e-07  5.89e-07  9.82e-06  3.17e+00

(CVXPY) Jul 07 11:52:25 AM: Problem status: optimal
(CVXPY) Jul 07 11:52:25 AM: Optimal value: 1.593e-07
(CVXPY) Jul 07 11:52:25 AM: Compilation took 5.774e-02 seconds
(CVXPY) Jul 07 11:52:25 AM: Solver (including time spent in interface) took 3.763e+00 seconds
(CVXPY) Jul 07 11:52:25 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:52:25 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:52:25 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:52:25 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:52:25 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:52:25 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:52:25 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:52:25 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:52:25 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:52:25 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:52:25 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:52:25 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:52:25 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:52:25 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:52:25 AM: Applying reduction SCS
(CVXPY) Jul 07 11:52:25 AM: Finished problem compilation (took 5.176e-02 seconds).
(CVXPY) Jul 07 11:52:25 AM: Invoking solver SCS  to obtain a solution.

   300| 2.18e-05  2.48e-08  3.07e-07  3.13e-07  9.82e-06  3.76e+00
------------------------------------------------------------------
status:  solved
timings: total: 3.76e+00s = setup: 2.61e-02s + solve: 3.73e+00s
	 lin-sys: 1.83e-01s, cones: 3.48e+00s, accel: 1.99e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  2.79e-02  4.28e-02  1.17e-01  1.00e-01  5.17e-02
   250| 9.56e-05  5.40e-08  5.41e-07  5.60e-07  9.79e-06  3.20e+00

(CVXPY) Jul 07 11:52:29 AM: Problem status: optimal
(CVXPY) Jul 07 11:52:29 AM: Optimal value: 1.501e-07
(CVXPY) Jul 07 11:52:29 AM: Compilation took 5.176e-02 seconds
(CVXPY) Jul 07 11:52:29 AM: Solver (including time spent in interface) took 3.777e+00 seconds
(CVXPY) Jul 07 11:52:29 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:52:29 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:52:29 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:52:29 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:52:29 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:52:29 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:52:29 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:52:29 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:52:29 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:52:29 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:52:29 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:52:29 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:52:29 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:52:29 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:52:29 AM: Applying reduction SCS
(CVXPY) Jul 07 11:52:29 AM: Finished problem compilation (took 7.633e-02 seconds).
(CVXPY) Jul 07 11:52:29 AM: Invoking solver SCS  to obtain a solution.

   300| 2.12e-05  2.46e-08  2.92e-07  2.96e-07  9.79e-06  3.77e+00
------------------------------------------------------------------
status:  solved
timings: total: 3.77e+00s = setup: 2.78e-02s + solve: 3.74e+00s
	 lin-sys: 1.84e-01s, cones: 3.49e+00s, accel: 1.98e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.47e+00  1.74e-02  1.16e-02  9.48e-02  1.00e-01  4.76e-02
   250| 8.74e-05  3.01e-08  2.99e-07  3.51e-07  7.60e-06  3.15e+00

(CVXPY) Jul 07 11:52:32 AM: Problem status: optimal
(CVXPY) Jul 07 11:52:32 AM: Optimal value: 1.081e-07
(CVXPY) Jul 07 11:52:32 AM: Compilation took 7.633e-02 seconds
(CVXPY) Jul 07 11:52:32 AM: Solver (including time spent in interface) took 3.736e+00 seconds
(CVXPY) Jul 07 11:52:32 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:52:32 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:52:32 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:52:32 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:52:32 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:52:32 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:52:32 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:52:32 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:52:32 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:52:32 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:52:33 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:52:33 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:52:33 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:52:33 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:52:33 AM: Applying reduction SCS
(CVXPY) Jul 07 11:52:33 AM: Finished problem compilation (took 7.597e-02 seconds).
(CVXPY) Jul 07 11:52:33 AM: Invoking solver SCS  to obtain a solution.

   300| 2.28e-05  1.68e-08  1.71e-07  1.94e-07  7.60e-06  3.73e+00
------------------------------------------------------------------
status:  solved
timings: total: 3.73e+00s = setup: 2.22e-02s + solve: 3.71e+00s
	 lin-sys: 1.77e-01s, cones: 3.46e+00s, accel: 2.17e-02s
------------------------------------------------------------------
objective = 0.000000
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.86e+01  1.00e-01  3.81e-02

(CVXPY) Jul 07 11:52:34 AM: Problem status: optimal
(CVXPY) Jul 07 11:52:34 AM: Optimal value: 1.070e-01
(CVXPY) Jul 07 11:52:34 AM: Compilation took 7.597e-02 seconds
(CVXPY) Jul 07 11:52:34 AM: Solver (including time spent in interface) took 1.642e+00 seconds
(CVXPY) Jul 07 11:52:34 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:52:34 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:52:34 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:52:34 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:52:34 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:52:34 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:52:34 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:52:34 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:52:34 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:52:34 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:52:34 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:52:34 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:52:34 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:52:34 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:52:34 AM: Applying reduction SCS
(CVXPY) Jul 07 11:52:34 AM: Finished problem compilation (took 5.457e-02 seconds).
(CVXPY) Jul 07 11:52:34 AM: Invoking solver SCS  to obtain a solution.

    75| 8.01e-07  7.52e-11  1.05e-07  1.07e-01  1.00e-01  1.64e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.64e+00s = setup: 2.35e-02s + solve: 1.61e+00s
	 lin-sys: 4.78e-02s, cones: 1.55e+00s, accel: 5.21e-03s
------------------------------------------------------------------
objective = 0.106965
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.86e+01  1.00e-01  4.57e-02

(CVXPY) Jul 07 11:52:35 AM: Problem status: optimal
(CVXPY) Jul 07 11:52:35 AM: Optimal value: 1.297e-01
(CVXPY) Jul 07 11:52:35 AM: Compilation took 5.457e-02 seconds
(CVXPY) Jul 07 11:52:35 AM: Solver (including time spent in interface) took 8.825e-01 seconds
(CVXPY) Jul 07 11:52:35 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:52:35 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:52:35 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:52:35 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:52:35 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:52:35 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:52:35 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:52:35 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:52:35 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:52:35 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:52:35 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:52:35 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:52:35 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:52:35 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:52:35 AM: Applying reduction SCS
(CVXPY) Jul 07 11:52:35 AM: Finished problem compilation (took 5.134e-02 seconds).
(CVXPY) Jul 07 11:52:35 AM: Invoking solver SCS  to obtain a solution.

    50| 1.92e-05  7.70e-09  1.82e-06  1.30e-01  1.00e-01  8.77e-01
------------------------------------------------------------------
status:  solved
timings: total: 8.77e-01s = setup: 2.57e-02s + solve: 8.51e-01s
	 lin-sys: 3.21e-02s, cones: 8.05e-01s, accel: 3.87e-03s
------------------------------------------------------------------
objective = 0.129656
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.86e+01  1.00e-01  4.83e-02

(CVXPY) Jul 07 11:52:37 AM: Problem status: optimal
(CVXPY) Jul 07 11:52:37 AM: Optimal value: 1.513e-01
(CVXPY) Jul 07 11:52:37 AM: Compilation took 5.134e-02 seconds
(CVXPY) Jul 07 11:52:37 AM: Solver (including time spent in interface) took 1.677e+00 seconds
(CVXPY) Jul 07 11:52:37 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:52:37 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:52:37 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:52:37 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:52:37 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:52:37 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:52:37 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:52:37 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:52:37 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:52:37 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:52:37 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:52:37 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:52:37 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:52:37 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:52:37 AM: Applying reduction SCS
(CVXPY) Jul 07 11:52:37 AM: Finished problem compilation (took 5.176e-02 seconds).
(CVXPY) Jul 07 11:52:37 AM: Invoking solver SCS  to obtain a solution.

    75| 8.82e-07  1.85e-10  1.23e-07  1.51e-01  1.00e-01  1.67e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.67e+00s = setup: 2.47e-02s + solve: 1.65e+00s
	 lin-sys: 4.81e-02s, cones: 1.58e+00s, accel: 5.57e-03s
------------------------------------------------------------------
objective = 0.151252
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.86e+01  1.00e-01  5.08e-02

(CVXPY) Jul 07 11:52:39 AM: Problem status: optimal
(CVXPY) Jul 07 11:52:39 AM: Optimal value: 1.188e-01
(CVXPY) Jul 07 11:52:39 AM: Compilation took 5.176e-02 seconds
(CVXPY) Jul 07 11:52:39 AM: Solver (including time spent in interface) took 1.600e+00 seconds
(CVXPY) Jul 07 11:52:39 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:52:39 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:52:39 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:52:39 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:52:39 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:52:39 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:52:39 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:52:39 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:52:39 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:52:39 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:52:39 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:52:39 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:52:39 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:52:39 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:52:39 AM: Applying reduction SCS
(CVXPY) Jul 07 11:52:39 AM: Finished problem compilation (took 5.007e-02 seconds).
(CVXPY) Jul 07 11:52:39 AM: Invoking solver SCS  to obtain a solution.

    75| 1.10e-06  7.68e-11  1.39e-07  1.19e-01  1.00e-01  1.60e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.60e+00s = setup: 2.48e-02s + solve: 1.57e+00s
	 lin-sys: 4.57e-02s, cones: 1.50e+00s, accel: 6.13e-03s
------------------------------------------------------------------
objective = 0.118819
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.87e+01  1.00e-01  5.28e-02

(CVXPY) Jul 07 11:52:40 AM: Problem status: optimal
(CVXPY) Jul 07 11:52:40 AM: Optimal value: 9.244e-02
(CVXPY) Jul 07 11:52:40 AM: Compilation took 5.007e-02 seconds
(CVXPY) Jul 07 11:52:40 AM: Solver (including time spent in interface) took 1.607e+00 seconds
(CVXPY) Jul 07 11:52:40 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:52:40 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:52:40 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:52:40 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:52:40 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:52:40 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:52:40 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:52:40 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:52:40 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:52:40 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:52:40 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:52:40 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:52:40 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:52:40 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:52:40 AM: Applying reduction SCS
(CVXPY) Jul 07 11:52:40 AM: Finished problem compilation (took 4.992e-02 seconds).
(CVXPY) Jul 07 11:52:40 AM: Invoking solver SCS  to obtain a solution.

    75| 1.11e-06  6.48e-11  1.34e-07  9.24e-02  1.00e-01  1.60e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.60e+00s = setup: 2.46e-02s + solve: 1.58e+00s
	 lin-sys: 5.44e-02s, cones: 1.50e+00s, accel: 5.12e-03s
------------------------------------------------------------------
objective = 0.092437
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.86e+01  1.00e-01  3.95e-02

(CVXPY) Jul 07 11:52:41 AM: Problem status: optimal
(CVXPY) Jul 07 11:52:41 AM: Optimal value: 1.367e-01
(CVXPY) Jul 07 11:52:41 AM: Compilation took 4.992e-02 seconds
(CVXPY) Jul 07 11:52:41 AM: Solver (including time spent in interface) took 1.115e+00 seconds
(CVXPY) Jul 07 11:52:41 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:52:41 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:52:41 AM: DCP verification time: 0.0003 seconds.
(CVXPY) Jul 07 11:52:41 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:52:41 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:52:41 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:52:41 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:52:41 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:52:41 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:52:41 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:52:41 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:52:41 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:52:42 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:52:42 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:52:42 AM: Applying reduction SCS
(CVXPY) Jul 07 11:52:42 AM: Finished problem compilation (took 4.860e-02 seconds).
(CVXPY) Jul 07 11:52:42 AM: Invoking solver SCS  to obtain a solution.

    50| 1.98e-05  1.15e-10  1.83e-06  1.37e-01  1.00e-01  1.11e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.11e+00s = setup: 2.32e-02s + solve: 1.09e+00s
	 lin-sys: 3.14e-02s, cones: 1.04e+00s, accel: 4.09e-03s
------------------------------------------------------------------
objective = 0.136697
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.86e+01  1.00e-01  4.54e-02

(CVXPY) Jul 07 11:52:43 AM: Problem status: optimal
(CVXPY) Jul 07 11:52:43 AM: Optimal value: 1.176e-01
(CVXPY) Jul 07 11:52:43 AM: Compilation took 4.860e-02 seconds
(CVXPY) Jul 07 11:52:43 AM: Solver (including time spent in interface) took 1.703e+00 seconds
(CVXPY) Jul 07 11:52:43 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:52:43 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:52:43 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:52:43 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:52:43 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:52:43 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:52:43 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:52:43 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:52:43 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:52:43 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:52:43 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:52:43 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:52:43 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:52:43 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:52:43 AM: Applying reduction SCS
(CVXPY) Jul 07 11:52:43 AM: Finished problem compilation (took 4.617e-02 seconds).
(CVXPY) Jul 07 11:52:43 AM: Invoking solver SCS  to obtain a solution.

    75| 8.12e-07  7.09e-11  8.74e-08  1.18e-01  1.00e-01  1.70e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.70e+00s = setup: 2.37e-02s + solve: 1.67e+00s
	 lin-sys: 5.02e-02s, cones: 1.60e+00s, accel: 4.63e-03s
------------------------------------------------------------------
objective = 0.117598
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.87e+01  1.00e-01  4.83e-02

(CVXPY) Jul 07 11:52:45 AM: Problem status: optimal
(CVXPY) Jul 07 11:52:45 AM: Optimal value: 9.142e-02
(CVXPY) Jul 07 11:52:45 AM: Compilation took 4.617e-02 seconds
(CVXPY) Jul 07 11:52:45 AM: Solver (including time spent in interface) took 1.657e+00 seconds
(CVXPY) Jul 07 11:52:45 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:52:45 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:52:45 AM: DCP verification time: 0.0009 seconds.
(CVXPY) Jul 07 11:52:45 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:52:45 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:52:45 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:52:45 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:52:45 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:52:45 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:52:45 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:52:45 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:52:45 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:52:45 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:52:45 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:52:45 AM: Applying reduction SCS
(CVXPY) Jul 07 11:52:45 AM: Finished problem compilation (took 5.118e-02 seconds).
(CVXPY) Jul 07 11:52:45 AM: Invoking solver SCS  to obtain a solution.

    75| 7.92e-07  6.97e-11  7.01e-08  9.14e-02  1.00e-01  1.65e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.65e+00s = setup: 2.36e-02s + solve: 1.63e+00s
	 lin-sys: 4.48e-02s, cones: 1.56e+00s, accel: 5.19e-03s
------------------------------------------------------------------
objective = 0.091417
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.86e+01  1.00e-01  4.93e-02

(CVXPY) Jul 07 11:52:47 AM: Problem status: optimal
(CVXPY) Jul 07 11:52:47 AM: Optimal value: 1.530e-01
(CVXPY) Jul 07 11:52:47 AM: Compilation took 5.118e-02 seconds
(CVXPY) Jul 07 11:52:47 AM: Solver (including time spent in interface) took 1.596e+00 seconds
(CVXPY) Jul 07 11:52:47 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:52:47 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:52:47 AM: DCP verification time: 0.0003 seconds.
(CVXPY) Jul 07 11:52:47 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:52:47 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:52:47 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:52:47 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:52:47 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:52:47 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:52:47 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:52:47 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:52:47 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:52:47 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:52:47 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:52:47 AM: Applying reduction SCS
(CVXPY) Jul 07 11:52:47 AM: Finished problem compilation (took 4.713e-02 seconds).
(CVXPY) Jul 07 11:52:47 AM: Invoking solver SCS  to obtain a solution.

    75| 1.09e-06  6.93e-11  1.18e-07  1.53e-01  1.00e-01  1.59e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.59e+00s = setup: 2.31e-02s + solve: 1.57e+00s
	 lin-sys: 4.83e-02s, cones: 1.50e+00s, accel: 5.28e-03s
------------------------------------------------------------------
objective = 0.153020
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.86e+01  1.00e-01  3.80e-02

(CVXPY) Jul 07 11:52:48 AM: Problem status: optimal
(CVXPY) Jul 07 11:52:48 AM: Optimal value: 1.004e-01
(CVXPY) Jul 07 11:52:48 AM: Compilation took 4.713e-02 seconds
(CVXPY) Jul 07 11:52:48 AM: Solver (including time spent in interface) took 1.648e+00 seconds
(CVXPY) Jul 07 11:52:48 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:52:48 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:52:48 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:52:48 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:52:48 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:52:48 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:52:48 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:52:48 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:52:48 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:52:48 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:52:48 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:52:48 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:52:48 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:52:48 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:52:48 AM: Applying reduction SCS
(CVXPY) Jul 07 11:52:48 AM: Finished problem compilation (took 5.580e-02 seconds).
(CVXPY) Jul 07 11:52:48 AM: Invoking solver SCS  to obtain a solution.

    75| 1.08e-06  7.17e-11  1.09e-07  1.00e-01  1.00e-01  1.64e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.64e+00s = setup: 2.20e-02s + solve: 1.62e+00s
	 lin-sys: 4.95e-02s, cones: 1.55e+00s, accel: 5.77e-03s
------------------------------------------------------------------
objective = 0.100402
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.87e+01  1.00e-01  4.58e-02

(CVXPY) Jul 07 11:52:50 AM: Problem status: optimal
(CVXPY) Jul 07 11:52:50 AM: Optimal value: 9.372e-02
(CVXPY) Jul 07 11:52:50 AM: Compilation took 5.580e-02 seconds
(CVXPY) Jul 07 11:52:50 AM: Solver (including time spent in interface) took 1.651e+00 seconds
(CVXPY) Jul 07 11:52:50 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:52:50 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:52:50 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:52:50 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:52:50 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:52:50 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:52:50 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:52:50 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:52:50 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:52:50 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:52:50 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:52:50 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:52:50 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:52:50 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:52:50 AM: Applying reduction SCS
(CVXPY) Jul 07 11:52:50 AM: Finished problem compilation (took 6.436e-02 seconds).
(CVXPY) Jul 07 11:52:50 AM: Invoking solver SCS  to obtain a solution.

    75| 1.09e-06  6.93e-11  1.06e-07  9.37e-02  1.00e-01  1.64e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.64e+00s = setup: 2.30e-02s + solve: 1.62e+00s
	 lin-sys: 4.97e-02s, cones: 1.55e+00s, accel: 6.32e-03s
------------------------------------------------------------------
objective = 0.093721
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.86e+01  1.00e-01  5.12e-02

(CVXPY) Jul 07 11:52:52 AM: Problem status: optimal
(CVXPY) Jul 07 11:52:52 AM: Optimal value: 1.452e-01
(CVXPY) Jul 07 11:52:52 AM: Compilation took 6.436e-02 seconds
(CVXPY) Jul 07 11:52:52 AM: Solver (including time spent in interface) took 1.469e+00 seconds
(CVXPY) Jul 07 11:52:52 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:52:52 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:52:52 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:52:52 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:52:52 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:52:52 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:52:52 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:52:52 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:52:52 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:52:52 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:52:52 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:52:52 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:52:52 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:52:52 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:52:52 AM: Applying reduction SCS
(CVXPY) Jul 07 11:52:52 AM: Finished problem compilation (took 6.174e-02 seconds).
(CVXPY) Jul 07 11:52:52 AM: Invoking solver SCS  to obtain a solution.

    75| 8.07e-07  2.44e-10  7.29e-08  1.45e-01  1.00e-01  1.46e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.46e+00s = setup: 2.58e-02s + solve: 1.44e+00s
	 lin-sys: 4.97e-02s, cones: 1.37e+00s, accel: 5.98e-03s
------------------------------------------------------------------
objective = 0.145207
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.86e+01  1.00e-01  4.60e-02

(CVXPY) Jul 07 11:52:53 AM: Problem status: optimal
(CVXPY) Jul 07 11:52:53 AM: Optimal value: 1.284e-01
(CVXPY) Jul 07 11:52:53 AM: Compilation took 6.174e-02 seconds
(CVXPY) Jul 07 11:52:53 AM: Solver (including time spent in interface) took 1.691e+00 seconds
(CVXPY) Jul 07 11:52:53 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:52:53 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:52:53 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:52:53 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:52:53 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:52:53 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:52:53 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:52:53 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:52:53 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:52:53 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:52:53 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:52:53 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:52:53 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:52:53 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:52:54 AM: Applying reduction SCS
(CVXPY) Jul 07 11:52:54 AM: Finished problem compilation (took 5.743e-02 seconds).
(CVXPY) Jul 07 11:52:54 AM: Invoking solver SCS  to obtain a solution.

    75| 1.08e-06  8.11e-11  1.39e-07  1.28e-01  1.00e-01  1.69e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.69e+00s = setup: 2.49e-02s + solve: 1.66e+00s
	 lin-sys: 5.26e-02s, cones: 1.59e+00s, accel: 4.85e-03s
------------------------------------------------------------------
objective = 0.128448
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.87e+01  1.00e-01  5.35e-02

(CVXPY) Jul 07 11:52:55 AM: Problem status: optimal
(CVXPY) Jul 07 11:52:55 AM: Optimal value: 9.547e-02
(CVXPY) Jul 07 11:52:55 AM: Compilation took 5.743e-02 seconds
(CVXPY) Jul 07 11:52:55 AM: Solver (including time spent in interface) took 1.152e+00 seconds
(CVXPY) Jul 07 11:52:55 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:52:55 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:52:55 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:52:55 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:52:55 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:52:55 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:52:55 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:52:55 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:52:55 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:52:55 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:52:55 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:52:55 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:52:55 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:52:55 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:52:55 AM: Applying reduction SCS
(CVXPY) Jul 07 11:52:55 AM: Finished problem compilation (took 5.734e-02 seconds).
(CVXPY) Jul 07 11:52:55 AM: Invoking solver SCS  to obtain a solution.

    50| 2.38e-05  1.01e-10  2.89e-06  9.55e-02  1.00e-01  1.15e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.15e+00s = setup: 2.84e-02s + solve: 1.12e+00s
	 lin-sys: 4.08e-02s, cones: 1.06e+00s, accel: 4.03e-03s
------------------------------------------------------------------
objective = 0.095464
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.86e+01  1.00e-01  4.05e-02

(CVXPY) Jul 07 11:52:56 AM: Problem status: optimal
(CVXPY) Jul 07 11:52:56 AM: Optimal value: 1.310e-01
(CVXPY) Jul 07 11:52:56 AM: Compilation took 5.734e-02 seconds
(CVXPY) Jul 07 11:52:56 AM: Solver (including time spent in interface) took 1.692e+00 seconds
(CVXPY) Jul 07 11:52:56 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:52:56 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:52:56 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:52:56 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:52:56 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:52:56 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:52:56 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:52:56 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:52:56 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:52:56 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:52:56 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:52:56 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:52:56 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:52:56 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:52:57 AM: Applying reduction SCS
(CVXPY) Jul 07 11:52:57 AM: Finished problem compilation (took 5.081e-02 seconds).
(CVXPY) Jul 07 11:52:57 AM: Invoking solver SCS  to obtain a solution.

    75| 7.92e-07  7.91e-11  8.69e-08  1.31e-01  1.00e-01  1.69e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.69e+00s = setup: 2.65e-02s + solve: 1.66e+00s
	 lin-sys: 5.03e-02s, cones: 1.59e+00s, accel: 4.63e-03s
------------------------------------------------------------------
objective = 0.131019
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.86e+01  1.00e-01  4.62e-02

(CVXPY) Jul 07 11:52:58 AM: Problem status: optimal
(CVXPY) Jul 07 11:52:58 AM: Optimal value: 1.275e-01
(CVXPY) Jul 07 11:52:58 AM: Compilation took 5.081e-02 seconds
(CVXPY) Jul 07 11:52:58 AM: Solver (including time spent in interface) took 1.645e+00 seconds
(CVXPY) Jul 07 11:52:58 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:52:58 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:52:58 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:52:58 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:52:58 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:52:58 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:52:58 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:52:58 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:52:58 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:52:58 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:52:58 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:52:58 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:52:58 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:52:58 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:52:58 AM: Applying reduction SCS
(CVXPY) Jul 07 11:52:58 AM: Finished problem compilation (took 5.256e-02 seconds).
(CVXPY) Jul 07 11:52:58 AM: Invoking solver SCS  to obtain a solution.

    75| 1.07e-06  7.01e-11  1.18e-07  1.27e-01  1.00e-01  1.64e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.64e+00s = setup: 2.31e-02s + solve: 1.62e+00s
	 lin-sys: 4.91e-02s, cones: 1.55e+00s, accel: 4.96e-03s
------------------------------------------------------------------
objective = 0.127478
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.86e+01  1.00e-01  4.73e-02

(CVXPY) Jul 07 11:53:00 AM: Problem status: optimal
(CVXPY) Jul 07 11:53:00 AM: Optimal value: 1.134e-01
(CVXPY) Jul 07 11:53:00 AM: Compilation took 5.256e-02 seconds
(CVXPY) Jul 07 11:53:00 AM: Solver (including time spent in interface) took 1.597e+00 seconds
(CVXPY) Jul 07 11:53:00 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:53:00 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:53:00 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:53:00 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:53:00 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:53:00 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:53:00 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:53:00 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:53:00 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:53:00 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:53:00 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:53:00 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:53:00 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:53:00 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:53:00 AM: Applying reduction SCS
(CVXPY) Jul 07 11:53:00 AM: Finished problem compilation (took 5.865e-02 seconds).
(CVXPY) Jul 07 11:53:00 AM: Invoking solver SCS  to obtain a solution.

    75| 1.07e-06  7.09e-11  1.21e-07  1.13e-01  1.00e-01  1.59e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.59e+00s = setup: 2.38e-02s + solve: 1.57e+00s
	 lin-sys: 4.81e-02s, cones: 1.50e+00s, accel: 5.62e-03s
------------------------------------------------------------------
objective = 0.113397
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.86e+01  1.00e-01  5.53e-02

(CVXPY) Jul 07 11:53:02 AM: Problem status: optimal
(CVXPY) Jul 07 11:53:02 AM: Optimal value: 1.373e-01
(CVXPY) Jul 07 11:53:02 AM: Compilation took 5.865e-02 seconds
(CVXPY) Jul 07 11:53:02 AM: Solver (including time spent in interface) took 1.599e+00 seconds
(CVXPY) Jul 07 11:53:02 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:53:02 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:53:02 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:53:02 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:53:02 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:53:02 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:53:02 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:53:02 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:53:02 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:53:02 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:53:02 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:53:02 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:53:02 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:53:02 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:53:02 AM: Applying reduction SCS
(CVXPY) Jul 07 11:53:02 AM: Finished problem compilation (took 5.615e-02 seconds).
(CVXPY) Jul 07 11:53:02 AM: Invoking solver SCS  to obtain a solution.

    75| 8.01e-07  7.52e-11  7.48e-08  1.37e-01  1.00e-01  1.59e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.59e+00s = setup: 2.89e-02s + solve: 1.56e+00s
	 lin-sys: 4.98e-02s, cones: 1.50e+00s, accel: 4.26e-03s
------------------------------------------------------------------
objective = 0.137273
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.86e+01  1.00e-01  4.96e-02

(CVXPY) Jul 07 11:53:03 AM: Problem status: optimal
(CVXPY) Jul 07 11:53:03 AM: Optimal value: 1.312e-01
(CVXPY) Jul 07 11:53:03 AM: Compilation took 5.615e-02 seconds
(CVXPY) Jul 07 11:53:03 AM: Solver (including time spent in interface) took 1.729e+00 seconds
(CVXPY) Jul 07 11:53:03 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:53:03 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:53:03 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:53:03 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:53:03 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:53:03 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:53:03 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:53:03 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:53:03 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:53:03 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:53:03 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:53:03 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:53:03 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:53:03 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:53:03 AM: Applying reduction SCS
(CVXPY) Jul 07 11:53:03 AM: Finished problem compilation (took 4.931e-02 seconds).
(CVXPY) Jul 07 11:53:03 AM: Invoking solver SCS  to obtain a solution.

    75| 8.06e-07  7.73e-11  8.73e-08  1.31e-01  1.00e-01  1.73e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.73e+00s = setup: 2.61e-02s + solve: 1.70e+00s
	 lin-sys: 5.76e-02s, cones: 1.62e+00s, accel: 5.44e-03s
------------------------------------------------------------------
objective = 0.131152
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 3.54e+00  1.25e-01  5.74e+01 -2.86e+01  1.00e-01  5.60e-02

(CVXPY) Jul 07 11:53:05 AM: Problem status: optimal
(CVXPY) Jul 07 11:53:05 AM: Optimal value: 1.274e-01
(CVXPY) Jul 07 11:53:05 AM: Compilation took 4.931e-02 seconds
(CVXPY) Jul 07 11:53:05 AM: Solver (including time spent in interface) took 1.762e+00 seconds
(CVXPY) Jul 07 11:53:05 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:53:05 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:53:05 AM: DCP verification time: 0.0006 seconds.
(CVXPY) Jul 07 11:53:05 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:53:05 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:53:05 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:53:05 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:53:05 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:53:05 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:53:05 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:53:05 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:53:05 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:53:05 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:53:05 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:53:05 AM: Applying reduction SCS
(CVXPY) Jul 07 11:53:05 AM: Finished problem compilation (took 5.247e-02 seconds).
(CVXPY) Jul 07 11:53:05 AM: Invoking solver SCS  to obtain a solution.

    75| 8.84e-07  2.10e-10  1.07e-07  1.27e-01  1.00e-01  1.76e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.76e+00s = setup: 3.11e-02s + solve: 1.73e+00s
	 lin-sys: 7.13e-02s, cones: 1.63e+00s, accel: 5.51e-03s
------------------------------------------------------------------
objective = 0.127413
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  3.86e-02

(CVXPY) Jul 07 11:53:07 AM: Problem status: optimal
(CVXPY) Jul 07 11:53:07 AM: Optimal value: 1.070e-01
(CVXPY) Jul 07 11:53:07 AM: Compilation took 5.247e-02 seconds
(CVXPY) Jul 07 11:53:07 AM: Solver (including time spent in interface) took 1.862e+00 seconds
(CVXPY) Jul 07 11:53:07 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:53:07 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:53:07 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:53:07 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:53:07 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:53:07 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:53:07 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:53:07 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:53:07 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:53:07 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:53:07 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:53:07 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:53:07 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:53:07 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:53:07 AM: Applying reduction SCS
(CVXPY) Jul 07 11:53:07 AM: Finished problem compilation (took 5.637e-02 seconds).
(CVXPY) Jul 07 11:53:07 AM: Invoking solver SCS  to obtain a solution.

    75| 8.35e-07  7.54e-11  4.38e-08  1.07e-01  1.00e-01  1.86e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.86e+00s = setup: 2.31e-02s + solve: 1.83e+00s
	 lin-sys: 5.58e-02s, cones: 1.76e+00s, accel: 7.25e-03s
------------------------------------------------------------------
objective = 0.106965
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  5.35e-02

(CVXPY) Jul 07 11:53:08 AM: Problem status: optimal
(CVXPY) Jul 07 11:53:08 AM: Optimal value: 1.297e-01
(CVXPY) Jul 07 11:53:08 AM: Compilation took 5.637e-02 seconds
(CVXPY) Jul 07 11:53:08 AM: Solver (including time spent in interface) took 1.150e+00 seconds
(CVXPY) Jul 07 11:53:08 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:53:08 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:53:08 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:53:08 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:53:08 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:53:08 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:53:08 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:53:08 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:53:08 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:53:08 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:53:08 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:53:08 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:53:08 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:53:08 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:53:08 AM: Applying reduction SCS
(CVXPY) Jul 07 11:53:08 AM: Finished problem compilation (took 5.255e-02 seconds).
(CVXPY) Jul 07 11:53:08 AM: Invoking solver SCS  to obtain a solution.

    50| 2.43e-05  1.11e-10  8.66e-07  1.30e-01  1.00e-01  1.14e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.14e+00s = setup: 2.58e-02s + solve: 1.12e+00s
	 lin-sys: 3.24e-02s, cones: 1.07e+00s, accel: 3.34e-03s
------------------------------------------------------------------
objective = 0.129667
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  4.63e-02

(CVXPY) Jul 07 11:53:10 AM: Problem status: optimal
(CVXPY) Jul 07 11:53:10 AM: Optimal value: 1.513e-01
(CVXPY) Jul 07 11:53:10 AM: Compilation took 5.255e-02 seconds
(CVXPY) Jul 07 11:53:10 AM: Solver (including time spent in interface) took 1.756e+00 seconds
(CVXPY) Jul 07 11:53:10 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:53:10 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:53:10 AM: DCP verification time: 0.0011 seconds.
(CVXPY) Jul 07 11:53:10 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:53:10 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:53:10 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:53:10 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:53:10 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:53:10 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:53:10 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:53:10 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:53:10 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:53:10 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:53:10 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:53:10 AM: Applying reduction SCS
(CVXPY) Jul 07 11:53:10 AM: Finished problem compilation (took 5.256e-02 seconds).
(CVXPY) Jul 07 11:53:10 AM: Invoking solver SCS  to obtain a solution.

    75| 1.14e-06  8.19e-11  6.40e-08  1.51e-01  1.00e-01  1.75e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.75e+00s = setup: 2.22e-02s + solve: 1.73e+00s
	 lin-sys: 4.71e-02s, cones: 1.66e+00s, accel: 4.63e-03s
------------------------------------------------------------------
objective = 0.151252
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  5.02e-02

(CVXPY) Jul 07 11:53:12 AM: Problem status: optimal
(CVXPY) Jul 07 11:53:12 AM: Optimal value: 1.188e-01
(CVXPY) Jul 07 11:53:12 AM: Compilation took 5.256e-02 seconds
(CVXPY) Jul 07 11:53:12 AM: Solver (including time spent in interface) took 1.718e+00 seconds
(CVXPY) Jul 07 11:53:12 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:53:12 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:53:12 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:53:12 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:53:12 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:53:12 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:53:12 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:53:12 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:53:12 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:53:12 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:53:12 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:53:12 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:53:12 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:53:12 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:53:12 AM: Applying reduction SCS
(CVXPY) Jul 07 11:53:12 AM: Finished problem compilation (took 5.393e-02 seconds).
(CVXPY) Jul 07 11:53:12 AM: Invoking solver SCS  to obtain a solution.

    75| 1.16e-06  7.69e-11  5.80e-08  1.19e-01  1.00e-01  1.71e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.71e+00s = setup: 2.46e-02s + solve: 1.69e+00s
	 lin-sys: 4.96e-02s, cones: 1.62e+00s, accel: 5.25e-03s
------------------------------------------------------------------
objective = 0.118819
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  5.79e-02

(CVXPY) Jul 07 11:53:14 AM: Problem status: optimal
(CVXPY) Jul 07 11:53:14 AM: Optimal value: 9.244e-02
(CVXPY) Jul 07 11:53:14 AM: Compilation took 5.393e-02 seconds
(CVXPY) Jul 07 11:53:14 AM: Solver (including time spent in interface) took 1.743e+00 seconds
(CVXPY) Jul 07 11:53:14 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:53:14 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:53:14 AM: DCP verification time: 0.0004 seconds.
(CVXPY) Jul 07 11:53:14 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:53:14 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:53:14 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:53:14 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:53:14 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:53:14 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:53:14 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:53:14 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:53:14 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:53:14 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:53:14 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:53:14 AM: Applying reduction SCS
(CVXPY) Jul 07 11:53:14 AM: Finished problem compilation (took 5.977e-02 seconds).
(CVXPY) Jul 07 11:53:14 AM: Invoking solver SCS  to obtain a solution.

    75| 1.16e-06  6.49e-11  5.61e-08  9.24e-02  1.00e-01  1.74e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.74e+00s = setup: 3.10e-02s + solve: 1.71e+00s
	 lin-sys: 5.21e-02s, cones: 1.63e+00s, accel: 7.14e-03s
------------------------------------------------------------------
objective = 0.092437
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  3.82e-02

(CVXPY) Jul 07 11:53:15 AM: Problem status: optimal
(CVXPY) Jul 07 11:53:15 AM: Optimal value: 1.367e-01
(CVXPY) Jul 07 11:53:15 AM: Compilation took 5.977e-02 seconds
(CVXPY) Jul 07 11:53:15 AM: Solver (including time spent in interface) took 1.235e+00 seconds
(CVXPY) Jul 07 11:53:15 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:53:15 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:53:15 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:53:15 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:53:15 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:53:15 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:53:15 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:53:15 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:53:15 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:53:15 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:53:15 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:53:15 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:53:15 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:53:15 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:53:15 AM: Applying reduction SCS
(CVXPY) Jul 07 11:53:15 AM: Finished problem compilation (took 5.530e-02 seconds).
(CVXPY) Jul 07 11:53:15 AM: Invoking solver SCS  to obtain a solution.

    50| 2.02e-05  1.15e-10  7.52e-07  1.37e-01  1.00e-01  1.23e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.23e+00s = setup: 2.38e-02s + solve: 1.21e+00s
	 lin-sys: 3.39e-02s, cones: 1.15e+00s, accel: 3.25e-03s
------------------------------------------------------------------
objective = 0.136698
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  5.22e-02

(CVXPY) Jul 07 11:53:17 AM: Problem status: optimal
(CVXPY) Jul 07 11:53:17 AM: Optimal value: 1.176e-01
(CVXPY) Jul 07 11:53:17 AM: Compilation took 5.530e-02 seconds
(CVXPY) Jul 07 11:53:17 AM: Solver (including time spent in interface) took 1.675e+00 seconds
(CVXPY) Jul 07 11:53:17 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:53:17 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:53:17 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:53:17 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:53:17 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:53:17 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:53:17 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:53:17 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:53:17 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:53:17 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:53:17 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:53:17 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:53:17 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:53:17 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:53:17 AM: Applying reduction SCS
(CVXPY) Jul 07 11:53:17 AM: Finished problem compilation (took 5.587e-02 seconds).
(CVXPY) Jul 07 11:53:17 AM: Invoking solver SCS  to obtain a solution.

    75| 8.42e-07  7.11e-11  3.61e-08  1.18e-01  1.00e-01  1.67e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.67e+00s = setup: 2.43e-02s + solve: 1.65e+00s
	 lin-sys: 5.19e-02s, cones: 1.57e+00s, accel: 5.02e-03s
------------------------------------------------------------------
objective = 0.117598
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  4.71e-02

(CVXPY) Jul 07 11:53:19 AM: Problem status: optimal
(CVXPY) Jul 07 11:53:19 AM: Optimal value: 9.142e-02
(CVXPY) Jul 07 11:53:19 AM: Compilation took 5.587e-02 seconds
(CVXPY) Jul 07 11:53:19 AM: Solver (including time spent in interface) took 1.734e+00 seconds
(CVXPY) Jul 07 11:53:19 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:53:19 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:53:19 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:53:19 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:53:19 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:53:19 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:53:19 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:53:19 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:53:19 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:53:19 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:53:19 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:53:19 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:53:19 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:53:19 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:53:19 AM: Applying reduction SCS
(CVXPY) Jul 07 11:53:19 AM: Finished problem compilation (took 5.760e-02 seconds).
(CVXPY) Jul 07 11:53:19 AM: Invoking solver SCS  to obtain a solution.

    75| 8.18e-07  6.98e-11  2.88e-08  9.14e-02  1.00e-01  1.73e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.73e+00s = setup: 2.34e-02s + solve: 1.70e+00s
	 lin-sys: 5.42e-02s, cones: 1.63e+00s, accel: 6.66e-03s
------------------------------------------------------------------
objective = 0.091417
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  4.90e-02

(CVXPY) Jul 07 11:53:21 AM: Problem status: optimal
(CVXPY) Jul 07 11:53:21 AM: Optimal value: 1.530e-01
(CVXPY) Jul 07 11:53:21 AM: Compilation took 5.760e-02 seconds
(CVXPY) Jul 07 11:53:21 AM: Solver (including time spent in interface) took 1.738e+00 seconds
(CVXPY) Jul 07 11:53:21 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:53:21 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:53:21 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:53:21 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:53:21 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:53:21 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:53:21 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:53:21 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:53:21 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:53:21 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:53:21 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:53:21 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:53:21 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:53:21 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:53:21 AM: Applying reduction SCS
(CVXPY) Jul 07 11:53:21 AM: Finished problem compilation (took 6.298e-02 seconds).
(CVXPY) Jul 07 11:53:21 AM: Invoking solver SCS  to obtain a solution.

    75| 1.14e-06  6.95e-11  4.94e-08  1.53e-01  1.00e-01  1.73e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.73e+00s = setup: 2.52e-02s + solve: 1.71e+00s
	 lin-sys: 5.48e-02s, cones: 1.63e+00s, accel: 4.87e-03s
------------------------------------------------------------------
objective = 0.153020
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  3.96e-02

(CVXPY) Jul 07 11:53:23 AM: Problem status: optimal
(CVXPY) Jul 07 11:53:23 AM: Optimal value: 1.004e-01
(CVXPY) Jul 07 11:53:23 AM: Compilation took 6.298e-02 seconds
(CVXPY) Jul 07 11:53:23 AM: Solver (including time spent in interface) took 1.884e+00 seconds
(CVXPY) Jul 07 11:53:23 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:53:23 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:53:23 AM: DCP verification time: 0.0005 seconds.
(CVXPY) Jul 07 11:53:23 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:53:23 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:53:23 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:53:23 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:53:23 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:53:23 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:53:23 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:53:23 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:53:23 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:53:23 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:53:23 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:53:23 AM: Applying reduction SCS
(CVXPY) Jul 07 11:53:23 AM: Finished problem compilation (took 4.990e-02 seconds).
(CVXPY) Jul 07 11:53:23 AM: Invoking solver SCS  to obtain a solution.

    75| 1.13e-06  7.18e-11  4.53e-08  1.00e-01  1.00e-01  1.88e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.88e+00s = setup: 2.66e-02s + solve: 1.85e+00s
	 lin-sys: 5.13e-02s, cones: 1.78e+00s, accel: 6.05e-03s
------------------------------------------------------------------
objective = 0.100402
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  4.59e-02

(CVXPY) Jul 07 11:53:24 AM: Problem status: optimal
(CVXPY) Jul 07 11:53:24 AM: Optimal value: 9.372e-02
(CVXPY) Jul 07 11:53:24 AM: Compilation took 4.990e-02 seconds
(CVXPY) Jul 07 11:53:24 AM: Solver (including time spent in interface) took 1.703e+00 seconds
(CVXPY) Jul 07 11:53:24 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:53:24 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:53:24 AM: DCP verification time: 0.0009 seconds.
(CVXPY) Jul 07 11:53:24 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:53:24 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:53:24 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:53:24 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:53:24 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:53:24 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:53:24 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:53:24 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:53:24 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:53:24 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:53:24 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:53:24 AM: Applying reduction SCS
(CVXPY) Jul 07 11:53:24 AM: Finished problem compilation (took 4.865e-02 seconds).
(CVXPY) Jul 07 11:53:24 AM: Invoking solver SCS  to obtain a solution.

    75| 1.14e-06  6.94e-11  4.40e-08  9.37e-02  1.00e-01  1.70e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.70e+00s = setup: 2.40e-02s + solve: 1.67e+00s
	 lin-sys: 6.08e-02s, cones: 1.59e+00s, accel: 5.54e-03s
------------------------------------------------------------------
objective = 0.093721
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  4.86e-02

(CVXPY) Jul 07 11:53:26 AM: Problem status: optimal
(CVXPY) Jul 07 11:53:26 AM: Optimal value: 1.453e-01
(CVXPY) Jul 07 11:53:26 AM: Compilation took 4.865e-02 seconds
(CVXPY) Jul 07 11:53:26 AM: Solver (including time spent in interface) took 1.678e+00 seconds
(CVXPY) Jul 07 11:53:26 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:53:26 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:53:26 AM: DCP verification time: 0.0012 seconds.
(CVXPY) Jul 07 11:53:26 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:53:26 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:53:26 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:53:26 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:53:26 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:53:26 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:53:26 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:53:26 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:53:26 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:53:26 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:53:26 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:53:26 AM: Applying reduction SCS
(CVXPY) Jul 07 11:53:26 AM: Finished problem compilation (took 5.314e-02 seconds).
(CVXPY) Jul 07 11:53:26 AM: Invoking solver SCS  to obtain a solution.

    75| 1.15e-06  8.26e-11  4.27e-08  1.45e-01  1.00e-01  1.67e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.67e+00s = setup: 2.30e-02s + solve: 1.65e+00s
	 lin-sys: 4.57e-02s, cones: 1.58e+00s, accel: 5.63e-03s
------------------------------------------------------------------
objective = 0.145343
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  4.82e-02

(CVXPY) Jul 07 11:53:28 AM: Problem status: optimal
(CVXPY) Jul 07 11:53:28 AM: Optimal value: 1.284e-01
(CVXPY) Jul 07 11:53:28 AM: Compilation took 5.314e-02 seconds
(CVXPY) Jul 07 11:53:28 AM: Solver (including time spent in interface) took 1.673e+00 seconds
(CVXPY) Jul 07 11:53:28 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:53:28 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:53:28 AM: DCP verification time: 0.0017 seconds.
(CVXPY) Jul 07 11:53:28 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:53:28 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:53:28 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:53:28 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:53:28 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:53:28 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:53:28 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:53:28 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:53:28 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:53:28 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:53:28 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:53:28 AM: Applying reduction SCS
(CVXPY) Jul 07 11:53:28 AM: Finished problem compilation (took 6.231e-02 seconds).
(CVXPY) Jul 07 11:53:28 AM: Invoking solver SCS  to obtain a solution.

    75| 1.14e-06  8.13e-11  5.82e-08  1.28e-01  1.00e-01  1.67e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.67e+00s = setup: 2.55e-02s + solve: 1.64e+00s
	 lin-sys: 5.35e-02s, cones: 1.57e+00s, accel: 5.06e-03s
------------------------------------------------------------------
objective = 0.128448
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  4.59e-02

(CVXPY) Jul 07 11:53:29 AM: Problem status: optimal
(CVXPY) Jul 07 11:53:29 AM: Optimal value: 9.548e-02
(CVXPY) Jul 07 11:53:29 AM: Compilation took 6.231e-02 seconds
(CVXPY) Jul 07 11:53:29 AM: Solver (including time spent in interface) took 1.226e+00 seconds
(CVXPY) Jul 07 11:53:29 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:53:29 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:53:29 AM: DCP verification time: 0.0008 seconds.
(CVXPY) Jul 07 11:53:29 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:53:29 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:53:29 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:53:29 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:53:29 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:53:29 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:53:29 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:53:29 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:53:29 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:53:29 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:53:29 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:53:29 AM: Applying reduction SCS
(CVXPY) Jul 07 11:53:29 AM: Finished problem compilation (took 5.910e-02 seconds).
(CVXPY) Jul 07 11:53:29 AM: Invoking solver SCS  to obtain a solution.

    50| 2.45e-05  1.01e-10  1.19e-06  9.55e-02  1.00e-01  1.22e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.22e+00s = setup: 2.41e-02s + solve: 1.20e+00s
	 lin-sys: 3.05e-02s, cones: 1.15e+00s, accel: 3.28e-03s
------------------------------------------------------------------
objective = 0.095465
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  4.23e-02

(CVXPY) Jul 07 11:53:31 AM: Problem status: optimal
(CVXPY) Jul 07 11:53:31 AM: Optimal value: 1.310e-01
(CVXPY) Jul 07 11:53:31 AM: Compilation took 5.910e-02 seconds
(CVXPY) Jul 07 11:53:31 AM: Solver (including time spent in interface) took 1.882e+00 seconds
(CVXPY) Jul 07 11:53:31 AM: Your problem has 4067 variables, 0 constraints, and 0 parameters.
(CVXPY) Jul 07 11:53:31 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jul 07 11:53:31 AM: DCP verification time: 0.0007 seconds.
(CVXPY) Jul 07 11:53:31 AM: Expression tree has 9 nodes.
(CVXPY) Jul 07 11:53:31 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jul 07 11:53:31 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Jul 07 11:53:31 AM: Your problem is compiled with the CPP canonicalization backend.
(CVXPY) Jul 07 11:53:31 AM: Compiling problem (target solver=SCS).
(CVXPY) Jul 07 11:53:31 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ExactCone2Cone -> EliminateZeroSized -> ConeMatrixStuffing -> SCS
(CVXPY) Jul 07 11:53:31 AM: Applying reduction Dcp2Cone
(CVXPY) Jul 07 11:53:31 AM: Applying reduction CvxAttr2Constr
(CVXPY) Jul 07 11:53:31 AM: Applying reduction ExactCone2Cone
(CVXPY) Jul 07 11:53:31 AM: Applying reduction EliminateZeroSized
(CVXPY) Jul 07 11:53:31 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Jul 07 11:53:31 AM: Applying reduction SCS
(CVXPY) Jul 07 11:53:31 AM: Finished problem compilation (took 5.195e-02 seconds).
(CVXPY) Jul 07 11:53:31 AM: Invoking solver SCS  to obtain a solution.

    75| 8.22e-07  7.92e-11  3.59e-08  1.31e-01  1.00e-01  1.88e+00
------------------------------------------------------------------
status:  solved
timings: total: 1.88e+00s = setup: 2.84e-02s + solve: 1.85e+00s
	 lin-sys: 5.60e-02s, cones: 1.77e+00s, accel: 4.95e-03s
------------------------------------------------------------------
objective = 0.131019
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary
-------------------------------------------------------------------------------
===============================================================================
                                     CVXPY
                                     v1.9.2
===============================================================================
-------------------------------------------------------------------------------
                                  Compilation
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
                                Numerical solver
-------------------------------------------------------------------------------
------------------------------------------------------------------
	       SCS v3.2.11 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 12582, constraints m: 12451
cones: 	  z: primal zero / dual free vars: 3936
	  s: psd vars: 8515, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
	  nnz(A): 28195, nnz(P): 3646
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 7.07e+00  2.50e-01  2.30e+02 -1.15e+02  1.00e-01  5.23e-02

In [ ]:
# Coordinate-descent tuning
l_unit, l_time, l_nn = TROP_cv_cycle(
    Y_control=Y_control,
    treated_periods=treated_periods,
    unit_grid=unit_grid,
    time_grid=time_grid,
    nn_grid=nn_grid,
    lambdas_init=None,
    max_iter=20,
    cv_sampling_method="resample",
    n_trials=50,
    n_treated_units=n_placebo_treated,
    n_jobs=-1,
    prefer="threads",
    random_seed=0,
    solver="SCS",
    verbose=False,
)

print("Selected lambdas (cycle CV):")
print("  lambda_unit =", l_unit)
print("  lambda_time =", l_time)
print("  lambda_nn   =", l_nn)

### Re-estimate `τ` using the tuned parameters

In [ ]:
tau_tuned = TROP_TWFE_average(
    Y=Y,
    W=W,
    treated_units=treated_units,
    lambda_unit=l_unit,
    lambda_time=l_time,
    lambda_nn=l_nn,
    treated_periods=treated_periods,
    solver="SCS",
    verbose=False,
)

print("Estimated tau (TROP with placebo-CV tuned lambdas):", tau_tuned)

### Joint grid search CV

If your grids are small, you can do a full joint search over
`unit_grid × time_grid × nn_grid`:

- Pros: global search over the discrete grid
- Cons: can be expensive (`len(grid)^3 × n_trials` optimizations)

This is useful as a robustness check once the pipeline is working.

In [ ]:
# This can be slow if grids are large
best_unit, best_time, best_nn = TROP_cv_joint(
    Y_control=Y_control,
    treated_periods=treated_periods,
    unit_grid=unit_grid,
    time_grid=time_grid,
    nn_grid=nn_grid,
    cv_sampling_method="resample",
    n_trials=25,
    n_treated_units=n_placebo_treated,
    n_jobs=-1,
    prefer="threads",
    random_seed=0,
    solver="SCS",
    verbose=False,
)

print("Selected lambdas (joint CV):", (best_unit, best_time, best_nn))

## 7. Simple sensitivity check

A good quick check is:
- hold `(lambda_unit, lambda_time)` fixed
- vary `lambda_nn` over a grid
- plot the resulting `τ`

If `τ` is extremely sensitive to small changes in `lambda_nn`, consider refining the CV grid or increasing `n_trials`.

In [ ]:
nn_grid_sens = np.array([0.001, 0.002, 0.005, 0.01, 0.02, 0.05, 0.1])

taus = []
for lam in nn_grid_sens:
    tau_val = TROP_TWFE_average(
        Y=Y,
        W=W,
        treated_units=treated_units,
        lambda_unit=l_unit,
        lambda_time=l_time,
        lambda_nn=float(lam),
        treated_periods=treated_periods,
        solver="SCS",
        verbose=False,
    )
    taus.append(tau_val)

fig, ax = plt.subplots(figsize=(6.5, 4))

ax.plot(nn_grid_sens, taus, marker="o", linewidth=2)
ax.set_xscale("log")
ax.xaxis.set_major_formatter(ScalarFormatter())
ax.ticklabel_format(axis="x", style="plain")
ax.set_xlabel(r"$\lambda_{\mathrm{nn}}$")
ax.set_ylabel(r"Estimated $\hat{\tau}$")
ax.set_title(r"Sensitivity of TROP estimate to $\lambda_{\mathrm{nn}}$")
ax.grid(True, which="both", linestyle="--", linewidth=0.6, alpha=0.6)
fig.tight_layout()
plt.show()

## 8. Notes

`treated_periods` enters the estimator in two places:

* defines the pre-period window for unit-distance weighting
* sets the center for time-distance weighting near the post block

So it should match how you construct `W`. If your design changes, revisit this choice.

### Runtime

Placebo CV is expensive. Practical workflow:

* start with coarse grids and small `n_trials`
* scale up `n_trials` after debugging
* use `n_jobs=-1`
* prefer `TROP_cv_cycle` before a full `TROP_cv_joint` grid

### Interpretation

`tau` is in standardized units if you standardize `Y`. For original units, don’t standardize.